table Facturation
	lineageTag: fd658ce3-6df6-4923-9645-18c89660af82

	measure '# collections concernées' = EXTERNALMEASURE("# collections concernées", INTEGER, "DirectQuery à AS – pst38")
		formatString: #,##0
		displayFolder: Indicateurs\Comptage
		lineageTag: ceddb0e4-28bb-4a8c-9630-59ccfeb5b63c
		sourceLineageTag: DirectQuery à AS – pst38.# collections concernées
		dataCategory: Uncategorized

	measure '# entreprises concernées' = EXTERNALMEASURE("# entreprises concernées", INTEGER, "DirectQuery à AS – pst38")
		formatString: #,##0
		displayFolder: Indicateurs\Comptage
		lineageTag: 5b4ec57f-f7a5-4248-abb2-831936c75ed6
		sourceLineageTag: DirectQuery à AS – pst38.# entreprises concernées
		dataCategory: Uncategorized

	measure 'Montant moyen HT facturable' = EXTERNALMEASURE("Montant moyen HT facturable", CURRENCY, "DirectQuery à AS – pst38")
		formatString: #,##0.00\ \€
		displayFolder: Indicateurs\Facturable
		lineageTag: 2da71b88-426d-40fe-82ce-d534658ba941
		sourceLineageTag: DirectQuery à AS – pst38.Montant moyen HT facturable
		dataCategory: Uncategorized

	measure 'Montant moyen HT facturé' = EXTERNALMEASURE("Montant moyen HT facturé", CURRENCY, "DirectQuery à AS – pst38")
		formatString: #,##0.00\ \€
		displayFolder: Indicateurs\Facturé
		lineageTag: 00d44824-6edf-457b-ac04-83e875eaa3e2
		sourceLineageTag: DirectQuery à AS – pst38.Montant moyen HT facturé
		dataCategory: Uncategorized

	measure 'Montant total hors taxe facturé' = EXTERNALMEASURE("Montant total hors taxe facturé", CURRENCY, "DirectQuery à AS – pst38")
		formatString: #,##0.00\ \€
		displayFolder: Indicateurs\Facturé
		lineageTag: 301a66cb-222d-437f-a095-2279c4b843d8
		sourceLineageTag: DirectQuery à AS – pst38.Montant total hors taxe facturé
		dataCategory: Uncategorized

	measure 'Montant total HT facturable' = EXTERNALMEASURE("Montant total HT facturable", CURRENCY, "DirectQuery à AS – pst38")
		formatString: #,##0.00\ \€
		displayFolder: Indicateurs\Facturable
		lineageTag: d2af7e4d-fbb3-4bc6-96fa-69713788b863
		sourceLineageTag: DirectQuery à AS – pst38.Montant total HT facturable
		dataCategory: Uncategorized

	measure 'Nombre de documents (facture & avoirs)' = EXTERNALMEASURE("Nombre de documents (facture & avoirs)", INTEGER, "DirectQuery à AS – pst38")
		formatString: #,##0
		displayFolder: Indicateurs\Comptage
		lineageTag: b3d6f28c-9e9c-44af-8dd2-bd6766e4825f
		sourceLineageTag: DirectQuery à AS – pst38.Nombre de documents (facture & avoirs)
		dataCategory: Uncategorized

	measure 'Nombre total d''actes facturables' = EXTERNALMEASURE("Nombre total d'actes facturables", INTEGER, "DirectQuery à AS – pst38")
		formatString: #,##0
		displayFolder: Indicateurs\Comptage
		lineageTag: 1b8a45e1-88b2-42e2-8a5d-8ab327e02581
		sourceLineageTag: DirectQuery à AS – pst38.Nombre total d'actes facturables
		dataCategory: Uncategorized

	measure 'Prix unitaire moyen HT facturable' = EXTERNALMEASURE("Prix unitaire moyen HT facturable", CURRENCY, "DirectQuery à AS – pst38")
		formatString: #,##0.00\ \€
		displayFolder: Indicateurs\Facturable
		lineageTag: 8d8b8492-b113-44d2-b3c4-a55d05f74a71
		sourceLineageTag: DirectQuery à AS – pst38.Prix unitaire moyen HT facturable
		dataCategory: Uncategorized

	measure 'Prix unitaire moyen HT facturé' = EXTERNALMEASURE("Prix unitaire moyen HT facturé", CURRENCY, "DirectQuery à AS – pst38")
		formatString: #,##0.00\ \€
		displayFolder: Indicateurs\Facturé
		lineageTag: e6ed6942-4953-4a1b-a9e5-6ebaa5cb0a65
		sourceLineageTag: DirectQuery à AS – pst38.Prix unitaire moyen HT facturé
		dataCategory: Uncategorized

	measure 'Quantité moyenne facturable' = EXTERNALMEASURE("Quantité moyenne facturable", DOUBLE, "DirectQuery à AS – pst38")
		formatString: #,##0
		displayFolder: Indicateurs\Facturable
		lineageTag: f7561ae1-aa7f-481c-874d-fb77ce43cf7e
		sourceLineageTag: DirectQuery à AS – pst38.Quantité moyenne facturable
		dataCategory: Uncategorized

	measure 'Quantité moyenne facturée' = EXTERNALMEASURE("Quantité moyenne facturée", DOUBLE, "DirectQuery à AS – pst38")
		formatString: #,##0
		displayFolder: Indicateurs\Facturé
		lineageTag: cc897720-fa78-4f98-9003-03f723dd016d
		sourceLineageTag: DirectQuery à AS – pst38.Quantité moyenne facturée
		dataCategory: Uncategorized

	measure 'Quantité totale facturable' = EXTERNALMEASURE("Quantité totale facturable", INTEGER, "DirectQuery à AS – pst38")
		formatString: #,##0
		displayFolder: Indicateurs\Facturable
		lineageTag: 1f3531a2-b367-4b2d-8833-ca5d194b6444
		sourceLineageTag: DirectQuery à AS – pst38.Quantité totale facturable
		dataCategory: Uncategorized

	measure 'Quantité totale facturée' = EXTERNALMEASURE("Quantité totale facturée", INTEGER, "DirectQuery à AS – pst38")
		formatString: #,##0
		displayFolder: Indicateurs\Facturé
		lineageTag: 694a526a-2ff6-43c4-9a13-2839a20a8593
		sourceLineageTag: DirectQuery à AS – pst38.Quantité totale facturée
		dataCategory: Uncategorized

	column 'Année activité'
		dataType: int64
		lineageTag: 429b9931-4c3c-4c04-91b5-4b0997f570a7
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Année activité

		annotation SummarizationSetBy = Automatic

	column id_article
		dataType: int64
		displayFolder: Colonnes inutilisées
		lineageTag: c6bb1600-1cb4-4b25-a138-dd3898ff9274
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: id_article

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id_date_facture
		dataType: int64
		displayFolder: Colonnes inutilisées
		lineageTag: 8d3ca45e-a0cf-4e80-a17a-0342bf7661bc
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: id_date_facture

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id_date_reference_facturation
		dataType: int64
		displayFolder: Colonnes inutilisées
		lineageTag: b92d05ab-c306-4200-846a-27f6ed700ae4
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: id_date_reference_facturation

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id_description_acte_facturable
		dataType: int64
		displayFolder: Colonnes inutilisées
		lineageTag: f167b86b-316d-463c-a144-c10aff07dae3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: id_description_acte_facturable

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id_entreprise
		dataType: int64
		displayFolder: Colonnes inutilisées
		lineageTag: ec054021-583d-49b9-9939-f80282d6128f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: id_entreprise

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id_entreprise_collection_regroupante
		dataType: int64
		displayFolder: Colonnes inutilisées
		lineageTag: 99a58144-f8a2-45c2-ad03-d879904b91ff
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: id_entreprise_collection_regroupante

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id_secteur
		dataType: int64
		displayFolder: Colonnes inutilisées
		lineageTag: d362e915-99c6-4b83-9c5d-1858679353b0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: id_secteur

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Montant hors taxe facturable'
		dataType: decimal
		formatString: ###0,00\ \€
		displayFolder: Colonnes inutilisées
		lineageTag: 0a257683-b4d5-4655-bef0-f036abb9aa57
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Montant hors taxe facturable

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Montant hors taxe facturé'
		dataType: decimal
		formatString: ###0,00\ \€
		displayFolder: Colonnes inutilisées
		lineageTag: 77668ca0-c9c7-41c2-a389-5ff70e92b901
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Montant hors taxe facturé

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column nb_acte_facturable
		dataType: int64
		displayFolder: Colonnes inutilisées
		lineageTag: 4e7a8600-4f75-4ed6-b9ae-6f87aac45f27
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: nb_acte_facturable

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Prix unitaire de l''article hors taxe facturable'
		dataType: double
		formatString: #\ ##0,00\ \€
		displayFolder: Colonnes inutilisées
		lineageTag: 6d495ac8-e0b2-4314-9125-9b2512f940cf
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Prix unitaire de l'article hors taxe facturable

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Prix unitaire de l''article hors taxe facturé'
		dataType: double
		formatString: #\ ##0,00\ \€
		displayFolder: Colonnes inutilisées
		lineageTag: 1607f693-9aec-4a02-be57-8efedd829735
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Prix unitaire de l'article hors taxe facturé

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Quantité facturable'
		dataType: int64
		displayFolder: Colonnes inutilisées
		lineageTag: 777bf6c2-005a-4f9f-8ae2-3ffc2704d2a9
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Quantité facturable

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Quantité facturée'
		dataType: int64
		displayFolder: Colonnes inutilisées
		lineageTag: 3d7bff9d-90b7-4eda-8eea-ab20d7e14b0f
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Quantité facturée

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id_facture_padoa_source
		dataType: int64
		displayFolder: Colonnes inutilisées
		lineageTag: 50ecb8a9-a6e6-4166-a42a-5add0d8aacee
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: id_facture_padoa_source

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id_info_facturation
		dataType: int64
		displayFolder: Colonnes inutilisées
		lineageTag: dd4f7acb-f134-448b-b9ac-7924c911634b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: id_info_facturation

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id_centre_convocation
		dataType: int64
		displayFolder: Colonnes inutilisées
		lineageTag: f71c32a3-a50c-4f2a-9352-5a1f53af2d72
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: id_centre_convocation

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Facturation = entity
		mode: directQuery
		source
			entityName: Facturation
			expressionSource: 'DirectQuery à AS – pst38'

