/// Table de mesure
table Mesures
	lineageTag: e4e5606e-6c09-4686-927a-7d77b8ae27e1

	measure 'Taux de convocations' = ```
			
			VAR NombreVisitesRealisees = [Nombre de visites réalisées (RDV)] -- Variable pour stocker le nombre de visites réalisées
			VAR NombreConvocations = [Nombre de RDV avec convocation] -- Variable pour stocker le nombre total de convocations
			
			RETURN
			    COALESCE(
			        DIVIDE(
			        NombreConvocations, --  nombre total de convocations
			        NombreVisitesRealisees, -- nombre de visites réalisées
			        0 -- Valeur de retour en cas de division par zéro
			    ),
			    0
			    )
			
			-- Cette mesure calcule le taux de convocations en divisant le nombre de visites réalisées
			-- par le nombre total de convocations. Elle utilise DIVIDE pour éviter les erreurs de division par zéro.
			
			```
		formatString: 0.00
		displayFolder: Visites
		lineageTag: be02f609-e699-4357-b77b-adec8e71732c

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'titre Répartition des visites fonction publique réalisées le mois dernier par catégorie' =
			
			VAR DateMoisDernier = EDATE(TODAY(), -1)                            -- Calcul de la date du mois dernier
			VAR DateFormatee = FORMAT(DateMoisDernier, "Mmmm yyyy", "fr-FR")    -- Formatage de la date
			RETURN
			"Répartition des visites fonction publique réalisées en " & DateFormatee & " par catégorie"                   -- Concaténation du texte avec la date formatée
			
			-- Description : Cette mesure calcule le nombre de visites réalisées le mois dernier et retourne un texte formaté indiquant le mois et l'année.
		displayFolder: Titres
		lineageTag: 5bb7c566-e5af-4c9a-973b-4701a13f3376

	measure 'Date Fin Arrêté' = ```
			
			max('Date principale'[Date])
			// VAR Selection = SELECTEDVALUE('Choisir Période'[ID], 2)
			// VAR DateAuj = TODAY() 
			
			// -- Bornes de fin standard
			// VAR FinAnneePrecedente = DATE(YEAR(DateAuj)-1, 12, 31)
			// VAR FinMoisDernier = EOMONTH(DateAuj, -1)
			// VAR FinMoisEnCours = EOMONTH(DateAuj, 0)
			
			// RETURN
			// SWITCH(
			//     Selection,
			//     1, FinAnneePrecedente,
			//     2, FinMoisDernier,
			//     3, FinMoisDernier,
			//     4, BLANK(),
			//     5, FinMoisEnCours,
			//     6, MAX('Date principale'[Date]), -- Ici on prend la fin de la sélection
			//     FinMoisDernier
			// )
			```
		formatString: General Date
		displayFolder: Suivi des indicateurs\Date
		lineageTag: b53a23a3-7b77-4014-b664-2e61b796c2c0

		changedProperty = DisplayFolder

		changedProperty = Name

	measure '# adhérents (respecte secteur)' = ```
			
			CALCULATE(
			    DISTINCTCOUNT('CRM - tickets'[id_entreprise]),
			    FILTER(
			        ALLSELECTED('CRM - tickets'), 
			        [Tickets en-cours] > 0
			    ),
			    KEEPFILTERS(VALUES('CRM - tickets'[id_secteur]))
			)
			
			```
		formatString: 0
		displayFolder: Tickets
		lineageTag: 65f8b280-04e9-454d-981a-1416b50b2823

		changedProperty = DisplayFolder

		changedProperty = Name

	measure '# adhérents avec un ticket depuis début de l''année' = ```
			
			VAR CetteAnnee = YEAR(TODAY())
			VAR T =
			    FILTER(
			        ALL('CRM - tickets'[id_entreprise]),          -- ne retire pas le filtre secteur
			        [# tickets] > 0
			    )
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('CRM - tickets'[id_entreprise]),
			    T,                                                -- condition “au moins 1 ticket”
			    KEEPFILTERS('CRM - activité - date'[Année activité] = CetteAnnee),  -- ajoute sans écraser
			    REMOVEFILTERS('Utilisateur'),                     -- remplace ALL(...) de façon ciblée
			    REMOVEFILTERS('Date principale')                  -- idem, si nécessaire
			)
			
			```
		formatString: #,0
		displayFolder: Tickets
		lineageTag: 4f411e69-3397-4a54-b8e1-e302b414d760

		changedProperty = Name

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure '# adhérents avec un ticket ouvert' = ```
			
			
			CALCULATE(
			    DISTINCTCOUNT('CRM - tickets'[id_entreprise]),
			    FILTER(
			        ALLSELECTED('CRM - tickets'), 
			        [Tickets en-cours] > 0
			    ),
			    KEEPFILTERS(VALUES('CRM - tickets'[id_secteur]))
			)
			
			```
		formatString: 0
		displayFolder: Tickets
		lineageTag: 2950f5fd-b6e8-4b2d-8cc8-07a82f00be99

		changedProperty = Name

		changedProperty = DisplayFolder

	measure '# adhérents sans FE moins de 1 an' = ```
			
			VAR DateSeuil = EDATE(TODAY(), -12) 
			
			// 1. On récupère la liste des IDs des adhérents récents dans la table 'Adhérent (actuel)'
			VAR AdherentsRecents = 
			    CALCULATETABLE(
			        VALUES('Adhérent (actuel)'[id_entreprise]), // Vérifie bien le nom exact de la colonne ID ici
			        'Adhérent (actuel)'[Date premier statut actif] >= DateSeuil
			    )
			
			RETURN
			// 2. On injecte cette liste dans le calcul de la mesure sans FE
			CALCULATE(
			    [# adhérents sans FE (fin de période)],
			    // On applique le filtre sur la table cible (probablement 'Evolution effectif' ou 'Adhérents')
			    TREATAS(AdherentsRecents, 'Evolution effectif'[id_entreprise]) 
			)
			```
		formatString: 0
		displayFolder: FE
		lineageTag: 63864a86-9079-4346-affc-658b3b325e90

		changedProperty = DisplayFolder

		changedProperty = Name

	measure '# ticket depuis début de l''année' =
			
			var cetteAnnee = YEAR(TODAY())
			
			Return
			
			CALCULATE(
			    [# tickets],
			    'CRM - activité - date'[Année activité] = cetteAnnee
			)
		formatString: #,0
		displayFolder: Tickets
		lineageTag: 58bec3e4-3f5d-4eca-9907-d9267eb3bbf1

		changedProperty = Name

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure '% adhérents à jour de APP (Table date secondaire)' =
			
			CALCULATE(
			    [% adhérents à jour d'AMT primaire (fin de période)],
			    TREATAS(
			        VALUES('Dates_Futur'[Date]),
			        'Date principale'[Date]
			    )
			)
		displayFolder: AMT\Simulation
		lineageTag: 084699d3-9d40-4917-a3cf-accf7b6a2794

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% adhérents à jour de FE (Table date secondaire)' =
			
			CALCULATE(
			    [% adhérents à jour de FE (fin de période)],
			    TREATAS(
			        VALUES('Dates_Futur'[Date]),
			        'Date principale'[Date]
			    )
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: FE\Simulation
		lineageTag: 3f56d081-4b6a-4a42-88ca-7ff3b1f8adec

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure '% adhérents avec ticket depuis début de l''année' =
			
			CALCULATE(
			    DIVIDE(
			    [# adhérents avec un ticket depuis début de l'année],
			    [Nombre d'adhérents actifs ou suspendus],
			    0
			    ),
			    ALL('Utilisateur')
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Tickets
		lineageTag: 24b8594b-d7ca-4f46-be1e-38523ce17705

		changedProperty = Name

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure '% adhérents avec un ticket ouvert' =
			
			CALCULATE(
			    DIVIDE(
			    [# adhérents avec un ticket ouvert],
			    [Nombre d'adhérents actifs ou suspendus],
			    0
			    ),
			    ALL('Utilisateur')
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Tickets
		lineageTag: 3dcdd0a5-1dea-4fdd-9b82-381a7f507add

		changedProperty = Name

		changedProperty = FormatString

		changedProperty = DisplayFolder

	measure '% effectif avec INS qualifié' =
			
			DIVIDE(
			    [Effectif avec INS qualifié],
			    'Evolution retard'[Nombre de salariés suivis],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\Effectif
		lineageTag: 1d3b161a-2b8d-431c-a69b-99f58b168fff

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure '% nouveaux adhérents sans FE' =
			
			var Aujourdhui = Max('Date principale'[Date])
			var NouveauxAdherents = CALCULATE(
			                            DISTINCTCOUNT('Adhérent (actuel)'[Matricule entreprise]),
			                            'Adhérent (actuel)'[Date création dossier entreprise] - Aujourdhui < 365
			)
			var NouveauxSansFE = CALCULATE(
			                            NouveauxAdherents,
			                            'Adhérent (actuel)'[Statut FE] = "Aucune FE renseignée"
			)
			
			RETURN
			divide(
			    NouveauxSansFE,
			    NouveauxAdherents,
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: FE
		lineageTag: 579d601f-c3d4-49e6-adca-f9db26c2916d

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure Afficher_jusqua_Cible = ```
			
			VAR CurDate  = DATEVALUE( MAX ( 'Dates_Futur'[EndOfMonth] ) )
			VAR Target0  =
			   COALESCE(
			    SELECTEDVALUE( Dates_Cible[Date] ),
			    MAXX( ALLSELECTED( Dates_Cible[Date] ), Dates_Cible[Date] )
			)
			VAR Target = DATEVALUE( EOMONTH( Target0, 0 ) )  // option: caler à fin de mois
			RETURN
			    NOT ISBLANK( Target ) && CurDate <= Target
			
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: FE\Simulation
		lineageTag: af5d126f-5e81-40cd-9b31-5cd1b988b136

		changedProperty = DisplayFolder

		changedProperty = Name

	measure APP_DerniereValeur =
			
			VAR d0 = [DerniereDateReelleAPP]
			
			RETURN
			    CALCULATE (
			        [% adhérents à jour d'AMT primaire (fin de période)],
			        TREATAS ( ROW ( "Date", d0 ), 'Date principale'[Date] )
			    )
		displayFolder: AMT\Simulation
		lineageTag: 58eea617-ce6a-4866-8139-d982451434d7

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Date Référence' = ```
			
			VAR Choix =
			    SELECTEDVALUE ( 'Choix Date'[Choix], "Aujourd'hui" )
			RETURN
			SWITCH(
			    TRUE(),
			    Choix = "Aujourd'hui",
			        TODAY(),
			    Choix = "31/12 année précédente",
			        DATE( YEAR( TODAY() ) - 1, 12, 31 ),
			    TODAY()
			)
			
			```
		formatString: General Date
		displayFolder: Date
		lineageTag: 4a674de7-cad6-4010-bf59-b1eba1728e2c

		changedProperty = DisplayFolder

		changedProperty = Name

	measure DerniereDateReelle = ```
			
			VAR d =
			    CALCULATE (
			        MAX ( 'Date principale'[Date] ),
			        FILTER ( ALLSELECTED ( 'Date principale' ),
			        NOT ISBLANK('Evolution effectif'[% adhérents à jour de FE (fin de période)])
			    ))
			RETURN 
			d
			```
		formatString: General Date
		displayFolder: FE\Simulation
		lineageTag: b1b388be-5476-4973-9615-455c6619817f

		changedProperty = DisplayFolder

		changedProperty = Name

	measure DerniereDateReelleAPP = ```
			
			VAR d =
			    CALCULATE (
			        MAX ( 'Date principale'[Date] ),
			        FILTER ( ALLSELECTED ( 'Date principale' ),
			        NOT ISBLANK('Evolution effectif'[% adhérents à jour d'AMT primaire (fin de période)])
			    ))
			RETURN 
			d
			```
		formatString: General Date
		displayFolder: AMT\Simulation
		lineageTag: e2721b37-1621-4b9a-b17e-d9a64b194936

		changedProperty = DisplayFolder

		changedProperty = Name

	measure DerniereDateReelleTxService = ```
			
			VAR d =
			    CALCULATE (
			        MAX ( 'Date principale'[Date] ),
			        FILTER ( ALLSELECTED ( 'Date principale' ),
			        NOT ISBLANK([Taux de service coalesce])
			    ))
			RETURN 
			d
			```
		formatString: General Date
		displayFolder: Taux de service\Simulation
		lineageTag: 718f3878-19b6-4795-8f5e-ee55469f3df0

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Données à jour à la dernière MAJ des données' = ```
			
			"Données à jour au : " & 
			FORMAT(
			    MAX(
			        '! Dernier rafraîchissement des données !'[Dernier rafraîchissement des données]),
			        "DD mmmm YYYY HH:mm", 
			        "fr-FR"
			)
			
			```
		displayFolder: Date
		lineageTag: b6e324fb-fc1d-4706-b07e-1d9dc702cf3e

		changedProperty = DisplayFolder

		changedProperty = Name

	measure Dummy = [Nombre de visites réalisées (RDV)] * 0.06
		lineageTag: 0f85e191-6cdc-43bb-b793-0bbe092b3c2b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Durée de traitement des tickets' =
			
			COALESCE(
			    [Durée moyenne traitement tickets (j)],
			    ""
			)
		formatString: 0
		lineageTag: d804d10b-f730-42a3-abf2-f12e532da981

		changedProperty = Name

		changedProperty = FormatString

	measure 'Effectif avec INS qualifié' =
			
			CALCULATE(
			    'Salariés'[Effectif suivi],
			    'Salarié (actuel)'[Statut INS] = "Qualifiée"
			)
		formatString: #,0
		displayFolder: Suivi des indicateurs\Effectif
		lineageTag: 60ab112f-9069-4e2c-b536-c347c21f0e4a

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Effectif Dynamique' = ```
			
			VAR ChoixSelectionne = SELECTEDVALUE('Choix Date'[Choix]) 
			
			VAR DateCible = 
			    SWITCH(
			        ChoixSelectionne,
			        "Date du jour", TODAY(),
			        "31/12 de l'année précédente", DATE(year(TODAY()) - 1, 12, 31),
			        BLANK()
			    )
			
			RETURN
			    CALCULATE(
			        [Evolution Effectif - effectif suivi], -- Votre mesure d'effectif existante (ex: COUNTROWS('Table Employes'))
			        FILTER(
			            ALL('Date principale'), -- Ignore tous les filtres de date existants
			            'Date principale'[Date] = DateCible -- Applique le filtre à la date cible
			        )
			    )
			```
		formatString: 0
		displayFolder: Date
		lineageTag: 762026e8-c80a-4d51-b8dc-260702f9e2ab

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Evolution Effectif - effectif suivi' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			CALCULATE(
			    COALESCE(
			        ('Evolution effectif'[Effectif suivi figé non intérimaire fin de période]+'Evolution effectif'[Effectif suivi figé intérimaire fin de période]),
			        0
			    ),
			    'Date principale'[Date] <= DateSnapshot
			)
		formatString: #,0
		displayFolder: Suivi des indicateurs\Effectif
		lineageTag: eb916d23-8446-4d70-8b66-6209c795c78d

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure FE_DerniereValeur =
			
			VAR d0 = [DerniereDateReelle]
			RETURN
			    CALCULATE (
			        [% adhérents à jour de FE (fin de période)],
			        TREATAS ( ROW ( "Date", d0 ), 'Date principale'[Date] )
			    )
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: FE\Simulation
		lineageTag: ac21a2fa-1300-46c0-abeb-e5b9290577cf

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Filtres actifs' = ```
			
			VAR SelDate = [Période (Du au)]
			VAR SelTaille =
			    IF(
			        ISFILTERED('Adhérent (actuel)'[Taille d'entreprise]),
			        VAR s = CONCATENATEX(VALUES('Adhérent (actuel)'[Taille d'entreprise]), 'Adhérent (actuel)'[Taille d'entreprise], ", ")
			        RETURN IF(LEN(s)=0, "Aucun", s),
			        "Tous"
			    )
			VAR SelType =
			    IF(
			        ISFILTERED('Adhérent (actuel)'[Type d'entreprise]),
			        VAR s = CONCATENATEX(VALUES('Adhérent (actuel)'[Type d'entreprise]), 'Adhérent (actuel)'[Type d'entreprise], ", ")
			        RETURN IF(LEN(s)=0, "Aucun", s),
			        "Tous"
			    )
			VAR SelUtilisateur =
			    IF(
			        ISFILTERED('Utilisateur'[Nom utilisateur]),
			        VAR s = CONCATENATEX(VALUES('Utilisateur'[Nom utilisateur]), 'Utilisateur'[Nom utilisateur], ", ")
			        RETURN IF(LEN(s)=0, "Aucun", s),
			        "Tous"
			    )    
			RETURN
			    "Dates : " & SelDate & " | Taille d'entreprise : " & SelTaille & " | Type d'entreprise : " & SelType & " | Préventeur : " & SelUtilisateur
			
			```
		lineageTag: 6e73330b-5d2e-4251-95a5-c9a90c9a66c9

		changedProperty = Name

	measure 'Max Y nbre de visites réalisées (RDV)' =
			
			MAXX(
			    ALLSELECTED('Date principale'[NomMoisAnnee]),
			    'RDV'[Nombre de visites réalisées (RDV)]
			    )
			    * 1.3
		lineageTag: 3bd1eb97-a4ca-45b9-b7b1-3471e770a9a1

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Mesure = "aa"
		displayFolder: FE\Simulation
		lineageTag: 2a196a2e-c85d-42e2-b900-51cc561c5674

		changedProperty = DisplayFolder

	measure 'Nb Mois Simulation' = ```
			
			VAR DateCible = SELECTEDVALUE('Dates_Futur'[Date]) // Récupère la date choisie dans le segment
			VAR DateReference = TODAY() // Ou la dernière date de vos données : MAX('Date principale'[Date])
			
			RETURN
			    // Calcul de la différence en mois
			    IF(
			        ISBLANK(DateCible) || DateCible <= DateReference, 
			        BLANK(), // Sécurité si pas de date ou date passée
			        DATEDIFF(DateReference, DateCible, MONTH)
			    )
			```
		formatString: 0
		displayFolder: FE\Simulation
		lineageTag: d4ed7a7a-7cc5-4b61-b32d-502644623b59

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Nbre annexes 4' =
			
			CALCULATE(
			    [Nombre de documents émis],
			    'Documents émis - type document'[Type document détaillé] in {"Attestation de suivi avec annexe 4 temporaire", "Attestation de suivi avec annexe 4 permanente"}
			)
		formatString: 0
		displayFolder: Visites
		lineageTag: 921c7d50-158c-4138-ae3d-7e55db9c1ee1

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Nbre de tickets' =
			
			COALESCE(
			    'CRM - tickets'[# tickets],
			    0
			)
		formatString: 0
		lineageTag: 88aded22-1b96-44c7-9e7e-42df6a9361b9

		changedProperty = Name

	measure 'Nbre orientations PDP' = ```
			
			CALCULATE(
			    'Demande consultation spécialisée'[# demandes consultation spécialisée], 
			    'Demande consultation spécialisée - type visite demandée'[Type détaillé visite demandée] = "Cellule Maintien en Emploi"
			)
			```
		formatString: 0
		displayFolder: Orientations
		lineageTag: c7cf4916-68cd-4d32-9856-15c1bf376c0e

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Nbre RDV / Effectif suivi' =
			
			var RDV = [Nombre de RDV]
			var effectif = 'Evolution effectif'[Effectif suivi non intérimaire fin de période]
			
			return
			DIVIDE(
			    RDV,
			    Effectif,
			    0
			    )
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Visites
		lineageTag: 9839f6b7-39da-4428-8586-20759a991c27

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Nbre Visites / Effectif suivi' =
			
			var Visites = [Nombre de visites réalisées (RDV)]
			var effectif = 'Evolution effectif'[Effectif suivi non intérimaire fin de période]
			
			return
			DIVIDE(
			    Visites,
			    Effectif,
			    0
			    )
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Visites
		lineageTag: 153eeb8c-1b42-4ad5-860d-19c342e1ec88

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Nombre d''embauches PST depuis début de l''année' = ```
			
			VAR DateMaxDansContexte =                                  -- Dernière date visible dans le contexte courant
			    MAX ( 'Date principale'[Date] )
			RETURN
			CALCULATE (                                              -- Recalcule en imposant un filtre YTD sur la table de dates
			    DISTINCTCOUNT ( '1 - salariés PST'[matricule] ),     -- Compte des salariés distincts embauchés
			    DATESYTD ( 'Date principale'[Date], "31/12" ),      -- Fenêtre YTD selon le calendrier; paramètre fin d'année optionnel
			    KEEPFILTERS (                                       -- Conserve les filtres existants et les croise avec YTD
			        'Date principale'[Date] <= DateMaxDansContexte   -- Garantit la borne supérieure au max du contexte (utile si DATESYTD voit plus large)
			    )
			)
			
			```
		formatString: 0
		lineageTag: 78e5928b-8e7b-40b8-bdce-3fb4ec8e1f0a

		changedProperty = Name

	measure 'Nombre de fins de contrat PST YTD' = ```
			
			VAR DateMaxDansContexte =                                     -- Dernière date visible dans le contexte courant (borne supérieure) 
			    MAX ( 'Date principale'[Date] )                           -- Utilise la dimension temps pour caler le "to-date" 
			RETURN
			CALCULATE (                                                   -- Recalcule en appliquant un filtre temps YTD + relation inactive 
			    DISTINCTCOUNT ( '1 - salariés PST'[matricule] ),              -- Comptage distinct des salariés concernés 
			    DATESYTD ( 'Date principale'[Date], "31/12" ),          -- Fenêtre Year-To-Date basée sur le calendrier fiscal (31/12 par défaut) 
			    KEEPFILTERS ( 'Date principale'[Date] <= DateMaxDansContexte ), -- Sécurise la borne supérieure au max visible (to-date)
			    USERELATIONSHIP ( '1 - salariés PST'[Fin de contrat], 'Date principale'[Date] ) -- Active la relation inactive sur Fin contrat le temps du calcul
			)
			-- Description : Compte les salariés PST distincts dont la Fin contrat tombe dans la fenêtre Year-To-Date (selon 'Date principale') jusqu'à la dernière date visible, en activant la relation inactive sur 'Fin contrat' pour que le filtre calendrier s'applique correctement.
			
			```
		formatString: 0
		lineageTag: c9bdfc50-1a6d-40dd-bebe-6c1283c4cf40

		changedProperty = Name

	measure 'nouveaux adhérentss' =
			
			var Aujourdhui = Max('Date principale'[Date])
			var NouveauxAdherents = CALCULATE(
			                            [Nombre d'adhérents actifs ou suspendus],
			                            'Adhérent (actuel)'[Date création dossier entreprise] - Aujourdhui < 365
			)
			
			RETURN
			NouveauxAdherents
		formatString: 0
		displayFolder: FE
		lineageTag: 2914a2df-2ea9-4947-80b1-4ae11384700e

		changedProperty = DisplayFolder

		changedProperty = Name

	measure ObjectifPct = DIVIDE(SELECTEDVALUE('Objectif (%)'[Objectif (%)], 100), 100)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: FE\Simulation
		lineageTag: e416c982-02dd-4925-ba39-abe2f996ab5a

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Période (Du au)' =
			
			Var DateMax = [Date Fin Arrêté]
			Var DateMin = EDATE(DateMax, -12)+1
			
			RETURN
			format(DateMin,"DD mmmm YYYY", "fr-FR")&" au "&format(DateMax,"DD mmmm YYYY", "fr-FR")
		displayFolder: Suivi des indicateurs\Date
		lineageTag: 4fd4a2b3-0129-4169-9b82-e3707de61ee6

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Plans MEE avec maintien au poste' = ```
			
			CALCULATE(
			    'Plan MEE'[# plans MEE], 
			    'Plan MEE - informations'[Situation salarié après plan MEE] in {"En poste avec aménagement (dans l'entreprise initiale)","En poste sans aménagement (dans l'entreprise initiale)"}
			 )
			```
		formatString: 0
		displayFolder: Consultations Spécialisées\PDP
		lineageTag: 6d1a0a7f-9758-4b8f-bf00-89e229f51de9

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Plans MEE avec maintien dans l''emploi' = ```
			
			CALCULATE(
			    'Plan MEE'[# plans MEE], 
			    'Plan MEE - informations'[Catégorie résultat plan MEE] = "Avec maintien en emploi" 
			 )
			```
		formatString: 0
		displayFolder: Consultations Spécialisées\PDP
		lineageTag: 7652f95e-b521-4166-9f15-d6159b9cab4b

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Plans MEE avec reclassement' = ```
			
			CALCULATE(
			    'Plan MEE'[# plans MEE], 
			    'Plan MEE - informations'[Situation salarié après plan MEE] in {"Reclassé en interne (dans l'entreprise initiale)","Reclassé en externe (hors de l'entreprise initiale)"}
			 )
			```
		formatString: 0
		displayFolder: Consultations Spécialisées\PDP
		lineageTag: ce58395c-0759-4316-92d0-c4b2f8e821d3

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Plans MEE refusé par le salarié' = ```
			
			CALCULATE(
			    'Plan MEE'[# plans MEE], 
			    'Plan MEE - dispositifs'[Motif de non réalisation du dispositif] = "Refus du salarié"
			)
			```
		formatString: 0
		displayFolder: Consultations Spécialisées\PDP
		lineageTag: 424c2929-e912-41b6-847a-053fde39547b

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Plans MEE sans solution' = ```
			
			CALCULATE(
			    'Plan MEE'[# plans MEE], 
			    'Plan MEE - informations'[SOUS-catégorie résultat plan MEE] = "Sans solution" 
			 )
			```
		formatString: 0
		displayFolder: Consultations Spécialisées\PDP
		lineageTag: 768857d3-1905-40ad-8264-3207e964aca1

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Ratio maintien au poste / plan MEE' =
			
			DIVIDE(
			    [Plans MEE avec maintien au poste],
			    'Plan MEE'[# plans MEE],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Consultations Spécialisées\PDP
		lineageTag: cf796004-bdd7-40d8-ae3c-96650e7895ea

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Ratio maintien dans l''emploi / plan MEE' =
			
			DIVIDE(
			    [Plans MEE avec maintien dans l'emploi],
			    'Plan MEE'[# plans MEE],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Consultations Spécialisées\PDP
		lineageTag: 0b5529e2-a01e-43c3-8df7-5d803fb08c38

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Ratio plan MEE sans solution / plan MEE' =
			
			DIVIDE(
			    [Plans MEE sans solution],
			    'Plan MEE'[# plans MEE],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Consultations Spécialisées\PDP
		lineageTag: 82eda09b-6c7c-443f-8e86-45d30449f910

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Ratio reclassement / plan MEE' =
			
			DIVIDE(
			    [Plans MEE avec reclassement],
			    'Plan MEE'[# plans MEE],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Consultations Spécialisées\PDP
		lineageTag: 62117a97-25af-4d77-8d7b-c9e72c11736d

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Ratio refus du salarié / plan MEE' =
			
			DIVIDE(
			    [Plans MEE refusé par le salarié],
			    'Plan MEE'[# plans MEE],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Consultations Spécialisées\PDP
		lineageTag: 960d71b3-e091-4845-8305-1f2f8e58b004

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'RDV / effectif Evol vs last year' = ```
			
			VAR TxConvoc_Period = [Nbre RDV / Effectif suivi]  // Mesure de la période courante; utilisée comme numérateur de la variation 
			VAR TxConvoc_LastYear = [RDV / effectif SameLastYear]  // Mesure de la période N-1; dénominateur et référence de comparaison 
			VAR Evolution_Proportion =  // Variation relative propre, gère les divisions par zéro via DIVIDE 
			    DIVIDE( TxConvoc_Period - TxConvoc_LastYear, TxConvoc_LastYear, 0 )
			VAR Signe_Affichage =  // Préfixe du signe basé sur 0 car la variation est une proportion (positif/négatif) 
			    IF( Evolution_Proportion >= 0, "+ ", "- " )
			VAR Valeur_Pourcent_Formattee =  // Mise en forme en pourcentage avec une décimale, appliquée sur la valeur absolue pour éviter un double signe 
			    FORMAT( ABS(Evolution_Proportion), "0.00 %" )
			RETURN
			    "("&Signe_Affichage & Valeur_Pourcent_Formattee&")"  // Sortie texte: utile pour cartes/étiquettes; préférer garder une version numérique pour analyses 
			
			/*
			Rôle de la mesure:
			- Produit un affichage texte de l’évolution des RDV vs N-1 avec signe explicite, ex: "+ 12,3%" ou "- 4,5%".
			- Le calcul de variation utilise DIVIDE pour la robustesse et sépare calcul (proportion) et présentation (signe/format).
			- Pour analyses et agrégations, utiliser en priorité une version numérique: RDV Evol vs last year (num), avec un format dynamique “+0.0%;-0.0%;0.0%”.
			*/ 
			
			```
		displayFolder: Visites
		lineageTag: aeb4342a-c613-45d3-a2e1-849814b562e3

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'RDV / effectif SameLastYear' = ```
			
			VAR ContexteDatesActuel = VALUES('Date principale'[Date]) // Garantit que l’on décale exactement le set de dates du visuel sans altérer d’autres filtres
			
			RETURN
			CALCULATE(
			[Nbre RDV / Effectif suivi],                            // Utilise la mesure source telle quelle
			DATEADD(ContexteDatesActuel, -1, YEAR)      // Décale la période d’un an en arrière, équivalent à SAMEPERIODLASTYEAR mais explicite et flexible
			) 
			
			// Rôle: calcule les RDV pour la même période de l’année précédente, en respectant le grain (jour/mois/trimestre) et les filtres actifs de la table de dates, sans supprimer ces filtres
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Visites
		lineageTag: 071ccfa1-d27b-46ae-a5a0-feadd2259f32

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'RDV Evol vs last year' = ```
			
			VAR RDV_Period = [Nombre de RDV]  // Mesure de la période courante; utilisée comme numérateur de la variation 
			VAR RDV_LastYear = [RDV SameLastYear]  // Mesure de la période N-1; dénominateur et référence de comparaison 
			VAR Evolution_Proportion =  // Variation relative propre, gère les divisions par zéro via DIVIDE 
			    DIVIDE( RDV_Period - RDV_LastYear, RDV_LastYear, 0 )
			VAR Signe_Affichage =  // Préfixe du signe basé sur 0 car la variation est une proportion (positif/négatif) 
			    IF( Evolution_Proportion >= 0, "+ ", "- " )
			VAR Valeur_Pourcent_Formattee =  // Mise en forme en pourcentage avec une décimale, appliquée sur la valeur absolue pour éviter un double signe 
			    FORMAT( ABS(Evolution_Proportion), "0.00 %" )
			RETURN
			    "("&Signe_Affichage & Valeur_Pourcent_Formattee&")"  // Sortie texte: utile pour cartes/étiquettes; préférer garder une version numérique pour analyses 
			
			/*
			Rôle de la mesure:
			- Produit un affichage texte de l’évolution des RDV vs N-1 avec signe explicite, ex: "+ 12,3%" ou "- 4,5%".
			- Le calcul de variation utilise DIVIDE pour la robustesse et sépare calcul (proportion) et présentation (signe/format).
			- Pour analyses et agrégations, utiliser en priorité une version numérique: RDV Evol vs last year (num), avec un format dynamique “+0.0%;-0.0%;0.0%”.
			*/ 
			
			```
		displayFolder: Visites
		lineageTag: 21c6ca7a-d539-408d-b352-be264db47bbe

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'RDV SameLastYear' = ```
			
			VAR ContexteDatesActuel = VALUES('Date principale'[Date]) // Garantit que l’on décale exactement le set de dates du visuel sans altérer d’autres filtres
			
			RETURN
			CALCULATE(
			[Nombre de RDV],                            // Utilise la mesure source telle quelle
			DATEADD(ContexteDatesActuel, -1, YEAR)      // Décale la période d’un an en arrière, équivalent à SAMEPERIODLASTYEAR mais explicite et flexible
			) 
			
			// Rôle: calcule les RDV pour la même période de l’année précédente, en respectant le grain (jour/mois/trimestre) et les filtres actifs de la table de dates, sans supprimer ces filtres
			```
		formatString: #,0
		displayFolder: Visites
		lineageTag: 15b54d8f-b2e8-40d5-8744-8215c7df7824

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Sous Titre Adhérents sans FE en date du' =
			
			Var DateMax = Max('Date principale'[Date])
			
			RETURN
			"Adhérents sans FE en date du " & format(DateMax,"DD mmmm YYYY", "fr-FR")
		displayFolder: Titres
		lineageTag: a7078c36-9636-4a86-806f-36384ccd956f

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Sous-titre adhérents à jour d''APP' =
			
			Var DateMax = Max('Date principale'[Date])
			Var DateMin = DateMax - 365.25*4 + 1
			
			RETURN
			"Adhérents ayant bénéficié d'une APP entre le "& format(DateMin,"DD mmmm YYYY", "fr-FR")& " et le " & format(DateMax,"DD mmmm YYYY", "fr-FR")
		displayFolder: Titres
		lineageTag: 43b52a30-cffb-460b-9287-e71c4c2ed064

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Sous-titre adhérents en retard d''APP' =
			
			Var DateMax = Max('Date principale'[Date])
			Var DateMin = DateMax - 365.25*4 + 1
			
			RETURN
			"Adhérents n'ayant pas bénéficié d'APP entre le "& format(DateMin,"DD mmmm YYYY", "fr-FR")& " et le " & format(DateMax,"DD mmmm YYYY", "fr-FR")
		displayFolder: Titres
		lineageTag: 07f38bd3-0948-4334-a51a-633c2c79ae7c

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Sous-titre adhérents FE à mettre à jour' =
			
			Var DateMax = Max('Date principale'[Date])-365
			
			RETURN
			"Adhérents dont la FE n'est pas à jour en date du "& format(DateMax,"DD mmmm YYYY", "fr-FR")&"."
		displayFolder: Titres
		lineageTag: ee8e82f1-0ae4-48e0-a978-a01cc992a275

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Sous-titre adhérents sans FE' =
			
			Var DateMax = Max('Date principale'[Date])-365
			
			RETURN
			"Adhérents sans FE dont la date de premier statut actif est supérieure au "& format(DateMax,"DD mmmm YYYY", "fr-FR")&". Non impacté par le filtre de dates."
		displayFolder: Titres
		lineageTag: 9bb486ba-d525-4f87-8459-f9a3e97896ad

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Taux d''annexes 4 Evol vs last year' = ```
			
			VAR Visites_Period = [Taux d'Annexes4]  // Mesure de la période courante; utilisée comme numérateur de la variation 
			VAR Visites_LastYear = [Taux d'annexes 4 SameLastYear]  // Mesure de la période N-1; dénominateur et référence de comparaison 
			VAR Evolution_Proportion =  // Variation relative propre, gère les divisions par zéro via DIVIDE 
			    DIVIDE( Visites_Period - Visites_LastYear, Visites_LastYear, 0 )
			VAR Signe_Affichage =  // Préfixe du signe basé sur 0 car la variation est une proportion (positif/négatif) 
			    IF( Evolution_Proportion >= 0, "+ ", "- " )
			VAR Valeur_Pourcent_Formattee =  // Mise en forme en pourcentage avec une décimale, appliquée sur la valeur absolue pour éviter un double signe 
			    FORMAT( ABS(Evolution_Proportion), "0.00 %" )
			RETURN
			    "("&Signe_Affichage & Valeur_Pourcent_Formattee&")"  // Sortie texte: utile pour cartes/étiquettes; préférer garder une version numérique pour analyses 
			
			/*
			Rôle de la mesure:
			- Produit un affichage texte de l’évolution des visites vs N-1 avec signe explicite, ex: "+ 12,3%" ou "- 4,5%".
			- Le calcul de variation utilise DIVIDE pour la robustesse et sépare calcul (proportion) et présentation (signe/format).
			- Pour analyses et agrégations, utiliser en priorité une version numérique: Visites Evol vs last year (num), avec un format dynamique “+0.0%;-0.0%;0.0%”.
			*/ 
			
			```
		displayFolder: Visites
		lineageTag: 246c3427-c464-4b3f-8624-ebc77f587e33

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Taux d''annexes 4 SameLastYear' = ```
			
			VAR ContexteDatesActuel = VALUES('Date principale'[Date]) // Garantit que l’on décale exactement le set de dates du visuel sans altérer d’autres filtres
			
			RETURN
			CALCULATE(
			[Taux d'Annexes4],                            // Utilise la mesure source telle quelle
			DATEADD(ContexteDatesActuel, -1, YEAR)      // Décale la période d’un an en arrière, équivalent à SAMEPERIODLASTYEAR mais explicite et flexible
			) 
			
			// Rôle: calcule les RDV pour la même période de l’année précédente, en respectant le grain (jour/mois/trimestre) et les filtres actifs de la table de dates, sans supprimer ces filtres
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Visites
		lineageTag: 03f7175a-877c-4f51-a090-a3905393f8ba

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Taux d''Annexes4' = ```
			
			VAR NombreVisitesRealisees = [Nombre de visites réalisées (RDV)] -- Variable pour stocker le nombre de visites réalisées
			VAR NombreAnnexes4 = [Nbre annexes 4] -- Variable pour stocker le nombre total de Annexes4
			
			RETURN
			    COALESCE(
			        DIVIDE(
			        NombreAnnexes4, --  nombre total de convocations
			        NombreVisitesRealisees, -- nombre de visites réalisées
			        0 -- Valeur de retour en cas de division par zéro
			    ),
			    0
			    )
			
			-- Cette mesure calcule le taux de convocations en divisant le nombre de visites réalisées
			-- par le nombre total de convocations. Elle utilise DIVIDE pour éviter les erreurs de division par zéro.
			
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Visites
		lineageTag: 9a68ea0e-06e6-4fc6-b93d-0d2c5fc71986

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Taux d''inaptitude' = ```
			
			VAR NombreVisitesRealisees = [Nombre de visites réalisées (RDV)] -- Variable pour stocker le nombre de visites réalisées
			VAR NombreInaptitude = [Nombre d'avis d'inaptitude] -- Variable pour stocker le nombre total de Inaptitude
			
			RETURN
			    COALESCE(
			        DIVIDE(
			        NombreInaptitude, --  nombre total de convocations
			        NombreVisitesRealisees, -- nombre de visites réalisées
			        0 -- Valeur de retour en cas de division par zéro
			    ),
			    0
			    )
			
			-- Cette mesure calcule le taux de convocations en divisant le nombre de visites réalisées
			-- par le nombre total de convocations. Elle utilise DIVIDE pour éviter les erreurs de division par zéro.
			
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Visites
		lineageTag: fe19721b-d869-48d5-8437-d0fe20016e84

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Taux d''inaptitude Evol vs last year' = ```
			
			VAR Visites_Period = [Taux d'inaptitude]  // Mesure de la période courante; utilisée comme numérateur de la variation 
			VAR Visites_LastYear = [Taux d'inaptitude SameLastYear]  // Mesure de la période N-1; dénominateur et référence de comparaison 
			VAR Evolution_Proportion =  // Variation relative propre, gère les divisions par zéro via DIVIDE 
			    DIVIDE( Visites_Period - Visites_LastYear, Visites_LastYear, 0 )
			VAR Signe_Affichage =  // Préfixe du signe basé sur 0 car la variation est une proportion (positif/négatif) 
			    IF( Evolution_Proportion >= 0, "+ ", "- " )
			VAR Valeur_Pourcent_Formattee =  // Mise en forme en pourcentage avec une décimale, appliquée sur la valeur absolue pour éviter un double signe 
			    FORMAT( ABS(Evolution_Proportion), "0.00 %" )
			RETURN
			    "("&Signe_Affichage & Valeur_Pourcent_Formattee&")"  // Sortie texte: utile pour cartes/étiquettes; préférer garder une version numérique pour analyses 
			
			/*
			Rôle de la mesure:
			- Produit un affichage texte de l’évolution des visites vs N-1 avec signe explicite, ex: "+ 12,3%" ou "- 4,5%".
			- Le calcul de variation utilise DIVIDE pour la robustesse et sépare calcul (proportion) et présentation (signe/format).
			- Pour analyses et agrégations, utiliser en priorité une version numérique: Visites Evol vs last year (num), avec un format dynamique “+0.0%;-0.0%;0.0%”.
			*/ 
			
			```
		displayFolder: Visites
		lineageTag: e18357e5-bc95-4e68-99ce-24fb2c892cfd

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Taux d''inaptitude SameLastYear' = ```
			
			VAR ContexteDatesActuel = VALUES('Date principale'[Date]) // Garantit que l’on décale exactement le set de dates du visuel sans altérer d’autres filtres
			
			RETURN
			CALCULATE(
			[Taux d'inaptitude],                            // Utilise la mesure source telle quelle
			DATEADD(ContexteDatesActuel, -1, YEAR)      // Décale la période d’un an en arrière, équivalent à SAMEPERIODLASTYEAR mais explicite et flexible
			) 
			
			// Rôle: calcule les RDV pour la même période de l’année précédente, en respectant le grain (jour/mois/trimestre) et les filtres actifs de la table de dates, sans supprimer ces filtres
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Visites
		lineageTag: 8141a8c8-e5f6-4532-9357-c97f056af053

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Taux d''orientations PDP' = ```
			
			VAR NombreVisitesRealisees = [Nombre de visites réalisées (RDV)] -- Variable pour stocker le nombre de visites réalisées
			VAR NombreOrientationsPDP = [Nbre orientations PDP] -- Variable pour stocker le nombre total de Orientations PDP
			
			RETURN
			    COALESCE(
			        DIVIDE(
			        NombreOrientationsPDP, --  nombre total de convocations
			        NombreVisitesRealisees, -- nombre de visites réalisées
			        0 -- Valeur de retour en cas de division par zéro
			    ),
			    0
			    )
			
			-- Cette mesure calcule le taux de convocations en divisant le nombre de visites réalisées
			-- par le nombre total de convocations. Elle utilise DIVIDE pour éviter les erreurs de division par zéro.
			
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Visites
		lineageTag: 2889196e-e02e-48fd-8400-d5827f4cb955

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Taux de convocation SameLastYear' =
			
			VAR ContexteDatesActuel = VALUES('Date principale'[Date]) // Garantit que l’on décale exactement le set de dates du visuel sans altérer d’autres filtres
			
			RETURN
			CALCULATE(
			[Taux de convocations],                            // Utilise la mesure source telle quelle
			DATEADD(ContexteDatesActuel, -1, YEAR)      // Décale la période d’un an en arrière, équivalent à SAMEPERIODLASTYEAR mais explicite et flexible
			)
			
			// Rôle: calcule les RDV pour la même période de l’année précédente, en respectant le grain (jour/mois/trimestre) et les filtres actifs de la table de dates, sans supprimer ces filtres
			```
		displayFolder: Visites
		lineageTag: 51ca9d43-e10f-420d-a04b-479b19dee1ae

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Taux de service (Passé uniquement)' = ```
			
			VAR DateCourante = SELECTEDVALUE('Dates_Futur'[Date])
			RETURN
			    IF(
			        DateCourante <= TODAY(),
			        CALCULATE(
			            [Taux de service coalesce],
			            TREATAS(
			                VALUES('Dates_Futur'[Date]),
			                'Date principale'[Date]
			            )
			        ),
			        BLANK()
			    )
			
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Taux de service\Simulation
		lineageTag: 29935ba3-607e-4c25-b6d3-32f4fc12b397

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Taux de service coalesce' = ```
			
			VAR TauxRetard = [Taux de retard] // Stocke la valeur de la mesure [Taux de retard]
			VAR TauxService = 1 - TauxRetard // Calcule le taux de service en soustrayant le taux de retard de 1
			
			RETURN
			     COALESCE(
			      IF(
			      ISBLANK(TauxRetard), // Vérifie si la valeur du taux de retard est vide
			      1, // Retourne une valeur vide si le taux de retard est vide
			      IF(
			          TauxService = 1, // Vérifie si le taux de service est égal à 1 (100%)
			          1, // Retourne une valeur vide si le taux de service est égal à 100%
			          TauxService // Retourne le taux de service calculé
			      )
			  ),
			  ""
			  )
			
			/*
			Description :
			Cette mesure calcule le taux de service en soustrayant le taux de retard de 1.
			Elle utilise une variable pour stocker la valeur de [Taux de retard] et une condition IF pour vérifier si la valeur est vide ou si le taux de service est égal à 100%.
			Si le taux de retard est vide ou si le taux de service est égal à 100%, la mesure retourne une valeur vide.
			*/
			
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Taux de service
		lineageTag: 0d0b213b-f9ed-40e5-a512-11bd20f86f44

		changedProperty = DisplayFolder

		changedProperty = Name

	measure Test =
			
			VAR DateSeuil = EDATE(TODAY(), -12)
			
			RETURN
			CALCULATETABLE(
			        VALUES('Adhérent (actuel)'[id_entreprise]), // Vérifie bien le nom exact de la colonne ID ici
			        'Adhérent (actuel)'[Date premier statut actif] >= DateSeuil
			    )
		formatString: 0
		lineageTag: 27d8edb8-4748-4289-a744-79554b47c434

		changedProperty = Name

	measure 'ticket créés par ...' =
			
			"Tickets créés par " & '[nom créateur ticket
		displayFolder: Titres
		lineageTag: a21614cc-46ff-454c-a506-e863450f9c3f

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Tickets en attente' =
			
			CALCULATE(
			    [# tickets],
			    'CRM - ticket - statut'[Statut ticket] = "En attente"
			)
		formatString: 0
		displayFolder: Tickets
		lineageTag: 9b440f68-e760-46c4-a4fb-9709755ad436

		changedProperty = Name

		changedProperty = DisplayFolder

	measure 'Tickets en attente adhérent' =
			
			CALCULATE(
			    [# tickets],
			    'CRM - ticket - statut'[Statut ticket] = "En attente réponse de l'adhérent"
			)
		formatString: 0
		displayFolder: Tickets
		lineageTag: fe3eb60d-ae79-401d-b294-398426287ec9

		changedProperty = Name

		changedProperty = DisplayFolder

	measure 'Tickets en-cours' =
			
			[Tickets en attente adhérent]+[Tickets en attente]+[Tickets ouverts]
		formatString: 0
		displayFolder: Tickets
		lineageTag: ea9fed61-1f38-435c-bfc2-75e7c1c10317

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Tickets fermés' =
			
			CALCULATE(
			    [# tickets],
			    'CRM - ticket - statut'[Statut ticket] = "Fermé"
			)
		formatString: 0
		displayFolder: Tickets
		lineageTag: ab110d0f-aaa3-4f61-88be-c79c32284d9c

		changedProperty = Name

		changedProperty = DisplayFolder

	measure 'Tickets ouverts' =
			
			CALCULATE(
			    [# tickets],
			    'CRM - ticket - statut'[Statut ticket] = "Ouvert"
			)
		formatString: 0
		displayFolder: Tickets
		lineageTag: cece52b7-ce1e-4245-95c5-8a61da432286

		changedProperty = Name

		changedProperty = DisplayFolder

	measure 'Titre Nombre d''adhérents actifs ou suspendus' =
			
			"Nombre d'adhérents actifs ou suspendus au "& format([Date Fin Arrêté], "DD mmmm YYYY", "fr-FR")
		displayFolder: Titres
		lineageTag: ff3781af-478d-4b30-97c4-6568c1c9d9f2

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Titre Nombre d''orientations PDP sur la période' =
			
			Var DateMax = Max('Date principale'[Date])
			Var DateMin = Min('Date principale'[Date])
			Var TimeFrame = DATESBETWEEN('Date principale'[Date],DateMax,DateMin)
			
			RETURN
			"Orientations vers la cellule maintien en emploi entre le "& format(DateMin,"DD mmmm YYYY", "fr-FR")&" et le "&format(DateMax,"DD mmmm YYYY", "fr-FR")
		displayFolder: Titres
		lineageTag: ed8b1ba7-4167-438f-b816-22dc6c8b3666

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Titre Nombre de convocations envoyées sur la période' =
			
			Var DateMax = Max('Date principale'[Date])
			Var DateMin = Min('Date principale'[Date])
			Var TimeFrame = DATESBETWEEN('Date principale'[Date],DateMax,DateMin)
			
			RETURN
			"Nombre de convocations envoyées entre le "& format(DateMin,"DD mmmm YYYY", "fr-FR")&" et le "&format(DateMax,"DD mmmm YYYY", "fr-FR")
		displayFolder: Titres
		lineageTag: ec417a32-fd96-4d85-aa75-818e73a0d520

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Titre Nombre de réclamations reçues sur la période' =
			
			Var DateMax = Max('Date principale'[Date])
			Var DateMin = Min('Date principale'[Date])
			Var TimeFrame = DATESBETWEEN('Date principale'[Date],DateMax,DateMin)
			
			RETURN
			"Nombre de réclamations reçues entre le "& format(DateMin,"DD mmmm YYYY", "fr-FR")&" et le "&format(DateMax,"DD mmmm YYYY", "fr-FR")
		displayFolder: Titres
		lineageTag: b094fafe-5f9b-4735-b40e-b2482f868d30

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Titre Nombre de salariés suivis' =
			
			"Nombre de salariés suivis au "& format([Date Fin Arrêté],"DD mmmm YYYY", "fr-FR")
		displayFolder: Titres
		lineageTag: 31b095df-918d-4a5a-96e1-6256bdae3322

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Titre Nombre de visites réalisées sur la période' =
			
			Var DateMax = Max('Date principale'[Date])
			Var DateMin = Min('Date principale'[Date])
			Var TimeFrame = DATESBETWEEN('Date principale'[Date],DateMax,DateMin)
			
			RETURN
			"Nombre de visites réalisées entre le "& format(DateMin,"DD mmmm YYYY", "fr-FR")&" et le "&format(DateMax,"DD mmmm YYYY", "fr-FR")
		displayFolder: Titres
		lineageTag: fd7f3639-e3a3-4793-a651-9f0e9e32f77e

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Titre période "Du ... au ..."' =
			
			Var DateMax = Max('Date principale'[Date])
			Var DateMin = Min('Date principale'[Date])
			Var TimeFrame = DATESBETWEEN('Date principale'[Date],DateMax,DateMin)
			
			RETURN
			"Du "& format(DateMin,"DD mmmm YYYY", "fr-FR")&" au "&format(DateMax,"DD mmmm YYYY", "fr-FR")&","
		displayFolder: Titres
		lineageTag: e2967e88-0963-4587-9797-51f910922f1f

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Titre répartition des adhérents sans FE par taille d''entreprise' =
			
			Var DateMax = Max('Date principale'[Date])
			
			RETURN
			"Répartition des adhérents sans FE en date du " & format(DateMax,"DD mmmm YYYY", "fr-FR")&" par taille d'entreprise"
		displayFolder: Titres
		lineageTag: e5ca1f4c-eca6-4257-8168-53b71468c6ad

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Tx convocation Evol vs last year' = ```
			
			VAR TxConvoc_Period = [Taux de convocations]  // Mesure de la période courante; utilisée comme numérateur de la variation 
			VAR TxConvoc_LastYear = [Taux de convocation SameLastYear]  // Mesure de la période N-1; dénominateur et référence de comparaison 
			VAR Evolution_Proportion =  // Variation relative propre, gère les divisions par zéro via DIVIDE 
			    DIVIDE( TxConvoc_Period - TxConvoc_LastYear, TxConvoc_LastYear, 0 )
			VAR Signe_Affichage =  // Préfixe du signe basé sur 0 car la variation est une proportion (positif/négatif) 
			    IF( Evolution_Proportion >= 0, "+ ", "- " )
			VAR Valeur_Pourcent_Formattee =  // Mise en forme en pourcentage avec une décimale, appliquée sur la valeur absolue pour éviter un double signe 
			    FORMAT( ABS(Evolution_Proportion), "0.00 %" )
			RETURN
			    "("&Signe_Affichage & Valeur_Pourcent_Formattee&")"  // Sortie texte: utile pour cartes/étiquettes; préférer garder une version numérique pour analyses 
			
			/*
			Rôle de la mesure:
			- Produit un affichage texte de l’évolution des RDV vs N-1 avec signe explicite, ex: "+ 12,3%" ou "- 4,5%".
			- Le calcul de variation utilise DIVIDE pour la robustesse et sépare calcul (proportion) et présentation (signe/format).
			- Pour analyses et agrégations, utiliser en priorité une version numérique: RDV Evol vs last year (num), avec un format dynamique “+0.0%;-0.0%;0.0%”.
			*/ 
			
			```
		displayFolder: Visites
		lineageTag: 9f5fcf62-8586-46aa-9367-d8ee76240ab5

		changedProperty = DisplayFolder

		changedProperty = Name

	measure TxService_DerniereValeur =
			
			VAR d0 = [DerniereDateReelleTxService]
			
			RETURN
			    CALCULATE (
			        [Taux de service coalesce],
			        TREATAS ( ROW ( "Date", d0 ), 'Date principale'[Date] )
			    )
		displayFolder: Taux de service\Simulation
		lineageTag: a1a98cd6-d497-4ade-a80b-3d3695146e58

		changedProperty = DisplayFolder

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TxService_Simule = ```
			
			VAR CurDate = MAX ( Dates_Futur[Date] )
			RETURN 
			IF(
			    CurDate <= [DerniereDateReelle], 
			    "", 
			    [TxService_Objectif_Courbe_Futur]
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Taux de service\Simulation
		lineageTag: c7dc58a4-c615-48b8-bd78-e53df6642d3b

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Utilisateur sélectionné' = ```
			
			VAR NomUtilisateurSelectionne = SELECTEDVALUE('Utilisateur'[Nom utilisateur])   // Récupère le nom de l'utilisateur sélectionné
			
			RETURN
			    IF(
			        NOT ISBLANK(NomUtilisateurSelectionne),                                 // Vérifie si un utilisateur est sélectionné
			        NomUtilisateurSelectionne,
			        "Ensemble du service"                                                   // Retourne un texte par défaut si aucun utilisateur n'est sélectionné
			    )
			
			/*
			Description :
			Cette mesure détermine l'utilisateur sélectionné dans le rapport Power BI.
			Elle retourne le nom de l'utilisateur si une sélection est faite, sinon elle retourne "Ensemble du service".
			*/
			
			```
		displayFolder: Divers
		lineageTag: c5aa017a-3922-4b12-9dca-6ac81979617b

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Visites / effectif Evol vs last year' = ```
			
			VAR Visites_Period = [Nbre Visites / Effectif suivi]  // Mesure de la période courante; utilisée comme numérateur de la variation 
			VAR Visites_LastYear = [Visites / effectif SameLastYear]  // Mesure de la période N-1; dénominateur et référence de comparaison 
			VAR Evolution_Proportion =  // Variation relative propre, gère les divisions par zéro via DIVIDE 
			    DIVIDE( Visites_Period - Visites_LastYear, Visites_LastYear, 0 )
			VAR Signe_Affichage =  // Préfixe du signe basé sur 0 car la variation est une proportion (positif/négatif) 
			    IF( Evolution_Proportion >= 0, "+ ", "- " )
			VAR Valeur_Pourcent_Formattee =  // Mise en forme en pourcentage avec une décimale, appliquée sur la valeur absolue pour éviter un double signe 
			    FORMAT( ABS(Evolution_Proportion), "0.00 %" )
			RETURN
			    "("&Signe_Affichage & Valeur_Pourcent_Formattee&")"  // Sortie texte: utile pour cartes/étiquettes; préférer garder une version numérique pour analyses 
			
			/*
			Rôle de la mesure:
			- Produit un affichage texte de l’évolution des visites vs N-1 avec signe explicite, ex: "+ 12,3%" ou "- 4,5%".
			- Le calcul de variation utilise DIVIDE pour la robustesse et sépare calcul (proportion) et présentation (signe/format).
			- Pour analyses et agrégations, utiliser en priorité une version numérique: Visites Evol vs last year (num), avec un format dynamique “+0.0%;-0.0%;0.0%”.
			*/ 
			
			```
		displayFolder: Visites
		lineageTag: d207e0a6-d86c-4ee1-8366-ce7a08aa5556

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Visites / effectif SameLastYear' = ```
			
			VAR ContexteDatesActuel = VALUES('Date principale'[Date]) // Garantit que l’on décale exactement le set de dates du visuel sans altérer d’autres filtres
			
			RETURN
			CALCULATE(
			[Nbre Visites / Effectif suivi],                            // Utilise la mesure source telle quelle
			DATEADD(ContexteDatesActuel, -1, YEAR)      // Décale la période d’un an en arrière, équivalent à SAMEPERIODLASTYEAR mais explicite et flexible
			) 
			
			// Rôle: calcule les RDV pour la même période de l’année précédente, en respectant le grain (jour/mois/trimestre) et les filtres actifs de la table de dates, sans supprimer ces filtres
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Visites
		lineageTag: 60a9ae26-8220-4c70-8e49-9a36f4b6ae8f

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Visites Evol vs last year' = ```
			
			VAR Visites_Period = [Visites (Graphique Dynamique)]  // Mesure de la période courante; utilisée comme numérateur de la variation 
			VAR Visites_LastYear = [Visites SameLastYear]  // Mesure de la période N-1; dénominateur et référence de comparaison 
			VAR Evolution_Proportion =  // Variation relative propre, gère les divisions par zéro via DIVIDE 
			    DIVIDE( Visites_Period - Visites_LastYear, Visites_LastYear, 0 )
			VAR Signe_Affichage =  // Préfixe du signe basé sur 0 car la variation est une proportion (positif/négatif) 
			    IF( Evolution_Proportion >= 0, "+ ", "- " )
			VAR Valeur_Pourcent_Formattee =  // Mise en forme en pourcentage avec une décimale, appliquée sur la valeur absolue pour éviter un double signe 
			    FORMAT( ABS(Evolution_Proportion), "0.00 %" )
			RETURN
			    "("&Signe_Affichage & Valeur_Pourcent_Formattee&")"  // Sortie texte: utile pour cartes/étiquettes; préférer garder une version numérique pour analyses 
			
			/*
			Rôle de la mesure:
			- Produit un affichage texte de l’évolution des visites vs N-1 avec signe explicite, ex: "+ 12,3%" ou "- 4,5%".
			- Le calcul de variation utilise DIVIDE pour la robustesse et sépare calcul (proportion) et présentation (signe/format).
			- Pour analyses et agrégations, utiliser en priorité une version numérique: Visites Evol vs last year (num), avec un format dynamique “+0.0%;-0.0%;0.0%”.
			*/ 
			
			```
		displayFolder: Visites
		lineageTag: d6b51abc-1297-40c0-9320-bb9c0fd31f4c

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Visites Evol vs last year (num)' = ```
			
			VAR Visites_Period = [Visites (Graphique Dynamique)]  // Calcule le total de la période courante via la mesure existante [web:27]
			VAR Visites_LastYear = [Visites SameLastYear]  // Calcule la valeur de la même période à N-1 via la mesure existante [web:27]
			VAR Evol_Proportion =  // Variation relative en proportion, robuste aux divisions par zéro [web:21]
			    DIVIDE( Visites_Period - Visites_LastYear, Visites_LastYear, 0 )
			RETURN
			    Evol_Proportion  // Mesure purement numérique, à formater en % au niveau du modèle [web:22][web:34]
			
			// Rôle: calcule l’évolution relative des visites vs N-1 en proportion (ex: 0,12 = +12%), réutilisable dans tout visuel [web:27][web:22].
			
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Visites
		lineageTag: 9ba20418-093e-40ea-b15a-ed6564241f1a

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Visites intérimaires' = ```
			
			-- 1. On récupère la date butoir dynamique (basée sur votre segment "Choisir Période")
			VAR DateFinContexte = [Date Fin Arrêté]
			
			-- 2. On construit la plage de 12 mois glissants qui se termine à cette date précise
			VAR Fenetre12M = DATESINPERIOD('Date principale'[Date], DateFinContexte, -12, MONTH)
			
			RETURN
			COALESCE(
			    CALCULATE(
			        'RDV'[Nombre de visites réalisées (RDV)],
			        
			        -- On conserve le filtre Intérim sans écraser d'autres filtres potentiels sur l'adhérent
			        KEEPFILTERS('Adhérent (actuel)'[Type entreprise] = "Intérim"),
			        
			        -- On force le contexte de date à être notre fenêtre glissante calculée
			        -- Cela va "surcharger" tout autre filtre de date présent sur la page pour ce calcul
			        Fenetre12M
			    ),
			    0
			)
			```
		formatString: #,0
		displayFolder: Suivi des indicateurs\Visites
		lineageTag: 0bff3b19-640d-44ed-a654-7ee80ea1cb4e

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Visites (Graphique Dynamique)' = ```
			
			-- 1. On définit la fenêtre de temps souhaitée par rapport au Slicer
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1 -- Recule de 12 mois + 1 jour
			
			-- 2. On regarde la date du point actuel du graphique
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			IF(
			    -- On affiche le chiffre UNIQUEMENT si la date de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			    
			    [Nombre de visites réalisées (RDV)],
			    
			    -- Sinon on renvoie BLANK, ce qui effacera la ligne sur le graphique
			    BLANK()
			)
			```
		formatString: #,0
		displayFolder: Suivi des indicateurs\Visites
		lineageTag: a86c17d1-63d0-44fa-a2a1-812d9ba699b6

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Visites Période N-1' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR DatesPeriodeN1 =
			    DATEADD(DatesPeriode, -1, YEAR)
			RETURN
			CALCULATE( [Nombre de visites réalisées (RDV)], DatesPeriodeN1 )
			
			```
		formatString: #,0
		displayFolder: Suivi des indicateurs\Visites
		lineageTag: afce843c-9584-43a3-a686-2612ed77b1a6

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Visites SameLastYear' = ```
			
			VAR ContexteDatesActuel = VALUES('Date principale'[Date]) // Garantit que l’on décale exactement le set de dates du visuel sans altérer d’autres filtres
			
			RETURN
			CALCULATE(
			[Nombre de visites réalisées (RDV)],        // Utilise la mesure source telle quelle
			DATEADD(ContexteDatesActuel, -1, YEAR)      // Décale la période d’un an en arrière, équivalent à SAMEPERIODLASTYEAR mais explicite et flexible
			) 
			
			// Rôle: calcule les visites pour la même période de l’année précédente, en respectant le grain (jour/mois/trimestre) et les filtres actifs de la table de dates, sans supprimer ces filtres
			```
		formatString: #,0
		displayFolder: Visites
		lineageTag: 30005181-68a9-4c10-ba28-5da16424dccb

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Adhérents actifs ou suspendus' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			CALCULATE(
			    COALESCE(
			        ('Evolution effectif'[Nombre d'adhérents fin de période]),
			        0
			    ),
			    'Date principale'[Date] <= DateSnapshot
			)
		formatString: #,0
		displayFolder: Suivi des indicateurs\Adhérents
		lineageTag: c3d25870-0783-43e1-a703-2ac223ddd039

	measure 'Données à jour à' = ```
			
			"Données à jour au " & 
			FORMAT(
			    [Date Fin Arrêté],
			        "DD mmmm YYYY", 
			        "fr-FR"
			)
			```
		displayFolder: Date
		lineageTag: ad24a5ee-80bb-4049-aa50-f3cfa5b3764c

	measure 'Données à jour à 2' = ```
			
			"au " & 
			FORMAT(
			    [Date Fin Arrêté],
			        "DD mmmm YYYY", 
			        "fr-FR"
			)
			```
		displayFolder: Date
		lineageTag: 1e195dd1-2c36-4f21-b78a-6863bb7ba411

	measure 'Adhérents actifs ou suspendus N-1' = ```
			
			-- 1. On récupère la date choisie actuelle
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date exacte 1 an avant (EDATE gère parfaitement les années bissextiles)
			VAR DateNMoins1 = EDATE(DateActuelle, -12)
			
			RETURN
			CALCULATE(
			    COALESCE(
			        ('Evolution effectif'[Nombre d'adhérents fin de période]), 
			        0
			    ),
			    -- 3. On remplace le filtre de date par celle de l'année précédente
			    'Date principale'[Date] <= DateNMoins1
			)
			```
		formatString: #,0
		displayFolder: Suivi des indicateurs\Adhérents
		lineageTag: 3a9b7e77-fb4f-458e-8f72-54d7748132b9

	measure 'Date 1 an avant' = ```
			
			-- 1. On récupère la date choisie actuelle
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date exacte 1 an avant (EDATE gère parfaitement les années bissextiles)
			VAR DateNMoins1 = EDATE(DateActuelle, -12)
			
			RETURN
			"vs. " & FORMAT(
			    DateNMoins1,
			        "DD mmm' YY", 
			        "fr-FR"
			)&" : "
			```
		displayFolder: Suivi des indicateurs\Date
		lineageTag: f9788490-18e3-4504-ada9-2c043c2fb803

	measure 'Adhérents évolution (Variation %)' =
			
			DIVIDE(
			    [Adhérents actifs ou suspendus] - [Adhérents actifs ou suspendus N-1],
			    [Adhérents actifs ou suspendus N-1]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\Adhérents
		lineageTag: b88e2657-d34d-460d-9815-758f3e1e8ac0

	measure 'Evolution effectif - Effectif suivi N-1' = ```
			
			-- 1. On récupère la date choisie actuelle
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date exacte 1 an avant (EDATE gère parfaitement les années bissextiles)
			VAR DateNMoins1 = EDATE(DateActuelle, -12)
			
			RETURN
			CALCULATE(
			    COALESCE(
			        ('Evolution effectif'[Effectif suivi figé non intérimaire fin de période] + 'Evolution effectif'[Effectif suivi figé intérimaire fin de période]), 
			        0
			    ),
			    -- 3. On remplace le filtre de date par celle de l'année précédente
			    'Date principale'[Date] <= DateNMoins1
			)
			```
		formatString: #,0
		displayFolder: Suivi des indicateurs\Effectif
		lineageTag: ceb7055d-b00e-4f18-98de-06648a4d5567

	measure 'Evolution Effectif (Variation %)' =
			
			DIVIDE(
			    [Evolution Effectif - effectif suivi] - [Evolution effectif - Effectif suivi N-1],
			    [Evolution effectif - Effectif suivi N-1]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\Effectif
		lineageTag: d40e3f6d-906b-4e43-9f49-6a9a62b0c06d

	measure 'Adhérents concernés AMT' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([# entreprises concernées (AMT)], DatesPeriode)
		formatString: #,0
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 3a4b9833-bf40-4b93-9964-3f7c2981d08b

	measure 'Sous titre visites réalisées' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"Visites médecins, IDEST & IDE du "& DatePeriode
		displayFolder: Titres
		lineageTag: 13d4c6a4-8c07-4afb-b061-d9b6f2f1d9dc

	measure 'Visites évolution (+/-)' =
			
			VAR Evolution = DIVIDE(
			    [Visites Période] - [Visites Période N-1],
			    [Visites Période N-1]
			)
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\Visites
		lineageTag: f1ba1ec0-3068-437b-b81a-7a27557a333e

	measure 'Mesure 3'
		displayFolder: Visites
		lineageTag: e7784991-8635-4b23-a736-25575e137247

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Visites Période' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([Nombre de visites réalisées (RDV)], DatesPeriode)
		formatString: #,0
		displayFolder: Suivi des indicateurs\Visites
		lineageTag: 9e71e53f-9405-4dac-934b-eca0c2979c41

	measure 'Visites évolution' =
			
			DIVIDE(
			    [Visites Période] - [Visites Période N-1],
			    [Visites Période N-1]
			)
		displayFolder: Suivi des indicateurs\Visites
		lineageTag: c781ce9c-c472-4b2b-96a0-67bce71bc5e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Evolution effectif (+/-)' =
			
			VAR Evolution = [Evolution Effectif (Variation %)]
			RETURN
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\Effectif
		lineageTag: b57f168c-a108-48c1-bc2a-153c20ce9752

	measure 'Adhérents évolution (+/-)' =
			
			Var Evolution = [Adhérents évolution (Variation %)]
			
			RETURN
			format(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\Adhérents
		lineageTag: 55d9ba61-b185-4b1c-b62c-291936a5d303

	measure 'Adhérents (Graphique Dynamique)' = ```
			
			-- 1. Définition de la fenêtre de temps (inchangé)
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1 
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			IF(
			    -- On affiche le chiffre UNIQUEMENT si la date de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			    
			    -- 2. On récupère simplement la valeur stockée dans votre table
			    ('Evolution effectif'[Nombre d'adhérents fin de période]),
			    
			    BLANK()
			)
			```
		formatString: #,0
		displayFolder: Suivi des indicateurs\Adhérents
		lineageTag: 23a73131-9838-43d3-acc1-0c1df0ab33e4

	measure 'Adhérents Min Y' = ```
			
			-- 1. On récupère la fenêtre de temps (identique à votre graphique)
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -12) + 1
			
			-- 2. On cherche la valeur minimale atteinte par la courbe sur cette période
			VAR MinVal = 
			    MINX(
			        DATESBETWEEN('Date principale'[Date], DateDebut, DateFin),
			        CALCULATE(('Evolution effectif'[Nombre d'adhérents fin de période]))
			    )
			
			-- 3. On applique la réduction de 3%
			RETURN MinVal * 0.97
			```
		displayFolder: Suivi des indicateurs\Adhérents
		lineageTag: 4a3fc3c6-fbc2-4c31-bbf2-0a804d409dd1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Adhérents Max Y' = ```
			
			-- 1. On récupère la fenêtre de temps (identique à votre graphique)
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -12) + 1
			
			-- 2. On cherche la valeur max atteinte par la courbe sur cette période
			VAR MaxVal = 
			    MAXX(
			        DATESBETWEEN('Date principale'[Date], DateDebut, DateFin),
			        CALCULATE(('Evolution effectif'[Nombre d'adhérents fin de période]))
			    )
			
			-- 3. On applique la majoration de 3%
			RETURN MaxVal * 1.03
			```
		displayFolder: Suivi des indicateurs\Adhérents
		lineageTag: 4509fd60-aee2-4845-b400-9b4affbfc3fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Effectif (Graphique Dynamique)' = ```
			
			-- 1. Définition de la fenêtre de temps (inchangé)
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1 
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			IF(
			    -- On affiche le chiffre UNIQUEMENT si la date de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			    
			    -- 2. On récupère simplement la valeur stockée dans votre table
			    ('Evolution effectif'[Effectif suivi figé non intérimaire fin de période]+'Evolution effectif'[Effectif suivi figé intérimaire fin de période]),
			    BLANK()
			)
			```
		formatString: #,0
		displayFolder: Suivi des indicateurs\Effectif
		lineageTag: ae56037c-a5f4-419b-a5c9-6b42018ee106

	measure 'Effectif Min Y' = ```
			
			-- 1. On récupère la fenêtre de temps (identique à votre graphique)
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1
			
			-- 2. On cherche la valeur minimale atteinte par la courbe sur cette période
			VAR MinVal = 
			    MINX(
			        DATESBETWEEN('Date principale'[Date], DateDebut, DateFin),
			        CALCULATE(('Evolution effectif'[Effectif suivi figé non intérimaire fin de période]+'Evolution effectif'[Effectif suivi figé intérimaire fin de période]))
			    )
			
			-- 3. On applique la réduction de 3%
			RETURN MinVal * 0.97
			```
		displayFolder: Suivi des indicateurs\Effectif
		lineageTag: 7925fbc0-5125-4a7a-a793-e29da7530e28

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Effectif Max Y' = ```
			
			-- 1. On récupère la fenêtre de temps (identique à votre graphique)
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1
			
			-- 2. On cherche la valeur max atteinte par la courbe sur cette période
			VAR MaxVal = 
			    MAXX(
			        DATESBETWEEN('Date principale'[Date], DateDebut, DateFin),
			        CALCULATE(('Evolution effectif'[Effectif suivi figé non intérimaire fin de période]+'Evolution effectif'[Effectif suivi figé intérimaire fin de période]))
			    )
			
			-- 3. On applique la majoration de 3%
			RETURN MaxVal * 1.03
			```
		displayFolder: Suivi des indicateurs\Effectif
		lineageTag: f6c5c3a4-3d1c-42e7-99db-ace02e957802

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nombre de réclamations' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			CALCULATE(
			    COALESCE(
			        CALCULATE(
			            'CRM - tickets'[# tickets],
			            'CRM - ticket - informations'[Type ticket] = "Réclamation"
			        ),
			        0
			    ),
			    'Date principale'[Date] <= DateSnapshot
			)
		formatString: 0
		displayFolder: Suivi des indicateurs\Réclamations
		lineageTag: 1ef34f3b-1aff-4c93-8d60-43e7219b935b

	measure 'Sous titre réclamations' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"Tickets de type 'Réclamation' créés du "& DatePeriode
		displayFolder: Titres
		lineageTag: 771831ea-f6e4-4051-9d5f-cf13b42cbb41

	measure 'Nombre de réclamations Période N-1' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR DatesPeriodeN1 =
			    DATEADD(DatesPeriode, -1, YEAR)
			RETURN
			CALCULATE( 
			    COALESCE(
			        CALCULATE(
			            [Tickets ouverts],
			            'CRM - ticket - informations'[Type ticket] = "Réclamation"
			        ),
			        0
			    ),
			DatesPeriodeN1 
			)
			
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\Réclamations
		lineageTag: 7925f811-4b44-4252-88b7-7ab52fd9f962

	measure 'Réclamations évolution' =
			
			DIVIDE(
			    [Nombre de réclamations]-[Nombre de réclamations Période N-1],
			    [Nombre de réclamations Période N-1]
			)
		displayFolder: Suivi des indicateurs\Réclamations
		lineageTag: 987a0ff2-5eb2-4a6c-98a2-a530c78a875c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Réclamation évolution (+/-)' =
			
			VAR Evolution = DIVIDE([Nombre de réclamations]-[Nombre de réclamations Période N-1],[Nombre de réclamations Période N-1])
			
			RETURN
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\Réclamations
		lineageTag: 0f20a32d-2bab-4ed6-a5f7-33ff2c10e24c

	measure 'Réclamations (Graphique Dynamique)' = ```
			
			-- 1. On définit la fenêtre de temps souhaitée par rapport au Slicer
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1 -- Recule de 12 mois + 1 jour
			
			-- 2. On regarde la date du point actuel du graphique
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			IF(
			    -- On affiche le chiffre UNIQUEMENT si la date de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			    
			    COALESCE(CALCULATE('CRM - tickets'[# tickets],'CRM - ticket - informations'[Type ticket] = "Réclamation"),0),
			    
			    -- Sinon on renvoie BLANK, ce qui effacera la ligne sur le graphique
			    BLANK()
			)
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\Réclamations
		lineageTag: 3e06cac8-b67d-4cb6-ac16-4fd9a3326774

	measure 'Visites Max Y' = ```
			
			-- 1. On récupère la fenêtre de temps (identique à votre graphique)
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -12) + 1
			
			-- 2. On cherche la valeur max atteinte par la courbe sur cette période
			VAR MaxVal = 
			    MAXX(
			        DATESBETWEEN('Date principale'[Date], DateDebut, DateFin),
			        CALCULATE([Visites évolution])
			    )
			
			-- 3. On applique la majoration de 3%
			RETURN MaxVal * 1.03
			```
		displayFolder: Suivi des indicateurs\Visites
		lineageTag: 851278b2-11b8-479f-8f85-d032136db448

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sous titre délai réclamations' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"Durée, en jours, de traitement des tickets de type 'Réclamation' créés du "& DatePeriode
		displayFolder: Titres
		lineageTag: c9ae1971-ba2f-4956-bc3a-b3dcfad61f6f

	measure 'Délai de traitement des réclamations' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			CALCULATE(
			    COALESCE(
			        CALCULATE(
			            'CRM - tickets'[Durée moyenne traitement tickets (j)],
			            'CRM - ticket - informations'[Type ticket] = "Réclamation"
			        ),
			        0
			    ),
			    'Date principale'[Date] <= DateSnapshot
			)
		displayFolder: Suivi des indicateurs\Réclamations
		lineageTag: 58b22496-5d29-4edc-81a3-a84853096fe3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Délai de traitement des réclamations Période N-1' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR DatesPeriodeN1 =
			    DATEADD(DatesPeriode, -1, YEAR)
			RETURN
			CALCULATE( 
			    COALESCE(
			        CALCULATE(
			            [Durée moyenne traitement tickets (j)],
			            'CRM - ticket - informations'[Type ticket] = "Réclamation"
			        ),
			        0
			    ),
			DatesPeriodeN1 
			)
			```
		displayFolder: Suivi des indicateurs\Réclamations
		lineageTag: 9908a3e4-b634-436e-9f68-1c1abe29f29a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Délai Réclamation évolution (+/-)' =
			
			VAR Evolution = DIVIDE([Délai de traitement des réclamations]-[Délai de traitement des réclamations Période N-1],[Délai de traitement des réclamations Période N-1])
			
			RETURN
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\Réclamations
		lineageTag: 4ebf3018-32db-4fbd-960f-9470bf4b7551

	measure 'Délai Réclamations évolution' =
			
			DIVIDE(
			    [Délai de traitement des réclamations]-[Délai de traitement des réclamations Période N-1],
			    [Délai de traitement des réclamations Période N-1]
			)
		displayFolder: Suivi des indicateurs\Réclamations
		lineageTag: 9a16b41b-c073-42f4-8f54-e52005447efe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Délais Réclamations (Graphique Dynamique)' = ```
			
			-- 1. On définit la fenêtre de temps souhaitée par rapport au Slicer
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1 -- Recule de 12 mois + 1 jour
			
			-- 2. On regarde la date du point actuel du graphique
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			IF(
			    -- On affiche le chiffre UNIQUEMENT si la date de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			    
			    CALCULATE('CRM - tickets'[Durée moyenne traitement tickets (j)],'CRM - ticket - informations'[Type ticket] = "Réclamation"),
			    
			    -- Sinon on renvoie BLANK, ce qui effacera la ligne sur le graphique
			    BLANK()
			)
			```
		displayFolder: Suivi des indicateurs\Réclamations
		lineageTag: c1a8194b-ae0a-45ac-98f3-e91b1f7804df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% emploi avec contrat renseigné' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([% Emploi actuel avec type de contrat renseigné (visite)], DatesPeriode)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: 541eae17-1470-4c73-b0d5-9131fde7affa

	measure '% emploi avec description renseignée' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([% Emploi actuel avec description renseignée (visite)], DatesPeriode)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: 4880c4d1-8b3f-4981-89fd-12fb39083d6a

	measure '% visites avec conclusion' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([% Visites avec conclusion (visite)], DatesPeriode)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: c863b7d3-227a-4a8c-99ac-a618b3bf0fd1

	measure '% visites avec IRDP rempli' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([% Visites avec IRDP rempli (visite)], DatesPeriode)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: 16ce2534-089a-483d-abb4-378f321665e5

	measure '% visites avec examen clinique' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([% Visites avec examen clinique (visite)], DatesPeriode)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: 5449c46c-7eec-41d8-bc75-c2f987a3ffa6

	measure 'Nbre d''examens cliniques par visite' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([# Examens cliniques par visite], DatesPeriode)
		formatString: 0.0
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: 7c03f958-e4eb-40a0-8728-9e6a7ac9c240

	measure '% examens cliniques avec RAS' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([% Examens cliniques avec RAS (visite)], DatesPeriode)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: 9910e3e4-c771-4b78-bf61-5d91d8d5f03c

	measure '% visites avec échelle remplie' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([% Visites avec échelle remplie (visite)], DatesPeriode)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: 79698a71-9512-4dfd-8352-48ee295a0ba2

	measure '% visites avec adapatations de poste' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([% Visites avec adaptation de poste (visite)], DatesPeriode)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: 5b6d1720-e60e-4fda-b5a1-3b89a91005c2

	measure 'Nbre de recommandations orales par visite' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([# Recommandations orales par visite], DatesPeriode)
		formatString: 0.0
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: 0837277b-2487-4e94-979f-364f266da432

	measure 'thésaurus antécédents familiaux utilisés' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE(sum('Saisie - visite'[nb Thésaurus antécédents familiaux (visite)]), DatesPeriode)
		formatString: #,0
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: b8b339bc-b5a8-4006-aac4-3fd5c2e37ba1

	measure 'thésaurus examens cliniques utilisés' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE(sum('Saisie - visite'[nb Thésaurus examens cliniques (visite)]), DatesPeriode)
		formatString: #,0
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: 3a37c709-1482-4f35-ac92-167dce4e2772

	measure 'thésaurus maladies professionnelles utilisés' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE(sum('Saisie - visite'[nb Thésaurus maladies professionnelles (visite)]), DatesPeriode)
		formatString: #,0
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: 472c6b6e-e395-4cd3-beed-0d662d6b9deb

	measure 'thésaurus CIM 10 utilisés' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE(sum('Saisie - visite'[nb Thésaurus cim10 (visite)]), DatesPeriode)
		formatString: #,0
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: b4ad7f34-0506-4eff-960f-86fa141e807b

	measure 'thésaurus accidents de travail utilisés' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE(sum('Saisie - visite'[nb Thésaurus accidents de travail (visite)]), DatesPeriode)
		formatString: #,0
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: ab1469b3-696b-42dd-99b3-8d9c04419589

	measure 'thésaurus pathologies utilisés' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE(sum('Saisie - visite'[nb Thésaurus pathologies (visite)]), DatesPeriode)
		formatString: #,0
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: 8304be08-dcd6-4b9f-9205-52aa80126b27

	measure 'thésaurus arrêts de travail utilisés' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE(sum('Saisie - visite'[nb Thésaurus arrêts de travail (visite)]), DatesPeriode)
		formatString: #,0
		displayFolder: Suivi des indicateurs\DMST
		lineageTag: 8989d73b-dfe1-4ad9-926c-de809903c956

	measure 100% =
			
			1
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: Suivi des indicateurs
		lineageTag: cd25a153-9998-47dc-b656-4e51ef09bbab

	measure 'nouveaux adhérents' =
			
			CALCULATE(
			    [Adhérents actifs ou suspendus],
			    'Adhérent (actuel)'[Date premier statut actif] > TODAY()-365
			)
		formatString: 0
		displayFolder: Suivi des indicateurs\Adhérents
		lineageTag: a312e447-55a6-4a00-8d4d-0a18c1e8a3f1

	measure 'Nouveaux adhérents sans FE' =
			
			-- 1. On définit la date d'arrêt pour le calcul (Mois du graphique OU Date du Slicer)
			VAR DateSnapshot = [Date Fin Arrêté]
			
			-- 2. On définit la date limite pour l'ancienneté (il y a 1 an)
			VAR DateLimiteAnciennete = EDATE(DateSnapshot, -12)
			
			RETURN
			CALCULATE(
			    -- Mesure de base
			    [Nombre d'adhérents fin de période avec FE non renseignée],
			
			    -- Filtre 1 : Critère "Nouveau" (Date d'entrée > il y a 1 an)
			    'Adhérent (actuel)'[Date premier statut actif] > DateLimiteAnciennete,
			
			    -- Filtre 2 : La fenêtre temporelle (Comme dans votre exemple "Adhérents actifs ou suspendus")
			    'Date principale'[Date] <= DateSnapshot
			)
		formatString: #,0
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 0b6cd74e-4653-4f78-8b2c-6a7718542f95

	measure '# adhérents avec FE à mettre à jour (fin de période)' = ```
			
			CALCULATE(
			    'Evolution effectif'[# adhérents en retard de FE (fin de période)],         -- Mesure à calculer
			    'Evolution effectif'[date dernière fe] <> DATE(1900, 1, 1)                  -- Filtre pour exclure les dates non valides
			)
			
			-- Description : Cette mesure calcule le nombre d'adhérents dont la fiche d'évaluation (FE) doit être mise à jour à la fin de la période.
			-- Elle exclut les adhérents dont la date de la dernière FE est une date par défaut (1900-01-01), indiquant que la FE n'est pas valide ou n'a pas été mise à jour.
			
			```
		formatString: 0
		displayFolder: FE
		lineageTag: bb1ecf4c-c9ed-4e0a-807b-faeaa25a1c1b

	measure 'Adhérents avec FE à mettre à jour' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			CALCULATE(
			    COALESCE(
			        ([# adhérents avec FE à mettre à jour (fin de période)]),
			        0
			    ),
			    'Date principale'[Date] <= DateSnapshot
			)
		formatString: #,0
		displayFolder: Suivi des indicateurs\FE
		lineageTag: e586e90f-0c7a-41e8-8c75-071897b9e061

	measure 'sous titre adhérents avec FE à mettre à jour' =
			
			"Adhérents dont la FE a été réalisé avant le "& format([Date 4 an avant], "DD mmmm YYYY", "fr-FR")
		displayFolder: Titres
		lineageTag: ad043f3b-7362-49b5-a353-4cb4e91b60a1

	measure 'Adhérents avec FE a mettre à jour (graph)' =
			
			-- 1. Définition de la fenêtre de temps (Bornes)
			VAR DateFin = [Date Fin Arrêté]           -- La date sélectionnée dans le Slicer (ex: 31/12/2024)
			VAR DateDebut = EDATE(DateFin, -13) + 1   -- 12 mois glissants avant
			
			-- 2. Contexte du graphique (Point actuel de l'axe X)
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			-- 3. Logique d'affichage
			IF(
			    -- Condition : On affiche seulement si le mois de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			
			    -- Valeur : On appelle directement la mesure de base (celle qui somme la table Evolution)
			    -- Elle va naturellement se calculer pour le "DateSurAxe" (le mois en cours)
			    [# adhérents avec FE à mettre à jour (fin de période)],
			
			    -- Sinon rien
			    BLANK()
			)
		formatString: #,0
		displayFolder: Suivi des indicateurs\FE
		lineageTag: d2a867b0-6416-43ef-966b-60d59322ad63

	measure 'Adhérents sans FE' = ```
			
			CALCULATE(
			    -- On appelle votre mesure de base
			    [# adhérents en retard de FE (fin de période)],
			    
			    -- On garde uniquement le filtre métier (Jamais eu de FE)
			    'Evolution effectif'[date dernière fe] = DATE(1900, 1, 1)
			)
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 99d49908-fd7e-44a9-91b6-00cc7c602495

	measure 'Adhérents sans FE (graph)' = ```
			
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			-- On récupère la valeur dynamique calculée par votre autre mesure graphique
			-- Assurez-vous que le nom correspond exactement à votre mesure "Nouveaux adhérents sans FE (graph)"
			VAR NouveauxSansFE = [Nouveaux adhérents sans FE (graph)]
			
			RETURN
			IF(
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			    
			    -- CORRECTION : C'est ici qu'on retire les nouveaux pour ne garder que les "vieux" sans FE
			    [Adhérents sans FE] - NouveauxSansFE,
			    
			    BLANK()
			)
			```
		formatString: #,0
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 82bd47cd-147e-49f5-a6d4-9c7c6e976942

	measure 'Adhérents à jour de FE' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			CALCULATE(
			    COALESCE(
			        ([# adhérents à jour de FE (fin de période)]),
			        0
			    ),
			    'Date principale'[Date] <= DateSnapshot
			)
		formatString: #,0
		displayFolder: Suivi des indicateurs\FE
		lineageTag: fcbb4b00-d107-4fb9-8fc8-8bec2b33eaf1

	measure 'Adhérents à jour de FE (graph)' =
			
			-- 1. Définition de la fenêtre de temps (Bornes)
			VAR DateFin = [Date Fin Arrêté]           -- La date sélectionnée dans le Slicer (ex: 31/12/2024)
			VAR DateDebut = EDATE(DateFin, -13) + 1   -- 12 mois glissants avant
			
			-- 2. Contexte du graphique (Point actuel de l'axe X)
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			-- 3. Logique d'affichage
			IF(
			    -- Condition : On affiche seulement si le mois de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			
			    -- Valeur : On appelle directement la mesure de base (celle qui somme la table Evolution)
			    -- Elle va naturellement se calculer pour le "DateSurAxe" (le mois en cours)
			    [# adhérents à jour de FE (fin de période)],
			
			    -- Sinon rien
			    BLANK()
			)
		formatString: #,0
		displayFolder: Suivi des indicateurs\FE
		lineageTag: d16258d0-4f51-4720-9d3a-f2f7cfc80031

	measure 'Adhérents sans FEE' =
			
			CALCULATE(
			        [# adhérents avec FE à mettre à jour (fin de période)],
			        'Evolution effectif'[date dernière fe] = DATE(1900, 1, 1)
			    )
		formatString: 0
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 5a734319-91c8-4923-b53c-66ba9508f98a

	measure '% Adhérents sans FE (graph)' = ```
			
			-- 1. Définition de la fenêtre
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			IF(
			    -- Condition d'affichage (fenêtre)
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			
			    -- 2. Calcul du pourcentage
			    DIVIDE(
			        [Adhérents sans FE]-[Nouveaux adhérents sans FE],                          -- Numérateur (Votre mesure de base corrigée)
			        [# adhérents éligibles FE (fin de période)],  -- Dénominateur
			        0
			    ),
			    
			    BLANK()
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\FE
		lineageTag: ba57c3dd-3616-4895-82cb-b75f0d2d9e52

	measure '% Adhérents à jour de FE (graph)' =
			
			-- 1. Définition de la fenêtre de temps (Bornes)
			VAR DateFin = [Date Fin Arrêté]           -- La date sélectionnée dans le Slicer (ex: 31/12/2024)
			VAR DateDebut = EDATE(DateFin, -13) + 1   -- 12 mois glissants avant
			
			-- 2. Contexte du graphique (Point actuel de l'axe X)
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			-- 3. Logique d'affichage
			IF(
			    -- Condition : On affiche seulement si le mois de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			
			    -- Valeur : On appelle directement la mesure de base (celle qui somme la table Evolution)
			    -- Elle va naturellement se calculer pour le "DateSurAxe" (le mois en cours)
			    [% adhérents à jour de FE (fin de période)],
			
			    -- Sinon rien
			    BLANK()
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 9bc9ae52-1c6d-4075-94b1-a7b0d58acfc3

	measure '% Adhérents avec FE à mettre à jour (graph)' = ```
			
			-- 1. Définition de la fenêtre
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			IF(
			    -- Condition d'affichage (fenêtre)
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			
			    -- 2. Calcul du pourcentage
			    DIVIDE(
			        [# adhérents avec FE à mettre à jour (fin de période)],                          -- Numérateur (Votre mesure de base corrigée)
			        [# adhérents éligibles FE (fin de période)],  -- Dénominateur
			        0
			    ),
			    
			    BLANK()
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\FE
		lineageTag: e1937046-5e39-4753-b3e1-fe44b7b66857

	measure 'Nouveaux adhérents sans FE (graph)' = ```
			
			-- 1. Définition de la fenêtre d'affichage (Statique par rapport au rapport)
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1
			VAR DateSurAxe = MAX('Date principale'[Date]) -- La date du mois en cours sur le graphique
			
			-- 2. Définition de la limite d'ancienneté (DYNAMIQUE par rapport au mois affiché)
			-- C'est la correction clé : on recule de 1 an par rapport au mois du graphique, pas la fin d'année
			VAR DateLimiteAnciennete = EDATE(DateSurAxe, -12)
			
			RETURN
			IF(
			    -- Condition d'affichage : est-on dans la fenêtre ?
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			    
			    -- Si oui, on calcule
			    CALCULATE(
			        -- Mesure de base
			        [Nombre d'adhérents fin de période avec FE non renseignée],
			
			        -- Filtre 1 : Critère "Nouveau" (Date d'entrée > il y a 1 an par rapport au mois affiché)
			        'Adhérent (actuel)'[Date premier statut actif] > DateLimiteAnciennete,
			
			        -- Sécurité : On s'assure que la date d'entrée n'est pas dans le futur par rapport au mois affiché
			        'Adhérent (actuel)'[Date premier statut actif] <= DateSurAxe,
			
			        -- Filtre 2 : Contexte temporel standard
			        'Date principale'[Date] <= DateSurAxe
			    ),
			    
			    BLANK()
			)
			```
		formatString: #,0
		displayFolder: Suivi des indicateurs\FE
		lineageTag: c4f1ef14-525c-4796-972d-33a4e5ddfa2f

	measure 'Nouveaux adhérents sans FE évolution (Variation %)' =
			
			DIVIDE(
			    [Nouveaux adhérents sans FE] - [Nouveaux adhérents sans FE N-1],
			    [Nouveaux adhérents sans FE N-1]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 44f93f54-3b90-4cbd-bdd1-c164b6502a84

	measure '% nouveaux Adhérents sans FE (graph)' = ```
			
			-- 1. Définition de la fenêtre
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			IF(
			    -- Condition d'affichage (fenêtre)
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			
			    -- 2. Calcul du pourcentage
			    DIVIDE(
			        [Nouveaux adhérents sans FE (graph)],                          -- Numérateur (Votre mesure de base corrigée)
			        [# adhérents éligibles FE (fin de période)],  -- Dénominateur
			        0
			    ),
			    
			    BLANK()
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 7300a96a-7828-44c2-84c4-78597921c0b8

	measure 'Nouveaux adhérents sans FE N-1' = ```
			
			-- 1. On récupère la date actuelle (Fin de période sélectionnée)
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date de référence pour l'année précédente (Le "Aujourd'hui" de l'an dernier)
			VAR DateNMoins1 = EDATE(DateActuelle, -12)
			
			-- 3. On définit la limite d'ancienneté pour cette époque-là 
			-- (Pour être "nouveau" en N-1, il faut être arrivé après N-2)
			VAR DateLimiteAncienneteNMoins1 = EDATE(DateNMoins1, -12)
			
			RETURN
			CALCULATE(
			    -- Mesure de base
			    [Nombre d'adhérents fin de période avec FE non renseignée],
			
			    -- Filtre 1 : Critère "Nouveau" adapté à l'année N-1
			    'Adhérent (actuel)'[Date premier statut actif] > DateLimiteAncienneteNMoins1,
			
			    -- Filtre 2 : On remonte le temps sur la date principale
			    'Date principale'[Date] <= DateNMoins1
			)
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\FE
		lineageTag: b2e67969-52cd-40a5-bec1-f49f466ad07b

	measure 'Nouveaux adhérents sans FE évolution (+/-)' =
			
			Var Evolution = [Nouveaux adhérents sans FE évolution (Variation %)]
			
			RETURN
			format(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 6697b287-2e76-4a95-af8c-9678b70441a1

	measure 'Sous Titre Nouveaux Adhérents sans FE en date du' =
			
			Var DateMax = [Date Fin Arrêté]
			Var DateUnAnAvant = EDATE(DateMax, -12)+1
			
			RETURN
			"Nouvelles entreprises adhérentes (depuis le  " & format(DateUnAnAvant,"DD mmmm YYYY", "fr-FR") & ") n'ayant pas de FE en date du " & format(DateMax,"DD mmmm YYYY", "fr-FR")
		displayFolder: Titres
		lineageTag: 55482ee4-95e7-4417-8b0c-b5d20b270c02

	measure 'Date 4 an avant' = ```
			
			-- 1. On récupère la date choisie actuelle
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date exacte 4 an avant (EDATE gère parfaitement les années bissextiles)
			VAR DateNMoins4 = EDATE(DateActuelle, -48)+1
			
			RETURN
			FORMAT(
			    DateNMoins4,
			        "DD mmmm YYYY", 
			        "fr-FR"
			)&" : "
			```
		displayFolder: Suivi des indicateurs\Date
		lineageTag: ccb1e080-dc9d-4737-9755-63f8f98fbef7

	measure 'Adhérents avec FE à mettre à jour N-1' = ```
			
			-- 1. On récupère la date actuelle (Fin de période sélectionnée)
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date de référence pour l'année précédente (Le "Aujourd'hui" de l'an dernier)
			VAR DateNMoins1 = EDATE(DateActuelle, -12)
			
			-- 3. On définit la limite d'ancienneté pour cette époque-là 
			-- (Pour être "nouveau" en N-1, il faut être arrivé après N-2)
			VAR DateLimiteAncienneteNMoins1 = EDATE(DateNMoins1, -12)
			
			RETURN
			CALCULATE(
			    -- Mesure de base
			    [# adhérents avec FE à mettre à jour (fin de période)],
			
			    -- Filtre 2 : On remonte le temps sur la date principale
			    'Date principale'[Date] <= DateNMoins1
			)
			```
		formatString: #,0
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 0636524e-1c8a-447e-9827-78d5a213aed6

	measure 'Adhérents avec FE à mettre à jour évolution (Variation %)' =
			
			DIVIDE(
			    [# Adhérents avec FE à mettre à jour (fin de période)] - [Adhérents avec FE à mettre à jour N-1],
			    [Adhérents avec FE à mettre à jour N-1]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 0ab7fc9b-1791-433f-aea6-36387139b897

	measure 'Adhérents avec FE à mettre à jour évolution (+/-)' =
			
			Var Evolution = [Adhérents avec FE à mettre à jour évolution (Variation %)]
			
			RETURN
			format(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 46e75ae0-fe8d-4f0e-81f5-e8bc64fa4088

	measure 'Objectif FE 2026 (Simu)' = ```
			
			-- 1. Configuration
			VAR DateAxe = EOMONTH(MAX('Date Simulation'[Date]), 0)
			VAR DateCible = DATE(2026, 12, 31)
			VAR ValCible = [Objectif FE]
			
			-- 2. On cherche la dernière date de données réelles
			VAR DateDerniereDonneeBrute = 
			    CALCULATE(
			        MAX('Date principale'[Date]),
			        FILTER(
			            ALL('Date principale'),
			            NOT(ISBLANK([% Adhérents FE (Base)]))
			        )
			    )
			
			-- 3. On définit le point d'ancrage à M-1
			VAR DateReference = EOMONTH(DateDerniereDonneeBrute, -1)
			
			-- 4. On calcule la valeur de départ sur ce point d'ancrage
			VAR ValDepart = 
			    CALCULATE(
			        [% Adhérents FE (Base)], 
			        DATESBETWEEN('Date principale'[Date], EOMONTH(DateReference, -1)+1, DateReference)
			    )
			
			-- 5. NOUVELLE LOGIQUE : Gestion de l'écart
			-- Si le départ est supérieur à la cible, l'écart est nul (on reste stable).
			-- Sinon, on calcule la différence classique pour la pente.
			VAR Ecart = 
			    IF(
			        ValDepart > ValCible, 
			        0, 
			        ValCible - ValDepart
			    )
			
			RETURN
			IF(
			    -- CAS 1 : Point de jonction (soudure avec le réel)
			    DateAxe = DateReference,
			    ValDepart,
			
			    -- CAS 2 : Projection dans le futur
			    IF(
			        DateAxe > DateReference && DateAxe <= DateCible,
			        
			        VAR DureeTotale = DATEDIFF(DateReference, DateCible, DAY)
			        VAR DureeEcoulee = DATEDIFF(DateReference, DateAxe, DAY)
			        
			        -- Si Ecart est 0 (car ValDepart > ValCible), le calcul ajoute 0, donc on reste à ValDepart
			        RETURN ValDepart + (Ecart * DIVIDE(DureeEcoulee, DureeTotale)),
			        
			        BLANK()
			    )
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 78a9f3d0-b1c5-4b68-9071-ee319f4ce8a2

	measure 'Objectif FE' =
			
			0.72
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: Suivi des indicateurs\FE
		lineageTag: d6f7d546-21e1-444d-ade5-f8a209fd4dcf

	measure '% Entreprises Concernées par AMT' = ```
			
			VAR EntreprisesConcerneesAMT =
			    [Adhérents concernés AMT]                                        -- Numérateur : Nombre d'entreprises concernées par une AMT
			
			VAR TotalAdherentsActifsOuSuspendus =
			    [Adhérents actifs ou suspendus]                                -- Dénominateur : Nombre total d'adhérents actifs ou suspendus
			
			VAR PourcentageEntreprisesConcerneesAMT =
			    DIVIDE(
			        EntreprisesConcerneesAMT,                                           -- Numérateur
			        TotalAdherentsActifsOuSuspendus,                                    -- Dénominateur
			        BLANK()                                                             -- Retourner une valeur vide si le dénominateur est nul
			    )
			
			RETURN
			    FORMAT(
			        PourcentageEntreprisesConcerneesAMT,
			        "0.00%"                                                             -- Formater le résultat en pourcentage avec deux décimales
			    )
			
			-- Description :
			-- Cette mesure calcule le pourcentage d'entreprises concernées par une AMT par rapport au nombre total d'adhérents actifs ou suspendus.
			-- Elle utilise DIVIDE pour gérer les divisions par zéro et FORMAT pour afficher le résultat en pourcentage.
			
			```
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 00ccffaf-e101-43f7-8d6d-a4539c441633

	measure '% adhérents bénéficiaire AMT DU' =
			
			"% des adhérents ayant bénéficié d'une AMT DUERP (info-DU, eval-DU ou sensi atelier-DU) du " & [Période (Du au)]
		displayFolder: Titres
		lineageTag: 88fac844-3271-4cf0-98c9-fb860157c30d

	measure 'Adhérents concernés AMT Période N-1' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR DatesPeriodeN1 =
			    DATEADD(DatesPeriode, -1, YEAR)
			RETURN
			CALCULATE( [# entreprises concernées (AMT)], DatesPeriodeN1 )
			
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 84f81628-56d5-4940-ab8c-aeba0dfa4ca0

	measure 'Adhérents concernés AMT évolution' =
			
			DIVIDE(
			    [Adhérents concernés AMT] - [Adhérents concernés AMT Période N-1],
			    [Adhérents concernés AMT Période N-1]
			)
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: d404122d-f73a-44fe-b554-2bbb9b051555

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Adhérents concernés AMT évolution (+/-)' =
			
			VAR Evolution = [Adhérents concernés AMT évolution]
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 226916ec-9b9f-4e09-81e5-e0c1f72e947b

	measure '% Entreprises Concernées par AMT N-1' = ```
			
			VAR EntreprisesConcerneesAMT =
			    [Adhérents concernés AMT Période N-1]                                        -- Numérateur : Nombre d'entreprises concernées par une AMT
			
			VAR TotalAdherentsActifsOuSuspendus =
			    [Adhérents actifs ou suspendus N-1]                                -- Dénominateur : Nombre total d'adhérents actifs ou suspendus
			
			VAR PourcentageEntreprisesConcerneesAMT =
			    DIVIDE(
			        EntreprisesConcerneesAMT,                                           -- Numérateur
			        TotalAdherentsActifsOuSuspendus,                                    -- Dénominateur
			        BLANK()                                                             -- Retourner une valeur vide si le dénominateur est nul
			    )
			
			RETURN
			    FORMAT(
			        PourcentageEntreprisesConcerneesAMT,
			        "0.00%"                                                             -- Formater le résultat en pourcentage avec deux décimales
			    )
			
			-- Description :
			-- Cette mesure calcule le pourcentage d'entreprises concernées par une AMT par rapport au nombre total d'adhérents actifs ou suspendus.
			-- Elle utilise DIVIDE pour gérer les divisions par zéro et FORMAT pour afficher le résultat en pourcentage.
			
			```
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: b09600bc-462d-413f-a1b2-eb95fd09cada

	measure 'Période (Du au) N-1' =
			
			Var DateMax = [Date Fin Arrêté]
			Var DateMin = EDATE(DateMax, -12)
			Var DateMinMoinsUn = EDATE(DateMin, -12)+1
			
			RETURN
			format(DateMinMoinsUn,"DD mmmm YYYY", "fr-FR")&" au "&format(DateMin,"DD mmmm YYYY", "fr-FR")
		displayFolder: Suivi des indicateurs\Date
		lineageTag: a56e65f9-044d-4ab2-a21f-8ef0dc6d0a8a

	measure 'sous titre adhérents à jour d''APP' =
			
			"Adhérents ayant bénéficié d'une APP entre le "& format([Date 4 an avant 2], "DD mmmm YYYY", "fr-FR") & " et le " &[Date Fin Arrêté]
		displayFolder: Titres
		lineageTag: c9540185-74af-46bb-9d9a-bdb9013eafee

	measure 'Date 4 an avant 2' = ```
			
			-- 1. On récupère la date choisie actuelle
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date exacte 4 an avant (EDATE gère parfaitement les années bissextiles)
			VAR DateNMoins4 = EDATE(DateActuelle, -48)+1
			
			RETURN
			FORMAT(
			    DateNMoins4,
			        "DD mmmm YYYY", 
			        "fr-FR"
			)
			```
		displayFolder: Suivi des indicateurs\Date
		lineageTag: 381c85a9-dec3-4432-ba05-6780a1e13a71

	measure 'AMT Période' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([# AMT terminées], DatesPeriode)
		formatString: #,0
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: f4af946a-a6c8-480a-8f58-f75682574b68

	measure 'Objectif APP' =
			
			0.75
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: a15d3b0e-a281-4d2c-80fd-c26cc54e620e

	measure '% Adhérents à jour de FE (Réalisé)' = ```
			
			VAR DerniereDateReelle = CALCULATE(MAX('Date principale'[Date]), ALL('Date principale'))
			VAR DateSimu = MAX('Date Simulation'[Date])
			
			RETURN
			IF(
			    -- On coupe l'affichage après la dernière vraie date pour laisser la place à la simu
			    DateSimu <= DerniereDateReelle,
			    
			    CALCULATE(
			        [% Adhérents FE (Base)], -- On appelle la mesure de BASE
			        TREATAS(VALUES('Date Simulation'[Date]), 'Date principale'[Date])
			    ),
			    BLANK()
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\FE
		lineageTag: c8c70f42-06ae-4045-b80d-7e8321405c6b

	measure 'Adhérents concernés AMT à leur demande' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([# entreprises concernées (AMT)],'AMT - informations principales'[Origine de la demande] = "AMT demandée par l'entreprise", DatesPeriode)
		formatString: 0
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 5401f432-5572-4564-bd41-2a7aefa37f8a

	measure '% Entreprises Concernées par AMT à leur demande' = ```
			
			VAR EntreprisesConcerneesAMT =
			    [Adhérents concernés AMT à leur demande]                                        -- Numérateur : Nombre d'entreprises concernées par une AMT
			
			VAR TotalAdherentsActifsOuSuspendus =
			    [Adhérents actifs ou suspendus]                                -- Dénominateur : Nombre total d'adhérents actifs ou suspendus
			
			VAR PourcentageEntreprisesConcerneesAMT =
			    DIVIDE(
			        EntreprisesConcerneesAMT,                                           -- Numérateur
			        TotalAdherentsActifsOuSuspendus,                                    -- Dénominateur
			        BLANK()                                                             -- Retourner une valeur vide si le dénominateur est nul
			    )
			
			RETURN
			    FORMAT(
			        PourcentageEntreprisesConcerneesAMT,
			        "0.00%"                                                             -- Formater le résultat en pourcentage avec deux décimales
			    )
			
			-- Description :
			-- Cette mesure calcule le pourcentage d'entreprises concernées par une AMT par rapport au nombre total d'adhérents actifs ou suspendus.
			-- Elle utilise DIVIDE pour gérer les divisions par zéro et FORMAT pour afficher le résultat en pourcentage.
			
			```
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 2a9c6b13-d2b2-4b00-bca9-f2f576b34bca

	measure 'Adhérents concernés AMT à leur demande Période N-1' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR DatesPeriodeN1 =
			    DATEADD(DatesPeriode, -1, YEAR)
			RETURN
			CALCULATE( [# entreprises concernées (AMT)], 'AMT - informations principales'[Origine de la demande] = "AMT demandée par l'entreprise", DatesPeriodeN1 )
			
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 5d525a97-7d2f-481c-b5e9-784dfd1d4119

	measure '% Entreprises Concernées par AMT à leur demande N-1' = ```
			
			VAR EntreprisesConcerneesAMT =
			    [Adhérents concernés AMT à leur demande Période N-1]                                        -- Numérateur : Nombre d'entreprises concernées par une AMT
			
			VAR TotalAdherentsActifsOuSuspendus =
			    [Adhérents actifs ou suspendus N-1]                                -- Dénominateur : Nombre total d'adhérents actifs ou suspendus
			
			VAR PourcentageEntreprisesConcerneesAMT =
			    DIVIDE(
			        EntreprisesConcerneesAMT,                                           -- Numérateur
			        TotalAdherentsActifsOuSuspendus,                                    -- Dénominateur
			        BLANK()                                                             -- Retourner une valeur vide si le dénominateur est nul
			    )
			
			RETURN
			    FORMAT(
			        PourcentageEntreprisesConcerneesAMT,
			        "0.00%"                                                             -- Formater le résultat en pourcentage avec deux décimales
			    )
			
			-- Description :
			-- Cette mesure calcule le pourcentage d'entreprises concernées par une AMT par rapport au nombre total d'adhérents actifs ou suspendus.
			-- Elle utilise DIVIDE pour gérer les divisions par zéro et FORMAT pour afficher le résultat en pourcentage.
			
			```
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: b6772407-40da-47a5-9932-6d0c84589d58

	measure '% Entreprises Concernées par AMT (graph)' = ```
			
			-- 1. Définition de la fenêtre
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			IF(
			    -- Condition d'affichage (fenêtre)
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			
			    [% Entreprises Concernées par AMT],
			    
			    BLANK()
			)
			```
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 834263f4-41c6-44f4-84c1-e22fef816666

	measure 'AMT CSE Période' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([# AMT terminées], 'AMT - modèle'[Modèle] = "Réunion - Participation CSE", DatesPeriode)
		formatString: 0
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: add50ac7-3abc-40d4-a692-aa142bd4d655

	measure 'AMT Période N-1' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR DatesPeriodeN1 =
			    DATEADD(DatesPeriode, -1, YEAR)
			RETURN
			CALCULATE( [# AMT terminées], DatesPeriodeN1 )
			
			```
		formatString: #,0
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 3083a376-911f-4954-9168-26180011bad4

	measure 'AMT CSE évolution' =
			
			DIVIDE(
			    [AMT CSE Période] - [AMT CSE Période N-1],
			    [AMT CSE Période N-1]
			)
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 16b452af-40fe-4e95-8598-cebece71f1f7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT CSE évolution (+/-)' =
			
			VAR Evolution = DIVIDE(
			    [AMT CSE Période] - [AMT CSE Période N-1],
			    [AMT CSE Période N-1]
			)
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 725da979-2cd6-42f0-ac15-89effdbb5379

	measure 'AMT (Graphique Dynamique)' = ```
			
			-- 1. On définit la fenêtre de temps souhaitée par rapport au Slicer
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1 -- Recule de 12 mois + 1 jour
			
			-- 2. On regarde la date du point actuel du graphique
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			IF(
			    -- On affiche le chiffre UNIQUEMENT si la date de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			    
			    [# AMT terminées],
			    
			    -- Sinon on renvoie BLANK, ce qui effacera la ligne sur le graphique
			    BLANK()
			)
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 6fdda952-07f8-431b-bd1c-ff72397c72b1

	measure '% AMT CSE sur Nbre d''ahdérents' =
			
			DIVIDE(
			    [AMT CSE Période],
			    [Adhérents actifs ou suspendus],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 89493817-c0a8-480e-a1f9-b8041e49866a

	measure 'AMT CSE Période N-1' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR DatesPeriodeN1 =
			    DATEADD(DatesPeriode, -1, YEAR)
			RETURN
			CALCULATE( [# AMT terminées], 'AMT - modèle'[Modèle] = "Réunion - Participation CSE", DatesPeriodeN1 )
			
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 5f0b1b6f-b1ad-4be9-82cb-91d83d127fcb

	measure '% AMT CSE sur Nbre d''ahdérents N-1' =
			
			DIVIDE(
			    [AMT CSE Période N-1],
			    [Adhérents actifs ou suspendus N-1],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 8b22680f-b426-425e-9319-01b4ec825875

	measure 'Sous titre AMT CSE' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"Part des adhérents de plus de 50 salariés bénéficiaire d'une AMT dont le modèle est 'Réunion - Participation CSE' du "& DatePeriode
		displayFolder: Titres
		lineageTag: 978be2d8-b5ab-466d-80d0-285892e28742

	measure '% Adhérents à jour d''APP' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			CALCULATE(
			    COALESCE(
			        ([% adhérents à jour d'AMT primaire (fin de période)]),
			        0
			    ),
			    'Date principale'[Date] <= DateSnapshot
			)
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: b3e5a653-32b0-48d7-aeac-8c9c8ef2f9c9

	measure 'Adhérents à jour d''APP (graph)' =
			
			-- 1. Définition de la fenêtre de temps (Bornes)
			VAR DateFin = [Date Fin Arrêté]           -- La date sélectionnée dans le Slicer (ex: 31/12/2024)
			VAR DateDebut = EDATE(DateFin, -13) + 1   -- 12 mois glissants avant
			
			-- 2. Contexte du graphique (Point actuel de l'axe X)
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			-- 3. Logique d'affichage
			IF(
			    -- Condition : On affiche seulement si le mois de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			
			    -- Valeur : On appelle directement la mesure de base (celle qui somme la table Evolution)
			    -- Elle va naturellement se calculer pour le "DateSurAxe" (le mois en cours)
			    [% adhérents à jour d'AMT primaire (fin de période)],
			
			    -- Sinon rien
			    BLANK()
			)
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 904099dd-145a-4596-8bfa-a44a0eb8ef77

	measure '% Adhérents à jour d''APP N-1' = ```
			
			-- 1. On récupère la date actuelle (Fin de période sélectionnée)
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date de référence pour l'année précédente (Le "Aujourd'hui" de l'an dernier)
			VAR DateNMoins1 = EDATE(DateActuelle, -12)
			
			-- 3. On définit la limite d'ancienneté pour cette époque-là 
			-- (Pour être "nouveau" en N-1, il faut être arrivé après N-2)
			VAR DateLimiteAncienneteNMoins1 = EDATE(DateNMoins1, -12)
			
			RETURN
			CALCULATE(
			    -- Mesure de base
			    [% adhérents à jour d'AMT primaire (fin de période)],
			
			    -- Filtre 2 : On remonte le temps sur la date principale
			    'Date principale'[Date] <= DateNMoins1
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: f918ea05-34e4-4e5e-94d6-7aee52472040

	measure 'Adhérents à jour d''APP (Variation %)' =
			
			DIVIDE(
			    [Adhérents à jour d'APP] - [Adhérents à jour d'APP N-1],
			    [Adhérents à jour d'APP N-1]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 3b50acfe-b39a-4aab-92ce-afabcf0163b7

	measure 'Adhérents à jour d''APP' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			CALCULATE(
			    COALESCE(
			        ([# adhérents à jour d'AMT primaire (fin de période)]),
			        0
			    ),
			    'Date principale'[Date] <= DateSnapshot
			)
		formatString: 0
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 06625ccc-a8e3-487c-8e1a-7c28891c0f37

	measure 'Adhérents à jour d''APP N-1' = ```
			
			-- 1. On récupère la date actuelle (Fin de période sélectionnée)
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date de référence pour l'année précédente (Le "Aujourd'hui" de l'an dernier)
			VAR DateNMoins1 = EDATE(DateActuelle, -12)
			
			-- 3. On définit la limite d'ancienneté pour cette époque-là 
			-- (Pour être "nouveau" en N-1, il faut être arrivé après N-2)
			VAR DateLimiteAncienneteNMoins1 = EDATE(DateNMoins1, -12)
			
			RETURN
			CALCULATE(
			    -- Mesure de base
			    [# adhérents à jour d'AMT primaire (fin de période)],
			
			    -- Filtre 2 : On remonte le temps sur la date principale
			    'Date principale'[Date] <= DateNMoins1
			)
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: e1fe47cf-d2fb-4e53-ae94-576b58dbc954

	measure 'Adhérents à jour d''APP évolution (+/-)' =
			
			Var Evolution = [Adhérents à jour d'APP (Variation %)]
			
			RETURN
			format(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: c3bc1d81-cb74-4ed2-ae69-31bfa9a3fe05

	measure '% Adhérents à jour de FE' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			CALCULATE(
			    COALESCE(
			        ([% adhérents à jour de FE (fin de période)]),
			        0
			    ),
			    'Date principale'[Date] <= DateSnapshot
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 4728fa63-7183-4d12-8f7d-c831c3f7e98c

	measure '% Adhérents à jour de APP (Réalisé)' = ```
			
			VAR DerniereDateReelle = CALCULATE(MAX('Date principale'[Date]), ALL('Date principale'))
			VAR DateSimu = MAX('Date Simulation'[Date])
			
			RETURN
			IF(
			    -- On coupe l'affichage après la dernière vraie date pour laisser la place à la simu
			    DateSimu <= DerniereDateReelle,
			    
			    CALCULATE(
			        [% adhérents à jour d'AMT primaire (fin de période)], -- On appelle la mesure de BASE
			        TREATAS(VALUES('Date Simulation'[Date]), 'Date principale'[Date])
			    ),
			    BLANK()
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: aec2c799-9405-4de4-bea2-ede3668f5ae1

	measure '% Adhérents à jour d''APP (graph)' =
			
			-- 1. Définition de la fenêtre de temps (Bornes)
			VAR DateFin = [Date Fin Arrêté]           -- La date sélectionnée dans le Slicer (ex: 31/12/2024)
			VAR DateDebut = EDATE(DateFin, -13) + 1   -- 12 mois glissants avant
			
			-- 2. Contexte du graphique (Point actuel de l'axe X)
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			-- 3. Logique d'affichage
			IF(
			    -- Condition : On affiche seulement si le mois de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			
			    -- Valeur : On appelle directement la mesure de base (celle qui somme la table Evolution)
			    -- Elle va naturellement se calculer pour le "DateSurAxe" (le mois en cours)
			    [% adhérents à jour d'AMT primaire (fin de période)],
			
			    -- Sinon rien
			    BLANK()
			)
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: cabc0a06-ed48-4f32-94bb-fac8d6fdf4ea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Objectif APP 2026 (Simu)' = ```
			
			-- 1. On récupère la date de l'axe et on la force en FIN DE MOIS
			VAR DateAxe = EOMONTH(MAX('Date Simulation'[Date]), 0)
			VAR DateCible = DATE(2026, 12, 31)
			VAR ValCible = [Objectif APP]
			
			-- 2. On cherche la dernière date de données réelles et on la force en FIN DE MOIS
			VAR DateDerniereDonneeBrute = 
			    CALCULATE(
			        MAX('Date principale'[Date]),
			        FILTER(
			            ALL('Date principale'),
			            NOT(ISBLANK([% adhérents à jour d'AMT primaire (fin de période)]))
			        )
			    )
			VAR DateReference = EOMONTH(DateDerniereDonneeBrute, -1) -- On recule de 1 mois et on cale sur la fin du mois
			
			-- 3. On récupère la valeur de départ
			VAR ValDepart = 
			    CALCULATE(
			        [% adhérents à jour d'AMT primaire (fin de période)], 
			        DATESBETWEEN('Date principale'[Date], EOMONTH(DateReference, -1)+1, DateReference)
			    )
			
			-- 4. NOUVELLE LOGIQUE : Gestion de l'écart
			-- Si le départ est supérieur à la cible, l'écart est nul (on reste stable).
			-- Sinon, on calcule la différence classique pour la pente.
			VAR Ecart = 
			    IF(
			        ValDepart > ValCible, 
			        0, 
			        ValCible - ValDepart
			    )
			
			RETURN
			IF(
			    -- CAS 1 : Point de soudure (Si l'axe est le même mois que la ref)
			    DateAxe = DateReference,
			    ValDepart,
			
			    -- CAS 2 : Projection
			    IF(
			        DateAxe > DateReference && DateAxe <= DateCible,
			        
			        VAR DureeTotale = DATEDIFF(DateReference, DateCible, DAY)
			        VAR DureeEcoulee = DATEDIFF(DateReference, DateAxe, DAY)
			        
			        -- Si Ecart est 0 (car ValDepart > ValCible), le calcul ajoute 0, donc on reste à ValDepart
			        RETURN ValDepart + (Ecart * DIVIDE(DureeEcoulee, DureeTotale)),
			        
			        BLANK()
			    )
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 32bd8697-869c-490c-b637-d12db5e9e4cf

	measure 'Visites sur effectif suivi' = ```
			
			Var visites = [Visites Période]
			Var effectifSuivi = [Evolution Effectif - effectif suivi]
			
			RETURN
			DIVIDE(
			    visites, 
			    effectifSuivi,
			    0
			)
			```
		displayFolder: Suivi des indicateurs\Visites
		lineageTag: 3f0ac253-1def-46bb-a032-811c72957e2a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visites sur effectif suivi N-1' = ```
			
			Var visites = [Visites Période N-1]
			Var effectifSuivi = [Evolution effectif - Effectif suivi N-1]
			
			RETURN
			DIVIDE(
			    visites, 
			    effectifSuivi,
			    0
			)
			```
		displayFolder: Suivi des indicateurs\Visites
		lineageTag: e3920461-2d19-45e8-97ad-9967330a93e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visites sur effectif évolution (+/-)' =
			
			VAR Evolution = DIVIDE(
			    [Visites sur effectif suivi] - [Visites sur effectif suivi N-1],
			    [Visites sur effectif suivi N-1]
			)
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\Visites
		lineageTag: c5b2e7d3-564c-4f74-a4d1-f7c121227243

	measure 'Visites sur effectif suivi évolution' =
			
			DIVIDE(
			    [Visites sur effectif suivi] - [Visites sur effectif suivi N-1],
			    [Visites sur effectif suivi N-1]
			)
		displayFolder: Suivi des indicateurs\Visites
		lineageTag: b90f4bd5-6f13-4524-91f1-4ed47459bb93

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visites sur effectif (Graphique Dynamique)' = ```
			
			-- 1. On définit la fenêtre de temps souhaitée par rapport au Slicer
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1 -- Recule de 12 mois + 1 jour
			
			-- 2. On regarde la date du point actuel du graphique
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			IF(
			    -- On affiche le chiffre UNIQUEMENT si la date de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			    
			    DIVIDE([Nombre de visites réalisées (RDV)],('Evolution effectif'[Effectif suivi figé non intérimaire fin de période])+'Evolution effectif'[Effectif suivi figé intérimaire fin de période])*10,
			    
			    -- Sinon on renvoie BLANK, ce qui effacera la ligne sur le graphique
			    BLANK()
			)
			```
		displayFolder: Suivi des indicateurs\Visites
		lineageTag: 129de09d-991b-4f0b-a303-f4e95be24eaa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RDV Période' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([Nombre de RDV avec convocation], DatesPeriode)
		formatString: #,0
		displayFolder: Suivi des indicateurs\RDV
		lineageTag: 61d8750f-61b8-4155-abd7-bc0a192f3f39

	measure 'RDV sur effectif suivi' = ```
			
			Var RDV = [RDV Période]
			Var effectifSuivi = [Evolution Effectif - effectif suivi]
			
			RETURN
			DIVIDE(
			    RDV, 
			    effectifSuivi,
			    0
			)
			```
		displayFolder: Suivi des indicateurs\RDV
		lineageTag: f3d7e25b-6300-4898-83ce-59e80787e9b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RDV Période N-1' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR DatesPeriodeN1 =
			    DATEADD(DatesPeriode, -1, YEAR)
			RETURN
			CALCULATE( [Nombre de RDV avec convocation], DatesPeriodeN1 )
			
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\RDV
		lineageTag: 3cf81bd4-3334-4cf7-b3b2-701d5348cf88

	measure 'RDV sur effectif suivi N-1' = ```
			
			Var RDV = [RDV Période N-1]
			Var effectifSuivi = [Evolution effectif - Effectif suivi N-1]
			
			RETURN
			DIVIDE(
			    RDV, 
			    effectifSuivi,
			    0
			)
			```
		displayFolder: Suivi des indicateurs\RDV
		lineageTag: 7fa58768-ce9c-4cad-bc4a-6bf76f4ba14a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RDV sur effectif suivi évolution' =
			
			DIVIDE(
			    [RDV sur effectif suivi] - [RDV sur effectif suivi N-1],
			    [RDV sur effectif suivi N-1]
			)
		displayFolder: Suivi des indicateurs\RDV
		lineageTag: 833cb84d-b4d0-48a1-acce-fee660757d7b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RDV sur effectif évolution (+/-)' =
			
			VAR Evolution = DIVIDE(
			    [RDV sur effectif suivi] - [RDV sur effectif suivi N-1],
			    [RDV sur effectif suivi N-1]
			)
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\RDV
		lineageTag: e95085ea-7517-4e4f-b31d-67cbd31dcdcd

	measure 'RDV sur effectif (Graphique Dynamique)' = ```
			
			-- 1. On définit la fenêtre de temps souhaitée par rapport au Slicer
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1 -- Recule de 12 mois + 1 jour
			
			-- 2. On regarde la date du point actuel du graphique
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			IF(
			    -- On affiche le chiffre UNIQUEMENT si la date de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			    
			    DIVIDE([Nombre de RDV avec convocation],('Evolution effectif'[Effectif suivi figé non intérimaire fin de période])+'Evolution effectif'[Effectif suivi figé intérimaire fin de période])*10,
			    
			    -- Sinon on renvoie BLANK, ce qui effacera la ligne sur le graphique
			    BLANK()
			)
			```
		displayFolder: Suivi des indicateurs\RDV
		lineageTag: 1bfa58e8-30bc-41d2-9f12-adfb10855360

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Date max' = ```
			
			"Au "&FORMAT(
			    [Date Fin Arrêté],
			        "DD mmmm YYYY", 
			        "fr-FR"
			)
			```
		displayFolder: Suivi des indicateurs\Date
		lineageTag: d2dbb1de-b354-4055-aacb-4e32a7ff32c8

	measure 'Date Max N-1' = ```
			
			"Au "&FORMAT(EDATE([Date Fin Arrêté],-12),
			        "DD mmmm YYYY", 
			        "fr-FR"
			)& " :  "
			```
		displayFolder: Suivi des indicateurs\Date
		lineageTag: 0c2ba2ad-e218-4db4-b19d-3d5a4ff993f4

	measure 'Objectif Taux de service' =
			
			0.9
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\Taux de service
		lineageTag: 57a23ee5-8947-4c05-ad74-f58e9b619f92

	measure 'Taux de service (Réalisé)' =
			
			CALCULATE(
			    [Taux de service (graph)],
			    -- On "transfère" la date sélectionnée vers la vraie table date
			    TREATAS(VALUES('Date Simulation'[Date]), 'Date principale'[Date])
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\Taux de service
		lineageTag: e563885e-e45b-40f6-a25f-6cafa16bcec2

	measure 'Taux de service' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			CALCULATE(
			    1-[Taux de retard],
			    'Date principale'[Date] <= DateSnapshot
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\Taux de service
		lineageTag: 754bdd05-3f0e-4030-baf2-2e596b1cf53f

	measure 'Taux de service (graph)' =
			
			-- 1. Définition de la fenêtre de temps (Bornes)
			VAR DateFin = [Date Fin Arrêté]           -- La date sélectionnée dans le Slicer (ex: 31/12/2024)
			VAR DateDebut = EDATE(DateFin, -13) + 1   -- 12 mois glissants avant
			VAR TauxService = 1-[Taux de retard]
			
			-- 2. Contexte du graphique (Point actuel de l'axe X)
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			-- 3. Logique d'affichage
			IF(
			    -- Condition : On affiche seulement si le mois de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			
			    -- Valeur : On appelle directement la mesure de base (celle qui somme la table Evolution)
			    -- Elle va naturellement se calculer pour le "DateSurAxe" (le mois en cours)
			    TauxService,
			
			    -- Sinon rien
			    BLANK()
			)
		displayFolder: Suivi des indicateurs\Taux de service
		lineageTag: b635685e-287a-4c4d-967d-75199b7e2836

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Objectif Taux de service 2026 (Simu)' = ```
			
			VAR DateAxe = MAX('Date Simulation'[Date]) -- On lit notre nouvel axe
			VAR DateCible = DATE(2026, 12, 31)
			VAR ValCible = [Objectif Taux de service]
			
			-- 1. On trouve la dernière date où on a du "vrai" réalisé
			VAR DateDerniereDonnee = 
			    CALCULATE(
			        MAX('Date principale'[Date]),
			        FILTER(
			            ALL('Date principale'), -- On prend toute la table
			            NOT(ISBLANK([Taux de service (graph)])) -- Et on teste la mesure ligne par ligne
			        )
			    )
			
			-- 2. On récupère la valeur de départ à cette date précise
			VAR ValDepart = 
			    CALCULATE(
			        [Taux de service (graph)],
			        'Date principale'[Date] = DateDerniereDonnee
			    )
			
			RETURN
			-- 3. On affiche la projection uniquement pour le futur
			IF(
			    DateAxe >= DateDerniereDonnee && DateAxe <= DateCible,
			    
			    VAR DureeTotale = DATEDIFF(DateDerniereDonnee, DateCible, DAY)
			    VAR DureeEcoulee = DATEDIFF(DateDerniereDonnee, DateAxe, DAY)
			    VAR Ecart = ValCible - ValDepart
			    
			    RETURN ValDepart + (Ecart * DIVIDE(DureeEcoulee, DureeTotale)),
			    
			    BLANK()
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\Taux de service
		lineageTag: 76e9d0c7-1e66-4497-bd5a-a4275f8868dd

	measure 'Taux de Service N-1' = ```
			
			-- 1. On récupère la date actuelle (Fin de période sélectionnée)
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date de référence pour l'année précédente (Le "Aujourd'hui" de l'an dernier)
			VAR DateNMoins1 = EDATE(DateActuelle, -12)
			
			-- 3. On définit la limite d'ancienneté pour cette époque-là 
			-- (Pour être "nouveau" en N-1, il faut être arrivé après N-2)
			VAR DateLimiteAncienneteNMoins1 = EDATE(DateNMoins1, -12)
			
			RETURN
			CALCULATE(
			    -- Mesure de base
			    1-[Taux de retard],
			
			    -- Filtre 2 : On remonte le temps sur la date principale
			    'Date principale'[Date] <= DateNMoins1
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\Taux de service
		lineageTag: 8b90155d-8355-4c7b-aab2-8dade1b864be

	measure 'Taux de service (Variation %)' =
			
			DIVIDE(
			    [Taux de service] - [Taux de service N-1],
			    [Taux de service N-1]
			)
		displayFolder: Suivi des indicateurs\Taux de service
		lineageTag: 5f1ef54f-a7dd-4bc8-9164-43b76c62ce5d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Taux de service évolution (+/-)' =
			
			VAR Evolution = [Taux de service (Variation %)]
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\Taux de service
		lineageTag: 80c3dc79-c78a-4ffd-9a25-f2d495cac96b

	measure 'Salariés en retard' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			CALCULATE(
			           'Evolution retard'[Nombre de salariés suivis],
			           'Evolution retard - catégorie retard'[Catégorie retard]="En retard",
			           'Date principale'[Date] <= DateSnapshot
			)
		formatString: #,0
		displayFolder: Suivi des indicateurs\Taux de service
		lineageTag: cf8d6a5c-46c9-414d-968b-56f0d63ca1f3

	measure 'Salariés en retard N-1' =
			
			-- 1. On récupère la date choisie actuelle
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date exacte 1 an avant (EDATE gère parfaitement les années bissextiles)
			VAR DateNMoins1 = EDATE(DateActuelle, -12)
			
			RETURN
			CALCULATE(
			    'Evolution retard'[Nombre de salariés suivis],
			    'Evolution retard - catégorie retard'[Catégorie retard] = "En retard",
			    -- 3. On remplace le filtre de date par celle de l'année précédente
			    'Date principale'[Date] <= DateNMoins1
			)
		formatString: #,0
		displayFolder: Suivi des indicateurs\Taux de service
		lineageTag: 27f247d0-82e2-4735-abc4-70eb37a5c6ee

	measure 'Salariés en retard (Variation %)' =
			
			DIVIDE(
			    [Salariés en retard] - [Salariés en retard N-1],
			    [Salariés en retard N-1]
			)
		displayFolder: Suivi des indicateurs\Taux de service
		lineageTag: 6a7892eb-291b-47a8-908e-d398150e1e24

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Evolution Salariés en retard (+/-)' =
			
			VAR Evolution = [Evolution salariés en retard (Variation %)]
			RETURN
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\Taux de service
		lineageTag: 280c46a3-80b3-4279-81c0-b10a6df7209a

	measure 'Evolution salariés en retard (Variation %)' =
			
			DIVIDE(
			    [Salariés en retard] - [Salariés en retard N-1],
			    [Salariés en retard N-1]
			)
		displayFolder: Suivi des indicateurs\Taux de service
		lineageTag: 6d031a72-a54a-4616-9bcb-8a586458e8f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Taux de convocation' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			CALCULATE(
			    [Taux de convocations],
			    'Date principale'[Date] <= DateSnapshot
			)
		formatString: 0.00
		displayFolder: Suivi des indicateurs\RDV
		lineageTag: 7425ec99-b089-4400-b26a-2f73516e5353

	measure 'Sous titre taux de convocation' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"Nombre de RDV avec convocation sur nombre de visites réalisées du "& DatePeriode
		displayFolder: Titres
		lineageTag: 006bdb3b-f2fc-4dfa-888b-0601cec5838d

	measure 'Taux de convocation N-1' = ```
			
			-- 1. On récupère la date actuelle (Fin de période sélectionnée)
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date de référence pour l'année précédente (Le "Aujourd'hui" de l'an dernier)
			VAR DateNMoins1 = EDATE(DateActuelle, -12)
			
			-- 3. On définit la limite d'ancienneté pour cette époque-là 
			-- (Pour être "nouveau" en N-1, il faut être arrivé après N-2)
			VAR DateLimiteAncienneteNMoins1 = EDATE(DateNMoins1, -12)
			
			RETURN
			CALCULATE(
			    -- Mesure de base
			    [Taux de convocations],
			
			    -- Filtre 2 : On remonte le temps sur la date principale
			    'Date principale'[Date] <= DateNMoins1
			)
			```
		displayFolder: Suivi des indicateurs\RDV
		lineageTag: 66cff75d-aa24-4e17-80b9-b6b90f0e4b2f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Taux de convocation (graph)' =
			
			-- 1. Définition de la fenêtre de temps (Bornes)
			VAR DateFin = [Date Fin Arrêté]           -- La date sélectionnée dans le Slicer (ex: 31/12/2024)
			VAR DateDebut = EDATE(DateFin, -13) + 1   -- 12 mois glissants avant
			VAR TauxConvocation = [Taux de convocations]
			
			-- 2. Contexte du graphique (Point actuel de l'axe X)
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			-- 3. Logique d'affichage
			IF(
			    -- Condition : On affiche seulement si le mois de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			
			    -- Valeur : On appelle directement la mesure de base (celle qui somme la table Evolution)
			    -- Elle va naturellement se calculer pour le "DateSurAxe" (le mois en cours)
			    TauxConvocation,
			
			    -- Sinon rien
			    BLANK()
			)
		displayFolder: Suivi des indicateurs\RDV
		lineageTag: 9ff16076-fe33-4878-9315-0e5d94a3e5a0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Taux de convocation (Variation %)' =
			
			DIVIDE(
			    [Taux de convocation] - [Taux de convocation N-1],
			    [Taux de convocation N-1]
			)
		displayFolder: Suivi des indicateurs\RDV
		lineageTag: b267e38f-eb10-40c5-85a6-65c92af06a16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Taux de convocation évolution (+/-)' =
			
			VAR Evolution = [Taux de convocation (Variation %)]
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\RDV
		lineageTag: f97c2a25-418a-4c56-9783-6e9b02f720cf

	measure 'Taux annexes 4 (graph)' =
			
			-- 1. Définition de la fenêtre de temps (Bornes)
			VAR DateFin = [Date Fin Arrêté]           -- La date sélectionnée dans le Slicer (ex: 31/12/2024)
			VAR DateDebut = EDATE(DateFin, -13) + 1   -- 12 mois glissants avant
			VAR TauxAnnexe4 = [Taux d'Annexes4]
			
			-- 2. Contexte du graphique (Point actuel de l'axe X)
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			-- 3. Logique d'affichage
			IF(
			    -- Condition : On affiche seulement si le mois de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			
			    -- Valeur : On appelle directement la mesure de base (celle qui somme la table Evolution)
			    -- Elle va naturellement se calculer pour le "DateSurAxe" (le mois en cours)
			    TauxAnnexe4,
			
			    -- Sinon rien
			    BLANK()
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\Annexes 4
		lineageTag: 9ff16076-fe33-4878-9315-0e5d94a3z5a0

	measure 'Taux annexes 4 (Variation %)' =
			
			DIVIDE(
			    [Taux annexes 4] - [Taux annexes 4 N-1],
			    [Taux annexes 4 N-1]
			)
		displayFolder: Suivi des indicateurs\Annexes 4
		lineageTag: b267e38f-eb10-40c5-85a6-65c92afz6a16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Taux annexes 4 évolution (+/-)' =
			
			VAR Evolution = [Taux annexes 4 (Variation %)]
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\Annexes 4
		lineageTag: f97c2a25-418a-4c56-9783-6z9b02f720cf

	measure 'Taux annexes 4 N-1' =
			
			-- 1. On récupère la date actuelle (Fin de période sélectionnée)
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date de référence pour l'année précédente (Le "Aujourd'hui" de l'an dernier)
			VAR DateNMoins1 = EDATE(DateActuelle, -12)
			
			-- 3. On définit la limite d'ancienneté pour cette époque-là
			-- (Pour être "nouveau" en N-1, il faut être arrivé après N-2)
			VAR DateLimiteAncienneteNMoins1 = EDATE(DateNMoins1, -12)
			
			RETURN
			CALCULATE(
			    -- Mesure de base
			    [Taux d'Annexes4],
			
			    -- Filtre 2 : On remonte le temps sur la date principale
			    'Date principale'[Date] <= DateNMoins1
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\Annexes 4
		lineageTag: 66cff75d-aa24-4e17-80bz-b6b90f0e4b2f

	measure 'Taux annexes 4' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			CALCULATE(
			    [Taux d'Annexes4],
			    'Date principale'[Date] <= DateSnapshot
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\Annexes 4
		lineageTag: f9803cc3-2f3b-4b38-ab6c-696878543f3d

	measure 'Taux inaptitude' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			CALCULATE(
			    [Taux d'inaptitude],
			    'Date principale'[Date] <= DateSnapshot
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\inaptitude
		lineageTag: f9803cc3-1f3b-4b38-ab6c-696878543f3d

	measure 'Taux inaptitude (graph)' =
			
			-- 1. Définition de la fenêtre de temps (Bornes)
			VAR DateFin = [Date Fin Arrêté]           -- La date sélectionnée dans le Slicer (ex: 31/12/2024)
			VAR DateDebut = EDATE(DateFin, -13) + 1   -- 12 mois glissants avant
			VAR TauxAnnexe4 = [Taux d'inaptitude]
			
			-- 2. Contexte du graphique (Point actuel de l'axe X)
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			-- 3. Logique d'affichage
			IF(
			    -- Condition : On affiche seulement si le mois de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			
			    -- Valeur : On appelle directement la mesure de base (celle qui somme la table Evolution)
			    -- Elle va naturellement se calculer pour le "DateSurAxe" (le mois en cours)
			    TauxAnnexe4,
			
			    -- Sinon rien
			    BLANK()
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\inaptitude
		lineageTag: 9ff16076-fe33-4878-9315-0e5d99a3z5a0

	measure 'Taux inaptitude (Variation %)' =
			
			DIVIDE(
			    [Taux inaptitude] - [Taux inaptitude N-1],
			    [Taux inaptitude N-1]
			)
		displayFolder: Suivi des indicateurs\inaptitude
		lineageTag: b267e38f-ab10-40c5-85a6-65c92afz6a16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Taux inaptitude évolution (+/-)' =
			
			VAR Evolution = [Taux inaptitude (Variation %)]
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\inaptitude
		lineageTag: f99c2a25-418a-4c56-9783-6z9b02f720cf

	measure 'Taux inaptitude N-1' =
			
			-- 1. On récupère la date actuelle (Fin de période sélectionnée)
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date de référence pour l'année précédente (Le "Aujourd'hui" de l'an dernier)
			VAR DateNMoins1 = EDATE(DateActuelle, -12)
			
			-- 3. On définit la limite d'ancienneté pour cette époque-là
			-- (Pour être "nouveau" en N-1, il faut être arrivé après N-2)
			VAR DateLimiteAncienneteNMoins1 = EDATE(DateNMoins1, -12)
			
			RETURN
			CALCULATE(
			    -- Mesure de base
			    [Taux d'inaptitude],
			
			    -- Filtre 2 : On remonte le temps sur la date principale
			    'Date principale'[Date] <= DateNMoins1
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\inaptitude
		lineageTag: 69cff75d-aa24-4e17-80bz-b6b90f0e4b2f

	measure 'Sous titre taux annexes 4' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"Nombre de documents émis de type annexes 4 temporaires ou permanentes sur nombre de visites réalisées du "& DatePeriode
		displayFolder: Titres
		lineageTag: f819b110-c6db-4e5b-9f68-3c7e0272d3fa

	measure 'Sous titre taux d''inaptitude' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"Nombre d'avis d'inaptitude sur nombre de visites réalisées du "& DatePeriode
		displayFolder: Titres
		lineageTag: 14cb7192-8cfe-46ed-9f5a-03c0b5db132e

	measure 'Adhérents concernés AMT (Graph)' = ```
			
			-- 1. Définition de la fenêtre de temps (inchangé)
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -13) + 1 
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			IF(
			    -- On affiche le chiffre UNIQUEMENT si la date de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			    
			    -- 2. On récupère simplement la valeur stockée dans votre table
			    ([# entreprises concernées (AMT)]),
			    
			    BLANK()
			)
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: dde2e6bf-584f-4994-b5e8-e3c77630df69

	measure 'Evénements collectifs Période' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			COALESCE(
			    CALCULATE(
			        [# évènements collectifs], DatesPeriode
			        ),
			        0
			)
		formatString: 0
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: d638caa2-96e8-4207-ad18-5ee1a70bff1f

	measure 'Orientations Période' =
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE([# demandes consultation spécialisée], DatesPeriode)
		formatString: #,0
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 23d5ee3d-8ee2-411f-b818-addbff9a5b9a

	measure 'Taux d''orientation MEE' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			CALCULATE(
			    [Taux d'orientations PDP],
			    'Date principale'[Date] <= DateSnapshot
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 9f9f9f77-7994-442f-ad5b-2bfa6e0a5ecd

	measure 'Plans MEE cloturés Période' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			COALESCE(
			    CALCULATE(
			        [# plans MEE], 
			        'Plan MEE - informations'[Statut plan MEE] = "Clôturé", 
			        DatesPeriode
			        ),
			        0
			)
			```
		formatString: #,0
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 17c944f1-21e8-4cc8-9dee-76ebc6c5fa08

	measure 'Plans MEE avec maintien au poste période' = ```
			
			CALCULATE(
			    [Plans MEE cloturés Période], 
			    'Plan MEE - informations'[Situation salarié après plan MEE] in {"En poste avec aménagement (dans l'entreprise initiale)","En poste sans aménagement (dans l'entreprise initiale)"}
			 )
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 6d1a0a7f-9758-4b8f-bf00-89e229f59de9

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Plans MEE avec maintien dans l''emploi période' = ```
			
			CALCULATE(
			    [Plans MEE cloturés Période], 
			    'Plan MEE - informations'[Catégorie résultat plan MEE] = "Avec maintien en emploi" 
			 )
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 7652f95e-b521-4166-9f15-d6159b7cab4b

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Plans MEE avec reclassement période' = ```
			
			CALCULATE(
			    [Plans MEE cloturés Période], 
			    'Plan MEE - informations'[Situation salarié après plan MEE] in {"Reclassé en interne (dans l'entreprise initiale)","Reclassé en externe (hors de l'entreprise initiale)"}
			 )
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: ce58395c-0759-4316-92d0-c4b2f8e121d3

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Plans MEE refusé par le salarié période' = ```
			
			CALCULATE(
			    [Plans MEE cloturés Période], 
			    'Plan MEE - dispositifs'[Motif de non réalisation du dispositif] = "Refus du salarié"
			)
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 424c2929-e912-41b6-847a-053fde39447b

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Plans MEE sans solution période' = ```
			
			CALCULATE(
			    [Plans MEE cloturés Période], 
			    'Plan MEE - informations'[SOUS-catégorie résultat plan MEE] = "Sans solution" 
			 )
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 768857d3-1905-40ad-8264-3207e944aca1

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Ratio maintien au poste / plan MEE période' =
			
			DIVIDE(
			    [Plans MEE avec maintien au poste période],
			    [Plans MEE cloturés Période],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: cf796004-bdd7-40d8-ae3c-96650e7795ea

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Ratio maintien dans l''emploi / plan MEE période' =
			
			DIVIDE(
			    [Plans MEE avec maintien dans l'emploi période],
			    [Plans MEE cloturés Période],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 0b5529e2-a01e-43c3-8df7-5d813fb08c38

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Ratio plan MEE sans solution / plan MEE période' =
			
			DIVIDE(
			    [Plans MEE sans solution période],
			    [Plans MEE cloturés Période],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 82eda09b-6c7c-443f-8e86-45d31449f910

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Ratio reclassement / plan MEE période' =
			
			DIVIDE(
			    [Plans MEE avec reclassement période],
			    [Plans MEE cloturés Période],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 62117a97-25af-4d77-8d7b-c1e72c11736d

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Ratio refus du salarié / plan MEE période' =
			
			DIVIDE(
			    [Plans MEE refusé par le salarié période],
			    [Plans MEE cloturés Période],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 960d71b3-e091-4845-8305-1f2f1e58b004

		changedProperty = DisplayFolder

		changedProperty = Name

		changedProperty = FormatString

	measure 'Orientations (Graph)' = ```
			
			-- 1. On définit la fenêtre de temps souhaitée par rapport au Slicer
			VAR DateFin = [Date Fin Arrêté]
			VAR DateDebut = EDATE(DateFin, -12) + 1 -- Recule de 12 mois + 1 jour
			
			-- 2. On regarde la date du point actuel du graphique
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			IF(
			    -- On affiche le chiffre UNIQUEMENT si la date de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			    
			    [# demandes consultation spécialisée],
			    
			    -- Sinon on renvoie BLANK, ce qui effacera la ligne sur le graphique
			    BLANK()
			)
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: b5bf40e2-0b01-4d56-9ab9-c49e56a74ec3

	measure 'sous titre plan mee' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"Plans MEE clôturés du "& DatePeriode
		displayFolder: Titres
		lineageTag: f61e5ef7-28be-43cd-a7da-21706f7f2f1a

	measure 'Orientations Période N-1' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR DatesPeriodeN1 =
			    DATEADD(DatesPeriode, -1, YEAR)
			RETURN
			CALCULATE( [# demandes consultation spécialisée], DatesPeriodeN1 )
			
			```
		formatString: #,0
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: fbe60ab1-22ca-4e6a-837a-9a5ccae9fbcb

	measure 'Plans MEE cloturés Période N-1' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR DatesPeriodeN1 =
			    DATEADD(DatesPeriode, -1, YEAR)
			Return
			COALESCE(
			    CALCULATE(
			        [# plans MEE], 
			        'Plan MEE - informations'[Statut plan MEE] = "Clôturé", 
			         DatesPeriodeN1
			        ),
			        0
			)
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 786fed82-d664-40d9-972e-c9e4cff7fcfe

	measure 'sous titre orientations mee' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"Demandes de consulations spécialisées vers un conseiller maintien en emploi du "& DatePeriode
		displayFolder: Titres
		lineageTag: 72013d68-9d38-4e3c-99e9-cb6af4187452

	measure 'sous titre AMT mee' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"AMT & événement collectifs 'Prévention de la désinsertion professionnelle' du "& DatePeriode
		displayFolder: Titres
		lineageTag: 3dcea2f8-4ef7-4247-9f39-4349a4d514dc

	measure 'Orientations évolution' =
			
			DIVIDE(
			    [Orientations Période] - [Orientations Période N-1],
			    [Orientations Période N-1]
			)
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 2118facc-f718-4bc9-b9a3-aae7ec6e00d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Orientations évolution (+/-)' =
			
			VAR Evolution = DIVIDE(
			    [Orientations Période] - [Orientations Période N-1],
			    [Orientations Période N-1]
			)
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 97c0685f-9420-41f8-bf4e-63dc54d11b4e

	measure 'Taux d''orientations MEE N-1' = ```
			
			-- 1. On récupère la date actuelle (Fin de période sélectionnée)
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date de référence pour l'année précédente (Le "Aujourd'hui" de l'an dernier)
			VAR DateNMoins1 = EDATE(DateActuelle, -12)
			
			-- 3. On définit la limite d'ancienneté pour cette époque-là 
			-- (Pour être "nouveau" en N-1, il faut être arrivé après N-2)
			VAR DateLimiteAncienneteNMoins1 = EDATE(DateNMoins1, -12)
			
			RETURN
			CALCULATE(
			    -- Mesure de base
			    [Taux d'orientations PDP],
			
			    -- Filtre 2 : On remonte le temps sur la date principale
			    'Date principale'[Date] <= DateNMoins1
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 121c6c97-99d9-4c54-ab86-542dc881b0cb

	measure 'Taux d''orientations MEE (Variation %)' = ```
			
			DIVIDE( 
			    [Taux d'orientation MEE] - [Taux d'orientations MEE N-1],
			    [Taux d'orientations MEE N-1]
			)
			```
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 72368fd5-a3a3-453d-a797-021ab62f01e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Taux d''orientations MEE évolution (+/-)' =
			
			VAR Evolution = [Taux d'orientations MEE (Variation %)]
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 573aa53a-8c59-45bb-b5a8-cdac11a1a853

	measure 'Taux d''orientations MEE (graph)' =
			
			-- 1. Définition de la fenêtre de temps (Bornes)
			VAR DateFin = [Date Fin Arrêté]           -- La date sélectionnée dans le Slicer (ex: 31/12/2024)
			VAR DateDebut = EDATE(DateFin, -13) + 1   -- 12 mois glissants avant
			VAR TauxCOrientationPDP = [Taux d'orientations PDP]
			
			-- 2. Contexte du graphique (Point actuel de l'axe X)
			VAR DateSurAxe = MAX('Date principale'[Date])
			
			RETURN
			-- 3. Logique d'affichage
			IF(
			    -- Condition : On affiche seulement si le mois de l'axe est dans la fenêtre
			    DateSurAxe >= DateDebut && DateSurAxe <= DateFin,
			
			    -- Valeur : On appelle directement la mesure de base (celle qui somme la table Evolution)
			    -- Elle va naturellement se calculer pour le "DateSurAxe" (le mois en cours)
			    TauxCOrientationPDP,
			
			    -- Sinon rien
			    BLANK()
			)
		displayFolder: Suivi des indicateurs\MEE
		lineageTag: 56675024-8b44-4f2b-ab39-e6cd1d62260d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% adhérents bénéficiaire AMT DU à leur demande' =
			
			"% des adhérents ayant bénéficié d'une AMT DUERP à leur demande (info-DU, eval-DU ou sensi atelier-DU) du " & [Période (Du au)]
		displayFolder: Titres
		lineageTag: f383ed98-b548-434c-8a1f-ac1dece09434

	measure '% adhérents bénéficiaire AMT Conseil - Actions DU' =
			
			"% des adhérents ayant bénéficié d'une AMT 'Conseil - Actions DU' du " & [Période (Du au)]
		displayFolder: Titres
		lineageTag: ffb21790-591e-4f11-b4a9-d55028a90ecd

	measure '% Adhérents FE (Base)' =
			
			-- Ici, on met juste la formule de calcul, sans conditions IF
			[% adhérents à jour de FE (fin de période)]
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 1ce2df1c-6ead-4fb7-a7d1-c4431aca9c80

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'sous titre AMT terminées' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"AMT ayant atteint le statut terminé du "& DatePeriode
		displayFolder: Titres
		lineageTag: e4e6bf6c-b826-4d3b-bfd5-b551382dc6c6

	measure 'AMT évolution' =
			
			DIVIDE(
			    [AMT Période] - [AMT Période N-1],
			    [AMT Période N-1]
			)
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 961b65a8-9a81-4dfe-b035-78bc6d3c48ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT évolution (+/-)' =
			
			VAR Evolution = DIVIDE(
			    [AMT Période] - [AMT Période N-1],
			    [AMT Période N-1]
			)
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: c2ed006d-9718-4303-befe-6534c4443336

	measure 'AMT en cours ayant atteint le statut à valider' =
			
			CALCULATE(
			    [# AMT en cours],
			    'AMT - statut'[Statut détaillé] in {"AMT à valider", "AMT validée"},
			    REMOVEFILTERS('Date principale')
			)
		formatString: 0
		displayFolder: AMT
		lineageTag: 44fb594d-bdc0-4bd7-9e91-16492f1d6e03

	measure 'sous titre AMT en cours' =
			
			Var today = TODAY()-1
			
			RETURN
			"AMT en-cours en date du " & format(today, "DD-MM-YYYY", "FR-fr")
		displayFolder: Titres
		lineageTag: 77eb5c71-0a7e-4e90-a8ad-c410a851664a

	measure 'sous titre APP en cours' =
			
			Var today = TODAY()-1
			
			RETURN
			"APP en-cours en date du " & format(today, "DD-MM-YYYY", "FR-fr")
		displayFolder: Titres
		lineageTag: 0aa7e8c4-4665-4870-b59f-7cb0f9629ce9

	measure 'sous titre APP terminées' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"APP ayant atteint le statut terminé du "& DatePeriode
		displayFolder: Titres
		lineageTag: 7278cca4-1c82-4f4f-ad1e-aa7b0be53f88

	measure 'sous titre AMT DU terminées' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"AMT relatives au DU ('Sensi - Ateliers DU', 'Eval - DU', 'Info - DU' et 'Conseil - Actions DU - de 50 salariés' ayant atteint le statut terminé du "& DatePeriode
		displayFolder: Titres
		lineageTag: 35677f08-517a-41b6-861b-e7fdfb305f24

	measure 'sous titre AMT DU en cours' =
			
			Var today = TODAY()-1
			
			RETURN
			"AMT relatives DU en-cours en date du " & format(today, "DD-MM-YYYY", "FR-fr")
		displayFolder: Titres
		lineageTag: e759a47b-bb7c-468e-a5e2-88d395e40a66

	measure 'sous titre AMT sensi terminées' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"AMT dont le modèle commence par 'Sensi' ayant atteint le statut terminé du "& DatePeriode
		displayFolder: Titres
		lineageTag: 88fd1e00-d7c0-4ee2-b5c4-594fe62239fd

	measure 'sous titre AMT sensi en cours' =
			
			Var today = TODAY()-1
			
			RETURN
			"AMT dont le modèle commence par 'Sensi' en-cours en date du " & format(today, "DD-MM-YYYY", "FR-fr")
		displayFolder: Titres
		lineageTag: ff87de4e-1d0c-45a8-b822-df25c55bc367

	measure 'AMT en cours' =
			
			CALCULATE(
			    [# AMT en cours],
			    REMOVEFILTERS('Date principale')
			)
		formatString: #,0
		displayFolder: AMT
		lineageTag: 3dd579be-d643-406e-8b37-f9f56db9a954

	measure 'AMT FE' =
			
			CALCULATE(
			    [# AMT terminées],
			    'AMT - modèle'[Modèle (APP, FE, Autres)] = "FE"
			)
		formatString: #,0
		displayFolder: AMT
		lineageTag: 92d54743-3cb9-42c5-b246-6d8e1c43a64c

	measure 'AMT EP simplifiié' =
			
			CALCULATE(
			    [# AMT terminées],
			    'AMT - modèle'[Modèle] = "Etude - Etude de poste  individuelle simplifiée"
			)
		formatString: #,0
		displayFolder: AMT
		lineageTag: 41b33e21-7a4d-488f-ace3-448cf61b2e07

	measure 'AMT EP' =
			
			CALCULATE(
			    [# AMT terminées],
			    'AMT - modèle'[Modèle] in {"Etude - Etude de poste individuelle", "Etude - Etude de poste collective"}
			)
		formatString: 0
		displayFolder: AMT
		lineageTag: 61a24a3c-a53a-4f50-8f84-15a673294bc1

	measure '% AMT FE' =
			
			[AMT FE]/[# AMT terminées]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: AMT
		lineageTag: 94e3d21a-0f59-4dd9-b5a4-0bded3a1c9c5

	measure '% AMT EP simplifié' =
			
			[AMT EP simplifiié]/[# AMT terminées]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: AMT
		lineageTag: 692f85f3-f60f-454b-a680-fb5c9cae5cbc

	measure '% AMT EP' =
			
			[AMT EP]/[# AMT terminées]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: AMT
		lineageTag: fe8f2549-b071-4aa1-9abe-a1ce60eb43b0

	measure 'AMT info-sensi-conseil' =
			
			CALCULATE(
			    [# AMT terminées],
			    'AMT - informations principales'[Type] = "Information - Sensibilisation - Formation"
			    )
		formatString: #,0
		displayFolder: AMT
		lineageTag: e37ba7ff-ab40-4457-942f-38ae302b3719

	measure '% AMT info sensi conseil' =
			
			[AMT info-sensi-conseil]/[# AMT terminées]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: AMT
		lineageTag: b4dbb398-bc50-4011-b5cf-b456783272ea

	measure 'AMT métrologie' =
			
			CALCULATE(
			    [# AMT terminées],
			    'AMT - informations principales'[Type] = "Métrologie"
			    )
		formatString: 0
		displayFolder: AMT
		lineageTag: d9b0fe17-2114-458a-8527-f29dd21b6e27

	measure 'AMT Risque chimique' =
			
			CALCULATE(
			    [# AMT terminées],
			    'AMT - informations principales'[Type] = "Risque chimique"
			    )
		formatString: 0
		displayFolder: AMT
		lineageTag: 1a09240d-bbf2-419d-842d-9ccb732f0cd2

	measure '% AMT Risque chimique' =
			
			[AMT Risque chimique]/[# AMT terminées]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: AMT
		lineageTag: e701180b-5b25-4ff0-8a3b-55aeae6a6d47

	measure '% AMT métrologie' =
			
			[AMT métrologie]/[# AMT terminées]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: AMT
		lineageTag: 4134e748-0a94-45c8-ba13-95366b0f8084

	measure 'AMT autres' =
			
			[# AMT terminées]-[AMT EP]-[AMT EP simplifiié]-[AMT FE]-[AMT info-sensi-conseil]-[AMT métrologie]-[AMT Risque chimique]
		formatString: 0
		displayFolder: AMT
		lineageTag: 4f1333d2-7536-42f3-8add-ba12a6f9788a

	measure '% AMT autres' =
			
			[AMT autres]/[# AMT terminées]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: AMT
		lineageTag: 2c06ac26-18d6-4df6-ab9d-e97d3cde8369

	measure 'AMT Sensi' = ```
			
			CALCULATE(
			    [# AMT terminées], -- Appel de la mesure de base à contextualiser
			    KEEPFILTERS( -- Maintient les filtres existants sur la colonne au lieu de les écraser
			        LEFT( 'AMT - modèle'[Modèle], 5 ) = "Sensi" -- Vérifie si les 8 premiers caractères correspondent au préfixe
			    )
			)
			/* Description : 
			Cette mesure calcule le nombre d'AMT terminées uniquement pour les modèles dont le nom commence par "sensi - ".
			L'utilisation de KEEPFILTERS garantit que si l'utilisateur filtre sur un sous-ensemble de modèles, la mesure respecte cette sélection tout en appliquant la condition "sensi - ".
			*/
			```
		formatString: 0
		displayFolder: AMT
		lineageTag: 14b07974-22fb-4a60-91be-aa66b7aa25b2

	measure '% AMT DU' = ```
			
			 CALCULATE(
			[AMT DU]/[# AMT terminées],
			REMOVEFILTERS('AMT - modèle'[Modèle])
			 )
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: AMT
		lineageTag: e2076890-f596-4a9d-b565-874d7807476f

	measure '% AMT sensi' = ```
			
			 CALCULATE(
			[AMT Sensi]/[# AMT terminées],
			REMOVEFILTERS('AMT - modèle'[Modèle])
			 )
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: AMT
		lineageTag: 72ecb2e3-0795-4129-b1d3-f18ada06de80

	measure 'AMT DU' = ```
			
			 CALCULATE(
			[# AMT terminées], 
			'AMT - modèle'[Modèle] in {"Conseil - Actions DU - de 50 salariés", "Eval - DU", "Sensi - Ateliers DU", "info - DU"}
			 )
			```
		formatString: 0
		displayFolder: AMT
		lineageTag: 90ed811c-141c-4828-bd01-a4dabb2e679d

	measure 'AMT APP' =
			
			CALCULATE(
			    [# AMT terminées],
			    'AMT - informations principales'[AMT prévention primaire] = "AMT relevant de la prévention primaire"
			)
		formatString: #,0
		displayFolder: AMT
		lineageTag: 8503f6c3-8df1-4149-b2d1-91c1b8593dc0

	measure '% AMT APP' = ```
			
			 CALCULATE(
			[AMT APP]/[# AMT terminées],
			REMOVEFILTERS('AMT - informations principales'[AMT prévention primaire])
			 )
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: AMT
		lineageTag: 68387218-3ffb-4e44-8200-6e53f1fc166b

	measure 'Temps Format Horaire' =
			
			VAR TotalHeures = 'temps travail'[temps total créneaux (en heures)]
			VAR Heures = INT(TotalHeures) // Partie entière des heures, pouvant dépasser 24
			VAR Minutes = INT((TotalHeures - Heures) * 60) // Minutes restantes
			RETURN FORMAT(Heures, "0") & " h " & FORMAT(Minutes, "00")
		displayFolder: Divers
		lineageTag: dea19eff-d1c5-450e-acb4-ac3cb67744cd

	measure 'temps travail total en h' =
			
			COALESCE(
			    [Temps total créneaux (en heures)],
			    0)
		lineageTag: 836a7e23-a8ce-47c5-9331-99c2581ac817

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'sous titre FE terminées' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"AMT de type 'Fiche d'entreprise' ayant atteint le statut terminé du "& DatePeriode
		displayFolder: Titres
		lineageTag: db733a09-fe1d-48b2-9bf7-8a4a8f487eae

	measure 'Délai moyen en-cours > à valider AMT Période' = ```
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode = FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR Resultat = CALCULATE(
			        AVERAGE('AMT v2'[Délai AMT statut en cours -> à valider]), -- Calcul de la moyenne arithmétique sur la colonne des délais
			        FILTER(
			            'AMT v2', -- Itération sur la table de faits pour évaluer la condition ligne par ligne
			            [# AMT terminées] >= 1 && -- Filtre pour ne garder que les lignes où l'AMT est considérée comme terminée
			            NOT(ISBLANK('AMT v2'[Délai AMT statut en cours -> à valider])) -- Optimisation : exclusion explicite des valeurs vides pour alléger le calcul
			        )
			    )
			RETURN
			    CALCULATE(
					Resultat, 
					DatesPeriode
				)
			/* Description : 
			Cette mesure calcule la moyenne des délais (en jours ou heures selon la colonne source) 
			entre le statut 'en cours' et 'à valider'. 
			Le calcul ne prend en compte que les AMT qui remplissent la condition d'être terminées ([# AMT terminées] >= 1)
			et exclut les valeurs vides pour garantir la pertinence de la moyenne.
			*/
			```
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 79c8936d-ac39-4dc9-b7d2-57700db28d72

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Délai moyen à faire > terminée AMT Période' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode = FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR Resultat = 
			    CALCULATE(
			        AVERAGE('AMT v2'[Délai AMT statut à Faire -> Terminée]), -- Calcul de la moyenne arithmétique sur la colonne des délais
			        FILTER(
			            'AMT v2', -- Itération sur la table de faits pour évaluer la condition ligne par ligne
			            [# AMT terminées] >= 1 && -- Filtre pour ne garder que les lignes où l'AMT est considérée comme terminée
			            NOT(ISBLANK('AMT v2'[Délai AMT statut à Faire -> Terminée])) -- Optimisation : exclusion explicite des valeurs vides pour alléger le calcul
			        )
			    )
			RETURN
			    CALCULATE(
					Resultat, 
					DatesPeriode
				)
			/* Description : 
			Cette mesure calcule la moyenne des délais (en jours ou heures selon la colonne source) 
			entre le statut 'à faire' et 'terminée'. 
			Le calcul ne prend en compte que les AMT qui remplissent la condition d'être terminées ([# AMT terminées] >= 1)
			et exclut les valeurs vides pour garantir la pertinence de la moyenne.
			*/
			```
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 059f2f78-dfef-442f-8a2d-e94088e06354

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Délai moyen à validée > validée AMT Période' = ```
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode = FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR Resultat = 
			    CALCULATE(
			        AVERAGE('AMT v2'[Délai AMT statut à valider -> validée]), -- Calcul de la moyenne arithmétique sur la colonne des délais
			        FILTER(
			            'AMT v2', -- Itération sur la table de faits pour évaluer la condition ligne par ligne
			            [# AMT terminées] >= 1 && -- Filtre pour ne garder que les lignes où l'AMT est considérée comme terminée
			            NOT(ISBLANK('AMT v2'[Délai AMT statut à valider -> validée])) -- Optimisation : exclusion explicite des valeurs vides pour alléger le calcul
			        )
			    )
			RETURN
			    CALCULATE(
					Resultat, 
					DatesPeriode
				)
			/* Description : 
			Cette mesure calcule la moyenne des délais (en jours ou heures selon la colonne source) 
			entre le statut 'à valider' et 'validéé. 
			Le calcul ne prend en compte que les AMT qui remplissent la condition d'être terminées ([# AMT terminées] >= 1)
			et exclut les valeurs vides pour garantir la pertinence de la moyenne.
			*/
			```
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 52a14503-aa37-4542-8e53-fc38a14ac0e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Délai moyen à faire > terminée AMT N-1' = ```
			
			VAR DateFin_Arrete = [Date Fin Arrêté]
			-- Calcul explicite des bornes pour la période N-1 (Glissant - 1 an)
			-- On recule la date de fin de 12 mois pour obtenir la fin N-1
			VAR DateFin_N1 = EDATE(DateFin_Arrete, -12) 
			-- On recule la date de fin de 24 mois + 1 jour pour obtenir le début N-1 (période de 12 mois)
			VAR DateDebut_N1 = EDATE(DateFin_Arrete, -24) + 1 
			
			VAR Resultat = 
			    CALCULATE(
			        AVERAGE('AMT v2'[Délai AMT statut à Faire -> Terminée]), -- La moyenne ignore nativement les vides
			        
			        -- Optimisation : On applique le filtre de date directement dans le CALCULATE principal
			        -- Cela est plus performant que de passer une table filtrée via FILTER(ALL(...))
			        'Date principale'[Date] >= DateDebut_N1,
			        'Date principale'[Date] <= DateFin_N1,
			
			        -- Filtre conditionnel sur les AMT terminées
			        -- Attention : En DirectQuery, assurez-vous que cette condition est indispensable. 
			        -- Si la colonne [Délai...] n'existe que pour les AMT terminées, ce filtre pourrait même être retiré.
			        FILTER(
			            'AMT v2', 
			            [# AMT terminées] >= 1 
			        )
			    )
			
			RETURN
			    Resultat
			
			/* Description :
			Cette mesure calcule le délai moyen (en jours) entre le statut 'à faire' et 'terminée' 
			pour la période de 12 mois précédant l'année glissante actuelle (N-1).
			Elle se base sur la date de fin d'arrêté sélectionnée.
			Le calcul filtre dynamiquement la période temporelle et ne considère que les lignes 
			où l'AMT est validée comme terminée via la mesure [# AMT terminées].
			*/
			```
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 059f2f78-dfef-442f-8a2d-e94088e06454

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Délai moyen à validée > validée AMT N-1' =
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode = FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR DatesPeriodeN1 = DATEADD(DatesPeriode, -1, YEAR)
			VAR Resultat =
			    CALCULATE(
			        AVERAGE('AMT v2'[Délai AMT statut à valider -> validée]), -- Calcul de la moyenne arithmétique sur la colonne des délais
			        FILTER(
			            'AMT v2', -- Itération sur la table de faits pour évaluer la condition ligne par ligne
			            [# AMT terminées] >= 1 && -- Filtre pour ne garder que les lignes où l'AMT est considérée comme terminée
			            NOT(ISBLANK('AMT v2'[Délai AMT statut à valider -> validée])) -- Optimisation : exclusion explicite des valeurs vides pour alléger le calcul
			        )
			    )
			RETURN
			    CALCULATE(
					Resultat,
					DatesPeriodeN1
				)
			/* Description :
			Cette mesure calcule la moyenne des délais de l'année N-1
			entre le statut à valider et validée'.
			Le calcul ne prend en compte que les AMT qui remplissent la condition d'être terminées ([# AMT terminées] >= 1)
			et exclut les valeurs vides pour garantir la pertinence de la moyenne.
			*/
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 52a14503-aa37-4532-8e53-fc38a14ac0e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Délai moyen en-cours > à valider AMT N-1' =
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode = FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR DatesPeriodeN1 = DATEADD(DatesPeriode, -1, YEAR)
			VAR Resultat =
			    CALCULATE(
			        AVERAGE('AMT v2'[Délai AMT statut en cours -> à valider]), -- Calcul de la moyenne arithmétique sur la colonne des délais
			        FILTER(
			            'AMT v2', -- Itération sur la table de faits pour évaluer la condition ligne par ligne
			            [# AMT terminées] >= 1 && -- Filtre pour ne garder que les lignes où l'AMT est considérée comme terminée
			            NOT(ISBLANK('AMT v2'[Délai AMT statut en cours -> à valider])) -- Optimisation : exclusion explicite des valeurs vides pour alléger le calcul
			        )
			    )
			RETURN
			    CALCULATE(
					Resultat,
					DatesPeriodeN1
				)
			/* Description :
			Cette mesure calcule la moyenne des délais de l'année N-1
			entre le statut à valider et validée'.
			Le calcul ne prend en compte que les AMT qui remplissent la condition d'être terminées ([# AMT terminées] >= 1)
			et exclut les valeurs vides pour garantir la pertinence de la moyenne.
			*/
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 79c8936d-ac39-4dc9-b8d2-57700db28d72

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Délai AMT en cours > à valider évolution' =
			
			DIVIDE(
			    [Délai moyen en-cours > à valider AMT Période] - [Délai moyen en-cours > à valider AMT N-1],
			    [Délai moyen en-cours > à valider AMT N-1]
			)
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: e77317b2-9f20-41f6-93b2-a60abbd07ff8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Délai AMT à valider > validée évolution' =
			
			DIVIDE(
			    [Délai moyen à validée > validée AMT Période] - [Délai moyen à validée > validée AMT N-1],
			    [Délai moyen à validée > validée AMT N-1]
			)
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: ab6d583e-3404-4f1b-a2fd-b19da32ac3e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Délai AMT à faire > terminée évolution' =
			
			DIVIDE(
			    [Délai moyen à faire > terminée AMT Période] - [Délai moyen à faire > terminée AMT N-1],
			    [Délai moyen à faire > terminée AMT N-1]
			)
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 6343dca0-857a-4bc9-b4a7-3c2175859fba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Délai AMT à faire > terminée évolution (+/-)' =
			
			VAR Evolution = [Délai AMT à faire > terminée évolution]
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: cb555349-7ae4-489e-bf2a-8ccec65fac71

	measure 'Délai AMT à valider > validée évolution (+/-)' =
			
			VAR Evolution = [Délai AMT à valider > validée évolution]
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: a622a595-b6ef-4329-8a7d-4eaf12bc6952

	measure 'Délai AMT en cours > à valider évolution (+/-)' =
			
			VAR Evolution = [Délai AMT en cours > à valider évolution]
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 4b89eee5-a662-4ee2-9dd0-a80dda188879

	measure 'AMT N-1' =
			
			CALCULATE(
			    [# AMT terminées],
			    DATEADD( 'Date principale'[Date], -1, YEAR ) -- Déplace la période visible de 2 ans en arrière
			)
			/* Description :
			Cette mesure calcule le résultat pour la même période que celle sélectionnée, mais deux ans plus tôt.
			Elle utilise DATEADD qui est plus flexible que SAMEPERIODLASTYEAR.
			Nécessite une table de dates marquée et continue.
			*/
		formatString: #,0
		displayFolder: AMT
		lineageTag: 70b62caf-a0bc-44b3-b35d-9898fc0087a1

	measure 'Max Y AMT' =
			
			MAXX(
			    ALLSELECTED('Date principale'[NomMoisAnnee]),
			    [# AMT réalisées]
			    )
			    * 1.5
		displayFolder: AMT
		lineageTag: 8eabe72c-1b1b-46d1-90e9-f42c4970a8a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'APP N-1' =
			
			CALCULATE(
			    [# AMT terminées],
			    'AMT - informations principales'[AMT prévention primaire] = "AMT relevant de la prévention primaire",
			    DATEADD( 'Date principale'[Date], -1, YEAR ) -- Déplace la période visible de 2 ans en arrière
			)
			/* Description :
			Cette mesure calcule le résultat pour la même période que celle sélectionnée, mais deux ans plus tôt.
			Elle utilise DATEADD qui est plus flexible que SAMEPERIODLASTYEAR.
			Nécessite une table de dates marquée et continue.
			*/
		formatString: 0
		displayFolder: AMT
		lineageTag: 5f2e1dcb-e9fa-4713-b7a0-6d4622c8848e

	measure 'Max Y APP' =
			
			MAXX(
			    ALLSELECTED('Date principale'[NomMoisAnnee]),
			    CALCULATE(
			        [# AMT réalisées],
			        'AMT - informations principales'[AMT prévention primaire] = "AMT relevant de la prévention primaire"
			    )
			)
			    * 0.8
		displayFolder: AMT
		lineageTag: 3151032f-ee9e-446d-8a1b-1b8f2ef588d2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Max Y FE' =
			
			MAXX(
			    ALLSELECTED('Date principale'[NomMoisAnnee]),
			    CALCULATE(
			        [# AMT réalisées],
			        'AMT - informations principales'[Type] = "Fiche d'entreprise"
			    )
			)
			    * 0.8
		displayFolder: AMT
		lineageTag: f05f5033-6edb-4d86-ab9a-afe396d528ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Max Y AMT Sensi' =
			
			MAXX(
			    ALLSELECTED('Date principale'[NomMoisAnnee]),
			    CALCULATE(
			    [# AMT terminées], -- Appel de la mesure de base à contextualiser
			    KEEPFILTERS( -- Maintient les filtres existants sur la colonne au lieu de les écraser
			        LEFT( 'AMT - modèle'[Modèle], 5 ) = "Sensi" -- Vérifie si les 8 premiers caractères correspondent au préfixe
			    )
			) * 1.2)
		formatString: 0
		displayFolder: AMT
		lineageTag: c135b8cc-ac6b-4df5-aec6-a60d32858b06

	measure 'Max Y AMT DU' =
			
			MAXX(
			    ALLSELECTED('Date principale'[NomMoisAnnee]),
			    CALCULATE(
			        [# AMT terminées],
			         'AMT - modèle'[Modèle] in {"Conseil - Actions DU - de 50 salariés", "Eval - DU", "Sensi - Ateliers DU", "info - DU"}
			 )
			) * 1.2
		displayFolder: AMT
		lineageTag: 9ea12997-e923-43ef-9868-d8ead8ebbef8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT 2024' = 7089
		formatString: #,0
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 768054b1-1ea0-4328-b75f-c3475d85fec1

	measure 'APP 2024' = 2485
		formatString: #,0
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: ffe6ac0d-f1a1-4795-a3fc-9009cde7f4d9

	measure 'FE 2024' = 2497
		formatString: #,0
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 7b749c8a-5c3f-4796-a6f3-7a85b907d1ee

	measure 'APP évolution (+/-)' =
			
			VAR Evolution = DIVIDE(
			    [AMT Période] - [APP 2024], // [AMT Période N-1],
			    [APP 2024] // [AMT Période N-1]
			)
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 856468e1-9ba8-4921-bc95-e185dcdecd13

	measure 'APP évolution' =
			
			DIVIDE(
			    [AMT Période] - [APP 2024],//[AMT Période N-1],
			    [APP 2024] //[AMT Période N-1]
			)
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: abd7c41f-42d8-43f8-936c-d235d6b2a9c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FE évolution' =
			
			DIVIDE(
			    [AMT Période] - [FE 2024],//[AMT Période N-1],
			    [FE 2024] //[AMT Période N-1]
			)
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 1e5a1568-e875-4016-86ca-1b7b5c491e7a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FE évolution (+/-)' =
			
			VAR Evolution = DIVIDE(
			    [AMT Période] - [FE 2024], // [AMT Période N-1],
			    [FE 2024] // [AMT Période N-1]
			)
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\FE
		lineageTag: f8fc1e6a-c429-4fd7-b68c-d2f94b432fdd

	measure '% Adhérents à jour de FE N-1' = ```
			
			-- 1. On récupère la date actuelle (Fin de période sélectionnée)
			VAR DateActuelle = [Date Fin Arrêté]
			
			-- 2. On calcule la date de référence pour l'année précédente (Le "Aujourd'hui" de l'an dernier)
			VAR DateNMoins1 = EDATE(DateActuelle, -12)
			
			-- 3. On définit la limite d'ancienneté pour cette époque-là 
			-- (Pour être "nouveau" en N-1, il faut être arrivé après N-2)
			VAR DateLimiteAncienneteNMoins1 = EDATE(DateNMoins1, -12)
			
			RETURN
			CALCULATE(
			    -- Mesure de base
			    [% adhérents à jour de FE (fin de période)],
			
			    -- Filtre 2 : On remonte le temps sur la date principale
			    'Date principale'[Date] <= DateNMoins1
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\FE
		lineageTag: b1100a63-caf4-48d2-9062-6c195d0d700c

	measure 'AMT évolution 2024>2025 (+/-)' =
			
			VAR Evolution = DIVIDE(
			    [AMT Période] - [AMT 2024], // [AMT Période N-1],
			    [AMT 2024] // [AMT Période N-1]
			)
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 8eb75c90-0642-4a05-bedd-c6dba6402ad1

	measure '% réalisation mise à jour de FE' =
			
			DIVIDE(
			    CALCULATE(
			        [# AMT terminées],
			        'AMT - modèle'[Modèle] = "Fiche entreprise - mise à jour"
			    ),
			    [Adhérents avec FE à mettre à jour N-1],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 37576713-84d9-42bb-ab6f-36ea9f71d814

	measure 'APP à mettre à jour dans les 12 mois' = ```
			
			-- 1. On identifie la date de fin de la période sélectionnée (ex: 31/12/2025)
			VAR DateReference = MAX('Date principale'[Date])
			
			-- 2. On définit la date butoir (Date Ref + 1 an)
			VAR DateButoir = DateReference + 365
			
			RETURN
			CALCULATE(
			    'Evolution effectif'[# adhérents à jour d'AMT primaire (fin de période)],
			    
			    -- Critère : La date prochaine doit être APRÈS la date de référence ET AVANT la date butoir
			    'Evolution effectif - date prochaine APP'[Date] > DateReference &&
			    'Evolution effectif - date prochaine APP'[Date] <= DateButoir
			)
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 4b71634c-807f-4bb6-b404-67265811bb53

	measure 'FE à mettre à jour dans les 12 mois' = ```
			
			-- 1. On identifie la date de fin de la période sélectionnée (ex: 31/12/2025)
			VAR DateReference = MAX('Date principale'[Date])
			
			-- 2. On définit la date butoir (Date Ref + 1 an)
			VAR DateButoir = DateReference + 365
			
			RETURN
			CALCULATE(
			    'Evolution effectif'[# adhérents à jour de FE (fin de période)],
			    
			    -- Critère : La date prochaine doit être APRÈS la date de référence ET AVANT la date butoir
			    'Evolution effectif - date prochaine FE'[Date] > DateReference &&
			    'Evolution effectif - date prochaine FE'[Date] <= DateButoir
			)
			```
		formatString: #,0
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 1e517c0d-2920-4401-9204-eb93eb3ed6b0

	measure 'Inaptitudes Période' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			Return
			CALCULATE(
			    [Nombre de documents émis], 
			    'Documents émis - type document'[Type document] = "Avis d'inaptitude", 
			    DatesPeriode)
			```
		formatString: #,0
		displayFolder: Suivi des indicateurs\inaptitude
		lineageTag: 7d77431e-4a87-44c5-b2c3-012c3d41ba85

	measure 'Inaptitudes Période N-1' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode =
			    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR DatesPeriodeN1 =
			    DATEADD(DatesPeriode, -1, YEAR)
			RETURN
			CALCULATE( 
			    [Nombre de documents émis], 
			    'Documents émis - type document'[Type document] = "Avis d'inaptitude",
			    DatesPeriodeN1 )
			
			```
		formatString: 0
		displayFolder: Suivi des indicateurs\inaptitude
		lineageTag: 0afd3a51-9412-419a-a46f-d031d857cb45

	measure 'Inaptitude évolution' =
			
			DIVIDE(
			    [Inaptitudes Période] - [Inaptitudes Période N-1],
			    [Inaptitudes Période N-1]
			)
		displayFolder: Suivi des indicateurs\inaptitude
		lineageTag: d4a6f4c2-4ac5-49eb-929c-cfb2af5e1a0a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Inaptitude évolution (+/-)' =
			
			VAR Evolution = [Inaptitude évolution]
			
			RETURN
			-- Syntaxe de format : "Format pour Positif ; Format pour Négatif ; Format pour Zéro"
			FORMAT(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\inaptitude
		lineageTag: bd5f5dd3-3aa0-4303-adad-61e714205b31

	measure 'Sous titre inaptitude' =
			
			Var DatePeriode = [Période (Du au)]
			RETURN
			"Nombre de documents émis de type 'avis d'inaptitude' du "& DatePeriode
		displayFolder: Titres
		lineageTag: a884621f-7577-49ea-8754-2a57f8eb307e

	measure '% adhérents avec FE à mettre à jour ou à créer' = ```
			
			1-[% adhérents à jour de FE]
			
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\FE
		lineageTag: 2b3bd769-b507-4b13-81aa-aaa9e7c2c39f

	measure 'Délai moyen A faire > En cours AMT Période' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode = FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR Resultat = 
			    CALCULATE(
			        AVERAGE('AMT v2'[Délai AMT statut à Faire -> En-cours]), -- Adaptez le nom de la colonne
			        FILTER(
			            'AMT v2', 
			            [# AMT terminées] >= 1 && 
			            NOT(ISBLANK('AMT v2'[Délai AMT statut à Faire -> En-cours])) 
			        )
			    )
			RETURN
			    CALCULATE(
			        Resultat, 
			        DatesPeriode
			    )
			```
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: d95eefb5-b628-4262-bfdf-1f9386fd16c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Délai moyen validée > terminée AMT Période' = ```
			
			VAR dMax = [Date Fin Arrêté]
			VAR dMin = EDATE([Date Fin Arrêté],-12)+1
			VAR DatesPeriode = FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
			VAR Resultat = 
			    CALCULATE(
			        AVERAGE('AMT v2'[Délai AMT statut Validée -> Terminée]), -- Adaptez le nom de la colonne
			        FILTER(
			            'AMT v2', 
			            [# AMT terminées] >= 1 && 
			            NOT(ISBLANK('AMT v2'[Délai AMT statut Validée -> Terminée])) 
			        )
			    )
			RETURN
			    CALCULATE(
			        Resultat, 
			        DatesPeriode
			    )
			```
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 27ffcd01-656e-4422-b20e-62bba2336edc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Adhérents ayant transmis leur DU' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			DIVIDE(
			    CALCULATE(
			    [Adhérents actifs ou suspendus],
			    'Adhérent (actuel)'[DU transmis] = "DU transmis par l'adhérent",
			    'Date principale'[Date] <= DateSnapshot
			    ),
			    [Adhérents actifs ou suspendus],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 197ced19-38cc-4dae-81eb-ad3bb6a6b0d9

	measure '% Adhérents DU non transmis' =
			
			VAR DateSnapshot = [Date Fin Arrêté]
			
			RETURN
			DIVIDE(
			    CALCULATE(
			    [Adhérents actifs ou suspendus],
			    'Adhérent (actuel)'[DU transmis] = "DU non transmis",
			    'Date principale'[Date] <= DateSnapshot
			    ),
			    [Adhérents actifs ou suspendus],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 0b746cad-03e5-48c3-a289-d50b495b55a0

	measure '% Adhérents DU non transmis N-1' =
			
			DIVIDE(
			    CALCULATE(
			    [Adhérents actifs ou suspendus N-1],
			    'Adhérent (actuel)'[DU transmis] = "DU non transmis"
			    ),
			    [Adhérents actifs ou suspendus N-1],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 9b60d56c-0677-49a4-949e-7bb00c81b4e9

	measure '% adhérents DU non transmis évolution (variation %)' =
			
			([% Adhérents DU non transmis] - [% Adhérents DU non transmis N-1])/[% Adhérents DU non transmis N-1]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 6b241128-add6-4175-8cb6-8976c571b54a

	measure '% Adhérents DU non transmis évolution (+/-)' =
			
			Var Evolution = [% adhérents DU non transmis évolution (variation %)]
			
			RETURN
			format(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: c1d144da-3742-4531-bbcd-550abbd7f06c

	measure '% Adhérents ayant transmis leur DU évolution (+/-)' =
			
			Var Evolution = [% adhérents ayant transmis leur DU évolution (variation %)]
			
			RETURN
			format(Evolution, "+ 0.0%;- 0.0%;0%")
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: c1d144da-3742-4531-bbcd-550abbd7f06x

	measure '% adhérents ayant transmis leur DU évolution (variation %)' =
			
			([% Adhérents ayant transmis leur DU] - [% Adhérents ayant transmis leur DU N-1])/[% Adhérents ayant transmis leur DU N-1]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 6b241128-add6-4175-8cb6-8976c571b54x

	measure '% Adhérents ayant transmis leur DU N-1' =
			
			DIVIDE(
			    CALCULATE(
			    [Adhérents actifs ou suspendus N-1],
			    'Adhérent (actuel)'[DU transmis] = "DU transmis par l'adhérent"
			    ),
			    [Adhérents actifs ou suspendus N-1],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Suivi des indicateurs\AMT
		lineageTag: 9b60d56c-0677-49a4-949e-7bb00c81b4x9

	partition Mesures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Colonne 1" = _t]),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"Colonne 1", type text}}),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Type modifié",{"Colonne 1"})
				in
				    #"Colonnes supprimées"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

