createOrReplace

	ref table Mesures

		measure '# adhérents (respecte secteur)' = ```
				
				CALCULATE(
				    DISTINCTCOUNT('CRM - tickets'[id_entreprise]),
				    FILTER(
				        ALLSELECTED('CRM - tickets'), 
				        [Tickets en-cours] > 0
				    ),
				    KEEPFILTERS(VALUES('CRM - tickets'[id_secteur]))
				)
				
				```
			formatString: 0
			displayFolder: Tickets
			lineageTag: 65f8b280-04e9-454d-981a-1416b50b2823

			changedProperty = DisplayFolder

			changedProperty = Name

		measure '# adhérents avec FE à mettre à jour (fin de période)' = EXTERNALMEASURE("# adhérents avec FE à mettre à jour (fin de période)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: FE
			lineageTag: c1810a7c-ff33-4c6f-acf1-fc17f5d719d2
			sourceLineageTag: fbd84859-ca72-4e9b-876f-ca968b57ed33
			dataCategory: Uncategorized

		measure '# adhérents avec un ticket depuis début de l''année' = ```
				
				VAR CetteAnnee = YEAR(TODAY())
				VAR T =
				    FILTER(
				        ALL('CRM - tickets'[id_entreprise]),          -- ne retire pas le filtre secteur
				        [# tickets] > 0
				    )
				RETURN
				CALCULATE(
				    DISTINCTCOUNT('CRM - tickets'[id_entreprise]),
				    T,                                                -- condition “au moins 1 ticket”
				    KEEPFILTERS('CRM - activité - date'[Année activité] = CetteAnnee),  -- ajoute sans écraser
				    REMOVEFILTERS('Utilisateur'),                     -- remplace ALL(...) de façon ciblée
				    REMOVEFILTERS('Date principale')                  -- idem, si nécessaire
				)
				
				```
			formatString: #,0
			displayFolder: Tickets
			lineageTag: 4f411e69-3397-4a54-b8e1-e302b414d760

			changedProperty = Name

			changedProperty = FormatString

			changedProperty = DisplayFolder

		measure '# adhérents avec un ticket ouvert' = ```
				
				
				CALCULATE(
				    DISTINCTCOUNT('CRM - tickets'[id_entreprise]),
				    FILTER(
				        ALLSELECTED('CRM - tickets'), 
				        [Tickets en-cours] > 0
				    ),
				    KEEPFILTERS(VALUES('CRM - tickets'[id_secteur]))
				)
				
				```
			formatString: 0
			displayFolder: Tickets
			lineageTag: 2950f5fd-b6e8-4b2d-8cc8-07a82f00be99

			changedProperty = Name

			changedProperty = DisplayFolder

		measure '# adhérents fin validité FE dans les 6 mois' = EXTERNALMEASURE("# adhérents fin validité FE dans les 6 mois", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: FE
			lineageTag: ed10606e-3b26-4067-8a68-d13f748c4497
			sourceLineageTag: a3c4006e-d9e6-4b3b-91b2-6b94a32208b7
			dataCategory: Uncategorized

		measure '# adhérents sans FE (fin de période)' = EXTERNALMEASURE("# adhérents sans FE (fin de période)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: FE
			lineageTag: 9fa80557-9e76-4647-ae04-94f34f52b5a8
			sourceLineageTag: 37dc6bc7-757d-41d6-9df0-3a6047b88b4b
			dataCategory: Uncategorized

		measure '# adhérents sans FE moins de 1 an' = ```
				
				VAR DateSeuil = EDATE(TODAY(), -12) 
				
				// 1. On récupère la liste des IDs des adhérents récents dans la table 'Adhérent (actuel)'
				VAR AdherentsRecents = 
				    CALCULATETABLE(
				        VALUES('Adhérent (actuel)'[id_entreprise]), // Vérifie bien le nom exact de la colonne ID ici
				        'Adhérent (actuel)'[Date premier statut actif] >= DateSeuil
				    )
				
				RETURN
				// 2. On injecte cette liste dans le calcul de la mesure sans FE
				CALCULATE(
				    [# adhérents sans FE (fin de période)],
				    // On applique le filtre sur la table cible (probablement 'Evolution effectif' ou 'Adhérents')
				    TREATAS(AdherentsRecents, 'Evolution effectif'[id_entreprise]) 
				)
				```
			formatString: 0
			displayFolder: FE
			lineageTag: 63864a86-9079-4346-affc-658b3b325e90

			changedProperty = DisplayFolder

			changedProperty = Name

		measure '# Demandes de RDV adhérent no coalesce' = EXTERNALMEASURE("# Demandes de RDV adhérent no coalesce", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Demandes de RDV
			lineageTag: 346e47d3-8024-46b3-b76b-210f8126833c
			sourceLineageTag: 9689762d-dcd2-4b3e-a0ca-a8a8ab8bc209
			dataCategory: Uncategorized

		measure '# ticket depuis début de l''année' =
				
				var cetteAnnee = YEAR(TODAY())
				
				Return
				
				CALCULATE(
				    [# tickets],
				    'CRM - activité - date'[Année activité] = cetteAnnee
				)
			formatString: #,0
			displayFolder: Tickets
			lineageTag: 58bec3e4-3f5d-4eca-9907-d9267eb3bbf1

			changedProperty = Name

			changedProperty = FormatString

			changedProperty = DisplayFolder

		measure '% adhérents à jour de APP (Table date secondaire)' =
				
				CALCULATE(
				    [% adhérents à jour d'AMT primaire (fin de période)],
				    TREATAS(
				        VALUES('Dates_Futur'[Date]),
				        'Date principale'[Date]
				    )
				)
			displayFolder: AMT\Simulation
			lineageTag: 084699d3-9d40-4917-a3cf-accf7b6a2794

			changedProperty = DisplayFolder

			changedProperty = Name

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		measure '% adhérents à jour de FE (Table date secondaire)' =
				
				CALCULATE(
				    [% adhérents à jour de FE (fin de période)],
				    TREATAS(
				        VALUES('Dates_Futur'[Date]),
				        'Date principale'[Date]
				    )
				)
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: FE\Simulation
			lineageTag: 3f56d081-4b6a-4a42-88ca-7ff3b1f8adec

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure '% adhérents avec FE à jour (fin de période)' = EXTERNALMEASURE("% adhérents avec FE à jour (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0\ %;-0\ %;0\ %
			displayFolder: FE
			lineageTag: adce47d0-5128-478f-9d08-88e0f36ca39e
			sourceLineageTag: 0bd20b4b-d74d-499c-b09c-7160c95ce350
			dataCategory: Uncategorized

		measure '% adhérents avec FE à mettre à jour (fin de période)' = EXTERNALMEASURE("% adhérents avec FE à mettre à jour (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0\ %;-0\ %;0\ %
			displayFolder: FE
			lineageTag: 022f1ddd-2296-4ce5-867a-8ccacfae4be4
			sourceLineageTag: 198ea384-548f-42d3-bebd-26be4d8bd86e
			dataCategory: Uncategorized

		measure '% adhérents avec ticket depuis début de l''année' =
				
				CALCULATE(
				    DIVIDE(
				    [# adhérents avec un ticket depuis début de l'année],
				    [Nombre d'adhérents actifs ou suspendus],
				    0
				    ),
				    ALL('Utilisateur')
				)
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Tickets
			lineageTag: 24b8594b-d7ca-4f46-be1e-38523ce17705

			changedProperty = Name

			changedProperty = FormatString

			changedProperty = DisplayFolder

		measure '% adhérents avec un ticket ouvert' =
				
				CALCULATE(
				    DIVIDE(
				    [# adhérents avec un ticket ouvert],
				    [Nombre d'adhérents actifs ou suspendus],
				    0
				    ),
				    ALL('Utilisateur')
				)
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Tickets
			lineageTag: 3dcdd0a5-1dea-4fdd-9b82-381a7f507add

			changedProperty = Name

			changedProperty = FormatString

			changedProperty = DisplayFolder

		measure '% adhérents sans FE (fin de période)' = EXTERNALMEASURE("% adhérents sans FE (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0\ %;-0\ %;0\ %
			displayFolder: FE
			lineageTag: dc8b4283-4a2e-43f3-bb54-ae74a368cdd5
			sourceLineageTag: b868194a-928c-4c36-9fc4-0f50d81106d0
			dataCategory: Uncategorized

		measure '% AMT Terminées par Type' = EXTERNALMEASURE("% AMT Terminées par Type", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0\ %;-0.0\ %;0.0\ %
			displayFolder: AMT
			lineageTag: 55102c50-5911-4896-a38e-25e75613033f
			sourceLineageTag: 539058dd-910b-4f2e-b80d-eb4ad4db1ecb
			dataCategory: Uncategorized

		measure '% AMT terminées par type / modèle' = EXTERNALMEASURE("% AMT terminées par type / modèle", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: AMT
			lineageTag: ce657cd7-55b9-44ef-a4c3-1deaff4abbe5
			sourceLineageTag: 984115ca-bca6-45d0-92f9-dad9a1429826
			dataCategory: Uncategorized

		measure '% Annulation par le Service' = EXTERNALMEASURE("% Annulation par le Service", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Annulation
			lineageTag: 9820c735-a2fc-4446-9404-5ed7c91440c1
			sourceLineageTag: 07e9df00-395c-43d9-8d1a-47f1314cbf75
			dataCategory: Uncategorized

		measure '% Annulation pour Absence Professionnel de Santé' = EXTERNALMEASURE("% Annulation pour Absence Professionnel de Santé", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Annulation
			lineageTag: bc52c690-fe73-4619-8520-d44513a5abcd
			sourceLineageTag: 1e8eb4d4-2f4b-43f6-ad1f-94df5cc31221
			dataCategory: Uncategorized

		measure '% Annulation pour Contraintes de Service' = EXTERNALMEASURE("% Annulation pour Contraintes de Service", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Annulation
			lineageTag: 7e8ed8ab-7060-4c6d-b039-66c04a1945fd
			sourceLineageTag: 2203209f-c9ed-4ebe-8eb4-01d423521c08
			dataCategory: Uncategorized

		measure '% demandes de visites déclinées' = EXTERNALMEASURE("% demandes de visites déclinées", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Demandes de RDV
			lineageTag: eb06d57e-a030-4c0f-952c-7581aef562b4
			sourceLineageTag: b8b52793-fa1d-4c9a-b43a-ad007eac1bd4
			dataCategory: Uncategorized

		measure '% effectif avec INS qualifié' =
				
				DIVIDE(
				    [Effectif avec INS qualifié],
				    'Evolution retard'[Nombre de salariés suivis],
				    0
				)
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Effectif
			lineageTag: 1d3b161a-2b8d-431c-a69b-99f58b168fff

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure '% Entreprises Concernées par AMT' = EXTERNALMEASURE("% Entreprises Concernées par AMT", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: AMT
			lineageTag: 6307dfd8-c426-4a52-bcbb-f281efa9d800
			sourceLineageTag: 10f001e8-a092-4ca9-8792-7cafd723b3e3
			dataCategory: Uncategorized

		measure '% heures non exploitées' = EXTERNALMEASURE("% heures non exploitées", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Temps de travail
			lineageTag: 3538c91b-d1c1-41c4-b3bd-57a02e3f94bc
			sourceLineageTag: 94e3f90e-d868-4aba-998e-b1e2ada80fe4
			dataCategory: Uncategorized

		measure '% inaptitude / Nbre salariés suivis' = EXTERNALMEASURE("% inaptitude / Nbre salariés suivis", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Visites
			lineageTag: e3e28633-9a78-4dc5-a3c7-a2e2647112a6
			sourceLineageTag: a0fe7f99-b052-457f-a20a-a33beb2b8cf7
			dataCategory: Uncategorized

		measure '% inaptitude / Nbre visites réalisées' = EXTERNALMEASURE("% inaptitude / Nbre visites réalisées", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Visites
			lineageTag: a9df95e4-fef9-4245-be1d-5426fd90dd47
			sourceLineageTag: 4b9f1289-94ab-4a04-967b-eb6dbf0cafd3
			dataCategory: Uncategorized

		measure '% mesure Audiométrie par rapport à total examens complémentaires' = EXTERNALMEASURE("% mesure Audiométrie par rapport à total examens complémentaires", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: IDEST\Examens complémentaires
			lineageTag: fa14008a-4f12-4d89-82f6-93959f747f7c
			sourceLineageTag: 7b0eb622-7c45-41e0-bef0-0ea90286859c
			dataCategory: Uncategorized

		measure '% mesure IMC par rapport à total examens complémentaires' = EXTERNALMEASURE("% mesure IMC par rapport à total examens complémentaires", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: IDEST\Examens complémentaires
			lineageTag: a3d09d11-3085-45fe-92c4-09123f1bc723
			sourceLineageTag: d369e781-749e-4325-9c9b-dc981bdd5090
			dataCategory: Uncategorized

		measure '% mesure Spirométrie par rapport à total examens complémentaires' = EXTERNALMEASURE("% mesure Spirométrie par rapport à total examens complémentaires", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: IDEST\Examens complémentaires
			lineageTag: b9cc6090-78c4-4201-9a8b-ad1389b96964
			sourceLineageTag: b1e0f36c-d640-48c7-b0ff-26054a2f9fd8
			dataCategory: Uncategorized

		measure '% mesure tension par rapport à total examens complémentaires' = EXTERNALMEASURE("% mesure tension par rapport à total examens complémentaires", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: IDEST\Examens complémentaires
			lineageTag: 098747d6-48b7-4877-8646-95869b4787ff
			sourceLineageTag: 88e9dd9a-755d-40b5-8f93-a308e32aa951
			dataCategory: Uncategorized

		measure '% mesure Visiotest par rapport à total examens complémentaires' = EXTERNALMEASURE("% mesure Visiotest par rapport à total examens complémentaires", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: IDEST\Examens complémentaires
			lineageTag: d79af790-f6d8-4ef2-8d93-0bb82ccfd344
			sourceLineageTag: cf34ee69-3f7d-4517-8502-41736b9fe130
			dataCategory: Uncategorized

		measure '% nouveaux adhérents sans FE' =
				
				var Aujourdhui = Max('Date principale'[Date])
				var NouveauxAdherents = CALCULATE(
				                            DISTINCTCOUNT('Adhérent (actuel)'[Matricule entreprise]),
				                            'Adhérent (actuel)'[Date création dossier entreprise] - Aujourdhui < 365
				)
				var NouveauxSansFE = CALCULATE(
				                            NouveauxAdherents,
				                            'Adhérent (actuel)'[Statut FE] = "Aucune FE renseignée"
				)
				
				RETURN
				divide(
				    NouveauxSansFE,
				    NouveauxAdherents,
				    0
				)
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: FE
			lineageTag: 579d601f-c3d4-49e6-adca-f9db26c2916d

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure '% variation convocables depuis début année' = EXTERNALMEASURE("% variation convocables depuis début année", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Retard
			lineageTag: 28a31952-a638-452b-bce4-f9ac1a5d9e8d
			sourceLineageTag: afae6042-dc66-4770-9304-09aeca66fe41
			dataCategory: Uncategorized

		measure '% Variation Retard S-2 à S-1' = EXTERNALMEASURE("% Variation Retard S-2 à S-1", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Retard
			lineageTag: abd8b9c1-41d7-499b-91bc-35c78d746d89
			sourceLineageTag: df522006-6ff0-42bc-a173-6981681b0962
			dataCategory: Uncategorized

		measure '% Variation Retard S-3 à S-2' = EXTERNALMEASURE("% Variation Retard S-3 à S-2", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Retard
			lineageTag: 280388dc-c301-4a6d-8a5d-e4ba44c62f29
			sourceLineageTag: 20d7ce92-467e-4670-9dab-41062593c472
			dataCategory: Uncategorized

		measure '% Variation Tx de service S-2 à S-1' = EXTERNALMEASURE("% Variation Tx de service S-2 à S-1", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Retard
			lineageTag: 54929c7a-6557-428e-b5c4-64c1ae714d3c
			sourceLineageTag: 5b538f3a-dbbe-49bc-b59f-2034a7a9f46c
			dataCategory: Uncategorized

		measure '% Variation Tx de service S-3 à S-2' = EXTERNALMEASURE("% Variation Tx de service S-3 à S-2", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Retard
			lineageTag: b6c46cb8-8d60-4378-80dc-bab7c332253f
			sourceLineageTag: d85c2eaf-5d39-40c4-b3d2-5b14fc193b87
			dataCategory: Uncategorized

		measure 'Absenteisme 12 derniers mois' = EXTERNALMEASURE("Absenteisme 12 derniers mois", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Absentéisme
			lineageTag: 7ad202f4-459a-41f3-ae14-5d0657fa59ce
			sourceLineageTag: 241b65f1-39be-47da-9efb-5dc15be5d2b8
			dataCategory: Uncategorized

		measure 'Absenteisme Penultieme Mois' = EXTERNALMEASURE("Absenteisme Penultieme Mois", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Absentéisme
			lineageTag: 2c6493aa-850a-4502-ad12-b19cf968d975
			sourceLineageTag: 5e37e88f-cf86-4272-98ab-117ccc4bfaed
			dataCategory: Uncategorized

		measure 'Adherents Fin Validite APP dans les 6 Mois' = EXTERNALMEASURE("Adherents Fin Validite APP dans les 6 Mois", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: AMT
			lineageTag: 07a06231-c812-477a-a6ae-97700f5a73ec
			sourceLineageTag: 8b666f48-eab6-44f7-bd20-a9b2000f8dd6
			dataCategory: Uncategorized

		measure Adhérents_Max_Axe_Y = EXTERNALMEASURE("Adhérents_Max_Axe_Y", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Adhérents\Graph
			lineageTag: 4d16cae8-c3c4-4ad1-8e3a-b0f8bf9b33c2
			sourceLineageTag: 525061ec-244d-44c9-906b-e1261a0d81fe
			dataCategory: Uncategorized

		measure Adhérents_Min_Axe_Y = EXTERNALMEASURE("Adhérents_Min_Axe_Y", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Adhérents\Graph
			lineageTag: 13591520-3519-431d-b04d-c81838c1954f
			sourceLineageTag: e70205d3-4120-42d2-8487-065b18e51aba
			dataCategory: Uncategorized

		measure Afficher_jusqua_Cible = ```
				
				VAR CurDate  = DATEVALUE( MAX ( 'Dates_Futur'[EndOfMonth] ) )
				VAR Target0  =
				   COALESCE(
				    SELECTEDVALUE( Dates_Cible[Date] ),
				    MAXX( ALLSELECTED( Dates_Cible[Date] ), Dates_Cible[Date] )
				)
				VAR Target = DATEVALUE( EOMONTH( Target0, 0 ) )  // option: caler à fin de mois
				RETURN
				    NOT ISBLANK( Target ) && CurDate <= Target
				
				```
			formatString: """TRUE"";""TRUE"";""FALSE"""
			displayFolder: FE\Simulation
			lineageTag: af5d126f-5e81-40cd-9b31-5cd1b988b136

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'AMT en-cours ayant atteint le statut à valider' = EXTERNALMEASURE("AMT en-cours ayant atteint le statut à valider", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: AMT
			lineageTag: 93b00bef-46e4-41a2-80f2-235787bd7e7a
			sourceLineageTag: b5806fb5-cc6e-486d-b032-1ac854d9fecc
			dataCategory: Uncategorized

		measure 'AMT en-cours ayant atteints le statut à valider' = EXTERNALMEASURE("AMT en-cours ayant atteints le statut à valider", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: AMT
			lineageTag: ce7a6d57-91f5-4805-97f3-2c44af6af622
			sourceLineageTag: 6b3c6ac6-6e6c-4c15-a11b-d80ef53a2a36
			dataCategory: Uncategorized

		measure 'AMT en-cours ou terminés ayant atteint le statut à valider' = EXTERNALMEASURE("AMT en-cours ou terminés ayant atteint le statut à valider", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: AMT
			lineageTag: d337e8c8-6aa3-4ba6-9e37-a31362d5b057
			sourceLineageTag: 621cb51e-711d-43d5-84f6-25f7402e448c
			dataCategory: Uncategorized

		measure APP_DerniereValeur =
				
				VAR d0 = [DerniereDateReelleAPP]
				
				RETURN
				    CALCULATE (
				        [% adhérents à jour d'AMT primaire (fin de période)],
				        TREATAS ( ROW ( "Date", d0 ), 'Date principale'[Date] )
				    )
			displayFolder: AMT\Simulation
			lineageTag: 58eea617-ce6a-4866-8139-d982451434d7

			changedProperty = DisplayFolder

			changedProperty = Name

			annotation PBI_FormatHint = {"isGeneralNumber":true}


		/// Booléen. La période sélectionnée appartient t'elle a la semaine précédente ? oui ou non
		measure 'Avant Pénultième Semaine' = EXTERNALMEASURE("Avant Pénultième Semaine", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Date
			lineageTag: aa31d422-5471-4637-8adb-80b225ea1afa
			sourceLineageTag: 7ef1787e-fbe8-44ed-b011-1a40d4d23e3e
			dataCategory: Uncategorized

		measure 'Avant Pénultième Semaine (Demande RDV)' = EXTERNALMEASURE("Avant Pénultième Semaine (Demande RDV)", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Demandes de RDV
			lineageTag: 0af68ab9-0c6f-41ac-bf2e-95850e6d3bb8
			sourceLineageTag: 385f30fd-1004-4c9f-afa7-f9e8d0c1a283
			dataCategory: Uncategorized

		measure 'Besoin IDEST' = EXTERNALMEASURE("Besoin IDEST", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0.00
			displayFolder: Prévision de charge
			lineageTag: e144a39e-bab6-415a-b58c-722f772fc281
			sourceLineageTag: 60a7a946-79de-48f6-96aa-01eb6257e898
			dataCategory: Uncategorized

		measure 'Besoin médecin' = EXTERNALMEASURE("Besoin médecin", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0.00
			displayFolder: Prévision de charge
			lineageTag: c6d12d63-b5c2-4a09-b726-99ec74019432
			sourceLineageTag: 92d3e8a1-07d1-4b2b-a5cc-13acd6024634
			dataCategory: Uncategorized

		measure 'Capacité Théorique IDEST' = EXTERNALMEASURE("Capacité Théorique IDEST", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Prévision de charge
			lineageTag: 1fc4b7f9-4292-415d-95ef-14b24d95f142
			sourceLineageTag: 1d656bb3-4f13-4532-967a-4e12b8408502
			dataCategory: Uncategorized

		measure 'Capacité Théorique Médecin' = EXTERNALMEASURE("Capacité Théorique Médecin", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Prévision de charge
			lineageTag: 0efa9447-1c34-4359-b4c4-34668c0b5efe
			sourceLineageTag: cf5d4f00-56ef-4112-9174-4e77392cca67
			dataCategory: Uncategorized

		measure 'Capacité vs. Visites théoriques IDEST' = EXTERNALMEASURE("Capacité vs. Visites théoriques IDEST", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0.00
			displayFolder: Prévision de charge
			lineageTag: e36ee89b-2da4-4a49-bb53-5d0fdd35fe2c
			sourceLineageTag: 0d465a1d-f837-493d-818c-b82a551f6301
			dataCategory: Uncategorized

		measure 'Capacité vs. Visites théoriques Médecin' = EXTERNALMEASURE("Capacité vs. Visites théoriques Médecin", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0.00
			displayFolder: Prévision de charge
			lineageTag: c039e065-90a5-4a14-9e93-c4224fb19663
			sourceLineageTag: bfa2be0e-694a-4ac5-addc-9b7af2a42007
			dataCategory: Uncategorized

		/// Classement des adhérents par taille d'effectif
		measure 'Classement Adherents' = EXTERNALMEASURE("Classement Adherents", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Adhérents
			lineageTag: 38d87e65-a6e4-4ca3-935f-591a57852f4c
			sourceLineageTag: 6d35a9ae-c550-4082-9841-86793145dfbb
			dataCategory: Uncategorized

		measure 'Coloration Evol convocables S-3 -> S-2' = EXTERNALMEASURE("Coloration Evol convocables S-3 -> S-2", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Retard
			lineageTag: 8c19e37b-3d6f-4074-9012-2818efe30f8a
			sourceLineageTag: 53cbf6d7-ebf6-4753-8de1-c624dda011be
			dataCategory: Uncategorized

		measure 'Date Fin Arrêté' =
				
				VAR Selection = SELECTEDVALUE('Choisir Période'[ID], 2) // Par défaut : dernier mois
				VAR DateAuj = TODAY()
				VAR AnneePrecedente = DATE(YEAR(DateAuj)-1, 12, 31)
				VAR FinDernierMois = EOMONTH(DateAuj, -1) // Fin du mois précédent
				
				RETURN
				SWITCH(
				    Selection,
				    1, AnneePrecedente,
				    2, FinDernierMois,
				    FinDernierMois // Valeur par défaut de sécurité
				)
			formatString: General Date
			displayFolder: Date
			lineageTag: b53a23a3-7b77-4014-b664-2e61b796c2c0

			changedProperty = DisplayFolder

			changedProperty = Name

		/// Affiche le premier puis le dernier jour de la période de données sélectionnée
		measure 'Date ou période sélectionnée' = EXTERNALMEASURE("Date ou période sélectionnée", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Date
			lineageTag: bd6dbaa2-6b8c-4ae7-ba3c-a25290f011b3
			sourceLineageTag: 0b70e8e5-7c15-4295-bd8b-bab70dd93f99
			dataCategory: Uncategorized

		measure 'Date Référence' = ```
				
				VAR Choix =
				    SELECTEDVALUE ( 'Choix Date'[Choix], "Aujourd'hui" )
				RETURN
				SWITCH(
				    TRUE(),
				    Choix = "Aujourd'hui",
				        TODAY(),
				    Choix = "31/12 année précédente",
				        DATE( YEAR( TODAY() ) - 1, 12, 31 ),
				    TODAY()
				)
				
				```
			formatString: General Date
			displayFolder: Date
			lineageTag: 4a674de7-cad6-4010-bf59-b1eba1728e2c

			changedProperty = DisplayFolder

			changedProperty = Name

		
		measure DateLastYear = EXTERNALMEASURE("DateLastYear", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Date
			lineageTag: 4b939374-e10b-4018-8ef6-bf2848c3ae6e
			sourceLineageTag: 03b6c40e-cde5-4599-9a1a-7d705dfddc75
			dataCategory: Uncategorized

		measure 'Début Dernier Mois' = EXTERNALMEASURE("Début Dernier Mois", DATETIME, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: Short Date
			displayFolder: Date
			lineageTag: a5c18991-b2b4-42ba-9093-1d777c39063e
			sourceLineageTag: 657bd6ea-3af9-4aa0-85c6-68cdee42f3ec
			dataCategory: Uncategorized

		/// Affiche le premier jour de l'avant dernière semaine (le lundi)
		measure 'Début Pénultième Semaine' = EXTERNALMEASURE("Début Pénultième Semaine", DATETIME, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: dddd d mmmm yyyy
			displayFolder: Date
			lineageTag: 51a442fa-728c-42d0-b86d-b30ad971ce99
			sourceLineageTag: 91508876-9788-4eab-9bc1-b14a4f22f3bb
			dataCategory: Uncategorized

		measure 'Delai Planification Demande de visite' = EXTERNALMEASURE("Delai Planification Demande de visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Demandes de RDV
			lineageTag: 300ca6ba-1998-4d57-985c-3dd7618e0584
			sourceLineageTag: 075d6984-3de8-4f5d-8f20-3e21e7f0725b
			dataCategory: Uncategorized

		measure 'Demande de rdv' = EXTERNALMEASURE("Demande de rdv", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Demandes de RDV
			lineageTag: 028602f9-5ef3-4c6c-ae89-b843a463c17d
			sourceLineageTag: 77514d12-a260-449a-a007-71e30f1bff48
			dataCategory: Uncategorized

		measure 'Demande de rdv blank' = EXTERNALMEASURE("Demande de rdv blank", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Demandes de RDV
			lineageTag: 7ac108ec-fda6-4b8f-98ff-000d2dc8b027
			sourceLineageTag: 4bb511ac-2097-4340-8f86-fa749ce66a0b
			dataCategory: Uncategorized

		measure DerniereDateReelle = ```
				
				VAR d =
				    CALCULATE (
				        MAX ( 'Date principale'[Date] ),
				        FILTER ( ALLSELECTED ( 'Date principale' ),
				        NOT ISBLANK('Evolution effectif'[% adhérents à jour de FE (fin de période)])
				    ))
				RETURN 
				d
				```
			formatString: General Date
			displayFolder: FE\Simulation
			lineageTag: b1b388be-5476-4973-9615-455c6619817f

			changedProperty = DisplayFolder

			changedProperty = Name

		measure DerniereDateReelleAPP = ```
				
				VAR d =
				    CALCULATE (
				        MAX ( 'Date principale'[Date] ),
				        FILTER ( ALLSELECTED ( 'Date principale' ),
				        NOT ISBLANK('Evolution effectif'[% adhérents à jour d'AMT primaire (fin de période)])
				    ))
				RETURN 
				d
				```
			formatString: General Date
			displayFolder: AMT\Simulation
			lineageTag: e2721b37-1621-4b9a-b17e-d9a64b194936

			changedProperty = DisplayFolder

			changedProperty = Name

		measure DerniereDateReelleTxService = ```
				
				VAR d =
				    CALCULATE (
				        MAX ( 'Date principale'[Date] ),
				        FILTER ( ALLSELECTED ( 'Date principale' ),
				        NOT ISBLANK([Taux de service coalesce])
				    ))
				RETURN 
				d
				```
			formatString: General Date
			displayFolder: Taux de service\Simulation
			lineageTag: 718f3878-19b6-4795-8f5e-ee55469f3df0

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'détails salariés convocables' = EXTERNALMEASURE("détails salariés convocables", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Divers
			lineageTag: a0833c09-9436-4fdd-a1e9-d96b58ed2507
			sourceLineageTag: 5d1c71b1-1831-435b-ab3f-4250fdb83aa2
			dataCategory: Uncategorized

		measure 'Différence prévisions / réel' = EXTERNALMEASURE("Différence prévisions / réel", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Visites
			lineageTag: e3ead1d8-7761-46b8-a465-a53edfd624e6
			sourceLineageTag: 5f0da02d-3dc4-482d-b6d1-257596c1054d
			dataCategory: Uncategorized

		measure 'Données à jour à la dernière MAJ des données' = ```
				
				"Données à jour au : " & 
				FORMAT(
				    MAX(
				        '! Dernier rafraîchissement des données !'[Dernier rafraîchissement des données]),
				        "DD mmmm YYYY HH:mm", 
				        "fr-FR"
				)
				
				```
			displayFolder: Date
			lineageTag: b6e324fb-fc1d-4706-b07e-1d9dc702cf3e

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Données à jour à la fin du mois dernier' = EXTERNALMEASURE("Données à jour à la fin du mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Date
			lineageTag: d6f5ff7c-f560-4522-bd1c-4541537e3646
			sourceLineageTag: 7d10db9f-0faa-4f99-896c-262141389619
			dataCategory: Uncategorized

		measure Dummy = [Nombre de visites réalisées (RDV)] * 0.06
			lineageTag: 0f85e191-6cdc-43bb-b793-0bbe092b3c2b

			changedProperty = Name

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		measure 'Durée AMT en jours (Pénultième mois)' = EXTERNALMEASURE("Durée AMT en jours (Pénultième mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: AMT
			lineageTag: 5f7070f3-84ac-4682-a072-3f5f4df73276
			sourceLineageTag: 764d7190-00db-4975-8371-65b598090070
			dataCategory: Uncategorized

		measure 'Durée de traitement des tickets' =
				
				COALESCE(
				    [Durée moyenne traitement tickets (j)],
				    ""
				)
			formatString: 0
			lineageTag: d804d10b-f730-42a3-abf2-f12e532da981

			changedProperty = Name

			changedProperty = FormatString

		measure 'Durée visite (Pénultième mois)' = EXTERNALMEASURE("Durée visite (Pénultième mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Visites
			lineageTag: 0e55dd6f-53d4-4642-975a-353595fbd51a
			sourceLineageTag: 5da16c60-ad7d-4979-9422-e57f089e173f
			dataCategory: Uncategorized

		measure 'Effectif avec INS qualifié' =
				
				CALCULATE(
				    'Salariés'[Effectif suivi],
				    'Salarié (actuel)'[Statut INS] = "Qualifiée"
				)
			formatString: #,0
			displayFolder: Effectif
			lineageTag: 60ab112f-9069-4e2c-b536-c347c21f0e4a

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Effectif déclaré Année-1' = EXTERNALMEASURE("Effectif déclaré Année-1", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Effectif
			lineageTag: fd895212-9211-4cbd-b554-fc36efb88b19
			sourceLineageTag: bfcdbec0-af22-4759-9a82-9a6e7625b84d
			dataCategory: Uncategorized

		measure 'Effectif Dynamique' = ```
				
				VAR ChoixSelectionne = SELECTEDVALUE('Choix Date'[Choix]) 
				
				VAR DateCible = 
				    SWITCH(
				        ChoixSelectionne,
				        "Date du jour", TODAY(),
				        "31/12 de l'année précédente", DATE(year(TODAY()) - 1, 12, 31),
				        BLANK()
				    )
				
				RETURN
				    CALCULATE(
				        [Evolution Effectif - effectif suivi], -- Votre mesure d'effectif existante (ex: COUNTROWS('Table Employes'))
				        FILTER(
				            ALL('Date principale'), -- Ignore tous les filtres de date existants
				            'Date principale'[Date] = DateCible -- Applique le filtre à la date cible
				        )
				    )
				```
			formatString: 0
			displayFolder: Date
			lineageTag: 762026e8-c80a-4d51-b8dc-260702f9e2ab

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Effectif en retard' = EXTERNALMEASURE("Effectif en retard", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Retard
			lineageTag: 2c51c6f5-449c-4a91-9e82-950fd3b4d282
			sourceLineageTag: acfb9510-1114-4a12-84f7-2f871ea26354
			dataCategory: Uncategorized

		measure 'Effectif en retard début d''année en-cours' = EXTERNALMEASURE("Effectif en retard début d'année en-cours", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Retard
			lineageTag: d41bb0c1-e21e-435c-8584-6391426acfd5
			sourceLineageTag: 55f01bd2-5acd-41f3-b95f-a940140ee624
			dataCategory: Uncategorized

		measure 'Effectif en retard M-1' = EXTERNALMEASURE("Effectif en retard M-1", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Retard
			lineageTag: 979e2bb4-dff9-469a-aaff-f69fd2a1d1c9
			sourceLineageTag: f933ed7e-b54f-4998-8536-bb7584d88bc2
			dataCategory: Uncategorized

		measure 'Effectif en retard M-2' = EXTERNALMEASURE("Effectif en retard M-2", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Retard
			lineageTag: 5c6a1aa9-da98-4b26-9c98-65812b3a725e
			sourceLineageTag: 9fc084fd-c085-4967-bda1-f0d8865db169
			dataCategory: Uncategorized

		measure 'Effectif en retard S-1' = EXTERNALMEASURE("Effectif en retard S-1", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Retard
			lineageTag: 3061a543-fd9d-4302-90a8-1ed2af0f86f2
			sourceLineageTag: 551d1c07-ad4d-4fbe-8129-a023241c37c6
			dataCategory: Uncategorized

		measure 'Effectif en retard S-2' = EXTERNALMEASURE("Effectif en retard S-2", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Retard
			lineageTag: 40ee0e05-f300-42c9-b10e-5625aeee49ae
			sourceLineageTag: d373cbc1-1318-448c-bd71-a3fbf73f3942
			dataCategory: Uncategorized

		measure 'Effectif en retard S-2 remove filter' = EXTERNALMEASURE("Effectif en retard S-2 remove filter", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Retard
			lineageTag: 4cef1ebc-a164-4d41-acd1-e9c9e704f6fc
			sourceLineageTag: 6cdaac9e-47c6-4924-af28-37777607fe1f
			dataCategory: Uncategorized

		measure 'Effectif en retard S-3' = EXTERNALMEASURE("Effectif en retard S-3", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Retard
			lineageTag: 6fa59df8-41c6-49b7-a416-17781219d638
			sourceLineageTag: b0ba7ea9-9643-4585-b720-4b3c67d4f52a
			dataCategory: Uncategorized

		measure 'Effectif suivi INB cat A' = EXTERNALMEASURE("Effectif suivi INB cat A", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Effectif
			lineageTag: 4ea75658-cb01-4a38-9456-50a6c4d96ab7
			sourceLineageTag: ab83b752-ab70-49ab-9440-be4fbbe69af7
			dataCategory: Uncategorized

		measure 'Effectif suivi INB cat B' = EXTERNALMEASURE("Effectif suivi INB cat B", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Effectif
			lineageTag: 5781d155-249b-4443-818c-03ad5ad72c78
			sourceLineageTag: 87b57543-544a-486c-819e-ae61d023fd60
			dataCategory: Uncategorized

		measure 'Effectif Suivi Non Intérimaire Non Filtré' = EXTERNALMEASURE("Effectif Suivi Non Intérimaire Non Filtré", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Adhérents
			lineageTag: 01364376-3a9c-4501-8209-e42f6efff75d
			sourceLineageTag: 4165e2c0-994c-4a51-a48d-273445ff280f
			dataCategory: Uncategorized

		measure 'Effectif suivi Rayonnements ionisants A' = EXTERNALMEASURE("Effectif suivi Rayonnements ionisants A", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Effectif
			lineageTag: 505ff068-6276-4ffb-9d0f-8dc326edb4d0
			sourceLineageTag: a58637ce-3371-4de0-8f11-1362841175c9
			dataCategory: Uncategorized

		measure 'Effectif suivi Rayonnements ionisants B' = EXTERNALMEASURE("Effectif suivi Rayonnements ionisants B", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Effectif
			lineageTag: 7d47aa09-d912-458b-8e6b-4343fc30a248
			sourceLineageTag: 95907840-3e22-4ffa-93ca-847239cc3e0f
			dataCategory: Uncategorized

		measure 'Effectif suivi SI' = EXTERNALMEASURE("Effectif suivi SI", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Effectif
			lineageTag: 2f8df8fb-3fc2-41b9-9909-7c8bef529043
			sourceLineageTag: cd7ce640-9138-4b3b-9d65-aff36c1d8efb
			dataCategory: Uncategorized

		measure 'Effectif suivi SIA' = EXTERNALMEASURE("Effectif suivi SIA", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Effectif
			lineageTag: 9ba65459-eefc-4387-9e15-ed0fc48ec28e
			sourceLineageTag: aac4355f-e8de-4eac-b121-c2cbf1d52f6d
			dataCategory: Uncategorized

		measure 'Effectif suivi SIR' = EXTERNALMEASURE("Effectif suivi SIR", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Effectif
			lineageTag: b2298a21-2570-483c-b465-aa5aaa3d53c6
			sourceLineageTag: d3af6495-2a26-4edc-96e0-076f1de98880
			dataCategory: Uncategorized

		measure Effectif_max_Axe_Y = EXTERNALMEASURE("Effectif_max_Axe_Y", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Adhérents\Graph
			lineageTag: 59c271eb-cc4a-4ad1-bbac-5fd4882d3f39
			sourceLineageTag: 673cdf76-ec9e-4af0-b2f6-d9c9fd5a84da
			dataCategory: Uncategorized

		measure Effectif_min_Axe_Y = EXTERNALMEASURE("Effectif_min_Axe_Y", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Adhérents\Graph
			lineageTag: 036b983b-9527-4168-8696-049087190e45
			sourceLineageTag: 5f8ec233-8b21-4fa2-86d5-ed1b847f5edc
			dataCategory: Uncategorized

		measure 'Etiquette dernier moy. QVCT' = EXTERNALMEASURE("Etiquette dernier moy. QVCT", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Etiquettes
			lineageTag: eda5a1c3-b9e9-438a-9b6a-dd311e7f316c
			sourceLineageTag: da659070-b577-4485-8c8c-79a29dc22f50
			dataCategory: Uncategorized

		measure 'Etiquette effectif suivi' = EXTERNALMEASURE("Etiquette effectif suivi", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Etiquettes
			lineageTag: 7018862a-b79e-42ff-9327-443b9d028081
			sourceLineageTag: f2e2c9b1-e9d8-483c-9d99-0f686c1eda43
			dataCategory: Uncategorized

		measure 'Etiquette min/max tx annulation IDEST' = EXTERNALMEASURE("Etiquette min/max tx annulation IDEST", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Etiquettes
			lineageTag: 5c589d5c-dbfa-4ae7-aaba-658ee29ddcf4
			sourceLineageTag: 39f7082d-7903-4e3a-80ba-feac45d95de8
			dataCategory: Uncategorized

		measure 'Etiquette min/max tx de service' = EXTERNALMEASURE("Etiquette min/max tx de service", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Etiquettes
			lineageTag: 743a2b5e-faee-44cc-91a9-d0890a0ed1ea
			sourceLineageTag: 0dd4b39d-bb11-4fbc-b627-596729552279
			dataCategory: Uncategorized

		/// Affiche seulement l'étiquette de données Max et Min sur le graph de l'évolution des effectifs suivis.
		measure 'Etiquette min/max/dernier effectif suivi' = EXTERNALMEASURE("Etiquette min/max/dernier effectif suivi", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Etiquettes
			lineageTag: 38786aa6-4181-4064-a9c6-3d837f10af9b
			sourceLineageTag: ecf7375e-9611-4126-b820-baa2dd82f279
			dataCategory: Uncategorized

		measure 'Etiquette min/max/dernier nbre d''adhérents' = EXTERNALMEASURE("Etiquette min/max/dernier nbre d'adhérents", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Etiquettes
			lineageTag: d2c3b607-dfe0-421a-a6f4-475fc1469f65
			sourceLineageTag: cf472743-71e9-4ff5-bfc1-74f95bf5cfb5
			dataCategory: Uncategorized

		measure 'Evol convocables S-2 -> S-1' = EXTERNALMEASURE("Evol convocables S-2 -> S-1", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Retard
			lineageTag: 8ba5da0d-5aa6-46da-bee2-d1b45b066c25
			sourceLineageTag: cd11e558-d4ab-4038-aa62-c9f11ab44ad4
			dataCategory: Uncategorized

		measure 'Evol convocables S-2 -> S-1 symbole' = EXTERNALMEASURE("Evol convocables S-2 -> S-1 symbole", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Retard
			lineageTag: f96928cb-1e9a-4cc2-82da-577121039ffb
			sourceLineageTag: aaaf5c58-5196-4e8e-ad12-3711b97a7221
			dataCategory: Uncategorized

		measure 'Evol effectif filtré par adhérent' = EXTERNALMEASURE("Evol effectif filtré par adhérent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Effectif
			lineageTag: aef9ba38-ad22-4b0f-a047-cddc2adf5180
			sourceLineageTag: 76170999-3d48-447d-8978-0dcfe4f9984d
			dataCategory: Uncategorized

		measure 'Evol retard depuis début année' = EXTERNALMEASURE("Evol retard depuis début année", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Retard
			lineageTag: 3cc4a8d4-a583-485c-9319-6e265c212e2c
			sourceLineageTag: 633dab14-0345-438e-b5e3-a40fffd1acc2
			dataCategory: Uncategorized

		measure 'Evol Tx de service S-2 -> S-1 symbole' = EXTERNALMEASURE("Evol Tx de service S-2 -> S-1 symbole", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Retard
			lineageTag: 5e544d52-908f-4088-995a-00d632aa4b50
			sourceLineageTag: 73cb3d34-5aae-4467-b5d4-16e09027ae5f
			dataCategory: Uncategorized

		measure 'Evol Tx de service S-3 -> S-2 symbole' = EXTERNALMEASURE("Evol Tx de service S-3 -> S-2 symbole", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Retard
			lineageTag: dd61325e-03dc-4f23-b3f0-2fe183e3e088
			sourceLineageTag: 0e0778a5-6707-4f3c-8021-14ebadb9362a
			dataCategory: Uncategorized

		measure 'Evolution Effectif' = EXTERNALMEASURE("Evolution Effectif", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Adhérents
			lineageTag: 6406c1e3-3daf-4501-a7f6-b020ab4b447b
			sourceLineageTag: 3735905c-ca38-45a0-a530-93caa1cd46e8
			dataCategory: Uncategorized

		measure 'Evolution Effectif - effectif suivi' =
				
				COALESCE(
				    'Evolution effectif'[Effectif suivi non intérimaire fin de période]+ 'Evolution effectif'[Effectif suivi intérimaire fin de période],
				    0
				)
			formatString: #,0
			displayFolder: Effectif
			lineageTag: eb916d23-8446-4d70-8b66-6209c795c78d

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Évolution Nbre AMT 2023->2024' = EXTERNALMEASURE("Évolution Nbre AMT 2023->2024", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: AMT
			lineageTag: e5f74b36-96f3-4682-90d8-011e9330ff59
			sourceLineageTag: 5809367d-5ec1-4759-9de0-21c07c76e44b
			dataCategory: Uncategorized

		measure FE_DerniereValeur =
				
				VAR d0 = [DerniereDateReelle]
				RETURN
				    CALCULATE (
				        [% adhérents à jour de FE (fin de période)],
				        TREATAS ( ROW ( "Date", d0 ), 'Date principale'[Date] )
				    )
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: FE\Simulation
			lineageTag: ac21a2fa-1300-46c0-abeb-e5b9290577cf

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString


		measure 'Filtres actifs' = ```
				
				VAR SelDate = [Période (Du au)]
				VAR SelTaille =
				    IF(
				        ISFILTERED('Adhérent (actuel)'[Taille d'entreprise]),
				        VAR s = CONCATENATEX(VALUES('Adhérent (actuel)'[Taille d'entreprise]), 'Adhérent (actuel)'[Taille d'entreprise], ", ")
				        RETURN IF(LEN(s)=0, "Aucun", s),
				        "Tous"
				    )
				VAR SelType =
				    IF(
				        ISFILTERED('Adhérent (actuel)'[Type d'entreprise :]),
				        VAR s = CONCATENATEX(VALUES('Adhérent (actuel)'[Type d'entreprise :]), 'Adhérent (actuel)'[Type d'entreprise :], ", ")
				        RETURN IF(LEN(s)=0, "Aucun", s),
				        "Tous"
				    )
				RETURN
				    "Dates : " & SelDate & " | Taille d'entreprise : " & SelTaille & " | Type d'entreprise : " & SelType
				
				```
			lineageTag: 6e73330b-5d2e-4251-95a5-c9a90c9a66c9

			changedProperty = Name

		measure 'Fin Dernier Mois' = EXTERNALMEASURE("Fin Dernier Mois", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Date
			lineageTag: 82906f7b-247a-4ca5-8d68-1f48b2780abd
			sourceLineageTag: d78d2cd4-d292-45fd-b97f-084c2bbfa4d3
			dataCategory: Uncategorized

		/// Affiche le dernier jour de l'avant dernière semaine (le dimanche)
		measure 'Fin Pénultième Semaine' = EXTERNALMEASURE("Fin Pénultième Semaine", DATETIME, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: dddd d mmmm yyyy
			displayFolder: Date
			lineageTag: 6b6ebece-ee27-4f0c-a56c-6065e8e3c8ee
			sourceLineageTag: 0fc1849a-ad90-4ae6-a9b6-c3d3e68c0354
			dataCategory: Uncategorized

		measure 'IDEST sélectionnée' = EXTERNALMEASURE("IDEST sélectionnée", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Divers
			lineageTag: 32d645e4-2285-4e92-b1e5-639084d2ac37
			sourceLineageTag: 04c0f093-e593-4246-8eb2-2cdcded69470
			dataCategory: Uncategorized

		measure 'Infos mesures' = EXTERNALMEASURE("Infos mesures", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			lineageTag: 5d059821-26db-4fff-8879-f9aad26c8a79
			sourceLineageTag: d4203c25-4aab-4b80-bc4c-da35f828e211
			dataCategory: Uncategorized

		measure 'Max AMT sur période' = EXTERNALMEASURE("Max AMT sur période", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: AMT\Graph
			lineageTag: b9478cfe-86f2-41ff-bc69-bf78a85fe660
			sourceLineageTag: ffc0ba72-b4d7-47be-82c3-9dcac8a0bc77
			dataCategory: Uncategorized

		measure 'max demande de rdv mensuel' = EXTERNALMEASURE("max demande de rdv mensuel", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Demandes de RDV
			lineageTag: 9221cf56-c2cc-4a25-ab33-a37a16c476bf
			sourceLineageTag: 30d12c3e-6051-4438-b2b6-4661e5d0b54f
			dataCategory: Uncategorized

		measure 'max demande de rdv mensuel non filtré' = EXTERNALMEASURE("max demande de rdv mensuel non filtré", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Demandes de RDV
			lineageTag: 27878eba-3a1a-4d06-8461-5b9437af121f
			sourceLineageTag: c267ae82-cfb8-43ff-a6bd-70641f24cca6
			dataCategory: Uncategorized

		measure 'max demande de rdv mensuel pour échelle Y' = EXTERNALMEASURE("max demande de rdv mensuel pour échelle Y", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Demandes de RDV
			lineageTag: 6dfa0812-aad1-4725-ae71-c8dee48503e6
			sourceLineageTag: c073b736-a238-43bb-9962-c6b152f523e4
			dataCategory: Uncategorized

		measure 'Max Entretien par Salarié QVCT' = EXTERNALMEASURE("Max Entretien par Salarié QVCT", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Consultations Spécialisées\QVCT
			lineageTag: a296f329-b313-47b6-8173-f0e8cc393504
			sourceLineageTag: fae81962-cbfc-4130-bca6-55dabd7a24da
			dataCategory: Uncategorized

		measure 'Max inaptitudes sur période' = EXTERNALMEASURE("Max inaptitudes sur période", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Divers
			lineageTag: d4d8ffd6-7e85-49d1-9b4b-29ceee2875e1
			sourceLineageTag: 913034a1-aafd-4794-91d8-6905f40e2e5f
			dataCategory: Uncategorized

		measure 'Max Orientations / mois' = EXTERNALMEASURE("Max Orientations / mois", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Orientations
			lineageTag: 75b6e406-2186-4e1e-b15b-57d970f62fa9
			sourceLineageTag: 82a804ad-7d9b-419c-bdae-b3a4f5e82017
			dataCategory: Uncategorized

		measure 'Max réclamation' = EXTERNALMEASURE("Max réclamation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Divers
			lineageTag: 3698a37c-1d3a-4bbd-ba01-d9c2860aee94
			sourceLineageTag: c78ca580-9d72-4763-903c-f0ecb33c6823
			dataCategory: Uncategorized

		measure 'Max téléconsultations sur période' = EXTERNALMEASURE("Max téléconsultations sur période", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Téléconsultations
			lineageTag: f4f6009b-9103-48ae-b5da-5248fac1c82d
			sourceLineageTag: b086678b-d72b-4c15-aa7a-63f25cfafa1f
			dataCategory: Uncategorized

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		measure 'Max Visites' = EXTERNALMEASURE("Max Visites", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Visites
			lineageTag: b99323bd-e759-4a48-b7c5-7029ad01f4ad
			sourceLineageTag: 71d53e86-cfc9-48d7-acc7-73cd989a70b2
			dataCategory: Uncategorized

		measure 'Max Y nbre de visites réalisées (RDV)' =
				
				MAXX(
				    ALLSELECTED('Date principale'[NomMoisAnnee]),
				    'RDV'[Nombre de visites réalisées (RDV)]
				    )
				    * 1.3
			lineageTag: 3bd1eb97-a4ca-45b9-b7b1-3471e770a9a1

			changedProperty = Name

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		measure Max_Créneaux_Par_Semaine_IDEST = EXTERNALMEASURE("Max_Créneaux_Par_Semaine_IDEST", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: IDEST
			lineageTag: 4a4637df-3ea2-4b91-8bdb-99ab6a75a2d4
			sourceLineageTag: 9026f407-fca4-4bea-9656-5a7a5bf63ff4
			dataCategory: Uncategorized

		measure Max_Visites_IDEST = EXTERNALMEASURE("Max_Visites_IDEST", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: IDEST
			lineageTag: 834523b1-1345-4336-aad1-56579ab569d3
			sourceLineageTag: de42bbc2-1017-4791-9e80-3a553e83f76a
			dataCategory: Uncategorized

		measure Max_Visites_Par_Mois_IDEST = EXTERNALMEASURE("Max_Visites_Par_Mois_IDEST", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: IDEST
			lineageTag: 554a7fc4-00d3-4149-aa8c-41e4adfa7280
			sourceLineageTag: edac0ee6-a860-4a24-8378-737a12970237
			dataCategory: Uncategorized

		measure Max_Visites_Par_Semaine_IDEST = EXTERNALMEASURE("Max_Visites_Par_Semaine_IDEST", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: IDEST
			lineageTag: 2d3a89c0-3c93-43a0-a4d5-3a127d6822b2
			sourceLineageTag: feec5afe-db30-4de8-a543-dbe081564b10
			dataCategory: Uncategorized

		measure MaxDemandeRDVSurPeriode = EXTERNALMEASURE("MaxDemandeRDVSurPeriode", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Divers
			lineageTag: 5364844f-ae7a-4809-a75d-0104d57c2068
			sourceLineageTag: 50444863-322e-4c46-9ef5-1488af6a7682
			dataCategory: Uncategorized

		measure MaxDureeMoyTraitement = EXTERNALMEASURE("MaxDureeMoyTraitement", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Divers
			lineageTag: f9558eb0-6f1d-4208-9808-6f2adfd3d2d9
			sourceLineageTag: 078c560d-79f7-4943-81d6-e62b486e1a6b
			dataCategory: Uncategorized

		/// Permet d'afficher la sélection dans le coin en haut à gauche du rapport : Ensemble du service, Zone, Centre ou équipe
		/// 
		/// Entite Selectionnee =
		/// VAR SelectedTeam = SELECTEDVALUE('Equipe médicale'[Equipe médicale])
		/// VAR SelectedCenter = SELECTEDVALUE('Equipe médicale'[Centre rattachement])
		/// VAR SelectedGeographicZone = SELECTEDVALUE('Equipe médicale'[Zone géographique])
		/// 
		/// RETURN
		/// IF(
		/// NOT ISBLANK(SelectedTeam),
		/// "Equipe médicale : " & SelectedTeam,
		/// IF(
		/// NOT ISBLANK(SelectedCenter),
		/// "Centre de convocation : " & SelectedCenter,
		/// IF(
		/// NOT ISBLANK(SelectedGeographicZone),
		/// "Zone géographique : " & SelectedGeographicZone,
		/// "Ensemble du service"
		/// )
		/// )
		/// )
		measure 'Médecin sélectionné' = EXTERNALMEASURE("Médecin sélectionné", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Divers
			lineageTag: 31f8924f-ed81-4639-9a28-9639c175d9b0
			sourceLineageTag: 3dd51da0-b737-4755-85f8-74356075ef37
			dataCategory: Uncategorized

		measure Mesure = "aa"
			displayFolder: FE\Simulation
			lineageTag: 2a196a2e-c85d-42e2-b900-51cc561c5674

			changedProperty = DisplayFolder

		measure 'Min Entretien par Salarié QVCT' = EXTERNALMEASURE("Min Entretien par Salarié QVCT", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Consultations Spécialisées\QVCT
			lineageTag: 627e131d-2937-4d62-856b-319d40fc1bd3
			sourceLineageTag: f6962335-29bb-47d5-a965-5041be14fb24
			dataCategory: Uncategorized

		measure 'Mois dernier' = EXTERNALMEASURE("Mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Date
			lineageTag: dc8c8f5b-6662-43b3-baee-8c24916b4096
			sourceLineageTag: 59eebeb0-0643-4202-a615-6447b2928317
			dataCategory: Uncategorized

		measure 'Moy. AMT (12 mois précédents)' = EXTERNALMEASURE("Moy. AMT (12 mois précédents)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: AMT
			lineageTag: 7b37be15-aa2d-4874-b6c1-954ebe49005d
			sourceLineageTag: 5594cb54-b155-4787-8e12-231a313bb92f
			dataCategory: Uncategorized

		measure 'Moy. AMT mensuelles PDP (12 mois)' = EXTERNALMEASURE("Moy. AMT mensuelles PDP (12 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: AMT
			lineageTag: f03b85e6-86da-4889-ae50-bad745b1748c
			sourceLineageTag: e7a1d568-4d00-4c14-935f-d55c74e660b7
			dataCategory: Uncategorized

		measure 'Moy. AMT mensuelles QVCT (12 mois)' = EXTERNALMEASURE("Moy. AMT mensuelles QVCT (12 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: AMT
			lineageTag: 48229623-7d6e-4067-932a-73e7454404ae
			sourceLineageTag: 0d9ba299-68b5-486c-9a56-7bcaff017ad0
			dataCategory: Uncategorized

		/// Affiche la moyenne des convocations hebdomadaires sur les 12 derniers mois
		measure 'Moy. Convocations Hebdomadaires (12 mois)' = EXTERNALMEASURE("Moy. Convocations Hebdomadaires (12 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Convocations
			lineageTag: 3c4a9a80-3105-4a83-9145-4a9848aed003
			sourceLineageTag: 5dcd3fc7-c9d7-4e76-ad32-f7589a2b9630
			dataCategory: Uncategorized

		/// Affiche la moyenne des convocations hebdomadaires sur les 6 derniers mois à destination des IDEST
		measure 'Moy. Convocations Hebdomadaires IDEST (6 mois)' = EXTERNALMEASURE("Moy. Convocations Hebdomadaires IDEST (6 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Convocations
			lineageTag: 987936f6-0317-4d41-a94d-a731e5871199
			sourceLineageTag: c28d4e09-7af5-417b-b2d6-f3f575573653
			dataCategory: Uncategorized

		measure 'Moy. Convocations Hebdomadaires Médecin (6 mois)' = EXTERNALMEASURE("Moy. Convocations Hebdomadaires Médecin (6 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Convocations
			lineageTag: 5e10d3a8-0ff5-47c4-b4c2-7732c50d96f9
			sourceLineageTag: 495f97b7-cc8d-4114-ab88-7a9e3a45fd3a
			dataCategory: Uncategorized

		measure 'Moy. créneaux ouverts (12 mois)' = EXTERNALMEASURE("Moy. créneaux ouverts (12 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Divers
			lineageTag: e748c6ad-f035-4dd9-a76b-622295ea98a8
			sourceLineageTag: 26de116a-34ed-486a-a5cf-f49a7aab85f4
			dataCategory: Uncategorized

		measure 'Moy. hebdo annulation par le service (6 mois)' = EXTERNALMEASURE("Moy. hebdo annulation par le service (6 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Annulation
			lineageTag: 7b771c69-1477-489c-8339-0e206c43f8dc
			sourceLineageTag: 9f93cf70-d4d9-41ee-b342-4d05495f1df4
			dataCategory: Uncategorized

		measure 'Moy. nb orientations mensuelles PDP (12 mois)' = EXTERNALMEASURE("Moy. nb orientations mensuelles PDP (12 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: fc1f67b2-8381-4502-8ae4-e7968b9e48ae
			sourceLineageTag: 780e6593-5714-46ed-ac54-df87d0bdd607
			dataCategory: Uncategorized

		measure 'Moy. nb orientations mensuelles QVCT (12 mois)' = EXTERNALMEASURE("Moy. nb orientations mensuelles QVCT (12 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Consultations Spécialisées\QVCT
			lineageTag: 4004293c-f5e3-48c8-ab5e-9b022829911c
			sourceLineageTag: db87e043-9269-44cf-b69e-951b4cbcbe21
			dataCategory: Uncategorized

		/// Affiche la moyenne des visites hebdomadaires des 12 derniers mois
		measure 'Moy. visites hebdomadaires (12 mois)' = EXTERNALMEASURE("Moy. visites hebdomadaires (12 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Visites
			lineageTag: 59d098e6-042a-42c4-809b-108cb5edcd1a
			sourceLineageTag: 8e06447d-74a0-4ec1-9a43-13e5ac99a0a2
			dataCategory: Uncategorized

		measure 'Moy. visites hebdomadaires IDEST (12 mois)' = EXTERNALMEASURE("Moy. visites hebdomadaires IDEST (12 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Visites
			lineageTag: 6d604a7f-d7ee-4799-9f2a-f026ce120734
			sourceLineageTag: 47675201-040b-4308-8235-eb129ccd6569
			dataCategory: Uncategorized

		/// Affiche la moyenne des visites hebdomadaires des 6 derniers mois réalisés par les IDEST
		measure 'Moy. visites hebdomadaires IDEST (6 mois)' = EXTERNALMEASURE("Moy. visites hebdomadaires IDEST (6 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Visites
			lineageTag: 7b98d049-065a-4959-964f-61bdff43a67a
			sourceLineageTag: 1b83c8e0-4aad-4490-ad37-d3f9dda69bdf
			dataCategory: Uncategorized

		measure 'Moy. visites hebdomadaires Médecin (12 mois)' = EXTERNALMEASURE("Moy. visites hebdomadaires Médecin (12 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Visites
			lineageTag: a78481f2-4384-4722-914b-544ceb2ec261
			sourceLineageTag: 5b1953cc-2dad-40d8-a27a-8a964eafff8b
			dataCategory: Uncategorized

		measure 'Moy. visites hebdomadaires Médecin (6 mois)' = EXTERNALMEASURE("Moy. visites hebdomadaires Médecin (6 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Visites
			lineageTag: 47d9a6b7-c246-4598-b5af-00b0a1dde1e8
			sourceLineageTag: 968bc2a1-78b4-4b35-9515-bd8d8cff0549
			dataCategory: Uncategorized

		/// Affiche la moyenne des visites des 12 derniers mois
		/// 
		measure 'Moy. visites mensuelles (12 mois)' = EXTERNALMEASURE("Moy. visites mensuelles (12 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Visites
			lineageTag: 8fa6161d-6343-4ca5-b262-9b3f7dc0c480
			sourceLineageTag: f64822a3-b0bd-4263-a0ad-e4a653753c52
			dataCategory: Uncategorized

		/// Affiche la moyenne des visites des 12 derniers mois réalisés par les IDEST
		measure 'Moy. visites mensuelles IDEST (12 mois)' = EXTERNALMEASURE("Moy. visites mensuelles IDEST (12 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Visites
			lineageTag: ee6272f4-af7d-41f8-b71a-f9aa2461f5a2
			sourceLineageTag: 57b26ea5-9aa4-4be5-9795-15251b4b37bf
			dataCategory: Uncategorized

		/// Affiche la moyenne des visites des 12 derniers mois réalisés par les Médecins
		measure 'Moy. visites mensuelles Médecin (12 mois)' = EXTERNALMEASURE("Moy. visites mensuelles Médecin (12 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0.00
			displayFolder: Visites
			lineageTag: 90362e22-8bc8-4902-a704-18ccd6822eca
			sourceLineageTag: ce4dbc09-5ced-4c01-8426-dfaff45af028
			dataCategory: Uncategorized

		measure 'Moyenne Entretiens PDP par Salarié (12 mois)' = EXTERNALMEASURE("Moyenne Entretiens PDP par Salarié (12 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: 11f37b72-3b3c-4901-a4c3-53fb7fbddba7
			sourceLineageTag: 931cff1e-b92d-434d-a6d4-b32cc224c031
			dataCategory: Uncategorized

		measure 'Moyenne Entretiens QVCT par Salarié (12 mois)' = EXTERNALMEASURE("Moyenne Entretiens QVCT par Salarié (12 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Consultations Spécialisées\QVCT
			lineageTag: fb3afd91-c9e8-4cc7-b49b-676589562182
			sourceLineageTag: fb3b62aa-ca05-4032-b4f8-7e2f03bd7a32
			dataCategory: Uncategorized

		measure 'Moyenne mobile visites Médecin' = EXTERNALMEASURE("Moyenne mobile visites Médecin", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Visites
			lineageTag: 8ec84f39-fcbc-4871-b5e3-ad36f8229ae1
			sourceLineageTag: 24c7a003-9534-4a5e-b9ee-eee2913ba6c5
			dataCategory: Uncategorized

		measure 'Moyenne mobile visites Médecin (12 mois)' = EXTERNALMEASURE("Moyenne mobile visites Médecin (12 mois)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Visites
			lineageTag: 61637f1c-15af-48b8-bc1c-47349a249548
			sourceLineageTag: 018e51f0-d29d-4f80-ae1d-582c4d6d1a7b
			dataCategory: Uncategorized

		measure 'Nb Mois Simulation' = ```
				
				VAR DateCible = SELECTEDVALUE('Dates_Futur'[Date]) // Récupère la date choisie dans le segment
				VAR DateReference = TODAY() // Ou la dernière date de vos données : MAX('Date principale'[Date])
				
				RETURN
				    // Calcul de la différence en mois
				    IF(
				        ISBLANK(DateCible) || DateCible <= DateReference, 
				        BLANK(), // Sécurité si pas de date ou date passée
				        DATEDIFF(DateReference, DateCible, MONTH)
				    )
				```
			formatString: 0
			displayFolder: FE\Simulation
			lineageTag: d4ed7a7a-7cc5-4b61-b32d-502644623b59

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'nb salariés concernés (12 mois)' = EXTERNALMEASURE("nb salariés concernés (12 mois)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Consultations Spécialisées
			lineageTag: 0853731b-437f-4f37-aae9-b48f79dff792
			sourceLineageTag: 1caff73d-91a7-41f8-8c8e-1515eef83650
			dataCategory: Uncategorized

		measure 'Nbre annexes 4' =
				
				CALCULATE(
				    [Nombre de documents émis],
				    'Documents émis - type document'[Type document détaillé] in {"Attestation de suivi avec annexe 4 temporaire", "Attestation de suivi avec annexe 4 permanente"}
				)
			formatString: 0
			displayFolder: Visites
			lineageTag: 921c7d50-158c-4138-ae3d-7e55db9c1ee1

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Nbre d''AMT terminées' = EXTERNALMEASURE("Nbre d'AMT terminées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: AMT
			lineageTag: 0bb37ab4-9234-472a-923c-69961f002b1d
			sourceLineageTag: ae8e30e1-a61e-4675-a9bc-532cb6d6dcf2
			dataCategory: Uncategorized

		measure 'Nbre d''avis d''inaptitude' = EXTERNALMEASURE("Nbre d'avis d'inaptitude", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Visites
			lineageTag: fbbb1e3f-2108-42bc-b773-ad48f11ae6dd
			sourceLineageTag: 66441537-0bb9-40f0-8c4a-5e4c9bc2c6f8
			dataCategory: Uncategorized

		measure 'NBre d''embauche Année-1' = EXTERNALMEASURE("NBre d'embauche Année-1", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Effectif
			lineageTag: 65f784f4-2a6a-481f-b5cd-4b05f36b8576
			sourceLineageTag: f98e75cb-6ac4-4b70-b46e-8498ddf8f65e
			dataCategory: Uncategorized

		measure 'NBre d''embauche Année-1 facturée' = EXTERNALMEASURE("NBre d'embauche Année-1 facturée", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Effectif
			lineageTag: aac0e8ee-4d0b-430a-8bb6-af682871086d
			sourceLineageTag: 2c6e7876-dc7b-4a98-ac99-71c03194ee71
			dataCategory: Uncategorized

		measure 'Nbre d''entretiens PDP' = EXTERNALMEASURE("Nbre d'entretiens PDP", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: 9a6ed25a-4e8e-434c-81d1-69bfd7b76ef0
			sourceLineageTag: 7ef7f0b7-4291-4345-8278-da6cb73f96c9
			dataCategory: Uncategorized

		measure 'Nbre d''entretiens PDP (12 mois)' = EXTERNALMEASURE("Nbre d'entretiens PDP (12 mois)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: c690f085-4b9f-4418-9e78-9166dbe8392c
			sourceLineageTag: 8e4c8f75-9632-4f35-a635-8b51aa19312d
			dataCategory: Uncategorized

		measure 'Nbre d''entretiens QVCT' = EXTERNALMEASURE("Nbre d'entretiens QVCT", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Consultations Spécialisées\QVCT
			lineageTag: 9d46d7eb-f129-4ee3-b68a-f4bf61d6b96b
			sourceLineageTag: 32d9ac41-93ab-46fc-9fb6-ac8b05c4916d
			dataCategory: Uncategorized

		measure 'Nbre d''entretiens QVCT (12 mois)' = EXTERNALMEASURE("Nbre d'entretiens QVCT (12 mois)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Consultations Spécialisées\QVCT
			lineageTag: dd684cf5-2954-432b-b6b8-394735da5ed2
			sourceLineageTag: 55e2c064-4876-454f-9638-f4a9086adaff
			dataCategory: Uncategorized

		measure 'Nbre de créneaux ouverts' = EXTERNALMEASURE("Nbre de créneaux ouverts", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Divers
			lineageTag: bd509013-1fc5-4aeb-86d6-c6f4f5c05a4d
			sourceLineageTag: ab183f2c-50f4-4489-a98b-258dfceaedd8
			dataCategory: Uncategorized

		measure 'Nbre de demandes de visites en attente' = EXTERNALMEASURE("Nbre de demandes de visites en attente", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Demandes de RDV
			lineageTag: f72e7d05-fd93-44ee-9dc8-c5e54455dfb5
			sourceLineageTag: 6c7a9ca6-5ab2-4dab-9117-a85a9b4e8198
			dataCategory: Uncategorized

		measure 'Nbre de FE' = EXTERNALMEASURE("Nbre de FE", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: FE
			lineageTag: 36c5487b-6acf-4678-8af7-4ba7e391c71f
			sourceLineageTag: eaf13df0-1944-4e33-80f6-faf06c4b9719
			dataCategory: Uncategorized

		measure 'Nbre de réclamations' = EXTERNALMEASURE("Nbre de réclamations", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Divers
			lineageTag: 90f6908b-3a01-4c74-a000-28f684954e37
			sourceLineageTag: e5614839-fe59-438a-9342-b0e1c6ece113
			dataCategory: Uncategorized

		measure 'Nbre de semaines pour rattraper retards' = EXTERNALMEASURE("Nbre de semaines pour rattraper retards", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Retard
			lineageTag: 04f0fa01-865a-463b-8dd0-269b51a15531
			sourceLineageTag: aa5f92fa-9dd5-4846-8f93-8eef7481ed18
			dataCategory: Uncategorized

		measure 'Nbre de tickets' =
				
				COALESCE(
				    'CRM - tickets'[# tickets],
				    0
				)
			formatString: 0
			lineageTag: 88aded22-1b96-44c7-9e7e-42df6a9361b9

			changedProperty = Name

		measure 'Nbre de visites intérimaires (12 derniers mois)' = EXTERNALMEASURE("Nbre de visites intérimaires (12 derniers mois)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Prévision de charge
			lineageTag: 0b8c41c8-7ba2-495e-b64f-4763dc3a370d
			sourceLineageTag: 3e53cb3c-8570-4b91-83f1-55d4c826500f
			dataCategory: Uncategorized

		measure 'Nbre de visites mensuelles / ETP théoriques' = EXTERNALMEASURE("Nbre de visites mensuelles / ETP théoriques", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0.00
			displayFolder: Prévision de charge
			lineageTag: 8e6a9e52-e1e4-492b-a2e6-f0d8c568ca93
			sourceLineageTag: ef88f325-9df9-402b-bf73-1fc5e751159d
			dataCategory: Uncategorized

		measure 'Nbre de visites réalisées' = EXTERNALMEASURE("Nbre de visites réalisées", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Visites
			lineageTag: 425038c0-8487-49f0-9af3-77cfd0340860
			sourceLineageTag: 5598d136-0825-47ee-8bb2-b31f5429b080
			dataCategory: Uncategorized

		measure 'Nbre orientations PDP' = ```
				
				CALCULATE(
				    'Demande consultation spécialisée'[# demandes consultation spécialisée], 
				    'Demande consultation spécialisée - type visite demandée'[Type détaillé visite demandée] = "Cellule Maintien en Emploi"
				)
				```
			formatString: 0
			displayFolder: Orientations
			lineageTag: c7cf4916-68cd-4d32-9856-15c1bf376c0e

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Nbre RDV / Effectif suivi' =
				
				var RDV = [Nombre de RDV]
				var effectif = 'Evolution effectif'[Effectif suivi non intérimaire fin de période]
				
				return
				DIVIDE(
				    RDV,
				    Effectif,
				    0
				    )
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Visites
			lineageTag: 9839f6b7-39da-4428-8586-20759a991c27

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Nbre RDV PDP' = EXTERNALMEASURE("Nbre RDV PDP", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: 5f295ef6-6bab-41c8-8cdb-63b4631749e3
			sourceLineageTag: eb492f93-fd9a-4966-911e-1ac9a4dbe0e0
			dataCategory: Uncategorized

		measure 'Nbre RDV QVCT' = EXTERNALMEASURE("Nbre RDV QVCT", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Consultations Spécialisées\QVCT
			lineageTag: d4cd1a94-3e62-4c12-b40f-7b0b77b133bf
			sourceLineageTag: ad9a3c05-d415-438a-acfa-e1cf8816299c
			dataCategory: Uncategorized

		measure 'Nbre Visites / Effectif suivi' =
				
				var Visites = [Nombre de visites réalisées (RDV)]
				var effectif = 'Evolution effectif'[Effectif suivi non intérimaire fin de période]
				
				return
				DIVIDE(
				    Visites,
				    Effectif,
				    0
				    )
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Visites
			lineageTag: 153eeb8c-1b42-4ad5-860d-19c342e1ec88

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Nbre visites effectuées chez l''adhérent' = EXTERNALMEASURE("Nbre visites effectuées chez l'adhérent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Visites
			lineageTag: 919bc77e-b7d1-4894-b62e-5ba824851cb8
			sourceLineageTag: b09ee39a-11f0-48f0-9628-2794b87e3e8f
			dataCategory: Uncategorized

		measure 'Nom Utilisateur Sélectionné' = EXTERNALMEASURE("Nom Utilisateur Sélectionné", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Divers
			lineageTag: e5cd4f53-34f7-40c7-8981-43a0a2fedcd3
			sourceLineageTag: 762624a4-e940-4616-b4a3-cb900f3cecdf
			dataCategory: Uncategorized

		measure 'Nombre Annulation par le Service' = EXTERNALMEASURE("Nombre Annulation par le Service", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Annulation
			lineageTag: 00b38ccd-9803-46ae-ab63-6feea18726d1
			sourceLineageTag: 4051eace-403f-4a4d-b7e0-6aa5e22a36a9
			dataCategory: Uncategorized

		measure 'Nombre Annulation pour Absence Professionnel de Santé' = EXTERNALMEASURE("Nombre Annulation pour Absence Professionnel de Santé", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Annulation
			lineageTag: 4267f502-6ac7-498c-b06f-3c18fb85d061
			sourceLineageTag: 5b90d428-eb94-4af8-935e-5eb10c9645bf
			dataCategory: Uncategorized

		measure 'Nombre Annulation pour Contraintes de Service' = EXTERNALMEASURE("Nombre Annulation pour Contraintes de Service", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Annulation
			lineageTag: 3a081de4-c203-4c7c-b066-a18ecb92316c
			sourceLineageTag: 9f158f8d-9ee1-4a12-9a01-79e7729e1b30
			dataCategory: Uncategorized

		measure 'Nombre d''AMT terminées (Pénultième mois)' = EXTERNALMEASURE("Nombre d'AMT terminées (Pénultième mois)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: AMT
			lineageTag: d26cd82c-f3d9-484d-a07e-6de9cd73a7c0
			sourceLineageTag: d3ff2f81-2cc4-4e46-bbb7-b7192d42c20d
			dataCategory: Uncategorized

		measure 'Nombre d''embauches PST depuis début de l''année' = ```
				
				VAR DateMaxDansContexte =                                  -- Dernière date visible dans le contexte courant
				    MAX ( 'Date principale'[Date] )
				RETURN
				CALCULATE (                                              -- Recalcule en imposant un filtre YTD sur la table de dates
				    DISTINCTCOUNT ( '1 - salariés PST'[matricule] ),     -- Compte des salariés distincts embauchés
				    DATESYTD ( 'Date principale'[Date], "31/12" ),      -- Fenêtre YTD selon le calendrier; paramètre fin d'année optionnel
				    KEEPFILTERS (                                       -- Conserve les filtres existants et les croise avec YTD
				        'Date principale'[Date] <= DateMaxDansContexte   -- Garantit la borne supérieure au max du contexte (utile si DATESYTD voit plus large)
				    )
				)
				
				```
			formatString: 0
			lineageTag: 78e5928b-8e7b-40b8-bdce-3fb4ec8e1f0a

			changedProperty = Name

		measure 'Nombre d''EPD actives' = EXTERNALMEASURE("Nombre d'EPD actives", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Téléconsultations
			lineageTag: 168665a4-9c26-4a03-a19f-ad9783351f77
			sourceLineageTag: 8dfd0aa2-9a3b-4145-aa97-4ee3b5c3f735
			dataCategory: Uncategorized

		measure 'Nombre d''EPD ayant pratiqué la téléconsultation' = EXTERNALMEASURE("Nombre d'EPD ayant pratiqué la téléconsultation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Téléconsultations
			lineageTag: 010a6e09-23e7-4e77-8cfc-f189338294f1
			sourceLineageTag: ddf224ef-a33d-4d70-a505-ff62bae73416
			dataCategory: Uncategorized

		measure 'Nombre d''IDEST actifs' = EXTERNALMEASURE("Nombre d'IDEST actifs", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Prévision de charge
			lineageTag: 51605501-beda-4f23-a067-b73f65511f1a
			sourceLineageTag: c46fd310-a817-4957-8b24-7a203350a68a
			dataCategory: Uncategorized

		measure 'Nombre de fins de contrat PST YTD' = ```
				
				VAR DateMaxDansContexte =                                     -- Dernière date visible dans le contexte courant (borne supérieure) 
				    MAX ( 'Date principale'[Date] )                           -- Utilise la dimension temps pour caler le "to-date" 
				RETURN
				CALCULATE (                                                   -- Recalcule en appliquant un filtre temps YTD + relation inactive 
				    DISTINCTCOUNT ( '1 - salariés PST'[matricule] ),              -- Comptage distinct des salariés concernés 
				    DATESYTD ( 'Date principale'[Date], "31/12" ),          -- Fenêtre Year-To-Date basée sur le calendrier fiscal (31/12 par défaut) 
				    KEEPFILTERS ( 'Date principale'[Date] <= DateMaxDansContexte ), -- Sécurise la borne supérieure au max visible (to-date)
				    USERELATIONSHIP ( '1 - salariés PST'[Fin de contrat], 'Date principale'[Date] ) -- Active la relation inactive sur Fin contrat le temps du calcul
				)
				-- Description : Compte les salariés PST distincts dont la Fin contrat tombe dans la fenêtre Year-To-Date (selon 'Date principale') jusqu'à la dernière date visible, en activant la relation inactive sur 'Fin contrat' pour que le filtre calendrier s'applique correctement.
				
				```
			formatString: 0
			lineageTag: c9bdfc50-1a6d-40dd-bebe-6c1283c4cf40

			changedProperty = Name

		measure 'Nombre de IDEST' = EXTERNALMEASURE("Nombre de IDEST", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Téléconsultations
			lineageTag: c18346b2-1ae3-4df1-ae35-7c3de2501b51
			sourceLineageTag: b57552b7-1768-4b93-b3f2-40f958ad044a
			dataCategory: Uncategorized

		measure 'Nombre de IDEST ayant pratiqué la téléconsultation' = EXTERNALMEASURE("Nombre de IDEST ayant pratiqué la téléconsultation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Téléconsultations
			lineageTag: e856a832-3616-46ec-b07d-2a3414d70c83
			sourceLineageTag: 2d6bb7d8-3c98-46ef-81cd-a6ba0661574d
			dataCategory: Uncategorized

		measure 'Nombre de médecins' = EXTERNALMEASURE("Nombre de médecins", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Téléconsultations
			lineageTag: a2f2fdec-2acf-4f63-b435-9f9aeb9f3a0e
			sourceLineageTag: c7021684-e17d-475c-865b-ca35a5236595
			dataCategory: Uncategorized

		measure 'Nombre de Médecins actifs' = EXTERNALMEASURE("Nombre de Médecins actifs", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Prévision de charge
			lineageTag: 9ea365f0-0e64-479d-b6e1-75b52eec6780
			sourceLineageTag: 79f5880c-f3aa-453b-a5ee-886a530e9583
			dataCategory: Uncategorized

		measure 'Nombre de médecins ayant pratiqué la téléconsultation' = EXTERNALMEASURE("Nombre de médecins ayant pratiqué la téléconsultation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Téléconsultations
			lineageTag: cda97bba-84ef-481f-8f26-2bd08f9c55cc
			sourceLineageTag: 9ae3bfa9-f246-44c8-810b-917663ad2f76
			dataCategory: Uncategorized

		measure 'Nombre de téléconsultations' = EXTERNALMEASURE("Nombre de téléconsultations", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Téléconsultations
			lineageTag: f9bf4624-b06f-4d0d-8c2a-6648791fbe1c
			sourceLineageTag: 6df1d929-f43f-47d2-a413-b37488204882
			dataCategory: Uncategorized

		measure 'Nombre de visites (Mois dernier)' = EXTERNALMEASURE("Nombre de visites (Mois dernier)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Visites
			lineageTag: c3f5c7f8-1b50-4048-a446-75dbf7e1368b
			sourceLineageTag: 61e4f46c-6a02-474c-8700-eca6b3450f48
			dataCategory: Uncategorized

		measure 'Nombre de visites (Pénultième mois)' = EXTERNALMEASURE("Nombre de visites (Pénultième mois)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Visites
			lineageTag: d7f150e1-9a07-43fd-b4d9-9da90ed71703
			sourceLineageTag: 6f9ce774-48df-4a4d-a4e1-e0477e0914fe
			dataCategory: Uncategorized

		measure 'Nombre de visites de pré-reprise' = EXTERNALMEASURE("Nombre de visites de pré-reprise", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Visites
			lineageTag: 52df09ba-9912-4ecb-8117-ee2be4a7fd45
			sourceLineageTag: 6aeace39-a91a-4717-9b18-4f682d7d2fd1
			dataCategory: Uncategorized

		measure 'Nombre de visites IDEST' = EXTERNALMEASURE("Nombre de visites IDEST", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Visites
			lineageTag: 8802988f-4af3-4bb5-b902-d788a0ee229e
			sourceLineageTag: 6b5d4c7a-ba22-4dd7-b758-b3cef07016de
			dataCategory: Uncategorized

		measure 'Nombre de visites intérimaires IDEST (12 derniers mois)' = EXTERNALMEASURE("Nombre de visites intérimaires IDEST (12 derniers mois)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Prévision de charge
			lineageTag: bf6520da-47c2-436d-908b-a530b5210447
			sourceLineageTag: a7b382a8-9c9f-4542-8849-4cb14ea30b92
			dataCategory: Uncategorized

		measure 'Nombre de visites intérimaires Médecin (12 derniers mois)' = EXTERNALMEASURE("Nombre de visites intérimaires Médecin (12 derniers mois)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Prévision de charge
			lineageTag: 1d8d6e66-ed8e-4ca9-b803-b35eb1039c6a
			sourceLineageTag: 07ac53eb-4898-43a3-bc3b-c70c2371821c
			dataCategory: Uncategorized

		measure 'Nombre de visites médecin' = EXTERNALMEASURE("Nombre de visites médecin", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Visites
			lineageTag: 0fe7a6fc-19b2-4095-9272-bf7bd4ab978c
			sourceLineageTag: 518d57ea-8ba9-4e18-9c52-550cc35ee50e
			dataCategory: Uncategorized

		measure 'Nombre de visites mois N-12 (mois complet)' = EXTERNALMEASURE("Nombre de visites mois N-12 (mois complet)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Visites
			lineageTag: 240efedf-503a-40ad-9e4c-d43c3c127c3c
			sourceLineageTag: 3cd1a99b-fb6f-4043-afb0-e9c4e9213d64
			dataCategory: Uncategorized

		measure 'Nombre de visites occasionnelles Médecin (12 derniers mois)' = EXTERNALMEASURE("Nombre de visites occasionnelles Médecin (12 derniers mois)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Prévision de charge
			lineageTag: c13a5ea6-4864-443f-a4e3-d28dea57d04a
			sourceLineageTag: 3a1c9300-fcc1-45aa-baf7-fe050e5ef7a6
			dataCategory: Uncategorized

		measure 'Nombre de visites PDP' = EXTERNALMEASURE("Nombre de visites PDP", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Visites
			lineageTag: 19eb4c65-6bc2-4cca-a355-a793188e03a6
			sourceLineageTag: 69d1859d-0e73-41ad-8dbe-74bb7fcee799
			dataCategory: Uncategorized

		measure 'Nombre de visites PDP 2' = EXTERNALMEASURE("Nombre de visites PDP 2", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Visites
			lineageTag: c34b390c-ee52-4e47-977c-ff1534d3b1ab
			sourceLineageTag: 07b58c9e-2d06-4602-941a-7170bda9e71c
			dataCategory: Uncategorized

		measure 'Nombre Moyen Entretiens PDP par Mois' = EXTERNALMEASURE("Nombre Moyen Entretiens PDP par Mois", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: f87f515b-d645-472e-9150-46c5047bfc62
			sourceLineageTag: fb2344a1-752a-4acd-8a25-cf413fede6e4
			dataCategory: Uncategorized

		measure 'Nombre Moyen Entretiens QVCT par Mois' = EXTERNALMEASURE("Nombre Moyen Entretiens QVCT par Mois", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Consultations Spécialisées\QVCT
			lineageTag: ac116930-8462-48fe-97f0-06e9689278e1
			sourceLineageTag: 03ccf627-e2e4-42b1-bfbd-fd31f059bb75
			dataCategory: Uncategorized

		measure 'nouveaux adhérents' =
				
				var Aujourdhui = Max('Date principale'[Date])
				var NouveauxAdherents = CALCULATE(
				                            [Nombre d'adhérents actifs ou suspendus],
				                            'Adhérent (actuel)'[Date création dossier entreprise] - Aujourdhui < 365
				)
				
				RETURN
				NouveauxAdherents
			formatString: 0
			displayFolder: FE
			lineageTag: 2914a2df-2ea9-4947-80b1-4ae11384700e

			changedProperty = DisplayFolder

			changedProperty = Name

		measure ObjectifPct = DIVIDE(SELECTEDVALUE('Objectif (%)'[Objectif (%)], 100), 100)
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: FE\Simulation
			lineageTag: e416c982-02dd-4925-ba39-abe2f996ab5a

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Part des EPD ayant pratiqué la téléconsultation' = EXTERNALMEASURE("Part des EPD ayant pratiqué la téléconsultation", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0\ %;-0\ %;0\ %
			displayFolder: Téléconsultations
			lineageTag: 44d1ac14-bbb9-4d1e-9df3-516da271b8d6
			sourceLineageTag: a2442a06-ba6c-4d2e-b5f0-8b46b37eba7d
			dataCategory: Uncategorized

		measure 'Part des IDEST ayant pratiqué la téléconsultation' = EXTERNALMEASURE("Part des IDEST ayant pratiqué la téléconsultation", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0\ %;-0\ %;0\ %
			displayFolder: Téléconsultations
			lineageTag: 503f0fa7-8afa-4ab7-856d-ca4311b8b8c9
			sourceLineageTag: c2f59cff-b869-4e4b-bd2c-0b556e6c1fdc
			dataCategory: Uncategorized

		measure 'Part des médecins ayant pratiqué la téléconsultation' = EXTERNALMEASURE("Part des médecins ayant pratiqué la téléconsultation", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0\ %;-0\ %;0\ %
			displayFolder: Téléconsultations
			lineageTag: 72e1cf54-5e37-40b2-8ddc-b015cbd0f0c0
			sourceLineageTag: 59be91dd-3885-43f4-8063-30bf4c636296
			dataCategory: Uncategorized

		measure 'Part des téléconsultations' = EXTERNALMEASURE("Part des téléconsultations", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Téléconsultations
			lineageTag: 0b208749-8c4b-4c31-96e7-46917631cdb5
			sourceLineageTag: c3e66aac-6489-4b64-8ace-c8424b48d218
			dataCategory: Uncategorized

		/// Affiche le numéro de l'avant dernière semaine
		measure 'Pénultième Semaine' = EXTERNALMEASURE("Pénultième Semaine", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Date
			lineageTag: 79e750c8-48d0-4db1-95da-c3e9179fcf3f
			sourceLineageTag: 178165c5-9af0-4a20-8247-1c76fdb97bc6
			dataCategory: Uncategorized

		/// Affiche les infos ssuivantes au sujet de l'avant dernière semaine:
		/// Semaine n°.... : lundi x ...... - dimanche y ........
		measure 'Pénultième Semaine détaillée' = EXTERNALMEASURE("Pénultième Semaine détaillée", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Date
			lineageTag: d0f13276-36b8-460e-bd7d-e2e1c4d228de
			sourceLineageTag: e49ff8ef-463b-426a-838f-48c1853e595e
			dataCategory: Uncategorized

		measure 'Période (Du au)' =
				
				Var DateMax = Max('Date principale'[Date])
				Var DateMin = Min('Date principale'[Date])
				
				RETURN
				format(DateMin,"DD mmmm YYYY", "fr-FR")&" au "&format(DateMax,"DD mmmm YYYY", "fr-FR")
			displayFolder: Date
			lineageTag: 4fd4a2b3-0129-4169-9b82-e3707de61ee6

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Plage Max Axe Y PDP' = EXTERNALMEASURE("Plage Max Axe Y PDP", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Orientations
			lineageTag: 63f07470-f3ec-4920-910e-4aba5d30025e
			sourceLineageTag: 4ed9ec56-d2f4-4e97-b647-80718fddfc3d
			dataCategory: Uncategorized

		measure 'Plans MEE avec maintien au poste' = ```
				
				CALCULATE(
				    'Plan MEE'[# plans MEE], 
				    'Plan MEE - informations'[Situation salarié après plan MEE] in {"En poste avec aménagement (dans l'entreprise initiale)","En poste sans aménagement (dans l'entreprise initiale)"}
				 )
				```
			formatString: 0
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: 6d1a0a7f-9758-4b8f-bf00-89e229f51de9

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Plans MEE avec maintien dans l''emploi' = ```
				
				CALCULATE(
				    'Plan MEE'[# plans MEE], 
				    'Plan MEE - informations'[Catégorie résultat plan MEE] = "Avec maintien en emploi" 
				 )
				```
			formatString: 0
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: 7652f95e-b521-4166-9f15-d6159b9cab4b

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Plans MEE avec reclassement' = ```
				
				CALCULATE(
				    'Plan MEE'[# plans MEE], 
				    'Plan MEE - informations'[Situation salarié après plan MEE] in {"Reclassé en interne (dans l'entreprise initiale)","Reclassé en externe (hors de l'entreprise initiale)"}
				 )
				```
			formatString: 0
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: ce58395c-0759-4316-92d0-c4b2f8e821d3

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Plans MEE refusé par le salarié' = ```
				
				CALCULATE(
				    'Plan MEE'[# plans MEE], 
				    'Plan MEE - dispositifs'[Motif de non réalisation du dispositif] = "Refus du salarié"
				)
				```
			formatString: 0
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: 424c2929-e912-41b6-847a-053fde39547b

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Plans MEE sans solution' = ```
				
				CALCULATE(
				    'Plan MEE'[# plans MEE], 
				    'Plan MEE - informations'[SOUS-catégorie résultat plan MEE] = "Sans solution" 
				 )
				```
			formatString: 0
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: 768857d3-1905-40ad-8264-3207e964aca1

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Ratio AMT Centre' = EXTERNALMEASURE("Ratio AMT Centre", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0\ %;-0.0\ %;0.0\ %
			displayFolder: AMT
			lineageTag: 8169d50d-fc0e-43c3-98ab-412a9ac6c694
			sourceLineageTag: 0d16fbfd-1545-4515-b7e7-c9fb0f5be5e5
			dataCategory: Uncategorized

		measure 'Ratio AMT Grand Nord' = EXTERNALMEASURE("Ratio AMT Grand Nord", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0\ %;-0.0\ %;0.0\ %
			displayFolder: AMT
			lineageTag: 456281a2-af0f-4ca0-a60d-f861d9ad5132
			sourceLineageTag: 115f3a69-7a42-4c98-93d3-bee13ce2445d
			dataCategory: Uncategorized

		measure 'Ratio AMT Nord' = EXTERNALMEASURE("Ratio AMT Nord", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0\ %;-0.0\ %;0.0\ %
			displayFolder: AMT
			lineageTag: d2dc4a6e-9a35-48e1-981a-02da123f8eff
			sourceLineageTag: 77bfe700-ce06-41b4-991b-336d915d44d4
			dataCategory: Uncategorized

		measure 'Ratio AMT Sud Est' = EXTERNALMEASURE("Ratio AMT Sud Est", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0\ %;-0.0\ %;0.0\ %
			displayFolder: AMT
			lineageTag: b8f60705-91c5-4658-a4c2-1b6027b3ee9d
			sourceLineageTag: c58e690c-b9c7-461d-995b-7ef117a451b5
			dataCategory: Uncategorized

		measure 'Ratio AMT Sud Ouest' = EXTERNALMEASURE("Ratio AMT Sud Ouest", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0\ %;-0.0\ %;0.0\ %
			displayFolder: AMT
			lineageTag: 716a0dc9-5e4f-4c3e-ba53-5e72e926ccd5
			sourceLineageTag: 4ec7536c-fc09-403c-af85-1f526b695b40
			dataCategory: Uncategorized

		measure 'Ratio maintien au poste / plan MEE' =
				
				DIVIDE(
				    [Plans MEE avec maintien au poste],
				    'Plan MEE'[# plans MEE],
				    0
				)
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: cf796004-bdd7-40d8-ae3c-96650e7895ea

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Ratio maintien dans l''emploi / plan MEE' =
				
				DIVIDE(
				    [Plans MEE avec maintien dans l'emploi],
				    'Plan MEE'[# plans MEE],
				    0
				)
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: 0b5529e2-a01e-43c3-8df7-5d803fb08c38

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Ratio plan MEE sans solution / plan MEE' =
				
				DIVIDE(
				    [Plans MEE sans solution],
				    'Plan MEE'[# plans MEE],
				    0
				)
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: 82eda09b-6c7c-443f-8e86-45d30449f910

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Ratio reclassement / plan MEE' =
				
				DIVIDE(
				    [Plans MEE avec reclassement],
				    'Plan MEE'[# plans MEE],
				    0
				)
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: 62117a97-25af-4d77-8d7b-c9e72c11736d

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Ratio refus du salarié / plan MEE' =
				
				DIVIDE(
				    [Plans MEE refusé par le salarié],
				    'Plan MEE'[# plans MEE],
				    0
				)
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Consultations Spécialisées\PDP
			lineageTag: 960d71b3-e091-4845-8305-1f2f8e58b004

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Ratio visite / temps' = EXTERNALMEASURE("Ratio visite / temps", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Temps de travail
			lineageTag: c2c63760-aa7f-486b-aad5-012c9f4eba2a
			sourceLineageTag: 92a2b117-21d8-41a9-bcaf-1a7b5c69e589
			dataCategory: Uncategorized

		measure 'Ratio Visites (Équipe Médicale)' = EXTERNALMEASURE("Ratio Visites (Équipe Médicale)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Visites
			lineageTag: b3fa0730-1510-404d-a202-499945c0eec0
			sourceLineageTag: d508f010-977f-466a-892e-022803c03471
			dataCategory: Uncategorized

		measure 'RDV / effectif Evol vs last year' = ```
				
				VAR TxConvoc_Period = [Nbre RDV / Effectif suivi]  // Mesure de la période courante; utilisée comme numérateur de la variation 
				VAR TxConvoc_LastYear = [RDV / effectif SameLastYear]  // Mesure de la période N-1; dénominateur et référence de comparaison 
				VAR Evolution_Proportion =  // Variation relative propre, gère les divisions par zéro via DIVIDE 
				    DIVIDE( TxConvoc_Period - TxConvoc_LastYear, TxConvoc_LastYear, 0 )
				VAR Signe_Affichage =  // Préfixe du signe basé sur 0 car la variation est une proportion (positif/négatif) 
				    IF( Evolution_Proportion >= 0, "+ ", "- " )
				VAR Valeur_Pourcent_Formattee =  // Mise en forme en pourcentage avec une décimale, appliquée sur la valeur absolue pour éviter un double signe 
				    FORMAT( ABS(Evolution_Proportion), "0.00 %" )
				RETURN
				    "("&Signe_Affichage & Valeur_Pourcent_Formattee&")"  // Sortie texte: utile pour cartes/étiquettes; préférer garder une version numérique pour analyses 
				
				/*
				Rôle de la mesure:
				- Produit un affichage texte de l’évolution des RDV vs N-1 avec signe explicite, ex: "+ 12,3%" ou "- 4,5%".
				- Le calcul de variation utilise DIVIDE pour la robustesse et sépare calcul (proportion) et présentation (signe/format).
				- Pour analyses et agrégations, utiliser en priorité une version numérique: RDV Evol vs last year (num), avec un format dynamique “+0.0%;-0.0%;0.0%”.
				*/ 
				
				```
			displayFolder: Visites
			lineageTag: aeb4342a-c613-45d3-a2e1-849814b562e3

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'RDV / effectif SameLastYear' = ```
				
				VAR ContexteDatesActuel = VALUES('Date principale'[Date]) // Garantit que l’on décale exactement le set de dates du visuel sans altérer d’autres filtres
				
				RETURN
				CALCULATE(
				[Nbre RDV / Effectif suivi],                            // Utilise la mesure source telle quelle
				DATEADD(ContexteDatesActuel, -1, YEAR)      // Décale la période d’un an en arrière, équivalent à SAMEPERIODLASTYEAR mais explicite et flexible
				) 
				
				// Rôle: calcule les RDV pour la même période de l’année précédente, en respectant le grain (jour/mois/trimestre) et les filtres actifs de la table de dates, sans supprimer ces filtres
				```
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Visites
			lineageTag: 071ccfa1-d27b-46ae-a5a0-feadd2259f32

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'RDV Evol vs last year' = ```
				
				VAR RDV_Period = [Nombre de RDV]  // Mesure de la période courante; utilisée comme numérateur de la variation 
				VAR RDV_LastYear = [RDV SameLastYear]  // Mesure de la période N-1; dénominateur et référence de comparaison 
				VAR Evolution_Proportion =  // Variation relative propre, gère les divisions par zéro via DIVIDE 
				    DIVIDE( RDV_Period - RDV_LastYear, RDV_LastYear, 0 )
				VAR Signe_Affichage =  // Préfixe du signe basé sur 0 car la variation est une proportion (positif/négatif) 
				    IF( Evolution_Proportion >= 0, "+ ", "- " )
				VAR Valeur_Pourcent_Formattee =  // Mise en forme en pourcentage avec une décimale, appliquée sur la valeur absolue pour éviter un double signe 
				    FORMAT( ABS(Evolution_Proportion), "0.00 %" )
				RETURN
				    "("&Signe_Affichage & Valeur_Pourcent_Formattee&")"  // Sortie texte: utile pour cartes/étiquettes; préférer garder une version numérique pour analyses 
				
				/*
				Rôle de la mesure:
				- Produit un affichage texte de l’évolution des RDV vs N-1 avec signe explicite, ex: "+ 12,3%" ou "- 4,5%".
				- Le calcul de variation utilise DIVIDE pour la robustesse et sépare calcul (proportion) et présentation (signe/format).
				- Pour analyses et agrégations, utiliser en priorité une version numérique: RDV Evol vs last year (num), avec un format dynamique “+0.0%;-0.0%;0.0%”.
				*/ 
				
				```
			displayFolder: Visites
			lineageTag: 21c6ca7a-d539-408d-b352-be264db47bbe

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'RDV SameLastYear' = ```
				
				VAR ContexteDatesActuel = VALUES('Date principale'[Date]) // Garantit que l’on décale exactement le set de dates du visuel sans altérer d’autres filtres
				
				RETURN
				CALCULATE(
				[Nombre de RDV],                            // Utilise la mesure source telle quelle
				DATEADD(ContexteDatesActuel, -1, YEAR)      // Décale la période d’un an en arrière, équivalent à SAMEPERIODLASTYEAR mais explicite et flexible
				) 
				
				// Rôle: calcule les RDV pour la même période de l’année précédente, en respectant le grain (jour/mois/trimestre) et les filtres actifs de la table de dates, sans supprimer ces filtres
				```
			formatString: #,0
			displayFolder: Visites
			lineageTag: 15b54d8f-b2e8-40d5-8744-8215c7df7824

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Semaine derniere détaillée' = EXTERNALMEASURE("Semaine derniere détaillée", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Date
			lineageTag: a8c789ed-3336-4165-b258-dad347cbb952
			sourceLineageTag: 8d932028-77be-4d12-9c31-2d5e8aecb9e6
			dataCategory: Uncategorized

		measure Signalements = EXTERNALMEASURE("Signalements", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Orientations
			lineageTag: e0f44cd5-3099-4143-a49e-f5e058842b2e
			sourceLineageTag: a6c9e21e-943c-464c-aed4-f3efaaf169ba
			dataCategory: Uncategorized

		measure 'Sous Titre Adhérents sans FE en date du' =
				
				Var DateMax = Max('Date principale'[Date])
				
				RETURN
				"Adhérents sans FE en date du " & format(DateMax,"DD mmmm YYYY", "fr-FR")
			displayFolder: Titres
			lineageTag: a7078c36-9636-4a86-806f-36384ccd956f

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Sous-titre adhérents à jour d''APP' =
				
				Var DateMax = Max('Date principale'[Date])
				Var DateMin = DateMax - 365.25*4 + 1
				
				RETURN
				"Adhérents ayant bénéficié d'une APP entre le "& format(DateMin,"DD mmmm YYYY", "fr-FR")& " et le " & format(DateMax,"DD mmmm YYYY", "fr-FR")
			displayFolder: Titres
			lineageTag: 43b52a30-cffb-460b-9287-e71c4c2ed064

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Sous-titre adhérents en retard d''APP' =
				
				Var DateMax = Max('Date principale'[Date])
				Var DateMin = DateMax - 365.25*4 + 1
				
				RETURN
				"Adhérents n'ayant pas bénéficié d'APP entre le "& format(DateMin,"DD mmmm YYYY", "fr-FR")& " et le " & format(DateMax,"DD mmmm YYYY", "fr-FR")
			displayFolder: Titres
			lineageTag: 07f38bd3-0948-4334-a51a-633c2c79ae7c

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Sous-titre adhérents FE à mettre à jour' =
				
				Var DateMax = Max('Date principale'[Date])-365
				
				RETURN
				"Adhérents dont la FE n'est pas à jour en date du "& format(DateMax,"DD mmmm YYYY", "fr-FR")&"."
			displayFolder: Titres
			lineageTag: ee8e82f1-0ae4-48e0-a978-a01cc992a275

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Sous-titre adhérents sans FE' =
				
				Var DateMax = Max('Date principale'[Date])-365
				
				RETURN
				"Adhérents sans FE dont la date de premier statut actif est supérieure au "& format(DateMax,"DD mmmm YYYY", "fr-FR")&". Non impacté par le filtre de dates."
			displayFolder: Titres
			lineageTag: 9bb486ba-d525-4f87-8459-f9a3e97896ad

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Taux Annulation IDEST' = EXTERNALMEASURE("Taux Annulation IDEST", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0\ %;-0.0\ %;0.0\ %
			displayFolder: Absentéisme
			lineageTag: 0b90183b-9e11-401e-9f60-5184b1931c40
			sourceLineageTag: 228934f7-8927-4029-a963-58b41f25514e
			dataCategory: Uncategorized

		measure 'Taux Annulation IDEST (Tout PST38)' = EXTERNALMEASURE("Taux Annulation IDEST (Tout PST38)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Absentéisme
			lineageTag: e76505ea-645d-4301-ab60-9904b59c8b39
			sourceLineageTag: d83be82b-1f07-4b0f-b5f9-e771315fe411
			dataCategory: Uncategorized

		measure 'Taux Annulation Médecin' = EXTERNALMEASURE("Taux Annulation Médecin", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0\ %;-0.0\ %;0.0\ %
			displayFolder: Absentéisme
			lineageTag: 290801a9-2b01-47e1-a0b0-b4da0b27fd19
			sourceLineageTag: 9daced4c-20ba-43a0-83b0-95812cb4a768
			dataCategory: Uncategorized

		measure 'Taux d''annexes 4 Evol vs last year' = ```
				
				VAR Visites_Period = [Taux d'Annexes4]  // Mesure de la période courante; utilisée comme numérateur de la variation 
				VAR Visites_LastYear = [Taux d'annexes 4 SameLastYear]  // Mesure de la période N-1; dénominateur et référence de comparaison 
				VAR Evolution_Proportion =  // Variation relative propre, gère les divisions par zéro via DIVIDE 
				    DIVIDE( Visites_Period - Visites_LastYear, Visites_LastYear, 0 )
				VAR Signe_Affichage =  // Préfixe du signe basé sur 0 car la variation est une proportion (positif/négatif) 
				    IF( Evolution_Proportion >= 0, "+ ", "- " )
				VAR Valeur_Pourcent_Formattee =  // Mise en forme en pourcentage avec une décimale, appliquée sur la valeur absolue pour éviter un double signe 
				    FORMAT( ABS(Evolution_Proportion), "0.00 %" )
				RETURN
				    "("&Signe_Affichage & Valeur_Pourcent_Formattee&")"  // Sortie texte: utile pour cartes/étiquettes; préférer garder une version numérique pour analyses 
				
				/*
				Rôle de la mesure:
				- Produit un affichage texte de l’évolution des visites vs N-1 avec signe explicite, ex: "+ 12,3%" ou "- 4,5%".
				- Le calcul de variation utilise DIVIDE pour la robustesse et sépare calcul (proportion) et présentation (signe/format).
				- Pour analyses et agrégations, utiliser en priorité une version numérique: Visites Evol vs last year (num), avec un format dynamique “+0.0%;-0.0%;0.0%”.
				*/ 
				
				```
			displayFolder: Visites
			lineageTag: 246c3427-c464-4b3f-8624-ebc77f587e33

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Taux d''annexes 4 SameLastYear' = ```
				
				VAR ContexteDatesActuel = VALUES('Date principale'[Date]) // Garantit que l’on décale exactement le set de dates du visuel sans altérer d’autres filtres
				
				RETURN
				CALCULATE(
				[Taux d'Annexes4],                            // Utilise la mesure source telle quelle
				DATEADD(ContexteDatesActuel, -1, YEAR)      // Décale la période d’un an en arrière, équivalent à SAMEPERIODLASTYEAR mais explicite et flexible
				) 
				
				// Rôle: calcule les RDV pour la même période de l’année précédente, en respectant le grain (jour/mois/trimestre) et les filtres actifs de la table de dates, sans supprimer ces filtres
				```
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Visites
			lineageTag: 03f7175a-877c-4f51-a090-a3905393f8ba

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Taux d''Annexes4' = ```
				
				VAR NombreVisitesRealisees = [Nombre de visites réalisées (RDV)] -- Variable pour stocker le nombre de visites réalisées
				VAR NombreAnnexes4 = [Nbre annexes 4] -- Variable pour stocker le nombre total de Annexes4
				
				RETURN
				    COALESCE(
				        DIVIDE(
				        NombreAnnexes4, --  nombre total de convocations
				        NombreVisitesRealisees, -- nombre de visites réalisées
				        0 -- Valeur de retour en cas de division par zéro
				    ),
				    0
				    )
				
				-- Cette mesure calcule le taux de convocations en divisant le nombre de visites réalisées
				-- par le nombre total de convocations. Elle utilise DIVIDE pour éviter les erreurs de division par zéro.
				
				```
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Visites
			lineageTag: 9a68ea0e-06e6-4fc6-b93d-0d2c5fc71986

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Taux d''annulation non excusée' = EXTERNALMEASURE("Taux d'annulation non excusée", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0\ %;-0.0\ %;0.0\ %
			displayFolder: Annulation
			lineageTag: 6c4f1aef-b588-43e1-821f-1d1e56deef7e
			sourceLineageTag: d06f40e0-e7bd-4dca-8728-ddae52ba5bfd
			dataCategory: Uncategorized

		measure 'Taux d''inaptitude' = ```
				
				VAR NombreVisitesRealisees = [Nombre de visites réalisées (RDV)] -- Variable pour stocker le nombre de visites réalisées
				VAR NombreInaptitude = [Nombre d'avis d'inaptitude] -- Variable pour stocker le nombre total de Inaptitude
				
				RETURN
				    COALESCE(
				        DIVIDE(
				        NombreInaptitude, --  nombre total de convocations
				        NombreVisitesRealisees, -- nombre de visites réalisées
				        0 -- Valeur de retour en cas de division par zéro
				    ),
				    0
				    )
				
				-- Cette mesure calcule le taux de convocations en divisant le nombre de visites réalisées
				-- par le nombre total de convocations. Elle utilise DIVIDE pour éviter les erreurs de division par zéro.
				
				```
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Visites
			lineageTag: fe19721b-d869-48d5-8437-d0fe20016e84

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Taux d''inaptitude Evol vs last year' = ```
				
				VAR Visites_Period = [Taux d'inaptitude]  // Mesure de la période courante; utilisée comme numérateur de la variation 
				VAR Visites_LastYear = [Taux d'inaptitude SameLastYear]  // Mesure de la période N-1; dénominateur et référence de comparaison 
				VAR Evolution_Proportion =  // Variation relative propre, gère les divisions par zéro via DIVIDE 
				    DIVIDE( Visites_Period - Visites_LastYear, Visites_LastYear, 0 )
				VAR Signe_Affichage =  // Préfixe du signe basé sur 0 car la variation est une proportion (positif/négatif) 
				    IF( Evolution_Proportion >= 0, "+ ", "- " )
				VAR Valeur_Pourcent_Formattee =  // Mise en forme en pourcentage avec une décimale, appliquée sur la valeur absolue pour éviter un double signe 
				    FORMAT( ABS(Evolution_Proportion), "0.00 %" )
				RETURN
				    "("&Signe_Affichage & Valeur_Pourcent_Formattee&")"  // Sortie texte: utile pour cartes/étiquettes; préférer garder une version numérique pour analyses 
				
				/*
				Rôle de la mesure:
				- Produit un affichage texte de l’évolution des visites vs N-1 avec signe explicite, ex: "+ 12,3%" ou "- 4,5%".
				- Le calcul de variation utilise DIVIDE pour la robustesse et sépare calcul (proportion) et présentation (signe/format).
				- Pour analyses et agrégations, utiliser en priorité une version numérique: Visites Evol vs last year (num), avec un format dynamique “+0.0%;-0.0%;0.0%”.
				*/ 
				
				```
			displayFolder: Visites
			lineageTag: e18357e5-bc95-4e68-99ce-24fb2c892cfd

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Taux d''inaptitude SameLastYear' = ```
				
				VAR ContexteDatesActuel = VALUES('Date principale'[Date]) // Garantit que l’on décale exactement le set de dates du visuel sans altérer d’autres filtres
				
				RETURN
				CALCULATE(
				[Taux d'inaptitude],                            // Utilise la mesure source telle quelle
				DATEADD(ContexteDatesActuel, -1, YEAR)      // Décale la période d’un an en arrière, équivalent à SAMEPERIODLASTYEAR mais explicite et flexible
				) 
				
				// Rôle: calcule les RDV pour la même période de l’année précédente, en respectant le grain (jour/mois/trimestre) et les filtres actifs de la table de dates, sans supprimer ces filtres
				```
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Visites
			lineageTag: 8141a8c8-e5f6-4532-9357-c97f056af053

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Taux d''orientations PDP' = ```
				
				VAR NombreVisitesRealisees = [Nombre de visites réalisées (RDV)] -- Variable pour stocker le nombre de visites réalisées
				VAR NombreOrientationsPDP = [Nbre orientations PDP] -- Variable pour stocker le nombre total de Orientations PDP
				
				RETURN
				    COALESCE(
				        DIVIDE(
				        NombreOrientationsPDP, --  nombre total de convocations
				        NombreVisitesRealisees, -- nombre de visites réalisées
				        0 -- Valeur de retour en cas de division par zéro
				    ),
				    0
				    )
				
				-- Cette mesure calcule le taux de convocations en divisant le nombre de visites réalisées
				-- par le nombre total de convocations. Elle utilise DIVIDE pour éviter les erreurs de division par zéro.
				
				```
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Visites
			lineageTag: 2889196e-e02e-48fd-8400-d5827f4cb955

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Taux de convocation SameLastYear' = ```
				
				VAR ContexteDatesActuel = VALUES('Date principale'[Date]) // Garantit que l’on décale exactement le set de dates du visuel sans altérer d’autres filtres
				
				RETURN
				CALCULATE(
				[Taux de convocations],                            // Utilise la mesure source telle quelle
				DATEADD(ContexteDatesActuel, -1, YEAR)      // Décale la période d’un an en arrière, équivalent à SAMEPERIODLASTYEAR mais explicite et flexible
				) 
				
				// Rôle: calcule les RDV pour la même période de l’année précédente, en respectant le grain (jour/mois/trimestre) et les filtres actifs de la table de dates, sans supprimer ces filtres
				```
			displayFolder: Visites
			lineageTag: 51ca9d43-e10f-420d-a04b-479b19dee1ae

			changedProperty = DisplayFolder

			changedProperty = Name

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		measure 'Taux de convocations' = ```
				
				VAR NombreVisitesRealisees = [Nombre de visites réalisées (RDV)] -- Variable pour stocker le nombre de visites réalisées
				VAR NombreConvocations = [Nombre de RDV avec convocation] -- Variable pour stocker le nombre total de convocations
				
				RETURN
				    COALESCE(
				        DIVIDE(
				        NombreConvocations, --  nombre total de convocations
				        NombreVisitesRealisees, -- nombre de visites réalisées
				        0 -- Valeur de retour en cas de division par zéro
				    ),
				    0
				    )
				
				-- Cette mesure calcule le taux de convocations en divisant le nombre de visites réalisées
				-- par le nombre total de convocations. Elle utilise DIVIDE pour éviter les erreurs de division par zéro.
				
				```
			formatString: 0.00
			displayFolder: Visites
			lineageTag: be02f609-e699-4357-b77b-adec8e71732c

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Taux de convocations 2' = EXTERNALMEASURE("Taux de convocations", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00
			displayFolder: Visites
			lineageTag: 21a47fd7-8d81-4892-a81c-16d5b4284453
			sourceLineageTag: 8b5ad6b5-0358-4616-b62f-2a7dc4e3d8b8
			dataCategory: Uncategorized

		/// Plutôt que d'afficher le taux de retard, affichons du positif avec le taux de service représentant le % de salariés à jour de visites
		measure 'Taux de service' = EXTERNALMEASURE("Taux de service", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0\ %;-0.0\ %;0.0\ %
			displayFolder: Taux de service
			lineageTag: d55c1b91-ef48-4ab5-884b-0a21f4475061
			sourceLineageTag: f7d52d6e-55c7-4bec-a94e-fd2b4491389d
			dataCategory: Uncategorized

			changedProperty = DisplayFolder

		measure 'Taux de service (Passé uniquement)' = ```
				
				VAR DateCourante = SELECTEDVALUE('Dates_Futur'[Date])
				RETURN
				    IF(
				        DateCourante <= TODAY(),
				        CALCULATE(
				            [Taux de service coalesce],
				            TREATAS(
				                VALUES('Dates_Futur'[Date]),
				                'Date principale'[Date]
				            )
				        ),
				        BLANK()
				    )
				
				```
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Taux de service\Simulation
			lineageTag: 29935ba3-607e-4c25-b6d3-32f4fc12b397

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Taux de Service (tout PST38)' = EXTERNALMEASURE("Taux de Service (tout PST38)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Taux de service
			lineageTag: fdc4fa08-aae7-4deb-8e5a-83bac56a3a31
			sourceLineageTag: 348ab1be-a0f5-4e15-84da-acfb32534659
			dataCategory: Uncategorized

			changedProperty = DisplayFolder

		measure 'Taux de service coalesce' = ```
				
				VAR TauxRetard = [Taux de retard] // Stocke la valeur de la mesure [Taux de retard]
				VAR TauxService = 1 - TauxRetard // Calcule le taux de service en soustrayant le taux de retard de 1
				
				RETURN
				     COALESCE(
				      IF(
				      ISBLANK(TauxRetard), // Vérifie si la valeur du taux de retard est vide
				      1, // Retourne une valeur vide si le taux de retard est vide
				      IF(
				          TauxService = 1, // Vérifie si le taux de service est égal à 1 (100%)
				          1, // Retourne une valeur vide si le taux de service est égal à 100%
				          TauxService // Retourne le taux de service calculé
				      )
				  ),
				  ""
				  )
				
				/*
				Description :
				Cette mesure calcule le taux de service en soustrayant le taux de retard de 1.
				Elle utilise une variable pour stocker la valeur de [Taux de retard] et une condition IF pour vérifier si la valeur est vide ou si le taux de service est égal à 100%.
				Si le taux de retard est vide ou si le taux de service est égal à 100%, la mesure retourne une valeur vide.
				*/
				
				```
			displayFolder: Taux de service
			lineageTag: 0d0b213b-f9ed-40e5-a512-11bd20f86f44

			changedProperty = DisplayFolder

			changedProperty = Name

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		measure 'Taux de service IDEST' = EXTERNALMEASURE("Taux de service IDEST", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Taux de service
			lineageTag: b7b5dc94-271d-454b-bb91-b6e6b60dab2b
			sourceLineageTag: a7336e31-64ce-4873-a947-5497c4257fda
			dataCategory: Uncategorized

			changedProperty = DisplayFolder

		measure 'Taux de SI' = EXTERNALMEASURE("Taux de SI", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Effectif
			lineageTag: 1bcefda7-8421-41ab-af2d-91ae9bfed2b3
			sourceLineageTag: 5aa60612-bd36-41ab-940e-412328f6b4cf
			dataCategory: Uncategorized

		measure 'Taux de SIA' = EXTERNALMEASURE("Taux de SIA", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Effectif
			lineageTag: 7da52c05-78c0-48c7-b1bd-766c83d0531e
			sourceLineageTag: afe0dfbf-d1c6-4864-b67d-3162bc77d02e
			dataCategory: Uncategorized

		measure 'Taux de SIR' = EXTERNALMEASURE("Taux de SIR", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Effectif
			lineageTag: 158cbf9f-2881-4c04-9f08-f9b549ae1332
			sourceLineageTag: 4713d107-a083-4a36-a73d-382fffdcf9dd
			dataCategory: Uncategorized

		measure 'Temps Format Horaire' = EXTERNALMEASURE("Temps Format Horaire", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Divers
			lineageTag: 3aeee158-10d0-4cc1-bd47-6c8a24b5b75a
			sourceLineageTag: cf756533-909d-41c1-a4ee-012993af1929
			dataCategory: Uncategorized

		measure Test =
				
				VAR DateSeuil = EDATE(TODAY(), -12)
				
				RETURN
				CALCULATETABLE(
				        VALUES('Adhérent (actuel)'[id_entreprise]), // Vérifie bien le nom exact de la colonne ID ici
				        'Adhérent (actuel)'[Date premier statut actif] >= DateSeuil
				    )
			formatString: 0
			lineageTag: 27d8edb8-4748-4289-a744-79554b47c434

			changedProperty = Name

		measure 'Test evol adhérent par équipe médicale' = EXTERNALMEASURE("Test evol adhérent par équipe médicale", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Effectif
			lineageTag: 629787d9-0050-44d7-a0e5-756c8730295d
			sourceLineageTag: d121c338-6885-44cb-a0f3-82c423366dba
			dataCategory: Uncategorized

		measure 'ticket créés par ...' =
				
				"Tickets créés par " & '[nom créateur ticket
			displayFolder: Titres
			lineageTag: a21614cc-46ff-454c-a506-e863450f9c3f

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Tickets en attente' =
				
				CALCULATE(
				    [# tickets],
				    'CRM - ticket - statut'[Statut ticket] = "En attente"
				)
			formatString: 0
			displayFolder: Tickets
			lineageTag: 9b440f68-e760-46c4-a4fb-9709755ad436

			changedProperty = Name

			changedProperty = DisplayFolder

		measure 'Tickets en attente adhérent' =
				
				CALCULATE(
				    [# tickets],
				    'CRM - ticket - statut'[Statut ticket] = "En attente réponse de l'adhérent"
				)
			formatString: 0
			displayFolder: Tickets
			lineageTag: fe3eb60d-ae79-401d-b294-398426287ec9

			changedProperty = Name

			changedProperty = DisplayFolder

		measure 'Tickets en-cours' =
				
				[Tickets en attente adhérent]+[Tickets en attente]+[Tickets ouverts]
			formatString: 0
			displayFolder: Tickets
			lineageTag: ea9fed61-1f38-435c-bfc2-75e7c1c10317

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Tickets fermés' =
				
				CALCULATE(
				    [# tickets],
				    'CRM - ticket - statut'[Statut ticket] = "Fermé"
				)
			formatString: 0
			displayFolder: Tickets
			lineageTag: ab110d0f-aaa3-4f61-88be-c79c32284d9c

			changedProperty = Name

			changedProperty = DisplayFolder

		measure 'Tickets ouverts' =
				
				CALCULATE(
				    [# tickets],
				    'CRM - ticket - statut'[Statut ticket] = "Ouvert"
				)
			formatString: 0
			displayFolder: Tickets
			lineageTag: cece52b7-ce1e-4245-95c5-8a61da432286

			changedProperty = Name

			changedProperty = DisplayFolder

		measure 'titre  FE réalisées le mois dernier' = EXTERNALMEASURE("titre  FE réalisées le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 0d9b5c04-6b65-457f-9c5f-b88b6ebef7a7
			sourceLineageTag: 6047cbd3-1055-4542-9703-3684b9688bf1
			dataCategory: Uncategorized

		measure 'titre  Taux de convocation le mois dernier' = EXTERNALMEASURE("titre  Taux de convocation le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: ee2b5e85-9eb8-4cd7-8499-b2b6a165c0c9
			sourceLineageTag: cad5a625-75b0-45a3-b3e8-89860be453a1
			dataCategory: Uncategorized

		measure 'titre  Téléconsultations le mois dernier' = EXTERNALMEASURE("titre  Téléconsultations le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: e49bd8d1-346a-42ee-b3a1-f5a9cb2161cd
			sourceLineageTag: d1fdba44-fdbc-4a18-9088-2810266d5d72
			dataCategory: Uncategorized

			annotation PBI_FormatHint = {"isText":true}

		measure 'titre ''Où en sont les demandes de RDV reçues le mois dernier''' = EXTERNALMEASURE("titre 'Où en sont les demandes de RDV reçues le mois dernier'", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: a6e8efa3-1fef-45de-9d3c-1f6915dae8bf
			sourceLineageTag: 8fce3826-b6af-41d0-86da-c6af2d0406d9
			dataCategory: Uncategorized

		measure 'titre ''Où en sont les demandes de RDV''' = EXTERNALMEASURE("titre 'Où en sont les demandes de RDV'", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 1663cf6b-85bd-4394-803c-e11a3cb38654
			sourceLineageTag: 80c25c80-1b8c-4a18-9699-1c9059ff016b
			dataCategory: Uncategorized

		measure 'titre % inaptitudes vs Visites effectuées le mois dernier' = EXTERNALMEASURE("titre % inaptitudes vs Visites effectuées le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 75716662-adea-44f4-bb5e-b418fca2db52
			sourceLineageTag: 4a4de229-9e3f-4b62-a73c-c01898639e1b
			dataCategory: Uncategorized

		measure 'titre AMT QVCT réalisées le mois dernier' = EXTERNALMEASURE("titre AMT QVCT réalisées le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 657c65a3-0822-4f5d-b37e-ef7c0d56ca1e
			sourceLineageTag: ede0a4ac-33cc-4ef0-b016-6e61bc5599fe
			dataCategory: Uncategorized

		measure 'titre AMT serrvies le mois dernier' = EXTERNALMEASURE("titre AMT serrvies le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 249d90f9-ebbf-4afa-b202-785e9c7d03c4
			sourceLineageTag: beb891cf-4984-469a-a052-2e89d76967f9
			dataCategory: Uncategorized

		measure 'titre AMT servies par fonction le mois dernier' = EXTERNALMEASURE("titre AMT servies par fonction le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: c0e1a1cb-3157-4053-9e37-6caa96abcbed
			sourceLineageTag: df77550d-042d-4fe2-8a3f-14cc1a27a5ee
			dataCategory: Uncategorized

		measure 'titre avis d''inaptitude délivrés le mois dernier' = EXTERNALMEASURE("titre avis d'inaptitude délivrés le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 6ff458a4-ac58-49a6-8e8e-c87195d10545
			sourceLineageTag: af06f936-62f5-4f75-9506-2a6fa9b639f6
			dataCategory: Uncategorized

		measure 'titre Délai de traitement des demandes le mois dernier' = EXTERNALMEASURE("titre Délai de traitement des demandes le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: b40a8004-fd1b-475a-8050-9e3a83c6beb1
			sourceLineageTag: ba84f6b4-ef67-42f7-b7c6-5ddd663c2a8e
			dataCategory: Uncategorized

		measure 'titre entretiens QVCT réalisées le mois dernier' = EXTERNALMEASURE("titre entretiens QVCT réalisées le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 04a5bc89-dd36-4b07-bce2-eba27f65215a
			sourceLineageTag: de22549e-d23d-4906-a6a2-54d192dd28b6
			dataCategory: Uncategorized

		measure 'titre Nbre d''adhérents ayant bénéficié d''une AMT le mois dernier' = EXTERNALMEASURE("titre Nbre d'adhérents ayant bénéficié d'une AMT le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 4b272796-993e-43ed-8eae-76a3c989e70d
			sourceLineageTag: c12f6123-ca81-450e-9123-7a5a8e20d068
			dataCategory: Uncategorized

		measure 'titre Nbre d''avoirs émis le mois dernier' = EXTERNALMEASURE("titre Nbre d'avoirs émis le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 212a0912-fe20-4c04-91ff-edb935b7f64a
			sourceLineageTag: 0e28a08b-91a4-4eb1-b009-aec8687cebe5
			dataCategory: Uncategorized

		measure 'titre Nbre d''heures perdues le mois dernier suite absentéisme' = EXTERNALMEASURE("titre Nbre d'heures perdues le mois dernier suite absentéisme", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: bafec28e-e9d7-4f45-82de-0ca09e86fc5c
			sourceLineageTag: f9d2e617-ae86-46c0-8482-eeb7978104f0
			dataCategory: Uncategorized

		measure 'titre Nbre de demandes de RDV reçues le mois dernier' = EXTERNALMEASURE("titre Nbre de demandes de RDV reçues le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 5fea58dc-6d2e-49db-994f-3ab653f782fe
			sourceLineageTag: 63a4e943-1ab0-4ae0-ae80-78ebd53c432a
			dataCategory: Uncategorized

		measure 'titre Nbre de réclamations reçues le mois dernier' = EXTERNALMEASURE("titre Nbre de réclamations reçues le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 6036c05a-05f9-41b0-8bce-7478d006ff3f
			sourceLineageTag: afbdf0f4-79c6-4488-8515-5dcb3bca0964
			dataCategory: Uncategorized

		measure 'titre Nbre de signalements PDP réalisées le mois dernier' = EXTERNALMEASURE("titre Nbre de signalements PDP réalisées le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 67432cad-7baf-4125-a969-bfe7628bb686
			sourceLineageTag: 0cf4eeca-bed9-45f1-8770-86776dcf5421
			dataCategory: Uncategorized

		measure 'titre Nbre de visites / ETP réalisées le mois dernier' = EXTERNALMEASURE("titre Nbre de visites / ETP réalisées le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 7107d13f-18cf-45c5-ad1c-6c2c835b79e0
			sourceLineageTag: d523168a-d017-4bd3-bd24-8eca047ad832
			dataCategory: Uncategorized

		measure 'titre Nbre de visites fonction publique réalisées le mois dernier' = EXTERNALMEASURE("titre Nbre de visites fonction publique réalisées le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 0ec93c6d-69c6-4cf6-b381-579cdf95aa7e
			sourceLineageTag: 6dcd096f-d61a-4c1f-9963-df98a4049949
			dataCategory: Uncategorized

		measure 'titre Nbre de visites occasionnelles réalisées le mois dernier' = EXTERNALMEASURE("titre Nbre de visites occasionnelles réalisées le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 2e6e2a5a-6d37-4736-959a-2260cf19cb77
			sourceLineageTag: cee68337-11c6-42a7-83ee-474957a67775
			dataCategory: Uncategorized

		measure 'titre Nbre de visites réalisées le mois dernier' = EXTERNALMEASURE("titre Nbre de visites réalisées le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 85491aa6-e796-4b0f-8c4e-78b061c13dd3
			sourceLineageTag: 374fac3c-4501-4960-a63a-147fac072626
			dataCategory: Uncategorized

		measure 'Titre Nombre d''adhérents actifs ou suspendus' =
				
				"Nombre d'adhérents actifs ou suspendus au "& format(max('Date principale'[Date]),"DD mmmm YYYY", "fr-FR")
			displayFolder: Titres
			lineageTag: ff3781af-478d-4b30-97c4-6568c1c9d9f2

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Titre Nombre d''orientations PDP sur la période' =
				
				Var DateMax = Max('Date principale'[Date])
				Var DateMin = Min('Date principale'[Date])
				Var TimeFrame = DATESBETWEEN('Date principale'[Date],DateMax,DateMin)
				
				RETURN
				"Orientations vers la cellule maintien en emploi entre le "& format(DateMin,"DD mmmm YYYY", "fr-FR")&" et le "&format(DateMax,"DD mmmm YYYY", "fr-FR")
			displayFolder: Titres
			lineageTag: ed8b1ba7-4167-438f-b816-22dc6c8b3666

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Titre Nombre de convocations envoyées sur la période' =
				
				Var DateMax = Max('Date principale'[Date])
				Var DateMin = Min('Date principale'[Date])
				Var TimeFrame = DATESBETWEEN('Date principale'[Date],DateMax,DateMin)
				
				RETURN
				"Nombre de convocations envoyées entre le "& format(DateMin,"DD mmmm YYYY", "fr-FR")&" et le "&format(DateMax,"DD mmmm YYYY", "fr-FR")
			displayFolder: Titres
			lineageTag: ec417a32-fd96-4d85-aa75-818e73a0d520

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Titre Nombre de réclamations reçues sur la période' =
				
				Var DateMax = Max('Date principale'[Date])
				Var DateMin = Min('Date principale'[Date])
				Var TimeFrame = DATESBETWEEN('Date principale'[Date],DateMax,DateMin)
				
				RETURN
				"Nombre de réclamations reçues entre le "& format(DateMin,"DD mmmm YYYY", "fr-FR")&" et le "&format(DateMax,"DD mmmm YYYY", "fr-FR")
			displayFolder: Titres
			lineageTag: b094fafe-5f9b-4735-b40e-b2482f868d30

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Titre Nombre de salariés suivis' =
				
				"Nombre de salariés suivis au "& format(max('Date principale'[Date]),"DD mmmm YYYY", "fr-FR")
			displayFolder: Titres
			lineageTag: 31b095df-918d-4a5a-96e1-6256bdae3322

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Titre Nombre de visites réalisées sur la période' =
				
				Var DateMax = Max('Date principale'[Date])
				Var DateMin = Min('Date principale'[Date])
				Var TimeFrame = DATESBETWEEN('Date principale'[Date],DateMax,DateMin)
				
				RETURN
				"Nombre de visites réalisées entre le "& format(DateMin,"DD mmmm YYYY", "fr-FR")&" et le "&format(DateMax,"DD mmmm YYYY", "fr-FR")
			displayFolder: Titres
			lineageTag: fd7f3639-e3a3-4793-a651-9f0e9e32f77e

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Titre période "Du ... au ..."' =
				
				Var DateMax = Max('Date principale'[Date])
				Var DateMin = Min('Date principale'[Date])
				Var TimeFrame = DATESBETWEEN('Date principale'[Date],DateMax,DateMin)
				
				RETURN
				"Du "& format(DateMin,"DD mmmm YYYY", "fr-FR")&" au "&format(DateMax,"DD mmmm YYYY", "fr-FR")&","
			displayFolder: Titres
			lineageTag: e2967e88-0963-4587-9797-51f910922f1f

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'titre RDV Psy réalisées le mois dernier' = EXTERNALMEASURE("titre RDV Psy réalisées le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 1f459c79-6240-4d17-8f9a-434ba7b6c7c9
			sourceLineageTag: b1d74662-434f-46da-9bf1-9f95d654a2e9
			dataCategory: Uncategorized

		measure 'Titre répartition des adhérents sans FE par taille d''entreprise' =
				
				Var DateMax = Max('Date principale'[Date])
				
				RETURN
				"Répartition des adhérents sans FE en date du " & format(DateMax,"DD mmmm YYYY", "fr-FR")&" par taille d'entreprise"
			displayFolder: Titres
			lineageTag: e5ca1f4c-eca6-4257-8168-53b71468c6ad

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'titre répartition des APP réalisées le mois dernier par taille d''entrerpise' = EXTERNALMEASURE("titre répartition des APP réalisées le mois dernier par taille d'entrerpise", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 952cf3f9-f65d-4af1-8eb1-90dea4b11e6f
			sourceLineageTag: aa47f41f-5101-4ef5-983e-4355880daa10
			dataCategory: Uncategorized

		measure 'titre répartition des FE réalisées le mois dernie par taille d''entrerpise' = EXTERNALMEASURE("titre répartition des FE réalisées le mois dernie par taille d'entrerpise", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 77c76763-5541-4436-8bc9-6feb4213ac06
			sourceLineageTag: 3beafa4a-ed21-409b-9eb4-21e5979f6f4f
			dataCategory: Uncategorized

		measure 'titre répartition des FE réalisées le mois dernier' = EXTERNALMEASURE("titre répartition des FE réalisées le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 2478bbbb-b889-4fec-876a-605bb8cd347a
			sourceLineageTag: 7e6cd7ee-a8df-474b-a24d-00e1095590fc
			dataCategory: Uncategorized

		measure 'titre Répartition des visites par catégorie et par centre le mois dernier' = EXTERNALMEASURE("titre Répartition des visites par catégorie et par centre le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 941bb18b-7920-4cc6-a649-61cace52f2c4
			sourceLineageTag: 31185a20-543f-4713-a873-e6e9cfeb55ef
			dataCategory: Uncategorized

		measure 'titre Répartition des visites par rôle et par centre le mois dernier' = EXTERNALMEASURE("titre Répartition des visites par rôle et par centre le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 5f1180e0-1264-4236-b4bd-37da8c294453
			sourceLineageTag: 7626a59d-e234-49dd-ba42-c8566c9bab00
			dataCategory: Uncategorized

		measure 'titre Répartition géographique des AMT terminées le mois dernier' = EXTERNALMEASURE("titre Répartition géographique des AMT terminées le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 655aac8f-dcd2-4030-98b0-f77e7afc646f
			sourceLineageTag: d49bae4a-9248-4f24-a210-4f34077d0d0d
			dataCategory: Uncategorized

		measure 'titre Répartition géographique des AMT terminées par role le mois dernier' = EXTERNALMEASURE("titre Répartition géographique des AMT terminées par role le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 1c2d659a-2fda-469c-9c8e-d81bd7f7b985
			sourceLineageTag: 9c9b12ba-1940-44b1-b06d-3950e7fecd78
			dataCategory: Uncategorized

		measure 'titre Répartition géographique des demandes de RDV reçues le mois dernier' = EXTERNALMEASURE("titre Répartition géographique des demandes de RDV reçues le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 0ee67b77-7bd6-4476-ae74-b41b1af05eb9
			sourceLineageTag: 9557cae9-227b-4ba7-ab3f-6f639b715709
			dataCategory: Uncategorized

		measure 'titre signalements PDP réalisées le mois dernier' = EXTERNALMEASURE("titre signalements PDP réalisées le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 3655676d-4fa6-4db8-b3d1-4ae4df77d43c
			sourceLineageTag: 51ec2b25-8f1e-4e4a-9f3f-d20d3f9a9e9a
			dataCategory: Uncategorized

		measure 'titre Statut des réclamations reçues le mois dernier' = EXTERNALMEASURE("titre Statut des réclamations reçues le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: f3d86a83-3566-4d41-91da-6dca16163169
			sourceLineageTag: f0f59600-011d-4a54-b62c-07fa70c2e3e8
			dataCategory: Uncategorized

		measure 'titre Taux d''absentéisme le mois dernier' = EXTERNALMEASURE("titre Taux d'absentéisme le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 3f42a36f-3ab7-4bb2-93aa-27065a06b507
			sourceLineageTag: 6ba890df-7908-4d61-88c0-8b9fdf760d55
			dataCategory: Uncategorized

		measure 'titre Taux de service à la date du' = EXTERNALMEASURE("titre Taux de service à la date du", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 3acee78a-d3a2-47c1-8e47-eca40cfcf807
			sourceLineageTag: 5f587c50-af74-4876-8495-791b5152500f
			dataCategory: Uncategorized

		measure 'titre Visites PDP réalisées le mois dernier' = EXTERNALMEASURE("titre Visites PDP réalisées le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: 2dbcfb82-31ef-4bb3-adda-71dead142af7
			sourceLineageTag: 3c083206-0718-411f-a4c7-488c7179fff3
			dataCategory: Uncategorized

		measure 'titreDurée moyenne de traitement des réclamations reçues le mois dernier' = EXTERNALMEASURE("titreDurée moyenne de traitement des réclamations reçues le mois dernier", STRING, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Titres
			lineageTag: d9a610a8-f082-40c3-a42e-6461e10c63cc
			sourceLineageTag: 9425658a-270e-47b4-af4e-7e6d5574e71e
			dataCategory: Uncategorized

		measure 'Tx convocation Evol vs last year' = ```
				
				VAR TxConvoc_Period = [Taux de convocations]  // Mesure de la période courante; utilisée comme numérateur de la variation 
				VAR TxConvoc_LastYear = [Taux de convocation SameLastYear]  // Mesure de la période N-1; dénominateur et référence de comparaison 
				VAR Evolution_Proportion =  // Variation relative propre, gère les divisions par zéro via DIVIDE 
				    DIVIDE( TxConvoc_Period - TxConvoc_LastYear, TxConvoc_LastYear, 0 )
				VAR Signe_Affichage =  // Préfixe du signe basé sur 0 car la variation est une proportion (positif/négatif) 
				    IF( Evolution_Proportion >= 0, "+ ", "- " )
				VAR Valeur_Pourcent_Formattee =  // Mise en forme en pourcentage avec une décimale, appliquée sur la valeur absolue pour éviter un double signe 
				    FORMAT( ABS(Evolution_Proportion), "0.00 %" )
				RETURN
				    "("&Signe_Affichage & Valeur_Pourcent_Formattee&")"  // Sortie texte: utile pour cartes/étiquettes; préférer garder une version numérique pour analyses 
				
				/*
				Rôle de la mesure:
				- Produit un affichage texte de l’évolution des RDV vs N-1 avec signe explicite, ex: "+ 12,3%" ou "- 4,5%".
				- Le calcul de variation utilise DIVIDE pour la robustesse et sépare calcul (proportion) et présentation (signe/format).
				- Pour analyses et agrégations, utiliser en priorité une version numérique: RDV Evol vs last year (num), avec un format dynamique “+0.0%;-0.0%;0.0%”.
				*/ 
				
				```
			displayFolder: Visites
			lineageTag: 9f5fcf62-8586-46aa-9367-d8ee76240ab5

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Tx de présence' = EXTERNALMEASURE("Tx de présence", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Absentéisme
			lineageTag: 83ae0a6d-a1e9-4d1c-85b1-257577e482b7
			sourceLineageTag: 8cd0d4a1-5e76-41a8-aaa3-654d77f9019e
			dataCategory: Uncategorized

		measure 'Tx de service S-1' = EXTERNALMEASURE("Tx de service S-1", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Retard
			lineageTag: 720d5fb9-5bf5-47a8-b60e-08316adf27bc
			sourceLineageTag: 4c59cb8d-3f9d-4cba-aea3-6510da0b7b3a
			dataCategory: Uncategorized

		measure 'Tx de service S-2' = EXTERNALMEASURE("Tx de service S-2", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Retard
			lineageTag: 4c20d79d-7e95-4df6-befd-6cf18718fe07
			sourceLineageTag: e071feb9-6397-4f2f-a973-2f304e55190d
			dataCategory: Uncategorized

		measure 'Tx de service S-3' = EXTERNALMEASURE("Tx de service S-3", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Retard
			lineageTag: aea15767-f312-4ba0-b1af-cca9b760e881
			sourceLineageTag: cf9cb7e5-a607-4ee7-9363-78f0dbd25f38
			dataCategory: Uncategorized

		measure 'Tx service coalesce' = EXTERNALMEASURE("Tx service coalesce", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Visites
			lineageTag: f3dca886-1707-420c-9b77-5c84e071370b
			sourceLineageTag: e3c1932d-1f39-4c7c-b353-da3908865b18
			dataCategory: Uncategorized

		measure TxService_DerniereValeur =
				
				VAR d0 = [DerniereDateReelleTxService]
				
				RETURN
				    CALCULATE (
				        [Taux de service coalesce],
				        TREATAS ( ROW ( "Date", d0 ), 'Date principale'[Date] )
				    )
			displayFolder: Taux de service\Simulation
			lineageTag: a1a98cd6-d497-4ade-a80b-3d3695146e58

			changedProperty = DisplayFolder

			changedProperty = Name

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		measure TxService_Simule = ```
				
				VAR CurDate = MAX ( Dates_Futur[Date] )
				RETURN 
				IF(
				    CurDate <= [DerniereDateReelle], 
				    "", 
				    [TxService_Objectif_Courbe_Futur]
				)
				```
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Taux de service\Simulation
			lineageTag: c7dc58a4-c615-48b8-bd78-e53df6642d3b

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Utilisateur sélectionné' = ```
				
				VAR NomUtilisateurSelectionne = SELECTEDVALUE('Utilisateur'[Nom utilisateur])   // Récupère le nom de l'utilisateur sélectionné
				
				RETURN
				    IF(
				        NOT ISBLANK(NomUtilisateurSelectionne),                                 // Vérifie si un utilisateur est sélectionné
				        NomUtilisateurSelectionne,
				        "Ensemble du service"                                                   // Retourne un texte par défaut si aucun utilisateur n'est sélectionné
				    )
				
				/*
				Description :
				Cette mesure détermine l'utilisateur sélectionné dans le rapport Power BI.
				Elle retourne le nom de l'utilisateur si une sélection est faite, sinon elle retourne "Ensemble du service".
				*/
				
				```
			displayFolder: Divers
			lineageTag: c5aa017a-3922-4b12-9dca-6ac81979617b

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Visites / effectif Evol vs last year' = ```
				
				VAR Visites_Period = [Nbre Visites / Effectif suivi]  // Mesure de la période courante; utilisée comme numérateur de la variation 
				VAR Visites_LastYear = [Visites / effectif SameLastYear]  // Mesure de la période N-1; dénominateur et référence de comparaison 
				VAR Evolution_Proportion =  // Variation relative propre, gère les divisions par zéro via DIVIDE 
				    DIVIDE( Visites_Period - Visites_LastYear, Visites_LastYear, 0 )
				VAR Signe_Affichage =  // Préfixe du signe basé sur 0 car la variation est une proportion (positif/négatif) 
				    IF( Evolution_Proportion >= 0, "+ ", "- " )
				VAR Valeur_Pourcent_Formattee =  // Mise en forme en pourcentage avec une décimale, appliquée sur la valeur absolue pour éviter un double signe 
				    FORMAT( ABS(Evolution_Proportion), "0.00 %" )
				RETURN
				    "("&Signe_Affichage & Valeur_Pourcent_Formattee&")"  // Sortie texte: utile pour cartes/étiquettes; préférer garder une version numérique pour analyses 
				
				/*
				Rôle de la mesure:
				- Produit un affichage texte de l’évolution des visites vs N-1 avec signe explicite, ex: "+ 12,3%" ou "- 4,5%".
				- Le calcul de variation utilise DIVIDE pour la robustesse et sépare calcul (proportion) et présentation (signe/format).
				- Pour analyses et agrégations, utiliser en priorité une version numérique: Visites Evol vs last year (num), avec un format dynamique “+0.0%;-0.0%;0.0%”.
				*/ 
				
				```
			displayFolder: Visites
			lineageTag: d207e0a6-d86c-4ee1-8366-ce7a08aa5556

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Visites / effectif SameLastYear' = ```
				
				VAR ContexteDatesActuel = VALUES('Date principale'[Date]) // Garantit que l’on décale exactement le set de dates du visuel sans altérer d’autres filtres
				
				RETURN
				CALCULATE(
				[Nbre Visites / Effectif suivi],                            // Utilise la mesure source telle quelle
				DATEADD(ContexteDatesActuel, -1, YEAR)      // Décale la période d’un an en arrière, équivalent à SAMEPERIODLASTYEAR mais explicite et flexible
				) 
				
				// Rôle: calcule les RDV pour la même période de l’année précédente, en respectant le grain (jour/mois/trimestre) et les filtres actifs de la table de dates, sans supprimer ces filtres
				```
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Visites
			lineageTag: 60a9ae26-8220-4c70-8e49-9a36f4b6ae8f

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'visites 2024' = EXTERNALMEASURE("visites 2024", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Visites
			lineageTag: bef27573-63cc-40b9-bd5c-edbe3606d7a6
			sourceLineageTag: 1e11de9d-a43d-47d2-8335-f223afc71c49
			dataCategory: Uncategorized

		measure 'Visites annuelles' = EXTERNALMEASURE("Visites annuelles", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Prévision de charge
			lineageTag: 9d2159a8-8572-4590-8c4d-fc4ee7bf7126
			sourceLineageTag: cd26d6eb-c3f0-449d-b4a4-ac5b8de68aab
			dataCategory: Uncategorized

		measure 'Visites embauche IDEST' = EXTERNALMEASURE("Visites embauche IDEST", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0.00
			displayFolder: Prévision de charge
			lineageTag: da464b22-ad57-4357-869a-7f1ea3d0573d
			sourceLineageTag: 25ff90de-39d1-435d-b5a3-1882038f6dfb
			dataCategory: Uncategorized

		measure 'Visites embauche Médecin' = EXTERNALMEASURE("Visites embauche Médecin", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Prévision de charge
			lineageTag: 89d37188-574b-47f8-a114-2a76c8bca57a
			sourceLineageTag: 06f053ec-1837-4016-b08b-a78cb54a8513
			dataCategory: Uncategorized

		measure 'Visites Evol vs last year' = ```
				
				VAR Visites_Period = [Visites Période]  // Mesure de la période courante; utilisée comme numérateur de la variation 
				VAR Visites_LastYear = [Visites SameLastYear]  // Mesure de la période N-1; dénominateur et référence de comparaison 
				VAR Evolution_Proportion =  // Variation relative propre, gère les divisions par zéro via DIVIDE 
				    DIVIDE( Visites_Period - Visites_LastYear, Visites_LastYear, 0 )
				VAR Signe_Affichage =  // Préfixe du signe basé sur 0 car la variation est une proportion (positif/négatif) 
				    IF( Evolution_Proportion >= 0, "+ ", "- " )
				VAR Valeur_Pourcent_Formattee =  // Mise en forme en pourcentage avec une décimale, appliquée sur la valeur absolue pour éviter un double signe 
				    FORMAT( ABS(Evolution_Proportion), "0.00 %" )
				RETURN
				    "("&Signe_Affichage & Valeur_Pourcent_Formattee&")"  // Sortie texte: utile pour cartes/étiquettes; préférer garder une version numérique pour analyses 
				
				/*
				Rôle de la mesure:
				- Produit un affichage texte de l’évolution des visites vs N-1 avec signe explicite, ex: "+ 12,3%" ou "- 4,5%".
				- Le calcul de variation utilise DIVIDE pour la robustesse et sépare calcul (proportion) et présentation (signe/format).
				- Pour analyses et agrégations, utiliser en priorité une version numérique: Visites Evol vs last year (num), avec un format dynamique “+0.0%;-0.0%;0.0%”.
				*/ 
				
				```
			displayFolder: Visites
			lineageTag: d6b51abc-1297-40c0-9320-bb9c0fd31f4c

			changedProperty = DisplayFolder

			changedProperty = Name

		measure 'Visites Evol vs last year (num)' = ```
				
				VAR Visites_Period = [Visites Période]  // Calcule le total de la période courante via la mesure existante [web:27]
				VAR Visites_LastYear = [Visites SameLastYear]  // Calcule la valeur de la même période à N-1 via la mesure existante [web:27]
				VAR Evol_Proportion =  // Variation relative en proportion, robuste aux divisions par zéro [web:21]
				    DIVIDE( Visites_Period - Visites_LastYear, Visites_LastYear, 0 )
				RETURN
				    Evol_Proportion  // Mesure purement numérique, à formater en % au niveau du modèle [web:22][web:34]
				
				// Rôle: calcule l’évolution relative des visites vs N-1 en proportion (ex: 0,12 = +12%), réutilisable dans tout visuel [web:27][web:22].
				
				```
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Visites
			lineageTag: 9ba20418-093e-40ea-b15a-ed6564241f1a

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Visites IDEST' = EXTERNALMEASURE("Visites IDEST", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Prévision de charge
			lineageTag: 44689c3b-baa0-4785-96eb-98174d777fd4
			sourceLineageTag: db5d3834-d344-4c49-b9ca-dd36aa118ed6
			dataCategory: Uncategorized

		measure 'Visites intérimaires' =
				
				VAR DerniereDateContexte = MAX('Date principale'[Date])                                         // dernière date visible dans le contexte actuel, plus performant que LASTDATE pour un scalaire
				VAR Fenetre12M = DATESINPERIOD('Date principale'[Date], DerniereDateContexte, -12, MONTH)       // construit la plage de dates des 12 mois glissants incluant la date max
				
				RETURN
				COALESCE(
				    CALCULATE(
				    'RDV'[Nombre de visites réalisées (RDV)],                                                   // mesure de base agrégée à évaluer
				    KEEPFILTERS('Adhérent (actuel)'[Type entreprise] = "Intérim"),                              // restreint aux entreprises d’intérim sans écraser d’autres filtres plus spécifiques
				    Fenetre12M),                                                                                // applique la fenêtre temporelle jour par jour sur la table de date
				    0
				)
				
				//Description: Calcule le total des visites réalisées pour les entreprises d’intérim sur les 12 derniers mois glissants jusqu’à la dernière date visible dans le contexte, en s’appuyant sur DATESINPERIOD pour une fenêtre temporelle robuste et performante.
			formatString: #,0
			displayFolder: Visites
			lineageTag: 0bff3b19-640d-44ed-a654-7ee80ea1cb4e

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Visites médecin' = EXTERNALMEASURE("Visites médecin", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Prévision de charge
			lineageTag: 444edac3-0736-4f69-b9dd-9f8e0dc59d88
			sourceLineageTag: 289c7af8-2326-4f2a-8f6d-c49661eddc25
			dataCategory: Uncategorized

		measure 'visites médecin 2024' = EXTERNALMEASURE("visites médecin 2024", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Visites
			lineageTag: 1f5badbd-75f6-4d71-ad34-b99bef364141
			sourceLineageTag: 690d2db2-31d8-4fb1-8896-06d9b653a720
			dataCategory: Uncategorized

		measure 'visites mi-carriere' = EXTERNALMEASURE("visites mi-carriere", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Visites
			lineageTag: f9d4c64b-1d23-40be-a588-48e4891270f4
			sourceLineageTag: 78f8363a-e449-4063-b154-2e8594cd8dc8
			dataCategory: Uncategorized

		measure 'Visites occasionelles Méd' = EXTERNALMEASURE("Visites occasionelles Méd", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Prévision de charge
			lineageTag: f8cd202e-0331-445a-9e38-70a57dda072c
			sourceLineageTag: 358a8c63-fc27-4ffb-b636-d94dbf84e02e
			dataCategory: Uncategorized

		measure 'visites occasionnelles 2024' = EXTERNALMEASURE("visites occasionnelles 2024", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Visites
			lineageTag: 3243f7f5-a82d-4bac-b31c-15008c9385db
			sourceLineageTag: 66d3169f-efe1-46e0-b0d5-f20cf9103c85
			dataCategory: Uncategorized

		measure 'visites occasionnelles 2024 vs visites 2024' = EXTERNALMEASURE("visites occasionnelles 2024 vs visites 2024", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Visites
			lineageTag: 1acd7549-dee3-4030-81b5-648db32ceb60
			sourceLineageTag: e0403394-94c4-43d0-9b76-fa583d1e36a4
			dataCategory: Uncategorized

		measure 'visites occasionnelles 2024 vs visites médecin 2024' = EXTERNALMEASURE("visites occasionnelles 2024 vs visites médecin 2024", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00\ %;-0.00\ %;0.00\ %
			displayFolder: Visites
			lineageTag: 6a9741fe-c1c8-4255-9c21-93bb2fc21c5b
			sourceLineageTag: 53e4c591-3dd9-40d4-973f-f9ac2db0e52b
			dataCategory: Uncategorized

		measure 'Visites occasionnelles IDEST' = EXTERNALMEASURE("Visites occasionnelles IDEST", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Prévision de charge
			lineageTag: 6cf75bbb-093c-4f2d-b086-7a62ee1bf840
			sourceLineageTag: acceb08a-dd5c-4437-9317-cba891e6474a
			dataCategory: Uncategorized

		measure 'Visites Période' = ```
				
				VAR dMin = MIN('Date principale'[Date])
				VAR dMax = MAX('Date principale'[Date])
				VAR DatesPeriode =
				    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
				
				Return 
				CALCULATE([Nombre de visites réalisées (RDV)], DatesPeriode)
				
				
				```
			formatString: #,0
			displayFolder: Visites
			lineageTag: a86c17d1-63d0-44fa-a2a1-812d9ba699b6

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Visites Période N-1' = ```
				
				VAR dMin = MIN('Date principale'[Date])
				VAR dMax = MAX('Date principale'[Date])
				VAR DatesPeriode =
				    FILTER(ALL('Date principale'[Date]), 'Date principale'[Date] >= dMin && 'Date principale'[Date] <= dMax)
				VAR DatesPeriodeN1 =
				    DATEADD(DatesPeriode, -1, YEAR)
				RETURN
				CALCULATE( [Nombre de visites réalisées (RDV)], DatesPeriodeN1 )
				
				```
			formatString: #,0
			displayFolder: Visites
			lineageTag: afce843c-9584-43a3-a686-2612ed77b1a6

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

		measure 'Visites périodiques IDEST' = EXTERNALMEASURE("Visites périodiques IDEST", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0.00
			displayFolder: Prévision de charge
			lineageTag: 19238049-cd9d-477e-975a-ba703ad6ed88
			sourceLineageTag: 97d9e488-e7f9-4cb1-80c4-7a2333131ea5
			dataCategory: Uncategorized

		measure 'Visites périodiques Médecin' = EXTERNALMEASURE("Visites périodiques Médecin", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Prévision de charge
			lineageTag: a4a702b2-5662-46ad-83a5-aa5ecbdccb01
			sourceLineageTag: 0e66b42b-3ffe-4c36-8e8d-0e61a02348a7
			dataCategory: Uncategorized

		measure 'Visites SameLastYear' = ```
				
				VAR ContexteDatesActuel = VALUES('Date principale'[Date]) // Garantit que l’on décale exactement le set de dates du visuel sans altérer d’autres filtres
				
				RETURN
				CALCULATE(
				[Nombre de visites réalisées (RDV)],        // Utilise la mesure source telle quelle
				DATEADD(ContexteDatesActuel, -1, YEAR)      // Décale la période d’un an en arrière, équivalent à SAMEPERIODLASTYEAR mais explicite et flexible
				) 
				
				// Rôle: calcule les visites pour la même période de l’année précédente, en respectant le grain (jour/mois/trimestre) et les filtres actifs de la table de dates, sans supprimer ces filtres
				```
			formatString: #,0
			displayFolder: Visites
			lineageTag: 30005181-68a9-4c10-ba28-5da16424dccb

			changedProperty = DisplayFolder

			changedProperty = Name

			changedProperty = FormatString

	ref table Adhérents

		measure '# adhérents AMT de prévention primaire à jour' = EXTERNALMEASURE("# adhérents AMT de prévention primaire à jour", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Retard AMT\AMT de prévention primaire
			lineageTag: 9963be2b-f7e6-48d3-8ed0-adc32ea37df3
			sourceLineageTag: 378bcf2f-c79c-4ee9-934e-c71ce19a1105
			dataCategory: Uncategorized

		measure '# adhérents AMT de prévention primaire en retard' = EXTERNALMEASURE("# adhérents AMT de prévention primaire en retard", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Retard AMT\AMT de prévention primaire
			lineageTag: fb8cb433-446d-46f8-bcbd-8224b3c0ff26
			sourceLineageTag: 7ac90a93-7b6b-4efd-bf05-d43d0ba81053
			dataCategory: Uncategorized

		measure '# adhérents éligibles AMT de prévention primaire' = EXTERNALMEASURE("# adhérents éligibles AMT de prévention primaire", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Retard AMT\AMT de prévention primaire
			lineageTag: 9c31f339-eaff-405a-a0a9-108742d25a78
			sourceLineageTag: 27bd95a9-3f53-42e7-808b-663a9efca40c
			dataCategory: Uncategorized

		measure '# adhérents éligibles FE' = EXTERNALMEASURE("# adhérents éligibles FE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Retard AMT\FE
			lineageTag: b44a0706-9d9b-44a0-9b25-78f6e72fdda7
			sourceLineageTag: fb2f3099-2893-4257-a470-0c354d744155
			dataCategory: Uncategorized

		measure '# adhérents FE à jour' = EXTERNALMEASURE("# adhérents FE à jour", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Retard AMT\FE
			lineageTag: 68d46d05-7774-47f5-80db-25b419d0f69b
			sourceLineageTag: 602d1f27-0700-41bc-a871-497a9425e3a8
			dataCategory: Uncategorized

		measure '# adhérents FE en retard' = EXTERNALMEASURE("# adhérents FE en retard", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Retard AMT\FE
			lineageTag: 1814fb99-050d-4ae5-be37-279e5fec21b7
			sourceLineageTag: 3c9e7527-42e1-4248-afe1-b06384f3a70f
			dataCategory: Uncategorized

		measure '# AMT terminées depuis 5 ans' = EXTERNALMEASURE("# AMT terminées depuis 5 ans", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\09 - Score card\Comptages
			lineageTag: efeffd17-9a94-4c7d-a9ec-69f0e9776e54
			sourceLineageTag: 681b0db7-e8da-409d-a994-b8f0335407d2
			dataCategory: Uncategorized

		measure '# salariés avec adaptation de poste depuis 5 ans' = EXTERNALMEASURE("# salariés avec adaptation de poste depuis 5 ans", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\09 - Score card\Comptages
			lineageTag: 6dc9a1a8-3baa-4de9-b87c-1d9141cfab0b
			sourceLineageTag: 2bd8b6c2-96ae-4402-a2ed-4abfc4c1f5e8
			dataCategory: Uncategorized

		measure '# salariés avec avis d''inaptitude depuis 5 ans' = EXTERNALMEASURE("# salariés avec avis d'inaptitude depuis 5 ans", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\09 - Score card\Comptages
			lineageTag: ffd6d012-6289-4ecd-93b6-a516749d7321
			sourceLineageTag: 5faf1c10-fd7f-46d5-842c-402006d94823
			dataCategory: Uncategorized

		measure '# salariés suivis (hors intérim) avec AMT de prévention primaire à jour' = EXTERNALMEASURE("# salariés suivis (hors intérim) avec AMT de prévention primaire à jour", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Retard AMT\AMT de prévention primaire
			lineageTag: 01bc655b-60d9-40d2-9c78-8399913674b8
			sourceLineageTag: a0364a81-ead7-4022-9bb5-1991734ec716
			dataCategory: Uncategorized

		measure '# salariés suivis (hors intérim) avec AMT de prévention primaire en retard' = EXTERNALMEASURE("# salariés suivis (hors intérim) avec AMT de prévention primaire en retard", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Retard AMT\AMT de prévention primaire
			lineageTag: 460c5e3e-4aaf-4195-87ec-8eab3ce0fa34
			sourceLineageTag: fd0271f7-9fb3-4f25-bf75-b5db73b3c55f
			dataCategory: Uncategorized

		measure '# salariés suivis (hors intérim) avec FE à jour' = EXTERNALMEASURE("# salariés suivis (hors intérim) avec FE à jour", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Retard AMT\FE
			lineageTag: 2c4c54fe-30f1-418c-92ed-cc5a09b2dff3
			sourceLineageTag: 0fd78407-14e5-4fe2-b908-90db0be157c9
			dataCategory: Uncategorized

		measure '# salariés suivis (hors intérim) avec FE en retard' = EXTERNALMEASURE("# salariés suivis (hors intérim) avec FE en retard", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Retard AMT\FE
			lineageTag: 3bcd9b25-07d0-4146-8d71-50c008e832cc
			sourceLineageTag: 6cd706ab-89f7-47ab-a22e-8eb01be9d9d0
			dataCategory: Uncategorized

		measure '# salariés suivis (hors intérim) éligibles AMT de prévention primaire' = EXTERNALMEASURE("# salariés suivis (hors intérim) éligibles AMT de prévention primaire", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Retard AMT\AMT de prévention primaire
			lineageTag: 07a7c7e3-4c0c-45a4-abad-c21703d5d722
			sourceLineageTag: 89e725dc-d8f2-4e48-88aa-ed73d1e34bbf
			dataCategory: Uncategorized

		measure '# salariés suivis (hors intérim) éligibles FE' = EXTERNALMEASURE("# salariés suivis (hors intérim) éligibles FE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Retard AMT\FE
			lineageTag: 5afd77a4-54cb-4b95-b3c9-63e265d95508
			sourceLineageTag: c839515d-a36f-4b4d-93a4-48f34b077f67
			dataCategory: Uncategorized

		measure '# situations de travail actives' = EXTERNALMEASURE("# situations de travail actives", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\09 - Score card\Comptages
			lineageTag: c80cd5b8-9012-48c0-94fc-68caa8b25f23
			sourceLineageTag: b1308190-9ec6-4188-b3ab-aaaaeb8a1589
			dataCategory: Uncategorized

		measure '# visite reprise par salarié' = EXTERNALMEASURE("# visite reprise par salarié", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs\09 - Score card\Comptages
			lineageTag: 3b346efa-c635-4ad9-aa7a-718cfcc499a1
			sourceLineageTag: 6fb21e8a-1d48-4299-a159-471888e76dd3
			dataCategory: Uncategorized

		measure '% adhérents AMT (hors FE) moins de 4 ans' = EXTERNALMEASURE("% adhérents AMT (hors FE) moins de 4 ans", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 092d272e-a3d3-4909-be99-43fc4c9fc961
			sourceLineageTag: 5bce7558-890e-4206-938c-d7469317da0e
			dataCategory: Uncategorized

		measure '% adhérents AMT (hors FE) plus de 4 ans' = EXTERNALMEASURE("% adhérents AMT (hors FE) plus de 4 ans", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 07021937-38ff-43cf-a8c2-79182b59fdb9
			sourceLineageTag: d81d277f-e889-44fb-b83c-8ba29a3a68a2
			dataCategory: Uncategorized

		measure '% adhérents AMT de prévention primaire à jour' = EXTERNALMEASURE("% adhérents AMT de prévention primaire à jour", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 11b71328-1b33-4b79-8d4e-d479af58245f
			sourceLineageTag: 383d23ea-3f5f-4f2b-bc2f-41a945cfde26
			dataCategory: Uncategorized

		measure '% adhérents AMT de prévention primaire de moins de 4 ans' = EXTERNALMEASURE("% adhérents AMT de prévention primaire de moins de 4 ans", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 899944d1-182d-41b9-a9c5-844484716d19
			sourceLineageTag: 854e86c7-231f-4757-a6da-f48d13c7b797
			dataCategory: Uncategorized

		measure '% adhérents AMT de prévention primaire de plus de 4 ans' = EXTERNALMEASURE("% adhérents AMT de prévention primaire de plus de 4 ans", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 451e1377-224d-497b-ae7d-6848f3fea8d8
			sourceLineageTag: 4e2bb47b-6e02-4059-9a58-b60343c3739b
			dataCategory: Uncategorized

		measure '% adhérents AMT de prévention primaire en retard' = EXTERNALMEASURE("% adhérents AMT de prévention primaire en retard", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: f3e48598-67fb-4c2a-900b-0013060bae77
			sourceLineageTag: dedbf381-72cb-4113-aac4-870eb9903261
			dataCategory: Uncategorized

		measure '% adhérents aucune AMT (hors FE) terminée (renseignée)' = EXTERNALMEASURE("% adhérents aucune AMT (hors FE) terminée (renseignée)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 94b7cae3-3adc-46aa-90ad-3fc8cdc9b44a
			sourceLineageTag: 7c3f42d3-9490-484c-b962-8c2fc18ded34
			dataCategory: Uncategorized

		measure '% adhérents aucune AMT de prévention primaire terminée (renseignée)' = EXTERNALMEASURE("% adhérents aucune AMT de prévention primaire terminée (renseignée)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: beea34f6-b5a5-4bea-bd7c-b4a17cc4a107
			sourceLineageTag: 9f569fe5-20a0-4e4d-8d2b-3cf41cd50580
			dataCategory: Uncategorized

		measure '% adhérents aucune FE renseignée' = EXTERNALMEASURE("% adhérents aucune FE renseignée", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 22698aa9-1632-430e-a35a-b3d9cdd6003e
			sourceLineageTag: 684be62c-7b6d-4d0c-95b0-6c7d4c58051e
			dataCategory: Uncategorized

		measure '% adhérents éligibles AMT de prévention primaire' = EXTERNALMEASURE("% adhérents éligibles AMT de prévention primaire", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 3eefb000-252a-48c2-97da-701f9967de36
			sourceLineageTag: a633a802-2a40-435a-a4ca-a2e2fb22d296
			dataCategory: Uncategorized

		measure '% adhérents FE à jour' = EXTERNALMEASURE("% adhérents FE à jour", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 23311478-9b1f-4373-a9c8-54cc228e2499
			sourceLineageTag: 43dfd221-afc6-4c1e-bbb4-1e101e96acab
			dataCategory: Uncategorized

		measure '% adhérents FE en retard' = EXTERNALMEASURE("% adhérents FE en retard", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 36e6ed95-242c-467f-a768-6fc31496fb2d
			sourceLineageTag: 4a87b490-4635-4695-9101-19df9908f9a7
			dataCategory: Uncategorized

		measure '% adhérents FE moins de 4 ans' = EXTERNALMEASURE("% adhérents FE moins de 4 ans", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: a81ba56a-dbc8-45e1-b2ea-3cb4201347df
			sourceLineageTag: 3c799791-7657-4b46-97e2-29e3931160ed
			dataCategory: Uncategorized

		measure '% adhérents FE plus de 4 ans' = EXTERNALMEASURE("% adhérents FE plus de 4 ans", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 6988eac3-6204-4737-9a40-71ac57352ebf
			sourceLineageTag: 5bf9a692-36e6-405f-8345-1117258a94e4
			dataCategory: Uncategorized

		measure '% contrats précaires' = EXTERNALMEASURE("% contrats précaires", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: d8ed1c23-7dcb-4c4b-afdf-cf82002279c3
			sourceLineageTag: aa195fd4-5e64-4b2d-a8ce-63aee0760c75
			dataCategory: Uncategorized

		measure '% CSE déclaré' = EXTERNALMEASURE("% CSE déclaré", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: cb574812-037b-4728-b510-af0f6d44e293
			sourceLineageTag: e86a72d8-8b64-4d78-bf9f-1fe3585f932b
			dataCategory: Uncategorized

		measure '% DU déclaré' = EXTERNALMEASURE("% DU déclaré", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 3c0b49da-22e7-4ee7-acdb-4153d103023b
			sourceLineageTag: 569adf7f-64e8-40e3-a337-6cf01646e257
			dataCategory: Uncategorized

		measure '% retard visite' = EXTERNALMEASURE("% retard visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: c313bb78-b13f-4b5f-98d6-efbcb63821f0
			sourceLineageTag: c9d71d6e-99f4-46af-a40d-0bf1d21744f7
			dataCategory: Uncategorized

		measure '% salarié avec situation de travail' = EXTERNALMEASURE("% salarié avec situation de travail", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 3223885f-3b1d-4f1c-85d7-38850fa235c4
			sourceLineageTag: 2abaed3c-de3e-4827-a3ed-611ddfccd416
			dataCategory: Uncategorized

		measure '% salariés suivis (hors intérim) avec AMT (hors FE) moins de 4 ans' = EXTERNALMEASURE("% salariés suivis (hors intérim) avec AMT (hors FE) moins de 4 ans", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: d66ec57b-76b8-4253-ab2f-24cbafdaecea
			sourceLineageTag: 4d0c14ec-93c9-44e2-848c-6b88c543d2e0
			dataCategory: Uncategorized

		measure '% salariés suivis (hors intérim) avec AMT (hors FE) plus de 4 ans' = EXTERNALMEASURE("% salariés suivis (hors intérim) avec AMT (hors FE) plus de 4 ans", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: b8d8c5f3-82d3-43dc-bff1-cb2a1d37fa2e
			sourceLineageTag: 4562288d-c172-430b-bf0b-fbc44529aea7
			dataCategory: Uncategorized

		measure '% salariés suivis (hors intérim) avec AMT de prévention primaire à jour' = EXTERNALMEASURE("% salariés suivis (hors intérim) avec AMT de prévention primaire à jour", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: da3291b6-0872-47b9-9182-25d84823791a
			sourceLineageTag: 30deb0ed-bdac-43c2-b1c1-55043ce3ce34
			dataCategory: Uncategorized

		measure '% salariés suivis (hors intérim) avec AMT de prévention primaire de moins de 4 ans' = EXTERNALMEASURE("% salariés suivis (hors intérim) avec AMT de prévention primaire de moins de 4 ans", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 1165ca44-d100-4a20-87e0-1f0aa15d92ae
			sourceLineageTag: 9f9edf2f-8d64-42f2-8b25-7f1258f1362d
			dataCategory: Uncategorized

		measure '% salariés suivis (hors intérim) avec AMT de prévention primaire de plus de 4 ans' = EXTERNALMEASURE("% salariés suivis (hors intérim) avec AMT de prévention primaire de plus de 4 ans", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: abb87147-a9d9-4115-968f-e3ad8bacee4e
			sourceLineageTag: ba6d17a9-c155-4c52-8f3f-2431953c55f5
			dataCategory: Uncategorized

		measure '% salariés suivis (hors intérim) avec AMT de prévention primaire en retard' = EXTERNALMEASURE("% salariés suivis (hors intérim) avec AMT de prévention primaire en retard", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: dcdd68e2-dd64-4781-a007-0b98ee070a01
			sourceLineageTag: 6e698973-5127-4cf8-940b-4df7d8382611
			dataCategory: Uncategorized

		measure '% salariés suivis (hors intérim) avec FE à jour' = EXTERNALMEASURE("% salariés suivis (hors intérim) avec FE à jour", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 9f78782e-b8c9-4f6c-b1bf-809687883cb0
			sourceLineageTag: 13415c00-08e1-4bac-a9c5-fe2d16af17d3
			dataCategory: Uncategorized

		measure '% salariés suivis (hors intérim) avec FE en retard' = EXTERNALMEASURE("% salariés suivis (hors intérim) avec FE en retard", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: ef6c1b68-e62b-4642-9541-fe37174f9574
			sourceLineageTag: 26b495d9-370e-4383-9d3e-ca23e60e16b6
			dataCategory: Uncategorized

		measure '% salariés suivis (hors intérim) avec FE moins de 4 ans' = EXTERNALMEASURE("% salariés suivis (hors intérim) avec FE moins de 4 ans", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 189ae11c-629f-4aac-be86-fc0fea50fef1
			sourceLineageTag: 37b2d332-cb3f-4fd9-8260-4f2fedb7ae1c
			dataCategory: Uncategorized

		measure '% salariés suivis (hors intérim) avec FE plus de 4 ans' = EXTERNALMEASURE("% salariés suivis (hors intérim) avec FE plus de 4 ans", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 658ce15d-4b91-40f3-ab90-a98e966044e4
			sourceLineageTag: fd09625f-545f-4541-a6d2-49c58721bc77
			dataCategory: Uncategorized

		measure '% salariés suivis (hors intérim) éligibles AMT de prévention primaire' = EXTERNALMEASURE("% salariés suivis (hors intérim) éligibles AMT de prévention primaire", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 1eb0398e-b5cf-465d-a38f-e7db8f6bd7da
			sourceLineageTag: 0eaf7418-fd05-40d2-8140-50e86314baf3
			dataCategory: Uncategorized

		measure '% salariés suivis (hors intérim) sans AMT (hors FE) terminée' = EXTERNALMEASURE("% salariés suivis (hors intérim) sans AMT (hors FE) terminée", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 27f2adf0-35ea-447f-8243-5fba3b0c6592
			sourceLineageTag: 74d14ea0-df5e-4c49-9105-c58b46d792c6
			dataCategory: Uncategorized

		measure '% salariés suivis (hors intérim) sans AMT de prévention primaire terminée' = EXTERNALMEASURE("% salariés suivis (hors intérim) sans AMT de prévention primaire terminée", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: d30a0d65-2cb3-4b29-a088-7f1aa0235fa1
			sourceLineageTag: b809a88d-77a6-48e8-8215-2f23273abf1c
			dataCategory: Uncategorized

		measure '% salariés suivis (hors intérim) sans FE renseignée' = EXTERNALMEASURE("% salariés suivis (hors intérim) sans FE renseignée", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: b0195e49-2b5c-4860-8fa1-646a7d924fa0
			sourceLineageTag: c2e473eb-f0d1-4620-b5b0-244db8e9df74
			dataCategory: Uncategorized

		measure '% SIR/SIA' = EXTERNALMEASURE("% SIR/SIA", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 66376e07-4998-4653-96aa-6168d77625f5
			sourceLineageTag: 196dfa79-d11e-4049-bbe3-5d77d7258873
			dataCategory: Uncategorized

		measure 'Âge moyen salarié' = EXTERNALMEASURE("Âge moyen salarié", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\09 - Score card\Anciennetés
			lineageTag: 84f7737e-125a-4a07-873e-6b5ddc5c898e
			sourceLineageTag: 8b7c9046-8808-4730-b4c2-8242a1db8082
			dataCategory: Uncategorized

		measure 'Ancienneté dernière AMT' = EXTERNALMEASURE("Ancienneté dernière AMT", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs\09 - Score card\Anciennetés
			lineageTag: f10a89d4-bc10-4677-aa1b-4861b7c0b69b
			sourceLineageTag: 4464bca4-b70f-485a-a5ef-d7596d229b0c
			dataCategory: Uncategorized

		measure 'Ancienneté dernière AMT (hors FE)' = EXTERNALMEASURE("Ancienneté dernière AMT (hors FE)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs\09 - Score card\Anciennetés
			lineageTag: c0ecbe2f-b834-47d0-86b0-3740f60f5544
			sourceLineageTag: 82c77e86-6580-4220-a110-270e85d13f82
			dataCategory: Uncategorized

		measure 'Ancienneté FE' = EXTERNALMEASURE("Ancienneté FE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs\09 - Score card\Anciennetés
			lineageTag: 3e502193-2f86-4fde-a32e-9e9d34b8d8bc
			sourceLineageTag: a68c4a7f-56b0-4b8d-9f43-5f0aa6eb2f75
			dataCategory: Uncategorized

		measure 'Ancienneté moyenne salarié' = EXTERNALMEASURE("Ancienneté moyenne salarié", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs\09 - Score card\Anciennetés
			lineageTag: d3e92994-0e11-48a2-8137-2f3ffd1b0b31
			sourceLineageTag: 5075d725-09dd-4721-8f9e-562bd2bd998b
			dataCategory: Uncategorized

		measure 'Dernier effectif actif' = EXTERNALMEASURE("Dernier effectif actif", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Indicateurs\08 - Dernier effectif actif
			lineageTag: ff0bec89-e54b-4be2-aff6-58de76a3058e
			sourceLineageTag: 90c66bb2-39f4-4c43-b801-36300ef75187
			dataCategory: Uncategorized

		measure 'Effectif de référence actuel' = EXTERNALMEASURE("Effectif de référence actuel", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Effectif déclaré actuel
			lineageTag: 3fd19352-7055-4ba2-8034-4fdd4638a218
			sourceLineageTag: 767f4d95-2caf-4269-b938-d8dbf7f05e65
			dataCategory: Uncategorized

		measure 'Effectif déclaré actuel' = EXTERNALMEASURE("Effectif déclaré actuel", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Effectif déclaré actuel
			lineageTag: aea6dff9-2e75-46ae-afef-4b0f8d76adaf
			sourceLineageTag: ea882561-14d7-4b00-8506-fffc23f02493
			dataCategory: Uncategorized

		measure 'Effectif déclaré facturable exercice comptable actuel' = EXTERNALMEASURE("Effectif déclaré facturable exercice comptable actuel", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Indicateurs\06 - Effectif déclaré exercice comptable actuel
			lineageTag: 8ff91957-edcb-4100-a53b-6eaa3b5535d7
			sourceLineageTag: c6a3c0f2-c30f-4d8e-8b49-c8ef38c6a617
			dataCategory: Uncategorized

		measure 'Effectif déclaré facturable exercice comptable précédent' = EXTERNALMEASURE("Effectif déclaré facturable exercice comptable précédent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Indicateurs\07 - Effectif déclaré exercice comptable précédent
			lineageTag: d58080b3-581b-4e89-a744-03b637d85341
			sourceLineageTag: ae3695ba-aba4-4ffc-8cc8-b31e9b620a30
			dataCategory: Uncategorized

		measure 'Effectif déclaré précédent' = EXTERNALMEASURE("Effectif déclaré précédent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Effectif déclaré précédent
			lineageTag: 62c14602-8ab9-42cd-9e2d-e3eb243f3765
			sourceLineageTag: a36c1b49-eb60-459e-8f1e-60807d7edcf3
			dataCategory: Uncategorized

		measure 'Effectif déclaré total exercice comptable actuel' = EXTERNALMEASURE("Effectif déclaré total exercice comptable actuel", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Indicateurs\06 - Effectif déclaré exercice comptable actuel
			lineageTag: 72235e0f-742a-4f99-8951-106b7282ec52
			sourceLineageTag: 55c69414-ba30-4cdd-8280-d8585166c7d7
			dataCategory: Uncategorized

		measure 'Effectif déclaré total exercice comptable précédent' = EXTERNALMEASURE("Effectif déclaré total exercice comptable précédent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Indicateurs\07 - Effectif déclaré exercice comptable précédent
			lineageTag: 9ed4afb4-aa6c-4d8d-aee2-55a7b3f5cbcf
			sourceLineageTag: be91f747-f98b-41a3-a4b9-a799b0d69b78
			dataCategory: Uncategorized

		measure 'Effectif estimé actuel' = EXTERNALMEASURE("Effectif estimé actuel", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Effectif déclaré actuel
			lineageTag: 5db7f47b-3e59-46c1-86b5-1043184059b1
			sourceLineageTag: 84efe4be-42a7-4cbc-96a5-5eccfda416bd
			dataCategory: Uncategorized

		measure 'Effectif suivi - hors intérim' = EXTERNALMEASURE("Effectif suivi - hors intérim", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Effectif suivi\2.2. Hors intérimaires
			lineageTag: bcddfeeb-42d9-4af1-bb54-5acb659878d0
			sourceLineageTag: 90c8485d-3361-4f10-8658-8a3e934c3f0e
			dataCategory: Uncategorized

		measure 'Effectif suivi - intérim uniquement' = EXTERNALMEASURE("Effectif suivi - intérim uniquement", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Effectif suivi\2.3. Intérimaires uniquement
			lineageTag: 111675e7-2858-4136-ac26-96af22226827
			sourceLineageTag: 1a0cf8cb-f437-4e5b-9412-e0e1b4d2668b
			dataCategory: Uncategorized

		measure 'Effectif suivi SI - hors intérim' = EXTERNALMEASURE("Effectif suivi SI - hors intérim", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Effectif suivi\2.2. Hors intérimaires
			lineageTag: 68b63227-3f3b-4ee0-986e-568cc2cab0d1
			sourceLineageTag: 6febebd1-5b9a-4365-8e6b-1c5554df1330
			dataCategory: Uncategorized

		measure 'Effectif suivi SI - intérim uniquement' = EXTERNALMEASURE("Effectif suivi SI - intérim uniquement", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Effectif suivi\2.3. Intérimaires uniquement
			lineageTag: 716c27a3-d1e1-40d3-995f-c21f2ddcc1c9
			sourceLineageTag: 7ab405bc-1cc9-4ebc-85e6-75e4c32f2afa
			dataCategory: Uncategorized

		measure 'Effectif suivi SI total' = EXTERNALMEASURE("Effectif suivi SI total", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Effectif suivi\2.1. Total
			lineageTag: 6ce4907d-48b6-4ea5-9c56-b379979842f5
			sourceLineageTag: de448ead-0c42-4e42-9284-c7799bb6a654
			dataCategory: Uncategorized

		measure 'Effectif suivi SIA - hors intérim' = EXTERNALMEASURE("Effectif suivi SIA - hors intérim", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Effectif suivi\2.2. Hors intérimaires
			lineageTag: 600cfda6-1daf-4f5d-868f-d8220ac9a4d0
			sourceLineageTag: 7b8e8c53-8c21-4f51-8494-2415ebbf5a3b
			dataCategory: Uncategorized

		measure 'Effectif suivi SIA - intérim uniquement' = EXTERNALMEASURE("Effectif suivi SIA - intérim uniquement", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Effectif suivi\2.3. Intérimaires uniquement
			lineageTag: 1c7ed0b3-f383-4897-ad3e-8ce87b296270
			sourceLineageTag: bdfe1fae-7535-4707-9600-9cffa5e4056b
			dataCategory: Uncategorized

		measure 'Effectif suivi SIA total' = EXTERNALMEASURE("Effectif suivi SIA total", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Effectif suivi\2.1. Total
			lineageTag: e8467042-2ff7-4ed3-beb1-bcdd22b77e4d
			sourceLineageTag: 6c34817f-b396-44d1-a994-7c302233b9d0
			dataCategory: Uncategorized

		measure 'Effectif suivi SIR - hors intérim' = EXTERNALMEASURE("Effectif suivi SIR - hors intérim", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Effectif suivi\2.2. Hors intérimaires
			lineageTag: 8c371710-28cd-4817-8060-2563cf5b1feb
			sourceLineageTag: c31428ca-6cac-4398-ae83-c8508c0d212c
			dataCategory: Uncategorized

		measure 'Effectif suivi SIR - intérim uniquement' = EXTERNALMEASURE("Effectif suivi SIR - intérim uniquement", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Effectif suivi\2.3. Intérimaires uniquement
			lineageTag: b38c89bc-64ba-4d90-aa04-e45528e32525
			sourceLineageTag: c17a4a6a-8997-44fa-8246-d78208cb47b6
			dataCategory: Uncategorized

		measure 'Effectif suivi SIR total' = EXTERNALMEASURE("Effectif suivi SIR total", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Effectif suivi\2.1. Total
			lineageTag: dec68f04-199b-4e29-86a0-d617623b9943
			sourceLineageTag: f6cb6849-b17d-430c-ac74-1aa553386eac
			dataCategory: Uncategorized

		measure 'Effectif suivi total' = EXTERNALMEASURE("Effectif suivi total", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Effectif suivi\2.1. Total
			lineageTag: 80c973ba-9277-41c0-9a9b-e9263dad1710
			sourceLineageTag: 3ea111bc-c520-4af1-831f-bb59b407f5b8
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents actifs ou suspendus' = EXTERNALMEASURE("Nombre d'adhérents actifs ou suspendus", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\01 - Nombre d'adhérents
			lineageTag: e454d15e-9066-46b2-bd4c-b8ed4de09435
			sourceLineageTag: 3f515e67-57a1-4859-add6-5771934833b1
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents actuel' = EXTERNALMEASURE("Nombre d'adhérents actuel", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\01 - Nombre d'adhérents
			lineageTag: 3d71eadc-8bc1-4af4-a80c-de255dd7936c
			sourceLineageTag: 331174a0-4c8b-4fe7-a465-d1f8aa1ba50e
			dataCategory: Uncategorized

		measure 'Nombre d''entités juridiques actuel' = EXTERNALMEASURE("Nombre d'entités juridiques actuel", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\01 - Nombre d'adhérents
			lineageTag: adf64e93-5702-4142-9887-95571c5455e9
			sourceLineageTag: d60c69e2-0ace-4f61-9074-bcf2cac24469
			dataCategory: Uncategorized

		measure 'Nombre de collections actuel' = EXTERNALMEASURE("Nombre de collections actuel", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\01 - Nombre d'adhérents
			lineageTag: 733b77a2-06ae-49f1-95ce-023450e97ba2
			sourceLineageTag: 64ba2c45-6d9e-4789-b336-34440527b0a7
			dataCategory: Uncategorized

		measure 'Nombre de SdT actives' = EXTERNALMEASURE("Nombre de SdT actives", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\05 - Nombre de SdT
			lineageTag: e989219b-393b-4b7f-93ce-ed691dce0fe8
			sourceLineageTag: a43bec0c-6767-477f-adda-717f7afd067b
			dataCategory: Uncategorized

		measure 'Taux SI - hors intérim' = EXTERNALMEASURE("Taux SI - hors intérim", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\02 - Effectif suivi\2.2. Hors intérimaires
			lineageTag: fb739c25-274c-4e72-9463-0d12790c1db9
			sourceLineageTag: 13311cb3-b840-4a5f-80cf-4aa0b0087960
			dataCategory: Uncategorized

		measure 'Taux SI - intérim uniquement' = EXTERNALMEASURE("Taux SI - intérim uniquement", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\02 - Effectif suivi\2.3. Intérimaires uniquement
			lineageTag: 3a9a61fe-d258-4916-89c2-acd3fb2c2467
			sourceLineageTag: cd1e43b3-5103-4e2b-930c-6d8a13458997
			dataCategory: Uncategorized

		measure 'Taux SI total' = EXTERNALMEASURE("Taux SI total", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\02 - Effectif suivi\2.1. Total
			lineageTag: f03bcba8-38ca-4ddd-90b2-e2497bcfa1d6
			sourceLineageTag: ac5197b1-f0a2-482e-b301-6abc50f5361c
			dataCategory: Uncategorized

		measure 'Taux SIA - hors intérim' = EXTERNALMEASURE("Taux SIA - hors intérim", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\02 - Effectif suivi\2.2. Hors intérimaires
			lineageTag: 91bb07be-1d76-4912-8ea3-c964f37d2073
			sourceLineageTag: a52a80be-234e-434d-9f4b-a6cc3b9ae6ec
			dataCategory: Uncategorized

		measure 'Taux SIA - intérim uniquement' = EXTERNALMEASURE("Taux SIA - intérim uniquement", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\02 - Effectif suivi\2.3. Intérimaires uniquement
			lineageTag: 8344e53e-69b7-47d2-8744-5ead294236a4
			sourceLineageTag: 11c5b197-5127-4f79-98f8-0fb972380e1d
			dataCategory: Uncategorized

		measure 'Taux SIA total' = EXTERNALMEASURE("Taux SIA total", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\02 - Effectif suivi\2.1. Total
			lineageTag: ca30eb6b-5476-4cee-82c8-c34f4e5e93a3
			sourceLineageTag: 50f1b60b-3e6e-4ea5-aecf-a94f509c9761
			dataCategory: Uncategorized

		measure 'Taux SIR - hors intérim' = EXTERNALMEASURE("Taux SIR - hors intérim", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\02 - Effectif suivi\2.2. Hors intérimaires
			lineageTag: f183f701-cd20-4185-8d59-9af86361c05a
			sourceLineageTag: 61dfbc3f-dd44-4906-9749-eb9f5c1f038b
			dataCategory: Uncategorized

		measure 'Taux SIR - intérim uniquement' = EXTERNALMEASURE("Taux SIR - intérim uniquement", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\02 - Effectif suivi\2.3. Intérimaires uniquement
			lineageTag: 1ae01742-9f46-4ea8-92cb-fcbccac77aad
			sourceLineageTag: a665d37f-07ab-4f60-8bb1-9bb85c7bbf50
			dataCategory: Uncategorized

		measure 'Taux SIR total' = EXTERNALMEASURE("Taux SIR total", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\02 - Effectif suivi\2.1. Total
			lineageTag: 1bd89ef9-ef23-48c3-82a2-c2ccba232735
			sourceLineageTag: af7c0ac5-741f-4cd3-93a8-6e5d16634ab9
			dataCategory: Uncategorized

		measure 'Turn over' = EXTERNALMEASURE("Turn over", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			displayFolder: Indicateurs\09 - Score card\Taux
			lineageTag: acfab298-66cb-4469-9ef0-50134346f286
			sourceLineageTag: 1c7630af-a896-425a-9ded-6d4ac57edc70
			dataCategory: Uncategorized

		measure 'Valeur moyenne par entreprise de la satisfaction salarié' = EXTERNALMEASURE("Valeur moyenne par entreprise de la satisfaction salarié", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs\09 - Score card
			lineageTag: 620bda43-9e77-4b85-a655-0b9bc9b91f2f
			sourceLineageTag: c11b3b46-6392-4135-8b1e-523a025ea361
			dataCategory: Uncategorized

		measure 'Variation effectif' = EXTERNALMEASURE("Variation effectif", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			displayFolder: Indicateurs\09 - Score card\Taux
			lineageTag: a9914f86-1d06-49b5-9c4c-dd52cbe469d2
			sourceLineageTag: 60ad68df-3493-4efe-852f-eecc962afa73
			dataCategory: Uncategorized

	ref table AMT

		measure '# AMT en cours réalisables avec le module FE' = EXTERNALMEASURE("# AMT en cours réalisables avec le module FE", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\5 - Module FE\Comptage
			lineageTag: 9ed8e918-6fa4-4e7c-b0c2-cee3c9d0f861
			sourceLineageTag: 8a89b65f-bfaa-4e63-876d-c302ad1d5020
			dataCategory: Uncategorized

		measure '# AMT en cours réalisées avec le module FE' = EXTERNALMEASURE("# AMT en cours réalisées avec le module FE", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\5 - Module FE\Comptage
			lineageTag: 97fc95e4-0d50-418f-9bc6-5771fd722c90
			sourceLineageTag: 8a3cc7c7-7773-48f6-b9cb-f825bc37ca0b
			dataCategory: Uncategorized

		measure '# AMT terminées avec une FE générée avec le module FE' = EXTERNALMEASURE("# AMT terminées avec une FE générée avec le module FE", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\5 - Module FE\Comptage
			lineageTag: 1562e026-0f4a-4217-a460-60ac80325e99
			sourceLineageTag: 3931efbf-3182-4c49-8038-9ae35e895312
			dataCategory: Uncategorized

		measure '# AMT terminées réalisables avec le module FE' = EXTERNALMEASURE("# AMT terminées réalisables avec le module FE", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\5 - Module FE\Comptage
			lineageTag: 7533e95a-11ec-4912-959c-ac43497359ec
			sourceLineageTag: 00893025-f584-49fd-b7ff-6024053beb7d
			dataCategory: Uncategorized

		measure '# salariés couverts (AMT)' = EXTERNALMEASURE("# salariés couverts (AMT)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Autres comptages
			lineageTag: 520a5998-4a0c-4c7b-8473-f363f8c43568
			sourceLineageTag: 2e75cbfc-ff69-47b2-9d14-6c6de12cac7c
			dataCategory: Uncategorized

		measure '% AMT en cours réalisées avec le module FE' = EXTERNALMEASURE("% AMT en cours réalisées avec le module FE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: fc0cd7fe-aa0f-4735-920b-e56458104e02
			sourceLineageTag: 9a0620fb-54fa-4320-8e99-1d4a3fe2db6e
			dataCategory: Uncategorized

		measure '% AMT terminées avec une FE générée avec le module FE' = EXTERNALMEASURE("% AMT terminées avec une FE générée avec le module FE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: c76ce998-4346-4746-b316-7abcf667ac06
			sourceLineageTag: 0b2eb305-8fe3-4aff-b3b1-5b43cf925ebe
			dataCategory: Uncategorized

		measure '% AMT terminées avec une FE importée avec le module FE' = EXTERNALMEASURE("% AMT terminées avec une FE importée avec le module FE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 06be2550-0e98-44d5-b6c3-2cb4cb4f3711
			sourceLineageTag: bc2b71e1-26e8-49dd-a3c7-85f6b8ced6d6
			dataCategory: Uncategorized

		measure 'Durée estimée totale (en heures)' = EXTERNALMEASURE("Durée estimée totale (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Durées estimées\Par AMT
			lineageTag: ff73398d-5d58-4f6e-a232-c88f35f9da85
			sourceLineageTag: d985887a-b915-44e4-8a49-67892bc9a63f
			dataCategory: Uncategorized

		measure 'Durée estimée totale chez l''adhérent (en heures)' = EXTERNALMEASURE("Durée estimée totale chez l'adhérent (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Durées estimées\Par AMT
			lineageTag: ccd486a0-51bf-43a6-82eb-0a07d41d181b
			sourceLineageTag: 158c2e5f-ed34-42f0-a5e8-dd3adc1700f9
			dataCategory: Uncategorized

		measure 'Durée estimée totale intervenant (en heures)' = EXTERNALMEASURE("Durée estimée totale intervenant (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Durées estimées\Par intervenant
			lineageTag: 7c18a22e-36a0-45d6-8632-0481cd5ac814
			sourceLineageTag: 403786c7-6b92-4f64-86c2-47b823d11dd1
			dataCategory: Uncategorized

		measure 'Durée estimée totale intervenant chez l''adhérent (en heures)' = EXTERNALMEASURE("Durée estimée totale intervenant chez l'adhérent (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Durées estimées\Par intervenant
			lineageTag: 2947999c-4300-4c6c-b700-34d81889890f
			sourceLineageTag: 90bb596e-884a-4fb2-b26f-2aecd47b37b5
			dataCategory: Uncategorized

		measure 'Durée estimée totale moyenne (en heures)' = EXTERNALMEASURE("Durée estimée totale moyenne (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs\3 - Durées estimées\Par AMT
			lineageTag: b93b7011-4d62-47f5-ad32-4c7e815625b5
			sourceLineageTag: ee2b0edb-bdb7-44a2-99f5-4d0f75d2d2fa
			dataCategory: Uncategorized

		measure 'Durée estimée totale moyenne intervenant (en heures)' = EXTERNALMEASURE("Durée estimée totale moyenne intervenant (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs\3 - Durées estimées\Par intervenant
			lineageTag: ef3dc11d-8c9d-4726-b359-712c4a5323af
			sourceLineageTag: ada07e87-1af6-4482-a314-2f2eb3580dbb
			dataCategory: Uncategorized

		measure 'Durée réelle évènements planning' = EXTERNALMEASURE("Durée réelle évènements planning", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Durées réelles\Par AMT
			lineageTag: 83cfc8e1-1cd7-43fd-afd7-fc809cbe3e51
			sourceLineageTag: 82a6e511-5784-44c5-9806-f989909cee2f
			dataCategory: Uncategorized

		measure 'Durée réelle intervention (en heures)' = EXTERNALMEASURE("Durée réelle intervention (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Durées réelles\Par AMT
			lineageTag: f1329423-689d-45d7-86c7-88eed7853606
			sourceLineageTag: 226a6735-e754-4a89-82ee-62dfdc7fdfe5
			dataCategory: Uncategorized

		measure 'Durée réelle intervention intervenant (en heures)' = EXTERNALMEASURE("Durée réelle intervention intervenant (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Durées réelles\Par intervenant
			lineageTag: f19f9416-e69d-4454-ac02-70753828c64f
			sourceLineageTag: 15874a28-4fa5-494f-9e66-13895ae3e9f6
			dataCategory: Uncategorized

		measure 'Durée réelle rédaction (en heures)' = EXTERNALMEASURE("Durée réelle rédaction (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Durées réelles\Par AMT
			lineageTag: 1140b6f3-5832-4d6d-b42d-5031fb9a1793
			sourceLineageTag: c5180dfc-c5dd-4634-91df-99873045cdc9
			dataCategory: Uncategorized

		measure 'Durée réelle rédaction intervenant (en heures)' = EXTERNALMEASURE("Durée réelle rédaction intervenant (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Durées réelles\Par intervenant
			lineageTag: 9c87771c-e7f7-44d5-a1f7-d7d529281a9e
			sourceLineageTag: 4d1616c6-80bf-4a21-b915-5f8e4f60b902
			dataCategory: Uncategorized

		measure 'Durée réelle totale (en heures)' = EXTERNALMEASURE("Durée réelle totale (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Durées réelles\Par AMT
			lineageTag: 2a977639-1ee6-4f19-9c2f-5d18c77c91c9
			sourceLineageTag: 5bc858ec-bb9b-4ab3-aae2-42bfa53ea2b5
			dataCategory: Uncategorized

		measure 'Durée réelle totale intervenant (en heures)' = EXTERNALMEASURE("Durée réelle totale intervenant (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Durées réelles\Par intervenant
			lineageTag: 27ef3ed1-64bf-4679-9282-551a42ade658
			sourceLineageTag: 663721b4-25f0-427f-8e22-c7b726da6117
			dataCategory: Uncategorized

		measure 'Durée réelle totale moyenne (en heures)' = EXTERNALMEASURE("Durée réelle totale moyenne (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs\4 - Durées réelles\Par AMT
			lineageTag: d74a6ef9-0ac4-4ef1-bb76-3d63ed0d2534
			sourceLineageTag: 18e40111-aeaf-461b-b865-c2875651f6be
			dataCategory: Uncategorized

		measure 'Durée réelle totale moyenne intervenant (en heures)' = EXTERNALMEASURE("Durée réelle totale moyenne intervenant (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs\4 - Durées réelles\Par intervenant
			lineageTag: e5cd93aa-f16d-4efa-9d0b-a8f472a12e02
			sourceLineageTag: 0a2dafbf-eb7d-4981-aaa3-7d8ac328a2de
			dataCategory: Uncategorized

		measure 'Durée réelle trajet (en heures)' = EXTERNALMEASURE("Durée réelle trajet (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Durées réelles\Par AMT
			lineageTag: 4742e170-dd59-4378-a1a3-59f8dbb6040f
			sourceLineageTag: 2734260a-2f17-46f1-b6b4-53a487685778
			dataCategory: Uncategorized

		measure 'Durée réelle trajet intervenant (en heures)' = EXTERNALMEASURE("Durée réelle trajet intervenant (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Durées réelles\Par intervenant
			lineageTag: 0d489104-98e7-44e7-828b-bedc1d33ea17
			sourceLineageTag: dd9e330d-33a0-4f12-ab1b-3ae022351b3e
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents concernés' = EXTERNALMEASURE("Nombre d'adhérents concernés", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Autres comptages\Périmètre
			lineageTag: 01479d9f-f037-42cb-abf1-e5cc2b7599bc
			sourceLineageTag: 4fd494d7-2795-4121-bc4e-0031f709bfdc
			dataCategory: Uncategorized

		measure 'Nombre d''AMT annulées' = EXTERNALMEASURE("Nombre d'AMT annulées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Comptages AMT principaux
			lineageTag: 3d80ebff-a6c7-4712-955e-3101374b789d
			sourceLineageTag: 8671c258-ac46-494c-9048-98f6d5f6a399
			dataCategory: Uncategorized

		measure 'Nombre d''AMT en cours d''exécution' = EXTERNALMEASURE("Nombre d'AMT en cours d'exécution", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Comptages AMT principaux
			lineageTag: e1cb1a2a-f41d-4593-867b-bb911380be68
			sourceLineageTag: 4d8f8d4d-b9b0-4196-a2a4-8ad8075978d7
			dataCategory: Uncategorized

		measure 'Nombre d''AMT suspendues' = EXTERNALMEASURE("Nombre d'AMT suspendues", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Comptages AMT principaux
			lineageTag: affc7859-548e-4f80-aaca-5366caa987d5
			sourceLineageTag: 46f60f4d-081b-4bae-8b4a-7daab15c583d
			dataCategory: Uncategorized

		measure 'Nombre d''AMT terminées' = EXTERNALMEASURE("Nombre d'AMT terminées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Comptages AMT principaux
			lineageTag: a66c7605-4348-46bb-9e28-14cd57fdecdd
			sourceLineageTag: 6dda7169-0730-4e7d-b0fc-3cc6f0a6d7f8
			dataCategory: Uncategorized

		measure 'Nombre d''entreprises concernées (AMT)' = EXTERNALMEASURE("Nombre d'entreprises concernées (AMT)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Indicateurs\2 - Autres comptages
			lineageTag: 16408524-eee2-4b73-8ea7-780ecc362cfb
			sourceLineageTag: 2c4693ac-e01d-4a1b-9638-10a169586b2f
			dataCategory: Uncategorized

		measure 'Nombre d''évènements' = EXTERNALMEASURE("Nombre d'évènements", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Autres comptages
			lineageTag: b77629fe-e4b8-4095-9c72-ddd15a98ac8f
			sourceLineageTag: 7eff86ff-b1d5-44bb-936a-31bfcac3e280
			dataCategory: Uncategorized

		measure 'Nombre de certificats d''inaptitudes délivrés suite à l''AMT' = EXTERNALMEASURE("Nombre de certificats d'inaptitudes délivrés suite à l'AMT", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Autres comptages
			lineageTag: 4a8b4355-8650-4b46-9c36-81da56203d1a
			sourceLineageTag: ff73478e-b180-458f-b661-fe9c7737725a
			dataCategory: Uncategorized

		measure 'Nombre de salariés concernés' = EXTERNALMEASURE("Nombre de salariés concernés", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Autres comptages\Périmètre
			lineageTag: 50e71741-f6bd-4a79-ab1e-a053da32c5db
			sourceLineageTag: 4282622f-4333-43f2-8cd9-1e2d8701aeb8
			dataCategory: Uncategorized

		measure 'Nombre de salariés concernés (AMT)' = EXTERNALMEASURE("Nombre de salariés concernés (AMT)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Indicateurs\2 - Autres comptages
			lineageTag: 2c560aba-5cd3-4d87-ac9f-c737c060b597
			sourceLineageTag: ddcb7d60-58cd-4d2a-8678-e8018f210e0d
			dataCategory: Uncategorized

		measure 'Nombre de tâches planifiées' = EXTERNALMEASURE("Nombre de tâches planifiées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Autres comptages\Tâches
			lineageTag: a622f1ca-a1c2-4bc8-8be3-66f2766135cf
			sourceLineageTag: 8f5aadd3-69de-4b75-8cff-f8aae3916dd2
			dataCategory: Uncategorized

		measure 'Nombre de tâches réalisées' = EXTERNALMEASURE("Nombre de tâches réalisées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Autres comptages\Tâches
			lineageTag: 64372fa1-5fb7-49ad-a972-4344f5efe80b
			sourceLineageTag: 05ceb302-27c8-4d6c-9264-b70a0d5860fd
			dataCategory: Uncategorized

		measure 'Nombre moyen d''intervenants' = EXTERNALMEASURE("Nombre moyen d'intervenants", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0
			displayFolder: Indicateurs\2 - Autres comptages\Intervenants
			lineageTag: 0eb292bf-6267-45da-b3b2-8239d7a6c69a
			sourceLineageTag: 567c86d8-f0ad-4b65-8875-37e43c758cf3
			dataCategory: Uncategorized

		measure 'Nombre total d''AMT' = EXTERNALMEASURE("Nombre total d'AMT", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Comptages AMT principaux
			lineageTag: 4c207f26-4747-49e6-abb7-738d15883f13
			sourceLineageTag: 88f51409-3c94-4f5e-a453-490bf97450b0
			dataCategory: Uncategorized

		measure 'Nombre total d''intervenants' = EXTERNALMEASURE("Nombre total d'intervenants", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Autres comptages\Intervenants
			lineageTag: b0473ac9-2f74-431d-91c5-61a45dc05467
			sourceLineageTag: b241a786-a326-4c49-a4a9-8318cae49a49
			dataCategory: Uncategorized

	ref table 'AMT - indicateurs par intervenant'

		measure 'Durée totale estimée' = EXTERNALMEASURE("Durée totale estimée", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Indicateurs
			lineageTag: 5081f252-ee68-42c0-b67d-4d8125f0bb45
			sourceLineageTag: bca2ad6f-7baa-4082-b2eb-165308a55cdc
			dataCategory: Uncategorized

		measure 'Durée totale estimée chez l''adhérent' = EXTERNALMEASURE("Durée totale estimée chez l'adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Indicateurs
			lineageTag: 6a04d6ae-4e38-4d04-a1a0-d7ab219a40da
			sourceLineageTag: 446e3cbd-4832-48a5-b49e-91c54b9a808a
			dataCategory: Uncategorized

		measure 'Durée totale réelle intervention' = EXTERNALMEASURE("Durée totale réelle intervention", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Indicateurs
			lineageTag: 9aa3d89c-c41a-449c-8863-ffb05a0e4703
			sourceLineageTag: c95bba56-695b-4804-91fb-aeff329e0937
			dataCategory: Uncategorized

		measure 'Durée totale réelle redaction' = EXTERNALMEASURE("Durée totale réelle redaction", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Indicateurs
			lineageTag: d7e810dc-6528-49af-b631-62d3edf1435b
			sourceLineageTag: 184116bb-add1-4c73-8541-406839cce437
			dataCategory: Uncategorized

		measure 'Durée totale réelle trajet' = EXTERNALMEASURE("Durée totale réelle trajet", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Indicateurs
			lineageTag: 5f691dd7-1130-4553-9f48-2130d29c2c3e
			sourceLineageTag: ed2b1e5b-72df-4789-99f9-0ca02e1789e4
			dataCategory: Uncategorized

	ref table 'AMT v2'

		measure '# AMT' = EXTERNALMEASURE("# AMT", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 4dbe7e51-a50c-4489-bd9b-f5828daea9d4
			sourceLineageTag: 3b9109ff-9c18-4018-81ce-bcda51ebc606
			dataCategory: Uncategorized

		measure '# AMT annulées' = EXTERNALMEASURE("# AMT annulées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: b9e053b9-f76c-4a44-9cd5-80b25f9ff7f5
			sourceLineageTag: 5e837b2f-d0a5-4529-b340-b585526e8441
			dataCategory: Uncategorized

		measure '# AMT en cours' = EXTERNALMEASURE("# AMT en cours", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 4f1a2932-bc80-4214-81eb-64c85303d040
			sourceLineageTag: 7f40c98d-1c01-4b69-b537-e2af0cddb3bc
			dataCategory: Uncategorized

		measure '# AMT en cours réalisables avec le module' = EXTERNALMEASURE("# AMT en cours réalisables avec le module", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 4 - Module FE
			lineageTag: 3b10dff1-ea50-4412-a6f9-c16d09fdbf10
			sourceLineageTag: 00d6300e-d7e2-4a9e-8d99-569afe28a6ee
			dataCategory: Uncategorized

		measure '# AMT en cours réalisées avec le module' = EXTERNALMEASURE("# AMT en cours réalisées avec le module", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 4 - Module FE
			lineageTag: 1df96512-6af7-44f6-a764-6989bd4c38fe
			sourceLineageTag: 957b3b8e-831d-436a-b3ba-4fcfd67ba40d
			dataCategory: Uncategorized

		measure '# AMT par entreprise' = EXTERNALMEASURE("# AMT par entreprise", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 1ee57bff-5e90-4e4e-9342-9cc6f2b7bc8a
			sourceLineageTag: b72829e0-a3fc-41c2-8345-4e00477bbec9
			dataCategory: Uncategorized

		measure '# AMT suspendues' = EXTERNALMEASURE("# AMT suspendues", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 57804ced-ca6f-4139-a565-2850b6faa9cf
			sourceLineageTag: 32d9276f-bd45-45ec-9da3-353dbca3ca70
			dataCategory: Uncategorized

		measure '# AMT terminées' = EXTERNALMEASURE("# AMT terminées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 8d5639b3-7bc0-4358-9b25-43b46a3edfb8
			sourceLineageTag: 0787416e-4ac5-4436-af74-d606c12eb9aa
			dataCategory: Uncategorized

		measure '# AMT terminées avec le module' = EXTERNALMEASURE("# AMT terminées avec le module", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 4 - Module FE
			lineageTag: eb51ff9a-1c35-4515-ad54-b7cb37b8ba44
			sourceLineageTag: b6e2cd44-98c0-460f-94c3-038cec09479d
			dataCategory: Uncategorized

		measure '# AMT terminées réalisables avec le module' = EXTERNALMEASURE("# AMT terminées réalisables avec le module", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 4 - Module FE
			lineageTag: 0bfc3ebe-0d26-44fe-a73f-a01a1228be0b
			sourceLineageTag: 590ed288-8149-4b79-a83a-24e50bd8befd
			dataCategory: Uncategorized

		measure '# autre type évènement' = EXTERNALMEASURE("# autre type évènement", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: a121ad4f-fc22-4ded-8a40-7a4be2522743
			sourceLineageTag: e1a26778-ca1a-431c-9b08-171780275ff7
			dataCategory: Uncategorized

		measure '# collections concernées (AMT)' = EXTERNALMEASURE("# collections concernées (AMT)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 2e25eec8-fba5-45da-a606-17c0e2d9ce94
			sourceLineageTag: 1274a5ac-3b59-4886-8213-337317988fb9
			dataCategory: Uncategorized

		measure '# entreprises concernées (AMT)' = EXTERNALMEASURE("# entreprises concernées (AMT)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 4c0e6ff2-25c3-4d78-9008-4b29f38bf1a6
			sourceLineageTag: be80b144-7357-4fb9-8d7d-faa3f66a8f44
			dataCategory: Uncategorized

		measure '# évènement collectif' = EXTERNALMEASURE("# évènement collectif", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: f59e67df-0d88-4dda-b149-709727e5dfec
			sourceLineageTag: cb84b360-0fd7-4663-a79f-b57b58f0caaa
			dataCategory: Uncategorized

		measure '# évènement collectif (AMT)' = EXTERNALMEASURE("# évènement collectif (AMT)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 624b4988-f05b-4b2b-999d-f466bd121e80
			sourceLineageTag: 924d6ab9-2eef-4b31-a516-6f2146825473
			dataCategory: Uncategorized

		measure '# évènements total' = EXTERNALMEASURE("# évènements total", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: cdf62c40-f7a6-4eff-bce8-4eafcd1abf28
			sourceLineageTag: 951708d8-7a26-4378-942b-c3ddda7893bd
			dataCategory: Uncategorized

		measure '# intervenants' = EXTERNALMEASURE("# intervenants", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 3dd2ba21-318e-4257-8d9e-a9f4ab30f9de
			sourceLineageTag: d1601293-feaf-4102-9609-7cfb1e2a2d92
			dataCategory: Uncategorized

		measure '# intervention' = EXTERNALMEASURE("# intervention", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: 3b4b06df-a8d7-4e04-b52b-eaf32f9e800a
			sourceLineageTag: c5f18168-e86e-46ec-a38e-dfa10e6f9f11
			dataCategory: Uncategorized

		measure '# intervention (AMT)' = EXTERNALMEASURE("# intervention (AMT)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 196f1055-48b1-49c8-8184-5305a083f4d0
			sourceLineageTag: c5793f7f-1382-46ff-aabf-4d61f543f52d
			dataCategory: Uncategorized

		measure '# rédaction' = EXTERNALMEASURE("# rédaction", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: a1cbd789-e090-44dc-92be-9b927d58a381
			sourceLineageTag: 09ae50b5-0905-42e5-a4f0-77385944ec47
			dataCategory: Uncategorized

		measure '# salariés concernés (AMT périmètre salarié)' = EXTERNALMEASURE("# salariés concernés (AMT périmètre salarié)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 7465d03b-d11a-49e4-8762-e2420df291cd
			sourceLineageTag: a5d7f354-27b4-491d-8dc2-025dddcdb001
			dataCategory: Uncategorized

		measure '# salariés couverts' = EXTERNALMEASURE("# salariés couverts", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 238d8c2c-9762-4c73-86f4-86cf3e76590b
			sourceLineageTag: 79b36645-8b10-4725-8931-c4a35fe06678
			dataCategory: Uncategorized

		measure '# tâches planifiées' = EXTERNALMEASURE("# tâches planifiées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 82eb71bb-9e7f-4455-919a-833f15d7406a
			sourceLineageTag: 7a63385c-104a-4b4b-b0dc-0ef1206526e6
			dataCategory: Uncategorized

		measure '# tâches réalisées' = EXTERNALMEASURE("# tâches réalisées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 5fa3d571-3e2c-49aa-8ac8-700ce290469c
			sourceLineageTag: 68e444cd-e22a-4547-a9c4-bd20ad960a66
			dataCategory: Uncategorized

		measure '% AMT en cours réalisées avec le module' = EXTERNALMEASURE("% AMT en cours réalisées avec le module", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 9d4cb818-a694-4170-bd64-68f3b07f142c
			sourceLineageTag: f33498a9-ea1b-4986-99bf-b02c662bd701
			dataCategory: Uncategorized

		measure '% AMT terminées avec le module' = EXTERNALMEASURE("% AMT terminées avec le module", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 7585d205-ab59-4834-961d-762e5131b95b
			sourceLineageTag: 62b0f722-712a-443b-87ae-ed23735021e8
			dataCategory: Uncategorized

		measure 'Durée autre type évènement (h)' = EXTERNALMEASURE("Durée autre type évènement (h)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: 0a2b5bf8-ec08-4993-89a3-eaeb23970608
			sourceLineageTag: e1725624-6b8b-43ad-8b6b-b834e095ab05
			dataCategory: Uncategorized

		measure 'Durée estimée action (h)' = EXTERNALMEASURE("Durée estimée action (h)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: 3 - Durées estimées / réelles (fois intervenant)
			lineageTag: d7aaf7ae-ab27-4d36-a03f-634ddecf532e
			sourceLineageTag: e98efc00-54ff-455b-ad36-bba357050f5c
			dataCategory: Uncategorized

		measure 'Durée estimée chez l''adhérent (h)' = EXTERNALMEASURE("Durée estimée chez l'adhérent (h)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: 3 - Durées estimées / réelles (fois intervenant)
			lineageTag: f09aecd1-f13c-432c-b082-8de5b4e9a8fe
			sourceLineageTag: 3987dc76-4e3f-49d2-a6ac-83c98a8c390c
			dataCategory: Uncategorized

		measure 'Durée évènement collectif (AMT)' = EXTERNALMEASURE("Durée évènement collectif (AMT)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: 1 - AMT
			lineageTag: e397eef0-0f8d-49e7-bda4-b62d29f0ba56
			sourceLineageTag: 812deb84-0bca-49c8-81b0-0d44e07b4ad7
			dataCategory: Uncategorized

		measure 'Durée évènement collectif (h)' = EXTERNALMEASURE("Durée évènement collectif (h)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: c8ae1c35-3dcd-435e-80b7-70173d820f8f
			sourceLineageTag: 1617999a-e547-4011-985a-d9a082f0d07d
			dataCategory: Uncategorized

		measure 'Durée intervention (AMT)' = EXTERNALMEASURE("Durée intervention (AMT)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: 1 - AMT
			lineageTag: 33a24aac-3e36-4b0c-a1a6-3f19eb4465b5
			sourceLineageTag: a0f878dd-d5b0-4891-ab95-186b9d1c2b52
			dataCategory: Uncategorized

		measure 'Durée intervention (h)' = EXTERNALMEASURE("Durée intervention (h)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: 2dc0d3a8-2c50-440b-a7a3-bb93541de384
			sourceLineageTag: aac086ec-bbf4-4bde-91f7-70a9527daaed
			dataCategory: Uncategorized

		measure 'Durée rédaction (h)' = EXTERNALMEASURE("Durée rédaction (h)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: 5102e586-0466-4093-b541-5b301a5ee782
			sourceLineageTag: e29b46e6-c469-46f5-ba91-32e778b1291c
			dataCategory: Uncategorized

		measure 'Durée réelle intervention (h)' = EXTERNALMEASURE("Durée réelle intervention (h)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: 3 - Durées estimées / réelles (fois intervenant)
			lineageTag: 5bee3929-08e5-48a5-9b24-358d616d409c
			sourceLineageTag: ff3a41d0-f134-4ff6-b636-d5a89935149d
			dataCategory: Uncategorized

		measure 'Durée réelle rédaction (h)' = EXTERNALMEASURE("Durée réelle rédaction (h)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: 3 - Durées estimées / réelles (fois intervenant)
			lineageTag: 5d07d470-7762-444b-8ae4-fb7edd09510c
			sourceLineageTag: 686a8bd2-5ffb-43fa-9ace-e1ebf7d801a7
			dataCategory: Uncategorized

		measure 'Durée réelle totale (h)' = EXTERNALMEASURE("Durée réelle totale (h)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: 3 - Durées estimées / réelles (fois intervenant)
			lineageTag: b7608023-f7b9-4b2a-909b-65d14ff45580
			sourceLineageTag: 7a09ae9a-6306-4eaf-8d4f-0a9d4fdadf3d
			dataCategory: Uncategorized

		measure 'Durée réelle trajet (h)' = EXTERNALMEASURE("Durée réelle trajet (h)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: 3 - Durées estimées / réelles (fois intervenant)
			lineageTag: ca29e9bc-e2ce-4ac6-b50d-b3f09b6edfa2
			sourceLineageTag: 82c85277-4119-4e4f-8e63-d46954cad5de
			dataCategory: Uncategorized

		measure 'Durée totale des évènements (h)' = EXTERNALMEASURE("Durée totale des évènements (h)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: 344eb630-1ae1-430b-8a3c-6ecdb622d08c
			sourceLineageTag: 5751d20c-dfab-4dc3-aac9-d0867ef8ec6a
			dataCategory: Uncategorized

	ref table 'Changement équipe médicale'

		measure '# adhérents ayant changé d''équipe médicale' = EXTERNALMEASURE("# adhérents ayant changé d'équipe médicale", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Changement équipe médicale
			lineageTag: 06bfd70c-095c-4d3b-afe7-ddc299b411f3
			sourceLineageTag: f58b1089-d060-4f12-a580-63fc6e1e069f
			dataCategory: Uncategorized

		measure '# adhérents ayant changé de médecin référent' = EXTERNALMEASURE("# adhérents ayant changé de médecin référent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Changement médecin référent
			lineageTag: 274969b8-d206-435d-9677-dc9ef56ea025
			sourceLineageTag: 4ea860c3-753d-4292-8472-f0181d3366a6
			dataCategory: Uncategorized

		measure '# changements d''équipes médicales' = EXTERNALMEASURE("# changements d'équipes médicales", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Changement équipe médicale
			lineageTag: 6e1c367a-1124-464f-8648-3ce3057b60ce
			sourceLineageTag: fde4a930-a760-4be1-a873-ef4b8a0cf894
			dataCategory: Uncategorized

		measure '# changements de médecins référents' = EXTERNALMEASURE("# changements de médecins référents", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Changement médecin référent
			lineageTag: ed294176-d97f-4ef6-ad8d-91a2bbd3d76e
			sourceLineageTag: f6d6dd41-d0c1-441f-a597-172a3d03fff0
			dataCategory: Uncategorized

		measure 'Effectif suivi intérimaire ayant changé d''équipe médicale' = EXTERNALMEASURE("Effectif suivi intérimaire ayant changé d'équipe médicale", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Changement équipe médicale
			lineageTag: d72b0c4d-bbf1-426b-aa2f-0d627726a9d3
			sourceLineageTag: 7e944232-2c9d-46f5-bdc4-1775957eabb4
			dataCategory: Uncategorized

		measure 'Effectif suivi intérimaire ayant changé de médecin référent' = EXTERNALMEASURE("Effectif suivi intérimaire ayant changé de médecin référent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Changement médecin référent
			lineageTag: 96ca3a38-e38f-4f45-bcad-8f04d6914756
			sourceLineageTag: 7b5ef41d-457a-4215-955d-45e3a922a994
			dataCategory: Uncategorized

		measure 'Effectif suivi non intérimaire ayant changé d''équipe médicale' = EXTERNALMEASURE("Effectif suivi non intérimaire ayant changé d'équipe médicale", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Changement équipe médicale
			lineageTag: be0bfe43-d70e-498c-953c-4d6d435df73c
			sourceLineageTag: efdcfe76-9668-4698-b25d-42ea51b3b3ea
			dataCategory: Uncategorized

		measure 'Effectif suivi non intérimaire ayant changé de médecin référent' = EXTERNALMEASURE("Effectif suivi non intérimaire ayant changé de médecin référent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Changement médecin référent
			lineageTag: cd86a2a4-ace7-4a5e-b608-56d44b71dfd0
			sourceLineageTag: 1bce1476-107e-4819-9719-b1a14fb129fe
			dataCategory: Uncategorized

	ref table 'CRM - activités'

		measure '# activités' = EXTERNALMEASURE("# activités", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			lineageTag: 73fe3354-6228-407b-8d17-f4aa79a6ca28
			sourceLineageTag: 0722818f-536e-4b22-a667-1e5f6b4d2c9e
			dataCategory: Uncategorized

		measure '# changements de responsable du ticket' = EXTERNALMEASURE("# changements de responsable du ticket", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			lineageTag: e5c386c1-93e5-471c-aa01-a36fa57724e6
			sourceLineageTag: 3d023155-8800-4731-802f-f10b6e4534d0
			dataCategory: Uncategorized

		measure '# changements de statut du ticket' = EXTERNALMEASURE("# changements de statut du ticket", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			lineageTag: 277ffbfa-da0a-4fed-81dc-608caa0dcaa9
			sourceLineageTag: 868d59c4-fd37-4236-aa42-c192c3aeea1b
			dataCategory: Uncategorized

		measure '# comptes rendus' = EXTERNALMEASURE("# comptes rendus", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			lineageTag: 90a18b21-e65e-438a-bccf-b675029a7c84
			sourceLineageTag: d2b567b3-1364-4e1c-9217-af79117e54aa
			dataCategory: Uncategorized

		measure '# notes' = EXTERNALMEASURE("# notes", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			lineageTag: 7fe85996-5884-4e37-957c-bccda14bae8b
			sourceLineageTag: fd204bf3-15ab-4efc-b5b9-fc140d4d5487
			dataCategory: Uncategorized

	ref table 'CRM - tickets'

		measure '# tickets' = EXTERNALMEASURE("# tickets", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			lineageTag: 9adb8001-20eb-408a-9205-9e9a26ea60ef
			sourceLineageTag: de9de7a1-e126-4cc7-9721-dc8e6ad67bb4
			dataCategory: Uncategorized

		measure '# tickets en retard' = EXTERNALMEASURE("# tickets en retard", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			lineageTag: d03d3a49-f3ea-4634-b1c7-b2f4a2792f98
			sourceLineageTag: 48f7accf-311f-4237-82bf-ed96feddf4b6
			dataCategory: Uncategorized

		measure '# tickets fermés' = EXTERNALMEASURE("# tickets fermés", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			lineageTag: 2f41a060-73cf-4e07-b7ad-cb2e6237614c
			sourceLineageTag: 04bd1266-1254-46ad-83d1-38941c9a5f7b
			dataCategory: Uncategorized

		measure '# tickets ouverts' = EXTERNALMEASURE("# tickets ouverts", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			lineageTag: e3da878b-658a-45ee-abf6-dc82b0477cda
			sourceLineageTag: b79c34c7-6c39-4a9a-888e-be5734380424
			dataCategory: Uncategorized

		measure 'Durée moyenne retard tickets (j)' = EXTERNALMEASURE("Durée moyenne retard tickets (j)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			lineageTag: 0709d448-85cb-4366-8961-2de2929b4d33
			sourceLineageTag: 25857bee-bb24-4e58-bbdf-dd7b696ac7f4
			dataCategory: Uncategorized

		measure 'Durée moyenne traitement tickets (j)' = EXTERNALMEASURE("Durée moyenne traitement tickets (j)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			lineageTag: 88215c36-68ae-4269-a56d-d568d786735f
			sourceLineageTag: 7940e07e-7d2c-4b10-adf1-b39d54495c11
			dataCategory: Uncategorized
		

	ref table 'Déclaration effectif'

		measure 'Délai moyen de renouvellement de la déclaration' = EXTERNALMEASURE("Délai moyen de renouvellement de la déclaration", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0
			displayFolder: Indicateurs\4 - Durées
			lineageTag: cde66601-6bce-4f38-8197-2b6f458b7011
			sourceLineageTag: 6176ebb4-77e8-496a-960a-abdc602e48df
			dataCategory: Uncategorized

		measure 'Durée moyenne du parcours de déclaration' = EXTERNALMEASURE("Durée moyenne du parcours de déclaration", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs\4 - Durées
			lineageTag: 0968bbf1-c60d-4926-abe1-1da21190dc66
			sourceLineageTag: 54e10161-1021-49a3-a119-f0c5b6c872b4
			dataCategory: Uncategorized

		measure 'Effectif déclaré' = EXTERNALMEASURE("Effectif déclaré", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Effectifs déclarés
			lineageTag: 4918f4f0-5c78-4f72-9746-fe37472acd00
			sourceLineageTag: 81071334-3237-49a1-8072-41a5ada6ee66
			dataCategory: Uncategorized

		measure 'Effectif SI déclaré' = EXTERNALMEASURE("Effectif SI déclaré", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Effectifs déclarés
			lineageTag: 0ea76a3f-1a19-4216-ab95-721e34451ede
			sourceLineageTag: ac3ccf7c-16c4-4284-a2a3-494bab873adc
			dataCategory: Uncategorized

		measure 'Effectif SIA déclaré' = EXTERNALMEASURE("Effectif SIA déclaré", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Effectifs déclarés
			lineageTag: acd305c1-e1a9-4cf3-895b-ec4bc95de8c9
			sourceLineageTag: 0c7caa95-a7eb-4e07-b29b-448b14be50a1
			dataCategory: Uncategorized

		measure 'Effectif SIR déclaré' = EXTERNALMEASURE("Effectif SIR déclaré", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Effectifs déclarés
			lineageTag: ac57998a-403c-424d-8420-d8e983a54a3c
			sourceLineageTag: 29fa9182-af71-47a8-81e8-ae7a5a417545
			dataCategory: Uncategorized

		measure 'Montant HT facturable' = EXTERNALMEASURE("Montant HT facturable", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ \€
			displayFolder: Indicateurs\3 - Facturation
			lineageTag: 47e16d91-ffae-44e4-8605-4a001f035a38
			sourceLineageTag: 8aa476ba-6f89-4e8a-874b-b0e02468bd03
			dataCategory: Uncategorized

		measure 'Montant HT facturé' = EXTERNALMEASURE("Montant HT facturé", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ \€
			displayFolder: Indicateurs\3 - Facturation
			lineageTag: b71a7419-2973-4a7e-9d7c-e7c60362a755
			sourceLineageTag: acfdef98-edcc-4a26-bef1-65f75e94ee15
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents appelés à déclarer' = EXTERNALMEASURE("Nombre d'adhérents appelés à déclarer", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Adhérents
			lineageTag: c77f5822-8083-4804-92f5-62bc74d34c6a
			sourceLineageTag: 18ca1502-f98d-4f4b-b290-31aee30788d7
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents ayant déclaré' = EXTERNALMEASURE("Nombre d'adhérents ayant déclaré", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Adhérents
			lineageTag: 2922a400-d179-41ad-a5d5-52d78e8bb1ac
			sourceLineageTag: e505539e-a914-41fb-a6e3-bd5f0e91f05d
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents concernés par la campagne' = EXTERNALMEASURE("Nombre d'adhérents concernés par la campagne", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Adhérents
			lineageTag: b34a8058-4619-4f1d-947e-b0724c506fea
			sourceLineageTag: d49fc46c-c853-4be8-b76b-4d89224b894c
			dataCategory: Uncategorized

	ref table 'Demande consultation spécialisée'

		measure '# demandes consultation spécialisée' = EXTERNALMEASURE("# demandes consultation spécialisée", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: c006d293-b117-4a35-9c4d-6ec15d3799ea
			sourceLineageTag: c5b87946-9ebb-4491-bfb7-a96471aaca8c
			dataCategory: Uncategorized

		measure 'Délai moyen planification demande (en jours)' = EXTERNALMEASURE("Délai moyen planification demande (en jours)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Indicateurs
			lineageTag: 39c588fd-27c7-4d4d-a0cd-afbf75f45130
			sourceLineageTag: d0e497c4-b530-409e-b090-7931d00be1e4
			dataCategory: Uncategorized

		measure 'Délai moyen traitement demande (en jours)' = EXTERNALMEASURE("Délai moyen traitement demande (en jours)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0
			displayFolder: Indicateurs
			lineageTag: e6e6d861-3a47-437e-8f2f-0e820161389e
			sourceLineageTag: 79b896a4-fbd5-4a11-a3d5-06470bcb471b
			dataCategory: Uncategorized

	ref table 'Demande visite adhérent'

		measure 'Délai moyen de planification des visites de reprise (en jours)' = EXTERNALMEASURE("Délai moyen de planification des visites de reprise (en jours)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0
			displayFolder: Indicateurs
			lineageTag: 1d4e5103-7d5a-4ce0-8e8e-bf669b21a1e4
			sourceLineageTag: 1340ac01-0eeb-4ed9-8150-321d7e426110
			dataCategory: Uncategorized

		measure 'Délai moyen de traitement de la demande (en jours)' = EXTERNALMEASURE("Délai moyen de traitement de la demande (en jours)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0
			displayFolder: Indicateurs
			lineageTag: 0b0b3fad-4459-4a0a-86f3-b849755dd398
			sourceLineageTag: de6d5e4d-cc47-4a01-8504-5769d363ee2d
			dataCategory: Uncategorized

		measure 'Nombre de demandes de visite adhérent' = EXTERNALMEASURE("Nombre de demandes de visite adhérent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,0
			displayFolder: Indicateurs
			lineageTag: a5a74e34-de21-4f6b-b3f9-4485a354adba
			sourceLineageTag: def496e9-73de-492a-9c8c-dfe267646ad0
			dataCategory: Uncategorized

		measure 'Taux de demande adhérent ayant abouti à une visite' = EXTERNALMEASURE("Taux de demande adhérent ayant abouti à une visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs
			lineageTag: 3b60d0ab-63cb-4844-bcce-e38ef2334c8b
			sourceLineageTag: 64e1c29c-0d17-4cad-a854-5e48cfd55ad7
			dataCategory: Uncategorized

		measure 'Taux de demande de visite adhérent acceptées' = EXTERNALMEASURE("Taux de demande de visite adhérent acceptées", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs
			lineageTag: 647d2d41-76aa-43ea-89db-c3c315541609
			sourceLineageTag: 0206326e-300e-4d31-bf09-842f393834d9
			dataCategory: Uncategorized

	ref table 'Documents émis'

		measure 'Nombre d''adaptations de poste' = EXTERNALMEASURE("Nombre d'adaptations de poste", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Adaptations de poste
			lineageTag: 0bd631ad-7b65-4613-9d90-fbcf82915a48
			sourceLineageTag: 495f1869-daa1-4010-8b2e-ac0914a52980
			dataCategory: Uncategorized

		measure 'Nombre d''avis d''inaptitude' = EXTERNALMEASURE("Nombre d'avis d'inaptitude", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Inaptitudes
			lineageTag: 501323e6-c5d9-4735-b4c1-26b9786688e5
			sourceLineageTag: a1bd1d32-5fb4-45a3-86c1-946c448cc5ba
			dataCategory: Uncategorized

		measure 'Nombre de documents avec adaptation de poste' = EXTERNALMEASURE("Nombre de documents avec adaptation de poste", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Adaptations de poste
			lineageTag: 1904eb31-37f1-45bf-8897-a5215d0571a0
			sourceLineageTag: 8cad7bbc-1e1c-4f3f-a9d1-7c30a7d86b93
			dataCategory: Uncategorized

		measure 'Nombre de documents émis' = EXTERNALMEASURE("Nombre de documents émis", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Tous les documents
			lineageTag: 00484326-9d1e-4908-b771-51f0d50bf9e8
			sourceLineageTag: 383c42cb-6031-4f3b-9098-7634409772c9
			dataCategory: Uncategorized

		measure 'Nombre de personnes concernées (adaptation de poste)' = EXTERNALMEASURE("Nombre de personnes concernées (adaptation de poste)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Adaptations de poste
			lineageTag: a6753d54-e42a-46a6-92c5-ac4392e4ccc2
			sourceLineageTag: ab841212-ff3b-4716-9eb7-e11505311258
			dataCategory: Uncategorized

		measure 'Nombre de personnes concernées (document)' = EXTERNALMEASURE("Nombre de personnes concernées (document)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Tous les documents
			lineageTag: 799be492-dd26-443e-b021-af8ac62a7cec
			sourceLineageTag: 4acefec2-ea19-4b4c-8446-d502de7040c0
			dataCategory: Uncategorized

		measure 'Nombre de personnes concernées (inaptitude)' = EXTERNALMEASURE("Nombre de personnes concernées (inaptitude)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Inaptitudes
			lineageTag: 5831c96a-7136-4374-82dd-40662accb62e
			sourceLineageTag: b6170b98-1549-4aa5-a95a-4d881af419ad
			dataCategory: Uncategorized

		measure 'Nombre de salariés concernés (adaptation de poste)' = EXTERNALMEASURE("Nombre de salariés concernés (adaptation de poste)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Adaptations de poste
			lineageTag: 49193379-e0e8-4199-a563-86ee3f8b6af7
			sourceLineageTag: 25d9482e-962a-4e07-bc73-c0afdf57ef2b
			dataCategory: Uncategorized

		measure 'Nombre de salariés concernés (document)' = EXTERNALMEASURE("Nombre de salariés concernés (document)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Tous les documents
			lineageTag: 711b8b23-2d4d-4bf4-a9d6-fbc401647406
			sourceLineageTag: 3a033c43-f1cd-49b1-9cd4-e9b8129da0e2
			dataCategory: Uncategorized

		measure 'Nombre de salariés concernés (inaptitude)' = EXTERNALMEASURE("Nombre de salariés concernés (inaptitude)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Inaptitudes
			lineageTag: 5c6bedb8-4f7e-46ec-8425-cef37c95a370
			sourceLineageTag: fa8355ac-791b-499a-89eb-a6b8aee61fc8
			dataCategory: Uncategorized

		measure 'Nombre de visites concernées (adaptation de poste)' = EXTERNALMEASURE("Nombre de visites concernées (adaptation de poste)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Adaptations de poste
			lineageTag: e01c3997-5c2e-4d24-b9a3-67158901e84e
			sourceLineageTag: 106671dc-3479-445a-b567-f24f8e52d8a9
			dataCategory: Uncategorized

		measure 'Nombre de visites concernées (document)' = EXTERNALMEASURE("Nombre de visites concernées (document)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Tous les documents
			lineageTag: 02b654e3-1418-410c-8a66-6c7c1f757b86
			sourceLineageTag: 586c1c81-c623-4078-9749-9c4d37036317
			dataCategory: Uncategorized

		measure 'Nombre de visites concernées (inaptitude)' = EXTERNALMEASURE("Nombre de visites concernées (inaptitude)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Inaptitudes
			lineageTag: a4c84f94-b5d5-4842-a6ed-b7dfb1234157
			sourceLineageTag: 2a9e7d44-6627-4ce7-9b98-d6b1b139b340
			dataCategory: Uncategorized

	ref table DPAE

		measure '# entreprises concernées (DPAE)' = EXTERNALMEASURE("# entreprises concernées (DPAE)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 7d83d5a5-cf9d-45ae-835a-242725389970
			sourceLineageTag: f594ae30-d80f-40f8-b5ed-33ed03a7eae4
			dataCategory: Uncategorized

		measure '# salariés à traiter' = EXTERNALMEASURE("# salariés à traiter", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 9327dffe-e1e2-4c2c-ba6e-6283f5b0c814
			sourceLineageTag: 59c405bd-8a10-419f-8a56-b9ac90cdd06d
			dataCategory: Uncategorized

		measure '# salariés issus DPAE' = EXTERNALMEASURE("# salariés issus DPAE", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: a1bd2ccc-f847-40c3-92c9-eb012f1992c2
			sourceLineageTag: 0f8bb89f-55ed-4796-985e-b6d7f1aa0586
			dataCategory: Uncategorized

		measure '# salariés traités' = EXTERNALMEASURE("# salariés traités", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 32c63412-8cda-4679-b2f8-441733134f3d
			sourceLineageTag: cad400e2-e482-4d2f-9d7f-ad4423d657de
			dataCategory: Uncategorized

		measure '# salariés traités archivés' = EXTERNALMEASURE("# salariés traités archivés", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 9d138bbb-ee3f-43b5-82a3-991029ed5079
			sourceLineageTag: c5810103-9dc1-4418-a48a-a06da5036646
			dataCategory: Uncategorized

		measure '# salariés traités créés' = EXTERNALMEASURE("# salariés traités créés", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 92d2026d-cbd3-43a6-957d-5580bd07ad34
			sourceLineageTag: 96f2be16-0c3b-48a5-a83d-54ffd3bfa57d
			dataCategory: Uncategorized

		measure '% salariés à traiter' = EXTERNALMEASURE("% salariés à traiter", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: bbad4297-ccee-4d5f-a89e-421cccdeee2a
			sourceLineageTag: a89457c4-a3ac-4c56-961c-5bb0a393d068
			dataCategory: Uncategorized

		measure '% salariés traités' = EXTERNALMEASURE("% salariés traités", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 17e3f17f-9455-4907-a40c-b0ac20984884
			sourceLineageTag: 600a0671-4c0d-437b-9dda-e3d54ede58ea
			dataCategory: Uncategorized

		measure '% salariés traités archivés' = EXTERNALMEASURE("% salariés traités archivés", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 846a008d-d80a-45e3-9dab-207d747a4cb6
			sourceLineageTag: fce4f232-6a77-47ee-a6be-94727e6dcd03
			dataCategory: Uncategorized

		measure '% salariés traités créés' = EXTERNALMEASURE("% salariés traités créés", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 94eeb3fb-28a1-46f1-b267-2924fa282ab7
			sourceLineageTag: 5f51a996-b1a3-4765-98dc-5f1283adffd5
			dataCategory: Uncategorized

	ref table DUERP

		measure 'Nombre d''actions de prévention' = EXTERNALMEASURE("Nombre d'actions de prévention", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\1 - Général
			lineageTag: b107f6dd-82f5-4ae8-8894-0a375531fa10
			sourceLineageTag: 99a4dd09-9ee6-4af5-b57a-a067949c96ca
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention ciblées sur des unités de travail' = EXTERNALMEASURE("Nombre d'actions de prévention ciblées sur des unités de travail", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\1 - Général
			lineageTag: dd4c47f2-a952-4f8e-9ac8-45410b1db5c4
			sourceLineageTag: 72329d32-7d6b-40db-bc21-671b774698c6
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention collectives' = EXTERNALMEASURE("Nombre d'actions de prévention collectives", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Collectives
			lineageTag: 33f53295-b50b-4c01-bf12-38deefc6ec7e
			sourceLineageTag: 7fd7833c-66cd-4a9a-8fc6-3d17d17a060a
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention de type adaptation de matériel' = EXTERNALMEASURE("Nombre d'actions de prévention de type adaptation de matériel", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Collectives
			lineageTag: 2cd2cef8-82ae-4a25-a726-e1ed740fe793
			sourceLineageTag: e136f554-477a-4232-b618-42262c2ee579
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention de type adaptation de poste' = EXTERNALMEASURE("Nombre d'actions de prévention de type adaptation de poste", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Individuelles
			lineageTag: 6081fd46-a201-497a-8dd7-88d924207e8b
			sourceLineageTag: e22be8f2-d043-4932-a362-a91aae3b7225
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention de type consigne/information' = EXTERNALMEASURE("Nombre d'actions de prévention de type consigne/information", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Individuelles
			lineageTag: a3d0b55a-91ec-45a8-8371-8bbe11af5a3d
			sourceLineageTag: 17523ade-349f-400c-ac2e-662c09d4e102
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention de type équipement de protection' = EXTERNALMEASURE("Nombre d'actions de prévention de type équipement de protection", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Individuelles
			lineageTag: 01373a3a-8974-47c8-9ea4-8ad71e755458
			sourceLineageTag: 6090c5d4-b16f-4bc3-b782-a49a59dcc119
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention de type formation collective' = EXTERNALMEASURE("Nombre d'actions de prévention de type formation collective", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Collectives
			lineageTag: af244a8b-b7d5-4265-894a-022e92cc60be
			sourceLineageTag: 09a3aa82-9f23-4a0c-ae08-14a2f731cc89
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention de type habilitation individuelle' = EXTERNALMEASURE("Nombre d'actions de prévention de type habilitation individuelle", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Individuelles
			lineageTag: 5e9d1057-9d3f-4a95-a160-2f33c44a4b6f
			sourceLineageTag: 663d5198-1a5f-4e9b-9d51-80c7c567fa06
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention de type modification de l''organisation' = EXTERNALMEASURE("Nombre d'actions de prévention de type modification de l'organisation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Processus
			lineageTag: 77f92cf3-35df-468a-8d62-b11acd5256ed
			sourceLineageTag: 73a4745c-1100-4fda-99b9-b41af11dfe89
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention de type protection du matériel' = EXTERNALMEASURE("Nombre d'actions de prévention de type protection du matériel", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Collectives
			lineageTag: b68cedf7-534f-4d98-846e-27e173de38cd
			sourceLineageTag: a3647ab2-d776-41c7-bbf2-1aac3423ca02
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention de type rédaction de protocole' = EXTERNALMEASURE("Nombre d'actions de prévention de type rédaction de protocole", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Processus
			lineageTag: b3e4008c-b389-4bd6-b48d-cec4e062321a
			sourceLineageTag: cf62705c-1213-4246-9e19-1c5d0c0f9b3b
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention en retard' = EXTERNALMEASURE("Nombre d'actions de prévention en retard", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\1 - Général
			lineageTag: dfec6f47-4cc7-44a3-8c92-d3340e4e7c6e
			sourceLineageTag: a3aed070-e84d-486b-934c-7d635414babd
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention globales' = EXTERNALMEASURE("Nombre d'actions de prévention globales", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\1 - Général
			lineageTag: b38877d2-2a9e-4119-a754-4eb60532235d
			sourceLineageTag: bbf3ce4a-0f8f-4214-853a-e1fe1552433f
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention individuelles' = EXTERNALMEASURE("Nombre d'actions de prévention individuelles", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Individuelles
			lineageTag: b1cb054d-0efe-4c6d-b3f1-6a7c431d35ac
			sourceLineageTag: c2d21e5e-0250-41de-92e2-2a089e3d0dc1
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention planifiées' = EXTERNALMEASURE("Nombre d'actions de prévention planifiées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\1 - Général
			lineageTag: 47f13c57-f0f1-4444-a7cb-a172963f9d4f
			sourceLineageTag: a17cc767-22fb-4b36-8566-e96c7575285a
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention processus' = EXTERNALMEASURE("Nombre d'actions de prévention processus", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Processus
			lineageTag: afc40d36-812c-4c0a-9eab-67ccc3c39a5d
			sourceLineageTag: 82b3578c-7ff1-4c96-8566-07354ef827b5
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention provenant du catalogue de prévention' = EXTERNALMEASURE("Nombre d'actions de prévention provenant du catalogue de prévention", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\1 - Général
			lineageTag: a7108808-bb7b-40fe-a0cb-4749a90692d1
			sourceLineageTag: 6bd8ebd2-9e2d-463a-871e-3af1ae12b848
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention réalisées' = EXTERNALMEASURE("Nombre d'actions de prévention réalisées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\1 - Général
			lineageTag: b2234916-6ba4-40ca-9758-5eca847085db
			sourceLineageTag: abbae282-c26d-4b57-9f03-aef88aae0400
			dataCategory: Uncategorized

		measure 'Nombre d''actions de prévention réglementaires' = EXTERNALMEASURE("Nombre d'actions de prévention réglementaires", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Actions de prévention\1 - Général
			lineageTag: 771532d3-4566-414b-b495-3e00e7b10162
			sourceLineageTag: ee0fd82a-8e68-42d1-a9c4-06b3ac0012a5
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents (actifs ou suspendus)' = EXTERNALMEASURE("Nombre d'adhérents (actifs ou suspendus)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Adhérents et DUERP
			lineageTag: f889c501-e689-4416-bcff-6e78af3b2d00
			sourceLineageTag: cfdcbb47-3e16-45f8-a1d8-b099ff1c1222
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents avec au moins un DUERP généré sur padoa' = EXTERNALMEASURE("Nombre d'adhérents avec au moins un DUERP généré sur padoa", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Adhérents et DUERP
			lineageTag: 65be4c03-3d66-4852-895f-16e50b64a9f7
			sourceLineageTag: c2c8e6e4-d2b2-4bcc-96b7-d7797fe7b905
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents avec une seule unité de travail' = EXTERNALMEASURE("Nombre d'adhérents avec une seule unité de travail", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Unités de travail
			lineageTag: 0e7b0c47-9836-4559-bf56-f05c3a782100
			sourceLineageTag: eac2a72d-2c2b-4899-b59d-40e679bbd022
			dataCategory: Uncategorized

		measure 'Nombre d''unités de travail' = EXTERNALMEASURE("Nombre d'unités de travail", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Unités de travail
			lineageTag: c83faf85-0021-4414-b6e5-67e6083d3a9f
			sourceLineageTag: 514ee913-3d23-4f49-9ae7-5f6e2b6cee93
			dataCategory: Uncategorized

		measure 'Nombre d''unités de travail créées avec suggestion' = EXTERNALMEASURE("Nombre d'unités de travail créées avec suggestion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Unités de travail
			lineageTag: c46f98aa-9e7b-422d-9d84-c8715950efe3
			sourceLineageTag: 8322c786-1ddc-46d7-8394-3b88b1b65e3e
			dataCategory: Uncategorized

		measure 'Nombre d''unités de travail créées avec suggestion puis renommées' = EXTERNALMEASURE("Nombre d'unités de travail créées avec suggestion puis renommées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Unités de travail
			lineageTag: e1d14876-6c62-46bd-8ccb-c9fbb477dee7
			sourceLineageTag: 131ba375-56a3-484b-a8bb-743a0f3422ab
			dataCategory: Uncategorized

		measure 'Nombre d''unités de travail créées avec suggestion sans renommage' = EXTERNALMEASURE("Nombre d'unités de travail créées avec suggestion sans renommage", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Unités de travail
			lineageTag: 7d863c90-be66-4290-a80e-a3b3fb0695c2
			sourceLineageTag: 174c62cb-31a1-4843-be54-5d76e98896bf
			dataCategory: Uncategorized

		measure 'Nombre d''unités de travail créées sans suggestion' = EXTERNALMEASURE("Nombre d'unités de travail créées sans suggestion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Unités de travail
			lineageTag: 877e7bd7-c817-473f-b878-c1f0fb6150ae
			sourceLineageTag: 3c61e6c9-db90-4535-8e28-ae5b8cd6bf44
			dataCategory: Uncategorized

		measure 'Nombre de risques' = EXTERNALMEASURE("Nombre de risques", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Risques\1 - Détail des risques
			lineageTag: 35e05e25-c1cf-4c53-8c61-6d02d1982b66
			sourceLineageTag: 0fa880ff-1e10-4998-87e1-76f465544812
			dataCategory: Uncategorized

		measure 'Nombre de risques avec annexe' = EXTERNALMEASURE("Nombre de risques avec annexe", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Risques\1 - Détail des risques
			lineageTag: b0c497ec-e426-4b0a-9dc2-69c026dac1e2
			sourceLineageTag: fbd70839-7025-4557-96da-102b3dd61f1e
			dataCategory: Uncategorized

		measure 'Nombre de risques avec cotation' = EXTERNALMEASURE("Nombre de risques avec cotation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Risques\1 - Détail des risques
			lineageTag: 28c5fa24-b1d3-4ddb-b707-bf08b881d208
			sourceLineageTag: f44306e7-4bbe-457e-8302-3a1c05e1640b
			dataCategory: Uncategorized

		measure 'Nombre de risques avec une description' = EXTERNALMEASURE("Nombre de risques avec une description", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Risques\1 - Détail des risques
			lineageTag: 3a3b4a68-7e86-4785-be15-467758493006
			sourceLineageTag: d8d398e8-9b86-46f3-8bcf-ba6250d3b687
			dataCategory: Uncategorized

		measure 'Nombre de risques avec une gravité corrigée' = EXTERNALMEASURE("Nombre de risques avec une gravité corrigée", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Risques\1 - Détail des risques
			lineageTag: fab8ef2f-6b3b-4eea-900f-b22c9a41d4da
			sourceLineageTag: 6f74a6d7-b2e5-4a5e-ab3c-e3b898105821
			dataCategory: Uncategorized

		measure 'Nombre de risques avec une prévention insatisfaisante selon l''adhérent' = EXTERNALMEASURE("Nombre de risques avec une prévention insatisfaisante selon l'adhérent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Risques\2 - Maîtrise des risques
			lineageTag: e383cf1d-a8b4-489d-b46c-0a01108d888e
			sourceLineageTag: 3c7be856-c3d8-48be-9a59-dba809b292d6
			dataCategory: Uncategorized

		measure 'Nombre de risques avec une prévention satisfaisante selon l''adhérent' = EXTERNALMEASURE("Nombre de risques avec une prévention satisfaisante selon l'adhérent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Risques\2 - Maîtrise des risques
			lineageTag: afb060a2-6a3a-4571-9729-36dbca1c31c1
			sourceLineageTag: 9065d93a-3830-410b-a746-32c65e453cb9
			dataCategory: Uncategorized

		measure 'Nombre de risques sans avis de l''adhérent sur la prévention' = EXTERNALMEASURE("Nombre de risques sans avis de l'adhérent sur la prévention", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Risques\2 - Maîtrise des risques
			lineageTag: f8d47ce3-7572-4bd5-b18e-ee22ed78ebf6
			sourceLineageTag: 7efb9061-ee5a-4280-9b14-49f133b038ab
			dataCategory: Uncategorized

		measure 'Nombre de salariés dans au moins une unité de travail' = EXTERNALMEASURE("Nombre de salariés dans au moins une unité de travail", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Unités de travail
			lineageTag: 352dc99d-ad7a-458e-b22c-61710a721cb3
			sourceLineageTag: 7cdfef12-fe1a-4d38-b149-236358126ae5
			dataCategory: Uncategorized

		measure 'Nombre moyen d''actions de prévention en retard par adhérent' = EXTERNALMEASURE("Nombre moyen d'actions de prévention en retard par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0
			displayFolder: Indicateurs\4 - Actions de prévention\1 - Général
			lineageTag: af090542-557c-494d-b9a9-8cd38d37b26a
			sourceLineageTag: e7650297-71f5-40d3-8a03-dd41ecee515f
			dataCategory: Uncategorized

		measure 'Nombre moyen d''actions de prévention globales par adhérent' = EXTERNALMEASURE("Nombre moyen d'actions de prévention globales par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0
			displayFolder: Indicateurs\4 - Actions de prévention\1 - Général
			lineageTag: f60be8c9-75eb-46be-b0de-ae72f0c1d83e
			sourceLineageTag: fb0be05e-05cf-4590-98a7-dc7cd0f1f193
			dataCategory: Uncategorized

		measure 'Nombre moyen d''actions de prévention planifiées par adhérent' = EXTERNALMEASURE("Nombre moyen d'actions de prévention planifiées par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0
			displayFolder: Indicateurs\4 - Actions de prévention\1 - Général
			lineageTag: dde05cfc-31b0-4cd0-8886-c51f5cb19783
			sourceLineageTag: cb5cd0db-3ada-47a8-bd52-a1213cfeafdc
			dataCategory: Uncategorized

		measure 'Nombre moyen d''actions de prévention réalisées par adhérent' = EXTERNALMEASURE("Nombre moyen d'actions de prévention réalisées par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0
			displayFolder: Indicateurs\4 - Actions de prévention\1 - Général
			lineageTag: 92d676af-ff01-4627-b470-dc84ee91449c
			sourceLineageTag: eb80a7ce-a22a-431a-abbd-266702aa9776
			dataCategory: Uncategorized

		measure 'Nombre moyen d''actions de prévention réglementaires par adhérent' = EXTERNALMEASURE("Nombre moyen d'actions de prévention réglementaires par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0
			displayFolder: Indicateurs\4 - Actions de prévention\1 - Général
			lineageTag: 35779753-c4d3-43f7-9cc2-8d1077791029
			sourceLineageTag: 0c48ad19-c85a-47e2-91c0-cb70c23e288f
			dataCategory: Uncategorized

		measure 'Nombre moyen d''unités de travail par adhérent' = EXTERNALMEASURE("Nombre moyen d'unités de travail par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0
			displayFolder: Indicateurs\2 - Unités de travail
			lineageTag: fb106fa0-0d62-4400-8838-16bb93d1c706
			sourceLineageTag: dc979130-af10-4d42-9551-a70580a1b4b1
			dataCategory: Uncategorized

		measure 'Nombre moyen de risques par adhérent' = EXTERNALMEASURE("Nombre moyen de risques par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0
			displayFolder: Indicateurs\3 - Risques\1 - Détail des risques
			lineageTag: 4ac62001-f898-4be2-9567-4f7f3e4a1c35
			sourceLineageTag: 66074e5f-2329-4c10-8bf8-0e30e5960501
			dataCategory: Uncategorized

		measure 'Nombre moyen de situations de travail par adhérent' = EXTERNALMEASURE("Nombre moyen de situations de travail par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0
			displayFolder: Indicateurs\3 - Risques\1 - Détail des risques
			lineageTag: fd9468cf-f3d4-4247-88c1-0e1cb62f98b4
			sourceLineageTag: 7a5bef94-a184-4605-8e04-2c212dd4da82
			dataCategory: Uncategorized

		measure 'Proportion d''adhérents avec au moins un DUERP généré sur padoa' = EXTERNALMEASURE("Proportion d'adhérents avec au moins un DUERP généré sur padoa", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\1 - Adhérents et DUERP
			lineageTag: 9bf96766-fc51-4fdf-a9e6-e58c819f4d39
			sourceLineageTag: 7438ea7b-1b1a-4f88-973f-096aacd1c69d
			dataCategory: Uncategorized

		measure 'Proportion de risques avec au moins une annexe' = EXTERNALMEASURE("Proportion de risques avec au moins une annexe", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\3 - Risques\1 - Détail des risques
			lineageTag: c5053907-f883-41fe-9846-764378c97c83
			sourceLineageTag: 1a02fbfb-f425-4408-b6db-6781b1d650cf
			dataCategory: Uncategorized

		measure 'Proportion de risques avec cotation' = EXTERNALMEASURE("Proportion de risques avec cotation", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\3 - Risques\1 - Détail des risques
			lineageTag: c08861a8-24b0-4839-8392-0b2806485c65
			sourceLineageTag: 76e63ce0-6bdb-448b-be78-4cbdc25de38d
			dataCategory: Uncategorized

		measure 'Proportion de risques avec une description' = EXTERNALMEASURE("Proportion de risques avec une description", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\3 - Risques\1 - Détail des risques
			lineageTag: 60168a8e-40ba-4dc5-a432-a9c5a80cc5a8
			sourceLineageTag: 3382ef46-4908-4e2e-b804-8fa7462a852a
			dataCategory: Uncategorized

		measure 'Proportion de risques avec une prévention insatisfaisante selon l''adhérent' = EXTERNALMEASURE("Proportion de risques avec une prévention insatisfaisante selon l'adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\3 - Risques\2 - Maîtrise des risques
			lineageTag: 2eae21b9-a83e-4bf3-a2b8-2d5c9cdccf2e
			sourceLineageTag: 82659b08-808a-496c-84ce-a0c2d0071935
			dataCategory: Uncategorized

		measure 'Proportion de risques avec une prévention satisfaisante selon l''adhérent' = EXTERNALMEASURE("Proportion de risques avec une prévention satisfaisante selon l'adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\3 - Risques\2 - Maîtrise des risques
			lineageTag: 6dbc565a-5f98-4e83-b8fd-2ccd59e6813b
			sourceLineageTag: d5fd5ec3-5a1b-4f57-be3b-3ae88644adb8
			dataCategory: Uncategorized

		measure 'Proportion de risques sans avis de l''adhérent sur la prévention' = EXTERNALMEASURE("Proportion de risques sans avis de l'adhérent sur la prévention", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\3 - Risques\2 - Maîtrise des risques
			lineageTag: 3cf93dc5-98a0-4915-90dc-d6a5eb97bff3
			sourceLineageTag: 7ef4befe-7829-444c-b841-15ab11990205
			dataCategory: Uncategorized

		measure 'Proportion de salariés suivis hors intérim dans au moins une unité de travail' = EXTERNALMEASURE("Proportion de salariés suivis hors intérim dans au moins une unité de travail", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\2 - Unités de travail
			lineageTag: c2560a28-dc47-4963-89d8-18f65eb194d7
			sourceLineageTag: 4405f733-6b76-4b10-b1fa-697378635bf1
			dataCategory: Uncategorized

		measure 'Proportion des actions de prévention ciblées sur des unités de travail' = EXTERNALMEASURE("Proportion des actions de prévention ciblées sur des unités de travail", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\4 - Actions de prévention\1 - Général
			lineageTag: 185efa06-9698-44e5-8626-516719048423
			sourceLineageTag: ad77d10f-cd99-4c74-bc20-35c44bdadf73
			dataCategory: Uncategorized

		measure 'Proportion des actions de prévention collectives' = EXTERNALMEASURE("Proportion des actions de prévention collectives", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Collectives
			lineageTag: e6b993b6-bcb2-4d6c-9c40-356b05a6992e
			sourceLineageTag: b0e253ab-74a6-4a4d-bb61-2420d635745e
			dataCategory: Uncategorized

		measure 'Proportion des actions de prévention de type adaptation de matériel' = EXTERNALMEASURE("Proportion des actions de prévention de type adaptation de matériel", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Collectives
			lineageTag: feb9a69e-3def-4716-83d7-d11b49e5594e
			sourceLineageTag: d774dfc2-6506-4ac8-ab5b-e9bb23a86fe3
			dataCategory: Uncategorized

		measure 'Proportion des actions de prévention de type adaptation de poste' = EXTERNALMEASURE("Proportion des actions de prévention de type adaptation de poste", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Individuelles
			lineageTag: fcb2db7f-2d23-45e7-91db-8216097d3ae0
			sourceLineageTag: c76c62f2-daa2-4e49-afdc-757aeba282e5
			dataCategory: Uncategorized

		measure 'Proportion des actions de prévention de type consigne/information' = EXTERNALMEASURE("Proportion des actions de prévention de type consigne/information", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Individuelles
			lineageTag: 339d47a8-40f1-4698-ae4c-28508952581e
			sourceLineageTag: a7811632-b7ce-4f9a-a47d-bf050c7f1ccd
			dataCategory: Uncategorized

		measure 'Proportion des actions de prévention de type équipement de protection' = EXTERNALMEASURE("Proportion des actions de prévention de type équipement de protection", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Individuelles
			lineageTag: f92ab318-8d2e-42c8-9cea-c0e2cd7fc5d2
			sourceLineageTag: 45fda73f-cd6b-44fb-9859-d45f586466a8
			dataCategory: Uncategorized

		measure 'Proportion des actions de prévention de type formation collective' = EXTERNALMEASURE("Proportion des actions de prévention de type formation collective", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Collectives
			lineageTag: 2eb92fbe-f890-4b42-a981-9d39e8936bf9
			sourceLineageTag: 8ab1e8b9-737f-4438-9689-7dbb68e0bfec
			dataCategory: Uncategorized

		measure 'Proportion des actions de prévention de type habilitation individuelle' = EXTERNALMEASURE("Proportion des actions de prévention de type habilitation individuelle", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Individuelles
			lineageTag: aefb7b08-af86-4cc6-ae10-f586e32c9286
			sourceLineageTag: 736618b5-5deb-43f6-8dca-89d6a37aa10b
			dataCategory: Uncategorized

		measure 'Proportion des actions de prévention de type modification de l''organisation' = EXTERNALMEASURE("Proportion des actions de prévention de type modification de l'organisation", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Processus
			lineageTag: 88db4fa8-8de9-45fc-a127-65d786f9835b
			sourceLineageTag: daf9e56e-91e8-4381-84d0-32767411369a
			dataCategory: Uncategorized

		measure 'Proportion des actions de prévention de type protection du matériel' = EXTERNALMEASURE("Proportion des actions de prévention de type protection du matériel", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Collectives
			lineageTag: 6bbc0354-faeb-4759-8f47-d8aab3c010f7
			sourceLineageTag: 61403e63-2d5c-4e18-8d36-3de3b239c8c1
			dataCategory: Uncategorized

		measure 'Proportion des actions de prévention de type rédaction de protocole' = EXTERNALMEASURE("Proportion des actions de prévention de type rédaction de protocole", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Processus
			lineageTag: 1cf35244-24d8-489f-b9fc-78bced2960ad
			sourceLineageTag: c6aa67a4-1f6a-4244-8078-e43647c3c5c1
			dataCategory: Uncategorized

		measure 'Proportion des actions de prévention individuelles' = EXTERNALMEASURE("Proportion des actions de prévention individuelles", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Individuelles
			lineageTag: 27b0ecaa-fa50-4c42-97f4-1bdc4f1c4da2
			sourceLineageTag: 0eff3f63-d284-4e60-a015-e2d945371f9e
			dataCategory: Uncategorized

		measure 'Proportion des actions de prévention processus' = EXTERNALMEASURE("Proportion des actions de prévention processus", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\4 - Actions de prévention\2 - Par type\Processus
			lineageTag: c1413937-1ded-4084-8622-acf20e8b6835
			sourceLineageTag: a67313fa-356c-4bc5-86e8-d79bb5d40fb9
			dataCategory: Uncategorized

		measure 'Proportion des actions de prévention provenant du catalogue' = EXTERNALMEASURE("Proportion des actions de prévention provenant du catalogue", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\4 - Actions de prévention\1 - Général
			lineageTag: 710dc98f-c7e1-472e-b6f7-c6c079b70944
			sourceLineageTag: f7c44f7d-faa7-4a3e-bd52-f455e335097c
			dataCategory: Uncategorized

		measure 'Proportion des adhérents avec une seule unité de travail' = EXTERNALMEASURE("Proportion des adhérents avec une seule unité de travail", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\2 - Unités de travail
			lineageTag: bdc1f9bc-e068-47c5-8d41-7f9160aaa8e6
			sourceLineageTag: ef068943-d1ac-4663-9559-61a5e2accce4
			dataCategory: Uncategorized

		measure 'Proportion des gravités corrigées par l''adhérent' = EXTERNALMEASURE("Proportion des gravités corrigées par l'adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\3 - Risques\1 - Détail des risques
			lineageTag: 518d27c5-c558-40a3-9729-9a5415081c79
			sourceLineageTag: 5a14db36-9c29-4e48-b0ed-3043e1eb9edb
			dataCategory: Uncategorized

		measure 'Proportion des unités de travail créées avec suggestion' = EXTERNALMEASURE("Proportion des unités de travail créées avec suggestion", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\2 - Unités de travail
			lineageTag: 6258fba9-dd1d-4f54-b308-711b84456d98
			sourceLineageTag: 6dddb8db-9e1e-448a-bbec-1c67ae34e8ec
			dataCategory: Uncategorized

		measure 'Proportion des unités de travail créées avec suggestion puis renommées' = EXTERNALMEASURE("Proportion des unités de travail créées avec suggestion puis renommées", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\2 - Unités de travail
			lineageTag: 0bff9d3c-7ff1-4c6e-b9b4-23f8389e35e2
			sourceLineageTag: 3f14cfe0-c368-411c-a5f3-ab11a340248c
			dataCategory: Uncategorized

		measure 'Proportion des unités de travail créées avec suggestion sans renommage' = EXTERNALMEASURE("Proportion des unités de travail créées avec suggestion sans renommage", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\2 - Unités de travail
			lineageTag: da6b8849-3606-43da-bc77-a7066d139ca7
			sourceLineageTag: ec575fce-9854-4490-b98f-8242373862fb
			dataCategory: Uncategorized

		measure 'Proportion des unités de travail créées sans suggestion' = EXTERNALMEASURE("Proportion des unités de travail créées sans suggestion", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\2 - Unités de travail
			lineageTag: d9e3d042-087b-4306-b20b-773ea7a959cd
			sourceLineageTag: 5de99383-1d27-4559-b76e-db355dca0ef8
			dataCategory: Uncategorized

	ref table 'Effectif au 31/12'

		measure 'Effectif fonction publique (31/12)' = EXTERNALMEASURE("Effectif fonction publique (31/12)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: a0a8424a-a040-4b7f-a89d-0bc200873992
			sourceLineageTag: fbdebf04-7b07-48a0-853f-e2ff8dbb9967
			dataCategory: Uncategorized

		measure 'Effectif suivi (31/12)' = EXTERNALMEASURE("Effectif suivi (31/12)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 642e4b20-5021-42dd-ab7c-42ce580139e3
			sourceLineageTag: a80428d5-a2ef-43e8-ac24-448a8c89499e
			dataCategory: Uncategorized

		measure 'Effectif suivi intérimaire (31/12)' = EXTERNALMEASURE("Effectif suivi intérimaire (31/12)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: afc252ae-7b2f-43c2-b752-0398e64d6c82
			sourceLineageTag: b586629d-1a01-4ea3-8417-9431415cbd2c
			dataCategory: Uncategorized

		measure 'Effectif suivi non-intérimaire (31/12)' = EXTERNALMEASURE("Effectif suivi non-intérimaire (31/12)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 72f3e9c0-a17f-482f-b84a-80e8ca756198
			sourceLineageTag: bd060a4e-e196-42c9-b335-9513d5c7c554
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents (31/12)' = EXTERNALMEASURE("Nombre d'adhérents (31/12)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 513da284-24fb-46cb-bb79-772b0290629d
			sourceLineageTag: 01cd454f-797a-493d-9626-0d016ffb180f
			dataCategory: Uncategorized

		measure 'Nombre de personnes suivies (31/12)' = EXTERNALMEASURE("Nombre de personnes suivies (31/12)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: c2736039-e029-4f16-9456-89b94aad6355
			sourceLineageTag: 739afa3a-b162-43d4-acf5-d3783737eaf4
			dataCategory: Uncategorized

		measure 'Nombre de salariés SIA (31/12)' = EXTERNALMEASURE("Nombre de salariés SIA (31/12)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 624e4cb0-d75c-4674-a156-0c4714ad0b5a
			sourceLineageTag: 2be8b1f2-33c2-4a9f-896a-13468be54b9a
			dataCategory: Uncategorized

		measure 'Nombre de salariés SIR (31/12)' = EXTERNALMEASURE("Nombre de salariés SIR (31/12)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 7a31debc-6d7a-477e-a476-257903d08329
			sourceLineageTag: 54cb7923-d18b-4f1a-bb8c-223f4122923f
			dataCategory: Uncategorized

		measure 'Taux d''agents fonction publique (31/12)' = EXTERNALMEASURE("Taux d'agents fonction publique (31/12)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs
			lineageTag: 76a40c9e-45c6-44c5-90d9-7fa168f40a73
			sourceLineageTag: ec6c5ab3-b4e1-4bc1-95c8-e304bd84da74
			dataCategory: Uncategorized

		measure 'Taux d''intérimaires (31/12)' = EXTERNALMEASURE("Taux d'intérimaires (31/12)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs
			lineageTag: 075a52f8-95c5-43b6-8428-c0a300069aaa
			sourceLineageTag: 309c42fd-6850-432d-9cdd-8f72a320dca6
			dataCategory: Uncategorized

		measure 'Taux de salariés SIA (31/12)' = EXTERNALMEASURE("Taux de salariés SIA (31/12)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs
			lineageTag: 197fe341-f250-475b-ae76-bfec817b113e
			sourceLineageTag: f7159351-feb6-4de0-af48-27b255677e54
			dataCategory: Uncategorized

		measure 'Taux de salariés SIR (31/12)' = EXTERNALMEASURE("Taux de salariés SIR (31/12)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs
			lineageTag: 53cb3293-7a58-42f7-b21b-a92647b34a30
			sourceLineageTag: d0320361-a3c6-4ddc-8dba-11a9629e4b8e
			dataCategory: Uncategorized

	ref table 'Equipe médicale'

		measure 'ETP infimier (effectif suivi)' = EXTERNALMEASURE("ETP infimier (effectif suivi)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\3 - ETP pondérés par effectif suivi
			lineageTag: bef8eb96-ce99-4250-877b-ff35d70d586a
			sourceLineageTag: 57a1d504-e21e-46cb-b31e-23610847bb6c
			dataCategory: Uncategorized

		measure 'ETP infimier (équipe médicale)' = EXTERNALMEASURE("ETP infimier (équipe médicale)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\2 - ETP pondérés par équipe médicale
			lineageTag: e6b60f9a-636d-4ca8-9737-71aa801ecbb0
			sourceLineageTag: 368dbcce-3f15-4798-9b96-a38aa932d469
			dataCategory: Uncategorized

		measure 'ETP infimier d''entreprise (effectif suivi)' = EXTERNALMEASURE("ETP infimier d'entreprise (effectif suivi)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\3 - ETP pondérés par effectif suivi
			lineageTag: 7efce97a-2f24-42f0-bf4e-87c4741a8b64
			sourceLineageTag: dbb08b08-801c-4d3d-a428-c6092e3e7de7
			dataCategory: Uncategorized

		measure 'ETP infimier d''entreprise (équipe médicale)' = EXTERNALMEASURE("ETP infimier d'entreprise (équipe médicale)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\2 - ETP pondérés par équipe médicale
			lineageTag: dd17e857-f6ba-494b-b36b-611160dd1130
			sourceLineageTag: 844c0bc7-9bfe-421d-bd57-fdbda4cd9a11
			dataCategory: Uncategorized

		measure 'ETP infimier d''entreprise total' = EXTERNALMEASURE("ETP infimier d'entreprise total", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\1 - ETP totaux
			lineageTag: c3e37c31-8223-44d1-a026-9eff28bd30c6
			sourceLineageTag: 82818f0e-a782-4c04-aa5b-149108c2e7a6
			dataCategory: Uncategorized

		measure 'ETP infimier total' = EXTERNALMEASURE("ETP infimier total", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\1 - ETP totaux
			lineageTag: f445751f-cdcd-48f9-a2ea-390dcd6ece0f
			sourceLineageTag: 10696a14-7300-43a5-b534-a9e020230cc5
			dataCategory: Uncategorized

		measure 'ETP médecin (effectif suivi)' = EXTERNALMEASURE("ETP médecin (effectif suivi)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\3 - ETP pondérés par effectif suivi
			lineageTag: e3609ea1-c0b7-4252-8699-ee7dd402b271
			sourceLineageTag: 614e2476-f6b9-42fa-bac0-9a87a8f3c897
			dataCategory: Uncategorized

		measure 'ETP médecin (équipe médicale)' = EXTERNALMEASURE("ETP médecin (équipe médicale)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\2 - ETP pondérés par équipe médicale
			lineageTag: 33ee706b-be72-4f66-ba6e-a62022039e5b
			sourceLineageTag: 6743e017-656a-4235-b972-61c8285423c7
			dataCategory: Uncategorized

		measure 'ETP médecin total' = EXTERNALMEASURE("ETP médecin total", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\1 - ETP totaux
			lineageTag: 689a4935-b6c4-412c-baff-d2cf8f66cb27
			sourceLineageTag: c297105e-9f3e-45ca-b994-f253bceb8366
			dataCategory: Uncategorized

		measure 'ETP préventeur total' = EXTERNALMEASURE("ETP préventeur total", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\1 - ETP totaux
			lineageTag: 5ec4d9ec-6034-41be-949b-7aaa3d55d287
			sourceLineageTag: 6afaf015-33d5-47a3-9b2f-6b0f2c5318c3
			dataCategory: Uncategorized

	ref table 'Evènement collectif'

		measure '# évènements collectifs' = EXTERNALMEASURE("# évènements collectifs", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: a573e013-2c2f-46e9-a720-cbd0971e12ac
			sourceLineageTag: e81016dd-35d1-49d7-855f-62c235fbf981
			dataCategory: Uncategorized

		measure '# salariés convoqués évènement collectif' = EXTERNALMEASURE("# salariés convoqués évènement collectif", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 2ed7f57a-69cc-4114-8d52-920adbcd3ad0
			sourceLineageTag: b57829d5-a66f-4bb4-b9b5-9a9250457776
			dataCategory: Uncategorized

		measure '# salariés venus évènement collectif' = EXTERNALMEASURE("# salariés venus évènement collectif", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: e136f283-dffa-4278-b9e5-befbbe1d8ad2
			sourceLineageTag: 32f529d8-2d68-4796-9944-28dbf79047cb
			dataCategory: Uncategorized

		measure '% absentéisme évènement collectif' = EXTERNALMEASURE("% absentéisme évènement collectif", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: b2f78234-87df-4414-b543-f0d31aa935bc
			sourceLineageTag: dc0088e2-b20b-4bbd-b4fd-b023bccc5e9c
			dataCategory: Uncategorized

		measure 'Durée évènement collectif' = EXTERNALMEASURE("Durée évènement collectif", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs
			lineageTag: 893bddb7-d802-4a31-979c-5f31403f5f16
			sourceLineageTag: 3a57ed0f-57c7-4eee-9bd3-5ea455955d4f
			dataCategory: Uncategorized

	ref table 'Evolution effectif'

		measure '# adhérents à jour d''AMT primaire (fin de période)' = EXTERNALMEASURE("# adhérents à jour d'AMT primaire (fin de période)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\08 - Comptages retard AMT primaire
			lineageTag: f13b55e5-f2d0-46c4-a052-5edab92af4fe
			sourceLineageTag: 63e013e7-fb0f-4b61-a567-79bdb86b97eb
			dataCategory: Uncategorized

		measure '# adhérents à jour de FE (fin de période)' = EXTERNALMEASURE("# adhérents à jour de FE (fin de période)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\07 - Comptages retard FE
			lineageTag: 9f96a376-36ca-4858-b9ee-a63b0f446d48
			sourceLineageTag: 7ecd0e1e-ca66-4361-9f86-8a29e982408b
			dataCategory: Uncategorized

		measure '# adhérents affectés à l''équipe médicale' = EXTERNALMEASURE("# adhérents affectés à l'équipe médicale", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\09 - Comptages changement équipe médicale
			lineageTag: 1b950be5-a319-4f1f-8bf5-87f6a261d881
			sourceLineageTag: 20da2d13-cde3-4b04-87e5-7e051bbf78c2
			dataCategory: Uncategorized

		measure '# adhérents affectés au médecin adhérent' = EXTERNALMEASURE("# adhérents affectés au médecin adhérent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Comptages changement médecin référent
			lineageTag: 7ad08422-42e7-42db-a64e-f7de97d32f84
			sourceLineageTag: 8045a90d-b046-47bf-9ec5-9e0d82163f66
			dataCategory: Uncategorized

		measure '# adhérents désaffectés à au médecin référent' = EXTERNALMEASURE("# adhérents désaffectés à au médecin référent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Comptages changement médecin référent
			lineageTag: c8c9ae65-7053-4212-84de-1640bdc21faa
			sourceLineageTag: f9ca4222-0eb4-4f77-a9ca-d4ceddf7f477
			dataCategory: Uncategorized

		measure '# adhérents désaffectés à l''équipe médicale' = EXTERNALMEASURE("# adhérents désaffectés à l'équipe médicale", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\09 - Comptages changement équipe médicale
			lineageTag: acd8cd76-d21d-40e8-aeab-6b477fa391ae
			sourceLineageTag: c837f75f-8001-40b0-8603-750a9dae8bfd
			dataCategory: Uncategorized

		measure '# adhérents éligibles AMT primaire (fin de période)' = EXTERNALMEASURE("# adhérents éligibles AMT primaire (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\08 - Comptages retard AMT primaire
			lineageTag: abb390d8-a96b-4f0d-b3a4-95d1c2d28ba8
			sourceLineageTag: 4d02a4b7-3910-48c8-a099-f187a1e3b3bd
			dataCategory: Uncategorized

		measure '# adhérents éligibles FE (fin de période)' = EXTERNALMEASURE("# adhérents éligibles FE (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\07 - Comptages retard FE
			lineageTag: c975a9bb-91b8-493f-90e1-3375f8d05c99
			sourceLineageTag: fc051740-265a-4145-abb1-76aea71cd515
			dataCategory: Uncategorized

		measure '# adhérents en retard d''AMT primaire (fin de période)' = EXTERNALMEASURE("# adhérents en retard d'AMT primaire (fin de période)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\08 - Comptages retard AMT primaire
			lineageTag: 9696b3b6-1b52-4c5b-ab79-bc0c3d12bcb0
			sourceLineageTag: 5a09b3a5-018b-4182-b0aa-685e0c48763d
			dataCategory: Uncategorized

		measure '# adhérents en retard de FE (fin de période)' = EXTERNALMEASURE("# adhérents en retard de FE (fin de période)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\07 - Comptages retard FE
			lineageTag: 18c5cd8e-51a2-404b-b4cd-3dc093c3b7fe
			sourceLineageTag: 078ce734-ebad-4b0a-908c-8aa8ee4cd1ea
			dataCategory: Uncategorized

		measure '# adhésions' = EXTERNALMEASURE("# adhésions", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\01 - Comptages adhérents
			lineageTag: 1f938345-1631-4eed-8b9b-e66f95955f4e
			sourceLineageTag: bef6f8ad-168a-404c-a96b-0dcaec5c361e
			dataCategory: Uncategorized

		measure '# réadhésions' = EXTERNALMEASURE("# réadhésions", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\01 - Comptages adhérents
			lineageTag: 61b37b85-4ea6-4e8b-8b75-80173eee989f
			sourceLineageTag: 64e88078-2b6a-4137-ae38-74934be71b84
			dataCategory: Uncategorized

		measure '% adhérents à jour d''AMT primaire (fin de période)' = EXTERNALMEASURE("% adhérents à jour d'AMT primaire (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0\ %;-0\ %;0\ %
			lineageTag: 761f56d1-2bd3-47af-8e94-49777fcb299a
			sourceLineageTag: 5a1324ed-ba87-4f0a-ae0c-4e439cb31be3
			dataCategory: Uncategorized

		measure '% adhérents à jour de FE (fin de période)' = EXTERNALMEASURE("% adhérents à jour de FE (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0\ %;-0\ %;0\ %
			lineageTag: 2e1e3168-c821-476f-be87-73943e9e761a
			sourceLineageTag: c4b63358-7fd1-493a-bc59-415d0fa849e7
			dataCategory: Uncategorized

		measure '% adhérents éligibles AMT primaire (fin de période)' = EXTERNALMEASURE("% adhérents éligibles AMT primaire (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: b31c31ed-600c-4a36-80dd-c8130d0e9fb9
			sourceLineageTag: c3afa73f-1f68-488a-8119-3996d893781a
			dataCategory: Uncategorized

		measure '% adhérents éligibles FE (fin de période)' = EXTERNALMEASURE("% adhérents éligibles FE (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: a2d2ff64-938e-443c-b66d-5c91de3e6b52
			sourceLineageTag: 7828777c-2f3c-4dc5-8034-10a8d2a781bf
			dataCategory: Uncategorized

		measure '% adhérents en retard d''AMT primaire (fin de période)' = EXTERNALMEASURE("% adhérents en retard d'AMT primaire (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 51e4309e-fe3e-4616-be62-6d9e9c0f2467
			sourceLineageTag: 5b67859a-f8f6-4e2e-9230-f45e4b2d57a5
			dataCategory: Uncategorized

		measure '% adhérents en retard de FE (fin de période)' = EXTERNALMEASURE("% adhérents en retard de FE (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 38bb0af6-5b59-4b4e-b83b-a1e4912274e9
			sourceLineageTag: 0e84c475-0860-4d0e-af77-a41173e10695
			dataCategory: Uncategorized

		measure '% effectif suivi figé non intérimaire à jour d''AMT primaire (fin de période)' = EXTERNALMEASURE("% effectif suivi figé non intérimaire à jour d'AMT primaire (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 5caa5749-f669-492a-a454-be52873bc07c
			sourceLineageTag: 54a02e40-2b68-4d35-8571-5e5c6efcc1b4
			dataCategory: Uncategorized

		measure '% effectif suivi figé non intérimaire à jour de FE (fin de période)' = EXTERNALMEASURE("% effectif suivi figé non intérimaire à jour de FE (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: dd4a1683-c5a5-444f-9b6b-21d7c42b4fc9
			sourceLineageTag: f5a3e0e0-6988-4c8a-8d6b-8e307c9ded2c
			dataCategory: Uncategorized

		measure '% effectif suivi figé non intérimaire éligibles AMT primaire (fin de période) ' = EXTERNALMEASURE("% effectif suivi figé non intérimaire éligibles AMT primaire (fin de période) ", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: afde0aa8-20d5-4925-9577-f7a4fea53cbf
			sourceLineageTag: d9df798e-2585-4145-ab51-c16b2c5bad1d
			dataCategory: Uncategorized

		measure '% effectif suivi figé non intérimaire éligibles FE (fin de période) ' = EXTERNALMEASURE("% effectif suivi figé non intérimaire éligibles FE (fin de période) ", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 5fc1c1c5-dc92-4400-9752-bf5cbff79f30
			sourceLineageTag: e1cb28cc-f8ed-448e-b1aa-ab2f6e5122aa
			dataCategory: Uncategorized

		measure '% effectif suivi figé non intérimaire en retard d''AMT primaire (fin de période)' = EXTERNALMEASURE("% effectif suivi figé non intérimaire en retard d'AMT primaire (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: dbd3d529-7d46-4cca-b2c9-a1aaedb0c23e
			sourceLineageTag: 7611aeef-e54a-4845-8b03-f42547c920e8
			dataCategory: Uncategorized

		measure '% effectif suivi figé non intérimaire en retard de FE (fin de période)' = EXTERNALMEASURE("% effectif suivi figé non intérimaire en retard de FE (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 019cb4d5-6f03-4144-8da3-6abd47483de9
			sourceLineageTag: ee0434a2-0ed0-473a-ad58-a1d4ccbee234
			dataCategory: Uncategorized

		measure 'Effectif de référence début de période' = EXTERNALMEASURE("Effectif de référence début de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\06 - Comptages effectif de référence
			lineageTag: 87db2b0e-93d1-4313-a45c-881d7059ebd3
			sourceLineageTag: a080ce0b-24b5-4d33-89a3-882f1a4d0a29
			dataCategory: Uncategorized

		measure 'Effectif de référence fin de période' = EXTERNALMEASURE("Effectif de référence fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\06 - Comptages effectif de référence
			lineageTag: c1b33268-a0e6-4f8d-8671-7051c445e969
			sourceLineageTag: c9215915-13fd-4d9a-a291-071e61d4566f
			dataCategory: Uncategorized

		measure 'Effectif déclaré début de période' = EXTERNALMEASURE("Effectif déclaré début de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\1 - Total
			lineageTag: ff957bfe-137c-4a9a-a4be-cc0db396b67b
			sourceLineageTag: cb55bc6c-5149-405d-9cd3-41bbfc746f18
			dataCategory: Uncategorized

		measure 'Effectif déclaré fin de période' = EXTERNALMEASURE("Effectif déclaré fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\1 - Total
			lineageTag: 88d53ddf-4a01-47e8-92ee-217a5d7540cd
			sourceLineageTag: 426cd4f4-d9ee-47c2-a527-fe5baae54466
			dataCategory: Uncategorized

		measure 'Effectif déclaré SI début de période' = EXTERNALMEASURE("Effectif déclaré SI début de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\2 - SI
			lineageTag: d22421e5-b374-4665-9dda-0c185b961599
			sourceLineageTag: 1e50a2bd-8b27-40f5-a2e9-8b19b3a10360
			dataCategory: Uncategorized

		measure 'Effectif déclaré SI fin de période' = EXTERNALMEASURE("Effectif déclaré SI fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\2 - SI
			lineageTag: 3fc365a7-32f7-4dc8-9083-2b41119e2106
			sourceLineageTag: 0779c3fe-3ecf-47a7-92e0-b6a1f9777c40
			dataCategory: Uncategorized

		measure 'Effectif déclaré SIA début de période' = EXTERNALMEASURE("Effectif déclaré SIA début de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\3 - SIA
			lineageTag: 6442cd25-5b8c-4803-b7b3-f7994efe24f4
			sourceLineageTag: 8c2f7c34-24cd-453a-842d-fde114142024
			dataCategory: Uncategorized

		measure 'Effectif déclaré SIA fin de période' = EXTERNALMEASURE("Effectif déclaré SIA fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\3 - SIA
			lineageTag: c01b2ffb-19d4-4ddf-8c88-112905972b3b
			sourceLineageTag: e1be5723-291f-4e3c-aaf1-28f70ce26864
			dataCategory: Uncategorized

		measure 'Effectif déclaré SIR début de période' = EXTERNALMEASURE("Effectif déclaré SIR début de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\4 - SIR
			lineageTag: 46b1854e-d02d-4b69-8a2f-e1bcc1527a54
			sourceLineageTag: c6e0f3df-0a11-4e17-b502-3fed30679584
			dataCategory: Uncategorized

		measure 'Effectif déclaré SIR fin de période' = EXTERNALMEASURE("Effectif déclaré SIR fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\4 - SIR
			lineageTag: 44ed39bb-441b-4a97-befc-dcd463c0b5ad
			sourceLineageTag: b55657b6-8858-4f54-a1b9-21b55943835a
			dataCategory: Uncategorized

		measure 'Effectif estimé début de période' = EXTERNALMEASURE("Effectif estimé début de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\05 - Comptages effectif estimé
			lineageTag: ed7059e1-d4f6-4f58-bf20-9fb5be2bcb0b
			sourceLineageTag: cbca2283-2c5a-4c39-8167-fb24d6aaa565
			dataCategory: Uncategorized

		measure 'Effectif estimé fin de période' = EXTERNALMEASURE("Effectif estimé fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\05 - Comptages effectif estimé
			lineageTag: dc223106-234a-434c-b9e9-c7a4313696d7
			sourceLineageTag: 6770affb-98d8-4281-abe6-d1e44ab627d4
			dataCategory: Uncategorized

		measure 'Effectif suivi figé intérimaire affecté à l''équipe médicale' = EXTERNALMEASURE("Effectif suivi figé intérimaire affecté à l'équipe médicale", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\09 - Comptages changement équipe médicale
			lineageTag: 1c250208-8cc0-4382-be82-d343a89f9f4c
			sourceLineageTag: c2a29f7c-a0d6-4d11-899d-39958e8ea070
			dataCategory: Uncategorized

		measure 'Effectif suivi figé intérimaire affecté au médecin référent' = EXTERNALMEASURE("Effectif suivi figé intérimaire affecté au médecin référent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Comptages changement médecin référent
			lineageTag: 6b134ddf-d72f-4a5f-82f3-a4405f7e7882
			sourceLineageTag: d649f2a6-f8a8-489d-8949-88e03c342f29
			dataCategory: Uncategorized

		measure 'Effectif suivi figé intérimaire début de période' = EXTERNALMEASURE("Effectif suivi figé intérimaire début de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\2. Intérimaires
			lineageTag: 86806340-f837-45b5-a10d-34b6be363a53
			sourceLineageTag: 7c121f31-408a-49a9-a529-a07a95af6568
			dataCategory: Uncategorized

		measure 'Effectif suivi figé intérimaire désaffecté à l''équipe médicale' = EXTERNALMEASURE("Effectif suivi figé intérimaire désaffecté à l'équipe médicale", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\09 - Comptages changement équipe médicale
			lineageTag: b47f24dd-af70-4c76-9fe9-9e73f7a658c3
			sourceLineageTag: d1eb387c-de16-4384-9e42-bdd4bfc09c63
			dataCategory: Uncategorized

		measure 'Effectif suivi figé intérimaire désaffecté au médecin référent' = EXTERNALMEASURE("Effectif suivi figé intérimaire désaffecté au médecin référent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Comptages changement médecin référent
			lineageTag: 51d034bf-270c-4a5e-8ffb-b205641f5a58
			sourceLineageTag: 80232fab-a3a8-4c00-90ba-f7b556ad2b1b
			dataCategory: Uncategorized

		measure 'Effectif suivi figé intérimaire fin de période' = EXTERNALMEASURE("Effectif suivi figé intérimaire fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\2. Intérimaires
			lineageTag: 4a633a49-bc01-4dae-b255-bc31ce2fb681
			sourceLineageTag: 0e731279-61e0-4251-b94f-5fc1e5f7f51d
			dataCategory: Uncategorized

		measure 'Effectif suivi figé intérimaire SI fin de période' = EXTERNALMEASURE("Effectif suivi figé intérimaire SI fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\2. Intérimaires
			lineageTag: 5de2f02f-b6b9-46cf-ab59-3f44a3c5ba06
			sourceLineageTag: 76fa4985-137a-4642-b1f1-6c8cf1b99416
			dataCategory: Uncategorized

		measure 'Effectif suivi figé intérimaire SIA fin de période' = EXTERNALMEASURE("Effectif suivi figé intérimaire SIA fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\2. Intérimaires
			lineageTag: 1535a250-0253-4864-ab4c-69909b3cff0c
			sourceLineageTag: 25b0c027-3250-4e5f-aba0-72b32517ad4c
			dataCategory: Uncategorized

		measure 'Effectif suivi figé intérimaire SIR fin de période' = EXTERNALMEASURE("Effectif suivi figé intérimaire SIR fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\2. Intérimaires
			lineageTag: 67083ce2-ff64-4439-8f6d-f425aa5cc46f
			sourceLineageTag: f65aa117-e350-4df6-915d-f75b9ae0daeb
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire à jour d''AMT primaire (fin de période)' = EXTERNALMEASURE("Effectif suivi figé non intérimaire à jour d'AMT primaire (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\08 - Comptages retard AMT primaire
			lineageTag: 9b966bcf-3f44-47f3-a628-a5ac11943672
			sourceLineageTag: 0dc4ab05-0cda-4ef7-8a5d-b34d06f250dc
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire à jour de FE (fin de période)' = EXTERNALMEASURE("Effectif suivi figé non intérimaire à jour de FE (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\07 - Comptages retard FE
			lineageTag: da2de231-67f6-49ee-827d-63a71f644d58
			sourceLineageTag: f1e0f1eb-b6eb-49e8-b371-934b3b083b0c
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire affecté à l''équipe médicale' = EXTERNALMEASURE("Effectif suivi figé non intérimaire affecté à l'équipe médicale", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\09 - Comptages changement équipe médicale
			lineageTag: c1f210e3-ad9b-4d80-b53c-b34b0672383f
			sourceLineageTag: af1b5440-ee52-4964-9d2e-4d8d4bb99715
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire affecté au médecin référent' = EXTERNALMEASURE("Effectif suivi figé non intérimaire affecté au médecin référent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Comptages changement médecin référent
			lineageTag: 0be5e0f6-f5b8-44be-8f93-02a71a4af3b7
			sourceLineageTag: a120191e-67f1-4eb1-b7b5-5d83589bc1d1
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire début de période' = EXTERNALMEASURE("Effectif suivi figé non intérimaire début de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\1. Non intérimaires
			lineageTag: 25d13de7-8026-48b4-98e0-8df031210c74
			sourceLineageTag: 9445e652-d868-40dc-a51b-f03ccb4900cd
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire désaffecté à l''équipe médicale' = EXTERNALMEASURE("Effectif suivi figé non intérimaire désaffecté à l'équipe médicale", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\09 - Comptages changement équipe médicale
			lineageTag: 1c88a549-ec0b-4b47-983a-70024be1b432
			sourceLineageTag: 4cdaca07-68d1-40b2-83b7-0bf58ef0b02d
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire désaffecté au médecin référent' = EXTERNALMEASURE("Effectif suivi figé non intérimaire désaffecté au médecin référent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\10 - Comptages changement médecin référent
			lineageTag: c6083bc9-fc75-46f2-9591-2f5dad5dacd5
			sourceLineageTag: 9935c7b8-7fe6-4f92-b7fe-182f14975a23
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire éligibles AMT primaire (fin de période)' = EXTERNALMEASURE("Effectif suivi figé non intérimaire éligibles AMT primaire (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\08 - Comptages retard AMT primaire
			lineageTag: 399f3eb1-882a-4a2a-94af-cb54b3674ad0
			sourceLineageTag: 171c7854-43d2-4b2a-bc71-c3f4ba8156fe
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire éligibles FE (fin de période)' = EXTERNALMEASURE("Effectif suivi figé non intérimaire éligibles FE (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\07 - Comptages retard FE
			lineageTag: 1cfd7650-223f-4bc0-baca-0b9a047521ac
			sourceLineageTag: 9086b422-0476-446f-b881-98705298ed89
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire en retard d''AMT primaire (fin de période)' = EXTERNALMEASURE("Effectif suivi figé non intérimaire en retard d'AMT primaire (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\08 - Comptages retard AMT primaire
			lineageTag: 8f9793d6-e879-48be-91ee-b5932192417e
			sourceLineageTag: 25c45e9f-8724-44fc-a804-f808b4d83331
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire en retard de FE (fin de période)' = EXTERNALMEASURE("Effectif suivi figé non intérimaire en retard de FE (fin de période)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\07 - Comptages retard FE
			lineageTag: 97dbc7d0-a62f-472b-8d90-f34c0e0354b8
			sourceLineageTag: 179259d5-7a2d-4eaa-9d8a-38ad3acd2bb6
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire fin de période' = EXTERNALMEASURE("Effectif suivi figé non intérimaire fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\1. Non intérimaires
			lineageTag: 1626825a-7fbc-4604-a0a0-65cb836eb3fe
			sourceLineageTag: 4fb48e04-83f1-483c-af40-ebaf0c0941ee
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire fin de période à jour de FE' = EXTERNALMEASURE("Effectif suivi figé non intérimaire fin de période à jour de FE", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\07 - Comptages retard FE
			lineageTag: 2e9a10fd-66c5-4258-a4e3-c76381aa378e
			sourceLineageTag: 1b13efe8-f322-4b78-bbfd-8857c4a09361
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire fin de période avec FE non renseignée' = EXTERNALMEASURE("Effectif suivi figé non intérimaire fin de période avec FE non renseignée", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\07 - Comptages retard FE
			lineageTag: 7552e033-1f79-4d04-bddd-68cdd71680c5
			sourceLineageTag: b2e6206a-2a85-4592-bd02-e834bb6846db
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire fin de période en retard de FE' = EXTERNALMEASURE("Effectif suivi figé non intérimaire fin de période en retard de FE", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\07 - Comptages retard FE
			lineageTag: 08f6be30-83d6-469c-8bed-d5e061e7c19e
			sourceLineageTag: 67fd8489-f904-462f-875f-5dee68e1833e
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire SI fin de période' = EXTERNALMEASURE("Effectif suivi figé non intérimaire SI fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\1. Non intérimaires
			lineageTag: 9b47de5f-1f61-40da-abd9-5ad0a0a2abf0
			sourceLineageTag: 80b97bb3-9d77-4b59-bcae-a1428b338220
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire SIA fin de période' = EXTERNALMEASURE("Effectif suivi figé non intérimaire SIA fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\1. Non intérimaires
			lineageTag: 6be9cc56-cb39-46c9-b57e-ada582713ec1
			sourceLineageTag: e18f2345-250a-4391-aa7f-860e9d1b7f57
			dataCategory: Uncategorized

		measure 'Effectif suivi figé non intérimaire SIR fin de période' = EXTERNALMEASURE("Effectif suivi figé non intérimaire SIR fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\1. Non intérimaires
			lineageTag: fe3baa5e-1c2c-4dc0-bea8-d56f63b8a37b
			sourceLineageTag: 3138ceb4-b8da-4d0b-98b5-e8205c8bf881
			dataCategory: Uncategorized

		measure 'Effectif suivi intérimaire début de période' = EXTERNALMEASURE("Effectif suivi intérimaire début de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Comptages effectif suivi\2. Intérimaires
			lineageTag: e646a4a4-1592-40ee-a3b5-4e6e4e7e29e0
			sourceLineageTag: 89efeceb-efbe-495d-9653-f6c1a2ade440
			dataCategory: Uncategorized

		measure 'Effectif suivi intérimaire fin de période' = EXTERNALMEASURE("Effectif suivi intérimaire fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Comptages effectif suivi\2. Intérimaires
			lineageTag: f243eff9-8afa-47a7-b1c0-c646815f9251
			sourceLineageTag: 9db77810-233d-4978-b41c-7c22e08457cd
			dataCategory: Uncategorized

		measure 'Effectif suivi non intérimaire début de période' = EXTERNALMEASURE("Effectif suivi non intérimaire début de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Comptages effectif suivi\1. Non intérimaires
			lineageTag: 022862e5-e375-4431-9a32-05c5dbcb88b5
			sourceLineageTag: d7c84367-c8f9-456c-8009-7e1beb887cdc
			dataCategory: Uncategorized

		measure 'Effectif suivi non intérimaire fin de période' = EXTERNALMEASURE("Effectif suivi non intérimaire fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Comptages effectif suivi\1. Non intérimaires
			lineageTag: c2c56687-040f-4ae5-9ca9-5f344609f16f
			sourceLineageTag: 6919f3d4-0289-4905-afbd-860633e5e56a
			dataCategory: Uncategorized

		measure 'Entrées effectif de référence adhésion' = EXTERNALMEASURE("Entrées effectif de référence adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\06 - Comptages effectif de référence
			lineageTag: cdcbf761-a924-4a9d-9565-fec4071745e4
			sourceLineageTag: cd9f5f56-f6ba-45b1-9be9-dff581ba90d7
			dataCategory: Uncategorized

		measure 'Entrées effectif de référence car adhésion' = EXTERNALMEASURE("Entrées effectif de référence car adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs dépréciés
			lineageTag: 70473a0e-d249-4a30-bf8a-3c8973d33a12
			sourceLineageTag: f7570d92-0de6-4ac5-abaf-7b57ddae8f87
			dataCategory: Uncategorized

		measure 'Entrées effectif de référence réadhésion' = EXTERNALMEASURE("Entrées effectif de référence réadhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\06 - Comptages effectif de référence
			lineageTag: acdb1435-2861-44ae-b512-2c3bf07fb211
			sourceLineageTag: db6e9488-d11c-46c8-9c40-c419cccbe3d9
			dataCategory: Uncategorized

		measure 'Entrées effectif déclaré adhésion' = EXTERNALMEASURE("Entrées effectif déclaré adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\1 - Total
			lineageTag: ace45a4b-3964-43fa-841f-c24d7435ea17
			sourceLineageTag: a85b6511-dd7b-4bfd-bfea-85be241d9b90
			dataCategory: Uncategorized

		measure 'Entrées effectif déclaré car adhésion' = EXTERNALMEASURE("Entrées effectif déclaré car adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs dépréciés
			lineageTag: 2e670c45-1c10-4af7-952a-f9c0b413bc13
			sourceLineageTag: 6d3fe842-b57c-4ed4-bf84-24810ec9dfb0
			dataCategory: Uncategorized

		measure 'Entrées effectif déclaré réadhésion' = EXTERNALMEASURE("Entrées effectif déclaré réadhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\1 - Total
			lineageTag: 4299bb91-f094-4933-b5e2-f6984f20c460
			sourceLineageTag: 264849cf-25f6-4e22-886b-a12936ddcc8f
			dataCategory: Uncategorized

		measure 'Entrées effectif déclaré SI adhésion' = EXTERNALMEASURE("Entrées effectif déclaré SI adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\2 - SI
			lineageTag: 9e135f1c-ce24-40a1-b306-d90cb68a0b31
			sourceLineageTag: 451c3f0b-73b0-4933-9b43-25f602c0acfd
			dataCategory: Uncategorized

		measure 'Entrées effectif déclaré SI car adhésion' = EXTERNALMEASURE("Entrées effectif déclaré SI car adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs dépréciés
			lineageTag: d3b50ed1-483e-4cee-8e86-0582d0fd4e56
			sourceLineageTag: d4650312-0e84-4d24-99a4-f027d9975f80
			dataCategory: Uncategorized

		measure 'Entrées effectif déclaré SI réadhésion' = EXTERNALMEASURE("Entrées effectif déclaré SI réadhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\2 - SI
			lineageTag: 4a2a931c-32ad-4333-9ad6-8d85fa5c7336
			sourceLineageTag: 8f47e78d-e492-48da-a2e1-94ff8cb1a850
			dataCategory: Uncategorized

		measure 'Entrées effectif déclaré SIA adhésion' = EXTERNALMEASURE("Entrées effectif déclaré SIA adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\3 - SIA
			lineageTag: 0de8857f-9357-4931-b766-7fca8b3736bd
			sourceLineageTag: 37570785-6291-422f-adb2-c54e083352db
			dataCategory: Uncategorized

		measure 'Entrées effectif déclaré SIA car adhésion' = EXTERNALMEASURE("Entrées effectif déclaré SIA car adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs dépréciés
			lineageTag: 43c17dd0-7229-45cf-8750-e9ca16b1e8af
			sourceLineageTag: 43b37b65-b9f4-467d-bb9d-c7b31c6dd0e4
			dataCategory: Uncategorized

		measure 'Entrées effectif déclaré SIA réadhésion' = EXTERNALMEASURE("Entrées effectif déclaré SIA réadhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\3 - SIA
			lineageTag: c71a660e-f5ca-42d0-977d-801ed57070cb
			sourceLineageTag: c0f698d9-e7b8-45c1-ad04-ee8b26cef323
			dataCategory: Uncategorized

		measure 'Entrées effectif déclaré SIR adhésion' = EXTERNALMEASURE("Entrées effectif déclaré SIR adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\4 - SIR
			lineageTag: 8f414f02-5571-4b0f-8786-cc305f88d25c
			sourceLineageTag: 7f513371-0234-49e8-926e-269986ab90b5
			dataCategory: Uncategorized

		measure 'Entrées effectif déclaré SIR car adhésion' = EXTERNALMEASURE("Entrées effectif déclaré SIR car adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs dépréciés
			lineageTag: 4f685c53-b900-459b-9787-81af61b5eefa
			sourceLineageTag: bcd071e8-894e-4387-86ca-6d3cf12ce240
			dataCategory: Uncategorized

		measure 'Entrées effectif déclaré SIR réadhésion' = EXTERNALMEASURE("Entrées effectif déclaré SIR réadhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\4 - SIR
			lineageTag: f81489f4-afe1-451c-9818-4c7fc4e883f3
			sourceLineageTag: ba671aae-b6d3-4900-b368-5b7b30570261
			dataCategory: Uncategorized

		measure 'Entrées effectif estimé adhésion' = EXTERNALMEASURE("Entrées effectif estimé adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\05 - Comptages effectif estimé
			lineageTag: 0e9907b1-4df1-4a9b-817a-83f43a62ead9
			sourceLineageTag: a79638a9-1192-444d-bc95-5ef1d1a6ef8f
			dataCategory: Uncategorized

		measure 'Entrées effectif estimé car adhésion' = EXTERNALMEASURE("Entrées effectif estimé car adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs dépréciés
			lineageTag: b8ffe69f-8be8-4fe4-8d24-6df92e8a4753
			sourceLineageTag: fb4f55ce-38d3-420f-989f-e18d34c78b82
			dataCategory: Uncategorized

		measure 'Entrées effectif estimé réadhésion' = EXTERNALMEASURE("Entrées effectif estimé réadhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\05 - Comptages effectif estimé
			lineageTag: 44a9bcb1-3ac1-4899-8751-a3375717a77f
			sourceLineageTag: 0f0d40b9-f6e2-45a1-9261-c0412e1d1bf3
			dataCategory: Uncategorized

		measure 'Entrées effectif suivi figé intérimaire adhésion' = EXTERNALMEASURE("Entrées effectif suivi figé intérimaire adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\2. Intérimaires
			lineageTag: 6b1bf075-c3c1-4f81-8458-62930e129613
			sourceLineageTag: 45722da4-53a6-476a-8145-a4b7f01e88ea
			dataCategory: Uncategorized

		measure 'Entrées effectif suivi figé intérimaire car adhésion' = EXTERNALMEASURE("Entrées effectif suivi figé intérimaire car adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs dépréciés
			lineageTag: 10f7c88b-2d76-4309-b384-e31e46dad636
			sourceLineageTag: 4406ceed-af4c-4eb9-a97d-d8bbb4ab1ce6
			dataCategory: Uncategorized

		measure 'Entrées effectif suivi figé intérimaire réadhésion' = EXTERNALMEASURE("Entrées effectif suivi figé intérimaire réadhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\2. Intérimaires
			lineageTag: f7a3057a-865b-4f65-bc4d-32af425497ba
			sourceLineageTag: f45fa099-1ada-482d-b5ad-3cf53fa94800
			dataCategory: Uncategorized

		measure 'Entrées effectif suivi figé non intérimaire adhésion' = EXTERNALMEASURE("Entrées effectif suivi figé non intérimaire adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\1. Non intérimaires
			lineageTag: 50b265db-b1f8-42d7-9e5c-6f74a9411577
			sourceLineageTag: 4d59f353-c62f-43f4-b7f6-2f71d7400bad
			dataCategory: Uncategorized

		measure 'Entrées effectif suivi figé non intérimaire car adhésion' = EXTERNALMEASURE("Entrées effectif suivi figé non intérimaire car adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs dépréciés
			lineageTag: eaddf869-6370-42d1-98f2-df3199274d34
			sourceLineageTag: 6e44f1e4-bc96-46a4-8652-9d6cc7b6300a
			dataCategory: Uncategorized

		measure 'Entrées effectif suivi figé non intérimaire réadhésion' = EXTERNALMEASURE("Entrées effectif suivi figé non intérimaire réadhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\1. Non intérimaires
			lineageTag: fd347abf-7c1f-4c25-8454-c61ffec1906b
			sourceLineageTag: e8552ad1-fb72-4877-84eb-1c6b27ace067
			dataCategory: Uncategorized

		measure 'Entrées effectif suivi intérimaire adhésion' = EXTERNALMEASURE("Entrées effectif suivi intérimaire adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Comptages effectif suivi\2. Intérimaires
			lineageTag: e9cf122f-8f8f-40ad-ac98-0b1581c0a64b
			sourceLineageTag: bc3e8828-4bd3-4dd4-b077-b9dc39cf449c
			dataCategory: Uncategorized

		measure 'Entrées effectif suivi intérimaire car adhésion' = EXTERNALMEASURE("Entrées effectif suivi intérimaire car adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs dépréciés
			lineageTag: de7ab7c4-e029-4e1b-bbdb-0e535dd34ba9
			sourceLineageTag: 036ea7c0-fde2-4410-a528-de4039892d5f
			dataCategory: Uncategorized

		measure 'Entrées effectif suivi intérimaire readhésion' = EXTERNALMEASURE("Entrées effectif suivi intérimaire readhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Comptages effectif suivi\2. Intérimaires
			lineageTag: c202686f-e723-4874-b4b8-f49da99a72ac
			sourceLineageTag: cff635e1-7422-41f4-a93b-36f83b39bd31
			dataCategory: Uncategorized

		measure 'Entrées effectif suivi non intérimaire adhésion' = EXTERNALMEASURE("Entrées effectif suivi non intérimaire adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Comptages effectif suivi\1. Non intérimaires
			lineageTag: 0e408a9f-0450-4c55-8ba4-5b27dd4355c5
			sourceLineageTag: 3a0dfb74-6407-48d0-bf5a-525e63c92bd9
			dataCategory: Uncategorized

		measure 'Entrées effectif suivi non intérimaire car adhésion' = EXTERNALMEASURE("Entrées effectif suivi non intérimaire car adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs dépréciés
			lineageTag: 490f9073-b13d-41cb-ad4a-7bf9718aced9
			sourceLineageTag: 8d965e1d-de76-4406-8cdc-9e322d67906e
			dataCategory: Uncategorized

		measure 'Entrées effectif suivi non intérimaire readhésion' = EXTERNALMEASURE("Entrées effectif suivi non intérimaire readhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Comptages effectif suivi\1. Non intérimaires
			lineageTag: 34ad28ad-9e23-4071-9a6a-93076314e20d
			sourceLineageTag: fa0fc19d-ab6f-4aca-bc3a-15280324a434
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents début de période' = EXTERNALMEASURE("Nombre d'adhérents début de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\01 - Comptages adhérents
			lineageTag: 2aab2ca4-a227-49e0-b51c-c367e8f8b05c
			sourceLineageTag: ba3dcd1e-d05e-4df7-8320-13f92ce7e658
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents fin de période' = EXTERNALMEASURE("Nombre d'adhérents fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\01 - Comptages adhérents
			lineageTag: f56de2e7-49d9-4d51-96a8-831ed8653627
			sourceLineageTag: e408559f-85cb-4e64-9bf3-d7dd436fdc90
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents fin de période à jour de FE' = EXTERNALMEASURE("Nombre d'adhérents fin de période à jour de FE", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\07 - Comptages retard FE
			lineageTag: 7c99fd58-2a8f-4927-9c3e-3d9f31fed967
			sourceLineageTag: 2f2d3821-bdcc-44a1-96ac-d9e159c4dd17
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents fin de période avec FE non renseignée' = EXTERNALMEASURE("Nombre d'adhérents fin de période avec FE non renseignée", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\07 - Comptages retard FE
			lineageTag: eaf956af-ce2c-4501-8634-3f1d70ab8899
			sourceLineageTag: 80ebff93-54b5-49c5-a936-2b78deacaafb
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents fin de période en retard de FE' = EXTERNALMEASURE("Nombre d'adhérents fin de période en retard de FE", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\07 - Comptages retard FE
			lineageTag: 53e710c5-47b3-4276-9850-60d936f72aec
			sourceLineageTag: 83c84150-bc6b-4551-a26e-06a1640568e9
			dataCategory: Uncategorized

		measure 'Nombre d''adhésions' = EXTERNALMEASURE("Nombre d'adhésions", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs dépréciés
			lineageTag: 9b1babd8-2225-41ef-ad79-fe7e3f9f1be2
			sourceLineageTag: 95f656d1-cd32-432f-ab7e-4529083050d1
			dataCategory: Uncategorized

		measure 'Nombre de radiations' = EXTERNALMEASURE("Nombre de radiations", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\01 - Comptages adhérents
			lineageTag: 7b8c5c1e-48fd-4656-9399-6aed219f33f7
			sourceLineageTag: 59cae58a-3450-45e9-9830-ac266897e120
			dataCategory: Uncategorized

		measure 'Sorties effectif de référence car radiation' = EXTERNALMEASURE("Sorties effectif de référence car radiation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\06 - Comptages effectif de référence
			lineageTag: d6811f25-3f9a-41dd-8545-3f0e811a8ce4
			sourceLineageTag: 7eeab31d-43f0-42cd-ac4a-b540f9ac14c4
			dataCategory: Uncategorized

		measure 'Sorties effectif déclaré car radiation' = EXTERNALMEASURE("Sorties effectif déclaré car radiation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\1 - Total
			lineageTag: 0b13a65f-81ec-4f08-b30a-c55171461b2e
			sourceLineageTag: ff776aee-6484-4597-9bdb-ab203a4f560d
			dataCategory: Uncategorized

		measure 'Sorties effectif déclaré SI car radiation' = EXTERNALMEASURE("Sorties effectif déclaré SI car radiation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\2 - SI
			lineageTag: d34aba04-66f4-46d2-8d8d-1b9b9d061de1
			sourceLineageTag: c17e6093-eb8f-4ce4-a74a-c7989ed6d6e3
			dataCategory: Uncategorized

		measure 'Sorties effectif déclaré SIA car radiation' = EXTERNALMEASURE("Sorties effectif déclaré SIA car radiation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\3 - SIA
			lineageTag: c009d197-06db-4836-905d-45220b539f03
			sourceLineageTag: 5488f32e-c1a0-4e2c-bd4d-5d045c2a2ec7
			dataCategory: Uncategorized

		measure 'Sorties effectif déclaré SIR car radiation' = EXTERNALMEASURE("Sorties effectif déclaré SIR car radiation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\4 - SIR
			lineageTag: 1a40d154-3a30-42f8-9e4f-2b1c1b60229a
			sourceLineageTag: d1bafe40-ba07-47d5-aa3c-10f79c9aa44b
			dataCategory: Uncategorized

		measure 'Sorties effectif estimé car radiation' = EXTERNALMEASURE("Sorties effectif estimé car radiation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\05 - Comptages effectif estimé
			lineageTag: 4f11373c-d080-495d-89b1-f8ed4fe696f9
			sourceLineageTag: f9b9ab21-4c78-4f41-9390-4fd1b80e69b3
			dataCategory: Uncategorized

		measure 'Sorties effectif suivi figé intérimaire car radiation' = EXTERNALMEASURE("Sorties effectif suivi figé intérimaire car radiation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\2. Intérimaires
			lineageTag: 28d6760c-f841-4b0e-bf2b-2c64fdb38d0c
			sourceLineageTag: 0554983d-ea38-4ed9-aee9-fd696e3ab2c0
			dataCategory: Uncategorized

		measure 'Sorties effectif suivi figé non intérimaire car radiation' = EXTERNALMEASURE("Sorties effectif suivi figé non intérimaire car radiation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\1. Non intérimaires
			lineageTag: 1ed55c80-e303-49d1-bfcb-d10fb36ebd42
			sourceLineageTag: 134beb91-2516-41e3-bf24-4e4e2658acd6
			dataCategory: Uncategorized

		measure 'Sorties effectif suivi intérimaire car radiation' = EXTERNALMEASURE("Sorties effectif suivi intérimaire car radiation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Comptages effectif suivi\2. Intérimaires
			lineageTag: 142caafb-2d43-4564-aa5d-5b973eddaf5c
			sourceLineageTag: 53927b0e-14c1-4e9d-bc26-a80aa9c99fd1
			dataCategory: Uncategorized

		measure 'Sorties effectif suivi non intérimaire car radiation' = EXTERNALMEASURE("Sorties effectif suivi non intérimaire car radiation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Comptages effectif suivi\1. Non intérimaires
			lineageTag: e4bd1b6b-997f-4497-a024-224f2edd99ae
			sourceLineageTag: d149298e-a95c-42f6-a7b3-e7afbe574eba
			dataCategory: Uncategorized

		measure 'Variation effectif de référence car renouvellement déclaration/estimation' = EXTERNALMEASURE("Variation effectif de référence car renouvellement déclaration/estimation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\06 - Comptages effectif de référence
			lineageTag: c59b5f13-ffcc-4fd0-b6c8-99bd0aa0521e
			sourceLineageTag: 4b9b670a-9b67-4792-8352-0379534d2619
			dataCategory: Uncategorized

		measure 'Variation effectif déclaré car renouvellement déclaration' = EXTERNALMEASURE("Variation effectif déclaré car renouvellement déclaration", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\1 - Total
			lineageTag: 30bbe1aa-9789-4b99-87bb-42f5543afefa
			sourceLineageTag: 21fdb747-1701-47f6-bf55-30e8989d3f1b
			dataCategory: Uncategorized

		measure 'Variation effectif déclaré SI car renouvellement déclaration' = EXTERNALMEASURE("Variation effectif déclaré SI car renouvellement déclaration", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\2 - SI
			lineageTag: ef0e5e49-7c21-4c91-b045-ebfc44815620
			sourceLineageTag: deb2f70b-7bad-4bbe-b3d9-e98605cc2cbd
			dataCategory: Uncategorized

		measure 'Variation effectif déclaré SIA car renouvellement déclaration' = EXTERNALMEASURE("Variation effectif déclaré SIA car renouvellement déclaration", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\3 - SIA
			lineageTag: 3d5a33bd-4041-41f6-a76e-4499defc2980
			sourceLineageTag: ebe79137-e7f3-4456-989b-525739e41754
			dataCategory: Uncategorized

		measure 'Variation effectif déclaré SIR car renouvellement déclaration' = EXTERNALMEASURE("Variation effectif déclaré SIR car renouvellement déclaration", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\04 - Comptages effectif déclaré\4 - SIR
			lineageTag: d85816b9-6fbb-49e3-b4fd-94379a214076
			sourceLineageTag: ef50cb89-f231-42c1-b263-5ee013684778
			dataCategory: Uncategorized

		measure 'Variation effectif estimé car renouvellement estimation' = EXTERNALMEASURE("Variation effectif estimé car renouvellement estimation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\05 - Comptages effectif estimé
			lineageTag: 14301300-3634-4845-9c07-e365d6180cbe
			sourceLineageTag: 5bddf837-219d-4483-bc1f-313d6be41c19
			dataCategory: Uncategorized

		measure 'Variation effectif suivi figé intérimaire car embauche/fin contrat' = EXTERNALMEASURE("Variation effectif suivi figé intérimaire car embauche/fin contrat", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\2. Intérimaires
			lineageTag: 9cc702bf-b9c0-490b-930a-0f305599a64f
			sourceLineageTag: 1c3b6c2e-f99f-4a6d-90bf-ea6734e10b0a
			dataCategory: Uncategorized

		measure 'Variation effectif suivi figé non intérimaire car embauche/fin contrat' = EXTERNALMEASURE("Variation effectif suivi figé non intérimaire car embauche/fin contrat", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\03 - Comptages effectif suivi figé\1. Non intérimaires
			lineageTag: 0d7a392d-4248-4c1b-b889-84502241030c
			sourceLineageTag: f255ddb8-5051-4288-a9b8-9d5ec05f7ac1
			dataCategory: Uncategorized

		measure 'Variation effectif suivi intérimaire car embauche/fin contrat' = EXTERNALMEASURE("Variation effectif suivi intérimaire car embauche/fin contrat", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Comptages effectif suivi\2. Intérimaires
			lineageTag: be5cc4b5-81ba-4765-bd46-034c057bd7e6
			sourceLineageTag: cb49e1bc-ff50-43d0-a1eb-415f5460c2e4
			dataCategory: Uncategorized

		measure 'Variation effectif suivi non intérimaire car embauche/fin contrat' = EXTERNALMEASURE("Variation effectif suivi non intérimaire car embauche/fin contrat", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\02 - Comptages effectif suivi\1. Non intérimaires
			lineageTag: 96040b82-3a62-4c6e-b38c-f43236c11b3f
			sourceLineageTag: e6973311-3d2a-4c24-b35e-08fc25b4f58d
			dataCategory: Uncategorized

	ref table 'Evolution retard'

		measure 'Nombre de salariés suivis' = EXTERNALMEASURE("Nombre de salariés suivis", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: ac32d48f-d190-4ddb-a086-1585fd691b21
			sourceLineageTag: 0fb0e7da-ae5d-4ed5-a3c7-90bc04a8cdce
			dataCategory: Uncategorized

		measure 'Taux de retard' = EXTERNALMEASURE("Taux de retard", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs
			lineageTag: 2f1ce390-cc3a-452a-8a19-50765c35a295
			sourceLineageTag: 9044d69d-8a9c-4272-bb97-4822ca80d8cf
			dataCategory: Uncategorized

	ref table 'Examen complémentaire'

		measure '# examens' = EXTERNALMEASURE("# examens", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages
			lineageTag: cc2085bf-3062-4f50-8c04-3ee058ca5f8b
			sourceLineageTag: 54134d21-b7b7-4552-8f82-3cfa141f28c4
			dataCategory: Uncategorized

		measure '# examens autres objets connectés' = EXTERNALMEASURE("# examens autres objets connectés", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages
			lineageTag: 64dc7106-f14e-4fb0-98b1-c80ab34f9eaf
			sourceLineageTag: 98060c57-2a14-46df-9c67-06645347a55c
			dataCategory: Uncategorized

		measure '# examens réalisés après transfert' = EXTERNALMEASURE("# examens réalisés après transfert", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages
			lineageTag: a9e02900-b24a-4609-bb5c-7de2c44bada3
			sourceLineageTag: 25aa49df-8388-4be1-8d75-fd37c014e647
			dataCategory: Uncategorized

		measure '# examens réalisés avant transfert' = EXTERNALMEASURE("# examens réalisés avant transfert", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages
			lineageTag: 1ba3a5ca-344c-4bff-96f7-3353eb8ffcab
			sourceLineageTag: 7e205615-02ca-4c9a-bb63-c1b5bcd7f796
			dataCategory: Uncategorized

		measure '# examens saisis à la main' = EXTERNALMEASURE("# examens saisis à la main", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages
			lineageTag: ad895f63-9e40-4770-b705-1910b748f086
			sourceLineageTag: 57a1c19d-799d-4f40-be7d-38a2d968f2ce
			dataCategory: Uncategorized

		measure '# tests de repérage' = EXTERNALMEASURE("# tests de repérage", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages
			lineageTag: 94923d64-9010-4b23-8ac4-c1fd488b6c9d
			sourceLineageTag: 69ec595f-3de4-4c44-8e3f-5b374edf77e4
			dataCategory: Uncategorized

		measure '% examens autres objets connectés' = EXTERNALMEASURE("% examens autres objets connectés", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 7d66b5b5-19fc-4448-b249-3c973b90f20f
			sourceLineageTag: b7e5c94f-455d-4035-b2a6-4db71bf3854f
			dataCategory: Uncategorized

		measure '% examens réalisés après transfert' = EXTERNALMEASURE("% examens réalisés après transfert", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 0cc8a467-7feb-403d-a84d-eb5aac563940
			sourceLineageTag: 8431bc75-0dde-4123-98e0-47ec3c7dc011
			dataCategory: Uncategorized

		measure '% examens réalisés avant transfert' = EXTERNALMEASURE("% examens réalisés avant transfert", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: afb90cd3-3c37-40d0-bc73-6eb0e7ca5e80
			sourceLineageTag: e4791886-7b52-475b-ba31-e07b010264d3
			dataCategory: Uncategorized

		measure '% examens saisis à la main' = EXTERNALMEASURE("% examens saisis à la main", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: e94a47ba-db4e-4908-8abe-9250973066d1
			sourceLineageTag: f40bdb33-16f8-4de6-b7ed-67e85b37130f
			dataCategory: Uncategorized

		measure '% tests de repérage' = EXTERNALMEASURE("% tests de repérage", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0\ %
			lineageTag: 69ca516b-7ba0-497f-bb88-3dbc7bf7d9f8
			sourceLineageTag: 84a2bbcc-2562-4d38-bb68-d1b398b8593c
			dataCategory: Uncategorized

	ref table Facturation

		measure '# collections concernées' = EXTERNALMEASURE("# collections concernées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptage
			lineageTag: f13245e4-6c0b-47f6-b35e-8a7e34528f78
			sourceLineageTag: 984fec9c-1511-44b8-8759-eecea612fa4c
			dataCategory: Uncategorized

		measure '# entreprises concernées' = EXTERNALMEASURE("# entreprises concernées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptage
			lineageTag: ee1b8723-c15f-436e-a5b6-d99d6621b1e6
			sourceLineageTag: ba84805f-5f0c-4f2c-b249-808f3d2952ad
			dataCategory: Uncategorized

		measure 'Montant moyen HT facturable' = EXTERNALMEASURE("Montant moyen HT facturable", CURRENCY, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ \€
			displayFolder: Indicateurs\Facturable
			lineageTag: 37db6aad-4b6b-4c91-8b41-c570a1b4c6f5
			sourceLineageTag: ea6b3f2d-21b1-4933-9780-938b18a796b9
			dataCategory: Uncategorized

		measure 'Montant moyen HT facturé' = EXTERNALMEASURE("Montant moyen HT facturé", CURRENCY, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ \€
			displayFolder: Indicateurs\Facturé
			lineageTag: b10c9c22-50e6-49c3-b6e5-93a1d9b80d25
			sourceLineageTag: 1d2c6bfe-7d5c-409d-aa3d-e64553347839
			dataCategory: Uncategorized

		measure 'Montant total hors taxe facturé' = EXTERNALMEASURE("Montant total hors taxe facturé", CURRENCY, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ \€
			displayFolder: Indicateurs\Facturé
			lineageTag: 22e2ed2c-cac9-4826-b19d-c667cdc27227
			sourceLineageTag: dd1c6424-a8c7-4ef7-82ed-cdbc63e8b614
			dataCategory: Uncategorized

		measure 'Montant total HT facturable' = EXTERNALMEASURE("Montant total HT facturable", CURRENCY, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ \€
			displayFolder: Indicateurs\Facturable
			lineageTag: 1129add3-3c7f-4fb5-9da0-3605737707fd
			sourceLineageTag: 79ef50b0-0c9c-48b7-acd2-dd1f772fdd7a
			dataCategory: Uncategorized

		measure 'Nombre de documents (facture & avoirs)' = EXTERNALMEASURE("Nombre de documents (facture & avoirs)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptage
			lineageTag: 1e23d080-ff28-475e-a423-3c326cfea10e
			sourceLineageTag: 5eacd402-996b-40cb-bc91-c064347d6b6b
			dataCategory: Uncategorized

		measure 'Nombre total d''actes facturables' = EXTERNALMEASURE("Nombre total d'actes facturables", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptage
			lineageTag: a7fe8a6f-71cd-4cd2-b4d7-c2306cbe024c
			sourceLineageTag: b1b02859-723b-473a-9579-6b4f7a51a099
			dataCategory: Uncategorized

		measure 'Prix unitaire moyen HT facturable' = EXTERNALMEASURE("Prix unitaire moyen HT facturable", CURRENCY, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ \€
			displayFolder: Indicateurs\Facturable
			lineageTag: 714ace25-572d-4d11-9f9c-6d766e2e6d08
			sourceLineageTag: a26f935e-b96e-4161-96fc-cc3b51bbe4b1
			dataCategory: Uncategorized

		measure 'Prix unitaire moyen HT facturé' = EXTERNALMEASURE("Prix unitaire moyen HT facturé", CURRENCY, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ \€
			displayFolder: Indicateurs\Facturé
			lineageTag: 439de4f4-d5c3-4429-a973-130ab475f0b5
			sourceLineageTag: 378ade15-522b-4e64-9746-3bc367435b01
			dataCategory: Uncategorized

		measure 'Quantité moyenne facturable' = EXTERNALMEASURE("Quantité moyenne facturable", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Facturable
			lineageTag: 14cf3013-b196-41b4-bd56-c75f2d0e941b
			sourceLineageTag: 7f352bcb-e4f3-4e49-a46e-bdc49dc42dd3
			dataCategory: Uncategorized

		measure 'Quantité moyenne facturée' = EXTERNALMEASURE("Quantité moyenne facturée", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Facturé
			lineageTag: 0f11736d-6481-4081-9711-66b3dc385b19
			sourceLineageTag: 7d54d1d8-9e76-474c-9ee0-11b02497708e
			dataCategory: Uncategorized

		measure 'Quantité totale facturable' = EXTERNALMEASURE("Quantité totale facturable", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Facturable
			lineageTag: 004c2a1b-1df6-47f7-83d1-0a14fc9c2352
			sourceLineageTag: b82039bd-8109-4540-8c42-14fa6788f695
			dataCategory: Uncategorized

		measure 'Quantité totale facturée' = EXTERNALMEASURE("Quantité totale facturée", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Facturé
			lineageTag: 393f190d-57ec-4ae6-8578-06c4c10e7790
			sourceLineageTag: ac348e1f-5e17-4f8d-a2ca-76553292aff3
			dataCategory: Uncategorized

	ref table 'Modèle de charge - AMT réalisées'

		measure '# AMT réalisées' = EXTERNALMEASURE("# AMT réalisées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 81eb23e1-ac98-4649-a8b9-6ff7b61be6c1
			sourceLineageTag: 89e53b18-8c24-43c9-8466-89611bc75d0a
			dataCategory: Uncategorized

		measure '# APP réalisées' = EXTERNALMEASURE("# APP réalisées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 48ac586c-c451-4b1b-9e82-10f0ed62765b
			sourceLineageTag: f42a85d6-2840-4645-9085-eecaa054379f
			dataCategory: Uncategorized

		measure '# créations FE réalisées' = EXTERNALMEASURE("# créations FE réalisées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: b4168ba7-7194-41e2-bbc7-3b0fe88c1eaf
			sourceLineageTag: 46dba000-ebb6-4d4f-94a6-189f8c047b77
			dataCategory: Uncategorized

		measure '# FE réalisées' = EXTERNALMEASURE("# FE réalisées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 4c0789f1-4c9a-4053-9390-0c944ced78a4
			sourceLineageTag: 5729fdd5-78fb-4954-9510-5167ec7269ec
			dataCategory: Uncategorized

		measure '# mises à jour FE réalisées' = EXTERNALMEASURE("# mises à jour FE réalisées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: b8b0380a-cadb-4e8d-81bc-8f9adfdf06b8
			sourceLineageTag: 94bc3170-7b06-4edc-a927-aca313f598c1
			dataCategory: Uncategorized

	ref table 'Modèle de charge - leviers charge AMT'

		measure 'Nombre adhérents actifs' = EXTERNALMEASURE("Nombre adhérents actifs", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 188bff57-77b0-4d4e-b9e9-d9b3ff0e20bd
			sourceLineageTag: 4cf2715d-9aad-421a-832c-5a5192286afd
			dataCategory: Uncategorized

		measure 'Nombre adhésions dernière année glissante' = EXTERNALMEASURE("Nombre adhésions dernière année glissante", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 9781b82d-cd07-4aa2-8c84-07fe641590c0
			sourceLineageTag: fa141b3c-3c18-40e1-aa4b-cdff57c5c000
			dataCategory: Uncategorized

		measure 'Nombre adhésions multiple 4 ans' = EXTERNALMEASURE("Nombre adhésions multiple 4 ans", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 3d8c48c2-1298-439a-ae3a-699077a797ca
			sourceLineageTag: 2da827ec-d858-4185-93da-5c07cbf272c5
			dataCategory: Uncategorized

		measure 'Nombre salariés commençant adaptation poste dernière année glissante' = EXTERNALMEASURE("Nombre salariés commençant adaptation poste dernière année glissante", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 9bcec2cc-660a-4cd3-831d-dc1c33c42cae
			sourceLineageTag: 6bededd2-8a95-439b-a701-c7e3645c31a0
			dataCategory: Uncategorized

		measure 'Nombre salariés déclarés inaptes dernière année glissante' = EXTERNALMEASURE("Nombre salariés déclarés inaptes dernière année glissante", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 00e70c53-cbe3-4972-b834-2f7702df082d
			sourceLineageTag: 6dcc5de7-3b47-4412-9a19-b3bfdd4ceb07
			dataCategory: Uncategorized

	ref table 'Modèle de charge - prévision charge AMT'

		measure '# AMT estimées' = EXTERNALMEASURE("# AMT estimées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: bfab114f-0f26-40d5-a117-9d72f917d64f
			sourceLineageTag: 7acaa8bb-643f-4ce1-b65c-7fc58e757f1d
			dataCategory: Uncategorized

		measure '# APP estimées' = EXTERNALMEASURE("# APP estimées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 35b1564d-c789-4828-b53e-c3ff3ecd4224
			sourceLineageTag: 6625b81b-c664-4811-9143-20f014903457
			dataCategory: Uncategorized

		measure '# créations FE estimées' = EXTERNALMEASURE("# créations FE estimées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: d7a21031-2b34-4dd9-93bb-8a35d0d6a6a4
			sourceLineageTag: 0a584c59-e60f-443d-ba78-01bb11229c7b
			dataCategory: Uncategorized

		measure '# FE estimées' = EXTERNALMEASURE("# FE estimées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 9c4411b1-33d6-4e49-90ba-69b27ea9024b
			sourceLineageTag: fff1393f-63f1-4b10-a17f-097b1183b6fc
			dataCategory: Uncategorized

		measure '# mises à jour FE estimées' = EXTERNALMEASURE("# mises à jour FE estimées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 4c5eb659-0239-4cf5-a71b-2511d905a581
			sourceLineageTag: ba423ce2-f077-4ac9-a8ad-88b1f5d294a3
			dataCategory: Uncategorized

	ref table 'Modèle de charge - prévision charge visites'

		measure 'Aléatoire médecin' = EXTERNALMEASURE("Aléatoire médecin", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Visites à réaliser par le médecin
			lineageTag: 729e2c25-08cd-468c-86d1-09d62988fb82
			sourceLineageTag: 6cda6ec6-f782-4b5b-9e9f-410eee708011
			dataCategory: Uncategorized

		measure 'Initiale infirmier' = EXTERNALMEASURE("Initiale infirmier", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Visites réalisables par l'infirmier
			lineageTag: 46a499a1-b090-468e-8c99-912d43df48ca
			sourceLineageTag: ca9e92f0-3018-40c3-8664-992a725b4297
			dataCategory: Uncategorized

		measure 'Initiale médecin' = EXTERNALMEASURE("Initiale médecin", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Visites à réaliser par le médecin
			lineageTag: 11594957-190f-4a8a-9956-227632d16b2b
			sourceLineageTag: f0d359f6-f423-48d2-933a-345c36da9b9e
			dataCategory: Uncategorized

		measure 'Intérimaire infirmier' = EXTERNALMEASURE("Intérimaire infirmier", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Visites réalisables par l'infirmier
			lineageTag: 6dbbd2f3-667f-4301-9519-8649b6c86022
			sourceLineageTag: a04328ed-0862-463a-b30b-5b13880ab3e2
			dataCategory: Uncategorized

		measure 'Intérimaire médecin' = EXTERNALMEASURE("Intérimaire médecin", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Visites à réaliser par le médecin
			lineageTag: 898404ec-a43b-4595-aa25-d8eff85ec2f6
			sourceLineageTag: 5c111c20-0957-4023-8bfd-5c4d87a54a91
			dataCategory: Uncategorized

		measure 'Nombre de visites à réaliser' = EXTERNALMEASURE("Nombre de visites à réaliser", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: c01d80a7-ff4e-4cfa-94e8-dd996ee646f6
			sourceLineageTag: 8a70acf3-c6c3-4744-8a55-3b7b4da55cfc
			dataCategory: Uncategorized

		measure 'Périodique infirmier' = EXTERNALMEASURE("Périodique infirmier", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Visites réalisables par l'infirmier
			lineageTag: 3cdb8b9c-b4cd-4a1b-9a9d-e99160c68f18
			sourceLineageTag: d7db8c1b-395f-455a-ad0a-e89f4d8ab8d4
			dataCategory: Uncategorized

		measure 'Périodique médecin' = EXTERNALMEASURE("Périodique médecin", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Visites à réaliser par le médecin
			lineageTag: be5bce86-21af-412b-9c5f-541b9bc7f52f
			sourceLineageTag: 6788e836-e15a-4dfe-a5bc-ac54e88f3807
			dataCategory: Uncategorized

		measure 'Retard infirmier' = EXTERNALMEASURE("Retard infirmier", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Visites réalisables par l'infirmier
			lineageTag: 06f25ddc-defc-4384-a5d2-5cede2f181a7
			sourceLineageTag: 7e6d085a-b3df-4e7e-a8ec-a1063471bc1f
			dataCategory: Uncategorized

		measure 'Retard médecin' = EXTERNALMEASURE("Retard médecin", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Visites à réaliser par le médecin
			lineageTag: 5d058d16-3b4a-4700-a248-6d3e17b86bf1
			sourceLineageTag: 4b1d23e2-be3d-4475-90ff-b11ebd87d9f8
			dataCategory: Uncategorized

		measure 'Visite assistant social' = EXTERNALMEASURE("Visite assistant social", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Visites à réaliser par les spécialistes
			lineageTag: dfb4ecab-fb0c-4a94-b08d-01ec82fb8a0b
			sourceLineageTag: a9735e6a-7d92-4185-8375-50c45d630aae
			dataCategory: Uncategorized

		measure 'Visite cardiologue' = EXTERNALMEASURE("Visite cardiologue", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Visites à réaliser par les spécialistes
			lineageTag: 29424caa-1df0-4df9-8b9e-0da149b59857
			sourceLineageTag: ae92cfcd-4324-4283-a9c4-84f78b2e8875
			dataCategory: Uncategorized

		measure 'Visite conseiller transition professionnelle' = EXTERNALMEASURE("Visite conseiller transition professionnelle", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Visites à réaliser par les spécialistes
			lineageTag: 5092b71b-c092-40b7-9696-092f0320deff
			sourceLineageTag: 19a9fa55-266e-4611-8c2a-8dbac3f3f818
			dataCategory: Uncategorized

		measure 'Visite ergothérapeute' = EXTERNALMEASURE("Visite ergothérapeute", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Visites à réaliser par les spécialistes
			lineageTag: 8f040a87-4d84-4dd6-98ba-777b9418046c
			sourceLineageTag: 9ccd1540-3ab9-4b40-96e1-987a4a1de714
			dataCategory: Uncategorized

		measure 'Visite médecin PDP' = EXTERNALMEASURE("Visite médecin PDP", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Visites à réaliser par les spécialistes
			lineageTag: 2cc4a642-2558-4c91-8f64-a6edff19eceb
			sourceLineageTag: 5d3d1740-db75-4d0c-87a1-825bb97b53a8
			dataCategory: Uncategorized

		measure 'Visite nutritionniste' = EXTERNALMEASURE("Visite nutritionniste", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Visites à réaliser par les spécialistes
			lineageTag: 8253eb7e-cb64-4cfd-a2f5-b91a7b5c9805
			sourceLineageTag: 58955f2b-570f-4cd5-a129-2e569b44ed26
			dataCategory: Uncategorized

		measure 'Visite pneumologue' = EXTERNALMEASURE("Visite pneumologue", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Visites à réaliser par les spécialistes
			lineageTag: abb31124-20a5-4912-8a8a-c9d28ab800ac
			sourceLineageTag: 67eb4a3b-9a25-48e8-8e58-f68b6a4c8ec8
			dataCategory: Uncategorized

		measure 'Visite psychologue' = EXTERNALMEASURE("Visite psychologue", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Visites à réaliser par les spécialistes
			lineageTag: b9a5fbfa-9725-4810-8407-018a52780f32
			sourceLineageTag: 02f10fff-9d29-4961-8529-4124d29cb444
			dataCategory: Uncategorized

	ref table 'Modèle de charge - visites réalisées'

		measure '# visites embauches réalisées année dernière' = EXTERNALMEASURE("# visites embauches réalisées année dernière", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Année dernière
			lineageTag: b8d118af-3da9-4f93-b355-b2259397137c
			sourceLineageTag: bf0249d6-fd54-43ce-8c73-24467ca05fa3
			dataCategory: Uncategorized

		measure '# visites embauches réalisées cette année' = EXTERNALMEASURE("# visites embauches réalisées cette année", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Année en cours
			lineageTag: 687a0425-fe8f-40fd-b7cf-5028a4fd4d5b
			sourceLineageTag: e4b41a85-2969-4491-b33c-cdeee8d961da
			dataCategory: Uncategorized

		measure '# visites intérimaires réalisées année dernière' = EXTERNALMEASURE("# visites intérimaires réalisées année dernière", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Année dernière
			lineageTag: c5512f14-f211-4f2f-a7a1-d2bb2ed71841
			sourceLineageTag: 6b6e09c8-bd54-487a-bff6-06ec7aa6df45
			dataCategory: Uncategorized

		measure '# visites intérimaires réalisées cette année' = EXTERNALMEASURE("# visites intérimaires réalisées cette année", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Année en cours
			lineageTag: 382e503a-11da-4136-a95f-f5fd8fd0268e
			sourceLineageTag: 0530a39a-b9f0-4c49-8e19-413f2fbc718e
			dataCategory: Uncategorized

		measure '# visites occasionnelles réalisées année dernière' = EXTERNALMEASURE("# visites occasionnelles réalisées année dernière", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Année dernière
			lineageTag: 4739e08d-3a7c-4d35-aea5-21f2babc5380
			sourceLineageTag: 698fbd1a-b5d4-4db4-b28e-f2a9f7e8f3de
			dataCategory: Uncategorized

		measure '# visites occasionnelles réalisées cette année' = EXTERNALMEASURE("# visites occasionnelles réalisées cette année", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Année en cours
			lineageTag: 21b2239d-c11f-4194-9b32-7f63dd5e295e
			sourceLineageTag: f91fe8b8-7782-4687-a0ab-9a47f62f5616
			dataCategory: Uncategorized

		measure '# visites périodiques réalisées année dernière' = EXTERNALMEASURE("# visites périodiques réalisées année dernière", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Année dernière
			lineageTag: d040fc4a-4bd9-43e7-b96e-a86cd6baa038
			sourceLineageTag: 1d1dd607-e2d4-4874-af99-ac0328f2af7b
			dataCategory: Uncategorized

		measure '# visites périodiques réalisées cette année' = EXTERNALMEASURE("# visites périodiques réalisées cette année", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Année en cours
			lineageTag: 110c0160-c334-4dbb-afa7-eb6564ff5b25
			sourceLineageTag: c5697f68-4464-4d0b-8604-0f73cf70e771
			dataCategory: Uncategorized

		measure '# visites réalisées année dernière' = EXTERNALMEASURE("# visites réalisées année dernière", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Année dernière
			lineageTag: d357deb8-04f5-4943-8473-6c43011bf47c
			sourceLineageTag: c0820124-0aec-4160-b7cd-bd1b7cd182c6
			dataCategory: Uncategorized

		measure '# visites réalisées cette année' = EXTERNALMEASURE("# visites réalisées cette année", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Année en cours
			lineageTag: 3a9c9a28-7fa8-4b71-bb33-aaf85dc71013
			sourceLineageTag: 91fe8c23-aca8-410f-9ca8-d354db46dc40
			dataCategory: Uncategorized

	ref table Orientation

		measure '# orientations' = EXTERNALMEASURE("# orientations", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Total
			lineageTag: f5fe136e-81c8-407d-99d8-1b255d460c47
			sourceLineageTag: 46b28162-6bc0-4330-80cd-7f18014bd3ee
			dataCategory: Uncategorized

		measure '# orientations externes' = EXTERNALMEASURE("# orientations externes", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Par type d'orientation
			lineageTag: 42f45a08-3cda-48c5-8dea-14791d853090
			sourceLineageTag: efed093f-5473-4b02-9e88-4f19415fe4dc
			dataCategory: Uncategorized

		measure '# orientations hors visite' = EXTERNALMEASURE("# orientations hors visite", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Total
			lineageTag: 4d28e47c-0b8e-46ff-808c-428bddefe248
			sourceLineageTag: e120611e-16c2-4f0e-9947-ac59371d01f6
			dataCategory: Uncategorized

		measure '# orientations internes' = EXTERNALMEASURE("# orientations internes", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Par type d'orientation
			lineageTag: 333042ec-8cfb-4d26-a4c6-482253ff956b
			sourceLineageTag: 5d74244c-18a4-4ebd-a1e7-d27d9dc48bb4
			dataCategory: Uncategorized

		measure '# recommandations orales' = EXTERNALMEASURE("# recommandations orales", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Par type d'orientation
			lineageTag: 81fa5852-0405-4783-be8c-22a401fdf5ae
			sourceLineageTag: 2aff461a-f77e-4551-ab24-065413683fe0
			dataCategory: Uncategorized

		measure '# salariés avec orientation' = EXTERNALMEASURE("# salariés avec orientation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Total
			lineageTag: 5d9ee5b9-eac0-4932-9618-4ad200b5e38f
			sourceLineageTag: 5897fcba-72b9-4e8a-9fe7-03eb816c8d87
			dataCategory: Uncategorized

		measure '# visites avec orientation' = EXTERNALMEASURE("# visites avec orientation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Total
			lineageTag: 6a670448-7fda-448e-ab4a-f03a23d00a4a
			sourceLineageTag: ac43fb1f-1640-4393-94f6-7c0a3a5c8042
			dataCategory: Uncategorized

		measure '% orientations hors visite' = EXTERNALMEASURE("% orientations hors visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			lineageTag: 5ff009a7-c74b-4020-85fb-ee5935f36cf1
			sourceLineageTag: 143d669b-8d53-4992-8c01-c8a594136b91
			dataCategory: Uncategorized

	ref table 'Plan MEE'

		measure '# dispositifs MEE (plan MEE)' = EXTERNALMEASURE("# dispositifs MEE (plan MEE)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: c261ddc6-df33-4777-9d31-413a4980c8e4
			sourceLineageTag: c3965cf4-5269-4a44-a87e-05c7c4df8962
			dataCategory: Uncategorized

		measure '# dispositifs par plan MEE' = EXTERNALMEASURE("# dispositifs par plan MEE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs
			lineageTag: f8346ac6-6856-458b-b5c8-4daf51c26779
			sourceLineageTag: 040b7717-6bfe-4445-9b49-6fa59ba4752a
			dataCategory: Uncategorized

		measure '# entreprises concernées (plan MEE)' = EXTERNALMEASURE("# entreprises concernées (plan MEE)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 7fc16f3d-8181-49b9-b460-6209513905b6
			sourceLineageTag: d6f3e54a-473c-4646-a327-0831f72e9449
			dataCategory: Uncategorized

		measure '# intervenants par plan MEE' = EXTERNALMEASURE("# intervenants par plan MEE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Indicateurs
			lineageTag: 1a57a355-f1ca-450a-9ad3-469aa3d0f678
			sourceLineageTag: 086aba14-f4fd-49bc-8fe3-cea865f7a81e
			dataCategory: Uncategorized

		measure '# objectifs par plan MEE' = EXTERNALMEASURE("# objectifs par plan MEE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs
			lineageTag: 0a9291f9-1cec-4420-8ec3-1e8b0ebb5c50
			sourceLineageTag: 80fbde88-fe86-48a2-8a9c-fcfd4cf01795
			dataCategory: Uncategorized

		measure '# plans MEE' = EXTERNALMEASURE("# plans MEE", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 4746004e-ea9c-4378-bbb8-a6465ace53ce
			sourceLineageTag: b3433431-5a21-4e0e-b45b-04d7e9331cca
			dataCategory: Uncategorized

		measure '# problèmes de santé' = EXTERNALMEASURE("# problèmes de santé", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 8da97149-5bb5-4fcd-8143-df34c7042ce4
			sourceLineageTag: 46b9a439-6cf0-4f53-8dcc-0f1919910048
			dataCategory: Uncategorized

		measure '# problèmes de santé par plan MEE' = EXTERNALMEASURE("# problèmes de santé par plan MEE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs
			lineageTag: d943cc77-2866-4e62-b9f3-bd99d4b57ff2
			sourceLineageTag: ee646a58-2903-47bb-97e7-cd92cb8773c5
			dataCategory: Uncategorized

		measure '# salariés concernés (plan MEE)' = EXTERNALMEASURE("# salariés concernés (plan MEE)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 864d2ac0-236e-4e6d-8695-a88b8edb38a2
			sourceLineageTag: 86891397-506a-4414-a2aa-c5855df100b3
			dataCategory: Uncategorized

		measure '# structures mobilisées par plan MEE' = EXTERNALMEASURE("# structures mobilisées par plan MEE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs
			lineageTag: 6f111e0b-a5c5-4fd7-9651-57e11f767391
			sourceLineageTag: 70a84871-5e2d-4513-a525-755f077ff8a9
			dataCategory: Uncategorized

		measure 'Durée moyenne plan MEE (j)' = EXTERNALMEASURE("Durée moyenne plan MEE (j)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 75c6da9d-8c1e-4a07-a4f7-7077b36b2413
			sourceLineageTag: 77e9393a-15e2-401f-93d9-f210847791fc
			dataCategory: Uncategorized

		measure 'IRDP moyen après plan MEE' = EXTERNALMEASURE("IRDP moyen après plan MEE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs
			lineageTag: 304a85fb-ccca-45b3-8229-da1fba5262de
			sourceLineageTag: f25913a7-6684-49fa-b9f9-2dadaecda4c9
			dataCategory: Uncategorized

		measure 'IRDP moyen avant plan MEE' = EXTERNALMEASURE("IRDP moyen avant plan MEE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs
			lineageTag: b50e5b2b-e27f-4a36-8987-5562d45d04ff
			sourceLineageTag: 7a1632b7-1a1e-4785-bba7-a57fb7d7f887
			dataCategory: Uncategorized

		measure 'IRI moyen après plan MEE' = EXTERNALMEASURE("IRI moyen après plan MEE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs
			lineageTag: b7024605-eb81-4040-9475-2a3cec090c4a
			sourceLineageTag: 68095f4d-c7f7-43b8-bd1e-cd40d393d3df
			dataCategory: Uncategorized

		measure 'IRI moyen avant plan MEE' = EXTERNALMEASURE("IRI moyen avant plan MEE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs
			lineageTag: 79d00ff8-b3d0-46ea-bf76-c662be5f18ac
			sourceLineageTag: ba2957da-800a-4a6c-9ed8-65c24400ae87
			dataCategory: Uncategorized

	ref table 'Plaquette de prévention'

		measure '# plaquettes de prévention' = EXTERNALMEASURE("# plaquettes de prévention", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 0a9e1938-f89f-47da-a675-618412dd5cec
			sourceLineageTag: f6c9e4e1-f25a-4a1c-a924-ed72c2ff7d6d
			dataCategory: Uncategorized

		measure '# salariés avec plaquette de prévention' = EXTERNALMEASURE("# salariés avec plaquette de prévention", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 2e3022b9-c8b9-42b9-9ff8-7887ce6cf3e5
			sourceLineageTag: a2d815a8-0c52-4633-8df9-74c5e70c2b16
			dataCategory: Uncategorized

		measure '# visites avec plaquette de prévention' = EXTERNALMEASURE("# visites avec plaquette de prévention", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 6577ede5-66da-4158-8cc0-01568e7ab92d
			sourceLineageTag: 95dcc6f1-2264-4f2e-a08e-ae8b5a6527b1
			dataCategory: Uncategorized

	ref table Prescription

		measure '# prescriptions' = EXTERNALMEASURE("# prescriptions", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 034e7146-a339-4416-97a5-61f97c88db62
			sourceLineageTag: 24102185-6af0-4c41-910e-cb6595bb205e
			dataCategory: Uncategorized

		measure '# prescriptions émises hors visite' = EXTERNALMEASURE("# prescriptions émises hors visite", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: c11c8015-48f1-4d45-b9d7-854174eb91e7
			sourceLineageTag: ac95d644-3e9b-46ad-8c03-0421a5a2a120
			dataCategory: Uncategorized

		measure '# prescriptions en attente de résultats' = EXTERNALMEASURE("# prescriptions en attente de résultats", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: fd023511-54c3-4e18-8acb-cbc25954f1c2
			sourceLineageTag: 7aa4de0d-93c4-4506-9da9-4a48b409dd8f
			dataCategory: Uncategorized

		measure '# salariés avec prescription' = EXTERNALMEASURE("# salariés avec prescription", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: f75370b9-a139-4291-8a61-a6a6732f53a2
			sourceLineageTag: 37920a0a-4e13-4998-92c7-e6345a8608bc
			dataCategory: Uncategorized

		measure '# visites avec prescription' = EXTERNALMEASURE("# visites avec prescription", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 58386fea-3bbb-4536-b71a-82835af60416
			sourceLineageTag: 498fd4cf-b740-4c98-8f9a-53f1dd6887b8
			dataCategory: Uncategorized

		measure '% prescriptions émises hors visite' = EXTERNALMEASURE("% prescriptions émises hors visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			lineageTag: 293d1f5f-363c-4d5f-b89a-34eeaf19ccd4
			sourceLineageTag: 4ce06d25-106d-45eb-aacf-5ba43f83d217
			dataCategory: Uncategorized

		measure '% prescriptions en attente de résultats' = EXTERNALMEASURE("% prescriptions en attente de résultats", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			lineageTag: ca76017f-b919-4b3f-9954-c6f844cbdc43
			sourceLineageTag: b1038eac-c2f2-4a48-98bc-73f7cef24352
			dataCategory: Uncategorized

	ref table Prospect

		measure '# adhésion' = EXTERNALMEASURE("# adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: e799ed0d-68a4-4078-9bec-cfafcdf0e86c
			sourceLineageTag: d6fa4bfa-a34c-4b83-8043-847183e14148
			dataCategory: Uncategorized

		measure '# demande de contact' = EXTERNALMEASURE("# demande de contact", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 6d2c1164-d3a4-480a-a09c-1a60687b992a
			sourceLineageTag: f9d746e0-8638-4dfb-902f-1ed263cbdc06
			dataCategory: Uncategorized

		measure '# éligibilité à déterminer' = EXTERNALMEASURE("# éligibilité à déterminer", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 05a8698d-e3d3-422a-afce-092b84ff9e95
			sourceLineageTag: da24296a-46a1-467a-bbc5-b1ed38ec45d9
			dataCategory: Uncategorized

		measure '# parcours d''adhésion' = EXTERNALMEASURE("# parcours d'adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 62d7b588-7a5e-4d26-b77c-b1d687de8764
			sourceLineageTag: 2b83b70d-dc97-4c32-b949-c2bf4a09ec8d
			dataCategory: Uncategorized

		measure '# prospect créé' = EXTERNALMEASURE("# prospect créé", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: b5e41516-6163-44aa-b861-a2f664472d41
			sourceLineageTag: af68323f-48aa-41c0-a8cc-b1345f1accb2
			dataCategory: Uncategorized

		measure '# prospect écarté' = EXTERNALMEASURE("# prospect écarté", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 1ec2128c-432f-4ca1-89e4-03d6703b5a1a
			sourceLineageTag: f2501bff-8bfa-48e4-be67-e43b814410f7
			dataCategory: Uncategorized

		measure '# prospect en cours d''adhésion' = EXTERNALMEASURE("# prospect en cours d'adhésion", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 43ddc059-1caa-443b-be77-10e9efe6e5c6
			sourceLineageTag: 69f42c17-64e0-4b1d-a833-9c9f1868624c
			dataCategory: Uncategorized

		measure '# salariés' = EXTERNALMEASURE("# salariés", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: b5a78d07-00b3-4f0a-8eaa-969ce02a33dd
			sourceLineageTag: 76f0f520-d3ef-47b8-b2a7-cadbe0c70ae0
			dataCategory: Uncategorized

		measure '# salariés SI' = EXTERNALMEASURE("# salariés SI", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: be3b8f79-2a05-4980-b87e-c002d5e228b1
			sourceLineageTag: 207155f8-c0e4-4868-886f-d3d1393763a1
			dataCategory: Uncategorized

		measure '# salariés SIA' = EXTERNALMEASURE("# salariés SIA", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 8fc25e32-856d-4109-91cc-74449df563d0
			sourceLineageTag: f3675939-3721-4342-928f-ad25591b14c8
			dataCategory: Uncategorized

		measure '# salariés SIR' = EXTERNALMEASURE("# salariés SIR", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: bcf1c5c2-15ee-4f4d-8c01-19eba0d9e4b5
			sourceLineageTag: 3a84ea17-596f-4916-904e-1c591d1f7bde
			dataCategory: Uncategorized

		measure 'Durée moyenne demande contact (min)' = EXTERNALMEASURE("Durée moyenne demande contact (min)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs
			lineageTag: 27a09620-31c9-433a-abb0-2761c4cc3566
			sourceLineageTag: 1818b049-c6bc-4cc2-bb6f-780307373d8e
			dataCategory: Uncategorized

		measure 'Durée moyenne éligibilité à déterminer (min)' = EXTERNALMEASURE("Durée moyenne éligibilité à déterminer (min)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs
			lineageTag: 86c25969-b6a9-425f-87e8-e3deab9ebbae
			sourceLineageTag: 20131bd2-0632-4abd-adb1-9d33434f0b11
			dataCategory: Uncategorized

		measure 'Durée moyenne parcours d''adhésion (min)' = EXTERNALMEASURE("Durée moyenne parcours d'adhésion (min)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs
			lineageTag: 7252115d-abf8-4ba8-ab4a-7a2646362b41
			sourceLineageTag: 0a0275c8-8778-493e-bf7e-bcf5eceb2c0b
			dataCategory: Uncategorized

		measure 'Gain potentiel du service' = EXTERNALMEASURE("Gain potentiel du service", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0\ \€
			displayFolder: Indicateurs
			lineageTag: 18f31e56-ee83-4d77-948d-c681b4a9ad48
			sourceLineageTag: 6f2db932-1f17-4189-ac39-d55353de4f9b
			dataCategory: Uncategorized

		measure 'Temps moyen passé avant adhésion (j)' = EXTERNALMEASURE("Temps moyen passé avant adhésion (j)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs
			lineageTag: bdab01ce-1ec7-4a5a-9fcd-85280a750a88
			sourceLineageTag: 8806e264-c0e6-4661-bea0-c6514490bb62
			dataCategory: Uncategorized

		measure 'Temps moyen passé avant mise à l''écart (j)' = EXTERNALMEASURE("Temps moyen passé avant mise à l'écart (j)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs
			lineageTag: 24e1ee2e-488b-4ed3-892a-983e9436b981
			sourceLineageTag: 0326731b-f7b4-42a8-871a-7f54b38981e7
			dataCategory: Uncategorized

		measure 'Temps moyen passé prospect en cours d''adhésion (j)' = EXTERNALMEASURE("Temps moyen passé prospect en cours d'adhésion (j)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs
			lineageTag: 110b6355-4943-4adc-8f11-78e6b89df543
			sourceLineageTag: 2caf7272-1256-4306-a160-3474d9941d60
			dataCategory: Uncategorized

	ref table RDV

		measure 'Délai médian reconvocation anticipée' = EXTERNALMEASURE("Délai médian reconvocation anticipée", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0
			displayFolder: Indicateurs\4 - Durées
			lineageTag: 8e5d3e07-18e2-4a5e-88ac-a7fb932439a8
			sourceLineageTag: f60ba465-c0a7-4a82-a521-5676ac6ccbdb
			dataCategory: Uncategorized

		measure 'Durée moyenne entre la création du RDV et sa date planifiée' = EXTERNALMEASURE("Durée moyenne entre la création du RDV et sa date planifiée", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs\4 - Durées
			lineageTag: 58be381f-a45a-4852-a18a-bb7b39da4144
			sourceLineageTag: 89da1d5b-79ee-4018-96fb-bfc22e7d5528
			dataCategory: Uncategorized

		measure 'Durée moyenne entre la mise à disposition du créneau et son remplissage par l''adhérent' = EXTERNALMEASURE("Durée moyenne entre la mise à disposition du créneau et son remplissage par l'adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs\4 - Durées
			lineageTag: 496743c1-c7af-4fbe-86c7-25a24a39aab2
			sourceLineageTag: acd263e3-4007-4ae5-8d77-ec42167aeeb3
			dataCategory: Uncategorized

		measure 'Durée moyenne entre la première convocation du RDV et sa date planifiée' = EXTERNALMEASURE("Durée moyenne entre la première convocation du RDV et sa date planifiée", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs\4 - Durées
			lineageTag: 8e9dd559-7edf-469a-9668-c656ea8dcfbd
			sourceLineageTag: 02e5c64e-71d7-466d-b9c2-c0f9e0ba2914
			dataCategory: Uncategorized

		measure 'Durée moyenne entretien théorique' = EXTERNALMEASURE("Durée moyenne entretien théorique", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.0
			displayFolder: Indicateurs\4 - Durées
			lineageTag: 7056bec9-0ba2-4413-b013-87725a05b8e0
			sourceLineageTag: a7f30eba-65d2-4812-a25d-b90d656a6ac5
			dataCategory: Uncategorized

		measure 'Nombre d''annulations techniques' = EXTERNALMEASURE("Nombre d'annulations techniques", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - RDV\Comptages
			lineageTag: 81f6eaf4-c445-4a4c-b259-b65355eb7c03
			sourceLineageTag: f5df286c-303b-44db-bfe7-93014912dd24
			dataCategory: Uncategorized

		measure 'Nombre de créneaux adhérent' = EXTERNALMEASURE("Nombre de créneaux adhérent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Créneaux adhérents\Comptages
			lineageTag: 97299d6d-1d1e-44a3-a8d1-869787bfbaa6
			sourceLineageTag: 14dba37a-083b-43b4-b32c-b9852bc5ce43
			dataCategory: Uncategorized

		measure 'Nombre de créneaux adhérent non pourvus' = EXTERNALMEASURE("Nombre de créneaux adhérent non pourvus", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Créneaux adhérents\Comptages
			lineageTag: 5446024a-c16a-44b2-a409-c189de5e56e5
			sourceLineageTag: 8438a6e9-20cb-410b-ba32-a1153c71528b
			dataCategory: Uncategorized

		measure 'Nombre de créneaux adhérent non pourvus excusés' = EXTERNALMEASURE("Nombre de créneaux adhérent non pourvus excusés", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Créneaux adhérents\Comptages
			lineageTag: 68077723-1507-4c2d-be9c-f50354751217
			sourceLineageTag: b6f14e63-20b2-4e8e-a562-8bd3ab4a5036
			dataCategory: Uncategorized

		measure 'Nombre de créneaux adhérent non pourvus non excusés' = EXTERNALMEASURE("Nombre de créneaux adhérent non pourvus non excusés", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Créneaux adhérents\Comptages
			lineageTag: 491e1d32-74ca-489e-ac85-a39586fae0ba
			sourceLineageTag: bc810e32-41a1-49ab-98a2-b66f6c24c54d
			dataCategory: Uncategorized

		measure 'Nombre de créneaux adhérent pourvus' = EXTERNALMEASURE("Nombre de créneaux adhérent pourvus", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Créneaux adhérents\Comptages
			lineageTag: 7bef1371-5d2f-42b7-8d8b-1198f84944f6
			sourceLineageTag: 85298182-69b8-4b4a-9424-15d4ecc0e480
			dataCategory: Uncategorized

		measure 'Nombre de déplacements de RDV' = EXTERNALMEASURE("Nombre de déplacements de RDV", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - RDV\Comptages
			lineageTag: 91988bef-c016-49a6-ac44-b36c4f6e326c
			sourceLineageTag: 7bc3754d-b698-4072-9e98-e6e646d9c381
			dataCategory: Uncategorized

		measure 'Nombre de déplacements de RDV après envoi de la convocation' = EXTERNALMEASURE("Nombre de déplacements de RDV après envoi de la convocation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - RDV\Comptages
			lineageTag: b547db0f-e034-4c3a-b9b4-c5d05d9e4842
			sourceLineageTag: 1547ccbe-75cf-45b0-8d66-c7a5dfdcfc93
			dataCategory: Uncategorized

		measure 'Nombre de déplacements de RDV avant envoi de la convocation' = EXTERNALMEASURE("Nombre de déplacements de RDV avant envoi de la convocation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - RDV\Comptages
			lineageTag: d19dda40-5bbc-4372-ad6e-fb648407f64a
			sourceLineageTag: 6c5acf2c-dedc-4678-b368-4c09ff2a178b
			dataCategory: Uncategorized

		measure 'Nombre de déplacements de RDV par l''adhérent' = EXTERNALMEASURE("Nombre de déplacements de RDV par l'adhérent", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - RDV\Comptages
			lineageTag: 1e0c97cf-b2d0-4708-9968-31bb3b6f90ba
			sourceLineageTag: ad3379a7-ada7-401f-a242-ed1c3c5e16ea
			dataCategory: Uncategorized

		measure 'Nombre de déplacements de RDV par le SST' = EXTERNALMEASURE("Nombre de déplacements de RDV par le SST", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - RDV\Comptages
			lineageTag: 878fc3eb-e7ba-4bef-9c30-693362f70d67
			sourceLineageTag: 552d02d3-64c2-4b75-84e0-295409c9e440
			dataCategory: Uncategorized

		measure 'Nombre de prochaine visite avec MdT' = EXTERNALMEASURE("Nombre de prochaine visite avec MdT", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - RDV\Comptages
			lineageTag: 79cbfde3-2f24-496b-9f5a-709fa8d016b4
			sourceLineageTag: 08a6a03b-2ea1-4cf9-9c1f-ba1c7715608c
			dataCategory: Uncategorized

		measure 'Nombre de prochaine visite modifiée' = EXTERNALMEASURE("Nombre de prochaine visite modifiée", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Indicateurs\1 - RDV\Comptages
			lineageTag: dfeadf13-c3b3-4dfd-9c5d-2fcce2322506
			sourceLineageTag: d2e2b2bf-8ea0-4c61-bab1-bdc43a8f0b98
			dataCategory: Uncategorized

		measure 'Nombre de rappels envoyés' = EXTERNALMEASURE("Nombre de rappels envoyés", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Convocations envoyées
			lineageTag: 3328c745-c896-45b6-bf05-df23f696d9a2
			sourceLineageTag: dcfa0b43-b4d8-49f0-a573-4ff94bf7d86c
			dataCategory: Uncategorized

		measure 'Nombre de RDV' = EXTERNALMEASURE("Nombre de RDV", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - RDV\Comptages
			lineageTag: 932b2398-f128-4ca2-a634-6f0c04e73a0c
			sourceLineageTag: cdad2796-22da-41c4-aed9-32f0f515b2e4
			dataCategory: Uncategorized

		measure 'Nombre de RDV annulés' = EXTERNALMEASURE("Nombre de RDV annulés", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - RDV\Comptages
			lineageTag: 34f85715-557d-4837-9236-105f4e7e4c10
			sourceLineageTag: c4ff15c9-bfda-4e33-b7b4-6d42fe78fd04
			dataCategory: Uncategorized

		measure 'Nombre de RDV annulés excusés' = EXTERNALMEASURE("Nombre de RDV annulés excusés", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - RDV\Comptages
			lineageTag: b27cfb88-f5d2-485a-bdce-9fe14d373c70
			sourceLineageTag: bacceef2-f0b5-4c6c-8dd3-154deea65e4f
			dataCategory: Uncategorized

		measure 'Nombre de RDV annulés non excusés' = EXTERNALMEASURE("Nombre de RDV annulés non excusés", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - RDV\Comptages
			lineageTag: 493085d9-9570-4a83-8961-5d606c9af7b9
			sourceLineageTag: d172d0ae-927f-4415-a363-36613fd87482
			dataCategory: Uncategorized

		measure 'Nombre de RDV avec convocation' = EXTERNALMEASURE("Nombre de RDV avec convocation", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - RDV\Comptages
			lineageTag: 713c2fb4-8ba3-4dfd-b3af-5d4095e1467b
			sourceLineageTag: 8b496feb-ce34-45b0-a0d2-c0eec20127db
			dataCategory: Uncategorized

		measure 'Nombre de salariés convoqués' = EXTERNALMEASURE("Nombre de salariés convoqués", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Convocations envoyées
			lineageTag: f3ffd01a-cdf6-4a60-9645-0361c26aca59
			sourceLineageTag: 9d54745b-1057-4b83-8a9d-0186d91a308a
			dataCategory: Uncategorized

		measure 'Nombre de salariés vus' = EXTERNALMEASURE("Nombre de salariés vus", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Convocations envoyées
			lineageTag: 8d3f2ca8-e270-407b-8d6f-2fa8a42351b0
			sourceLineageTag: 252f7a76-f3cc-4f59-969f-2d9b5775424e
			dataCategory: Uncategorized

		measure 'Nombre de visites réalisées (RDV)' = EXTERNALMEASURE("Nombre de visites réalisées (RDV)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - RDV\Comptages
			lineageTag: cc224836-946b-405f-b7ca-5296eb8e91a4
			sourceLineageTag: 1d3345ab-ae97-489e-bfb5-e6b543c1e437
			dataCategory: Uncategorized

		measure 'Ratio convoqués / venus' = EXTERNALMEASURE("Ratio convoqués / venus", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #.00
			displayFolder: Indicateurs\1 - RDV\Taux
			lineageTag: 216b1974-d661-48e1-8e36-40c58f539e0a
			sourceLineageTag: bfdf8d37-2889-44c7-b85d-31b4eee016a9
			dataCategory: Uncategorized

		measure 'Taux annulation non excusée (absentéisme)' = EXTERNALMEASURE("Taux annulation non excusée (absentéisme)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\1 - RDV\Taux
			lineageTag: bbfd0465-68fa-4b17-a260-1ff5a534732c
			sourceLineageTag: 23c9e174-3a7f-425b-8888-7fc96759cd5a
			dataCategory: Uncategorized

		measure 'Taux créneaux adhérents non pourvus' = EXTERNALMEASURE("Taux créneaux adhérents non pourvus", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\3 - Créneaux adhérents\Taux
			lineageTag: d645ccbf-964f-4cb0-b725-a5efe461c933
			sourceLineageTag: 217ba171-5f2d-470e-b4e8-e59f16c907a6
			dataCategory: Uncategorized

		measure 'Taux créneaux adhérents non pourvus (annulation excusée)' = EXTERNALMEASURE("Taux créneaux adhérents non pourvus (annulation excusée)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\3 - Créneaux adhérents\Taux
			lineageTag: b7a10fa2-37b6-4dcc-9ee9-8537e2ff6b97
			sourceLineageTag: 5f120678-0b01-4170-a97b-a114d31fe0ba
			dataCategory: Uncategorized

		measure 'Taux créneaux adhérents non pourvus (annulation non excusée)' = EXTERNALMEASURE("Taux créneaux adhérents non pourvus (annulation non excusée)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\3 - Créneaux adhérents\Taux
			lineageTag: 1a41bcd6-6cec-41cf-89e0-3c5eab3c7f29
			sourceLineageTag: d83bd915-fdbf-4bfb-b137-601a343449c4
			dataCategory: Uncategorized

		measure 'Taux créneaux adhérents pourvus' = EXTERNALMEASURE("Taux créneaux adhérents pourvus", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\3 - Créneaux adhérents\Taux
			lineageTag: de128c10-984e-4491-b368-beb6c56bfdcd
			sourceLineageTag: ed3f8dfc-b208-4700-ac1f-9de10c6e7dcb
			dataCategory: Uncategorized

		measure 'Taux de déplacements de RDV après envoi de la convocation' = EXTERNALMEASURE("Taux de déplacements de RDV après envoi de la convocation", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\1 - RDV\Taux
			lineageTag: 13ec6032-78c6-4830-ab3d-620da7dabfee
			sourceLineageTag: f55b9ee2-cca3-408d-9236-52cb596a952e
			dataCategory: Uncategorized

		measure 'Taux de déplacements de RDV avant envoi de la convocation' = EXTERNALMEASURE("Taux de déplacements de RDV avant envoi de la convocation", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\1 - RDV\Taux
			lineageTag: 2caa71dc-6544-4f89-b952-d69813085de6
			sourceLineageTag: cb712c1b-00ca-408a-85b1-772a81b89970
			dataCategory: Uncategorized

		measure 'Taux de déplacements de RDV par l''adhérent' = EXTERNALMEASURE("Taux de déplacements de RDV par l'adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\1 - RDV\Taux
			lineageTag: 3745d990-057d-4eab-ac28-834cd734ad60
			sourceLineageTag: 02f04b54-6a2f-4b6a-8511-877631dd9c38
			dataCategory: Uncategorized

		measure 'Taux de déplacements de RDV par le SST' = EXTERNALMEASURE("Taux de déplacements de RDV par le SST", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\1 - RDV\Taux
			lineageTag: b53e131a-d628-4487-8256-a645a9db6bfa
			sourceLineageTag: 2331086a-60cd-4099-9b55-8f907efc2652
			dataCategory: Uncategorized

		measure 'Taux de modification date prochaine visite' = EXTERNALMEASURE("Taux de modification date prochaine visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\1 - RDV\Taux
			lineageTag: 7fa2edc1-be4b-44e9-a247-3e657e2dce0c
			sourceLineageTag: 559e0fdb-3dc0-4ceb-aaaf-40dab02f982f
			dataCategory: Uncategorized

		measure 'Taux de visites réalisées délégables IDEST' = EXTERNALMEASURE("Taux de visites réalisées délégables IDEST", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\1 - RDV\Taux
			lineageTag: 454cf1d8-91dd-4b22-8cac-2ea897c0568e
			sourceLineageTag: b5df5cca-f6e1-4520-a5d2-f50f05598d95
			dataCategory: Uncategorized

		measure 'Taux prochaine visite modifiée à réaliser par MDT' = EXTERNALMEASURE("Taux prochaine visite modifiée à réaliser par MDT", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\1 - RDV\Taux
			lineageTag: dd803705-a3d2-466a-b25f-fa713ebd8f18
			sourceLineageTag: ad28cbf4-2074-48fe-a5e5-44045ef3f096
			dataCategory: Uncategorized

		measure 'Taux RDV déplacés par l''adhérent' = EXTERNALMEASURE("Taux RDV déplacés par l'adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\1 - RDV\Taux
			lineageTag: c4e73791-c8d6-49dc-a7ca-0e9d9669b03d
			sourceLineageTag: 505eede0-27fe-4f45-bd5f-6058b1f06f0c
			dataCategory: Uncategorized

		measure 'Taux RDV déplacés par le SST' = EXTERNALMEASURE("Taux RDV déplacés par le SST", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\1 - RDV\Taux
			lineageTag: 86081907-2164-4053-8a1f-933f40a7382b
			sourceLineageTag: fdb78b6c-7cf7-4e48-8053-376cb1e3210f
			dataCategory: Uncategorized

	ref table 'Remplissage noa'

		measure '# actions de prévention à réaliser' = EXTERNALMEASURE("# actions de prévention à réaliser", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Remplissage actuel
			lineageTag: ac547cda-5fde-4376-a5b0-b8247c780dce
			sourceLineageTag: 83063630-8910-434d-b018-592159cd794d
			dataCategory: Uncategorized

		measure '# actions de prévention à réaliser par adhérent' = EXTERNALMEASURE("# actions de prévention à réaliser par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\2 - Remplissage actuel
			lineageTag: ffc2f648-2823-4846-926c-74249eb8f461
			sourceLineageTag: 1bb69357-47ed-4e46-9298-7355474fb21e
			dataCategory: Uncategorized

		measure '# actions de prévention à réaliser supplémentaires par adhérent' = EXTERNALMEASURE("# actions de prévention à réaliser supplémentaires par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\5 - Evolution du remplissage
			lineageTag: 54ae3db3-420c-42af-9446-fb8c0d33ab1e
			sourceLineageTag: f596f907-ba3e-4967-96ab-277b841b1924
			dataCategory: Uncategorized

		measure '# actions de prévention réalisées' = EXTERNALMEASURE("# actions de prévention réalisées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Remplissage actuel
			lineageTag: 8e6820de-e480-4ff4-8c16-25d8b6fec343
			sourceLineageTag: 5801cc26-3fa1-4963-953d-e31cdd0498b0
			dataCategory: Uncategorized

		measure '# actions de prévention réalisées par adhérent' = EXTERNALMEASURE("# actions de prévention réalisées par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\2 - Remplissage actuel
			lineageTag: a70721f1-176b-42f8-9010-765f52990487
			sourceLineageTag: 4a9f000c-2322-4d4a-b8d1-e7e73724f5e2
			dataCategory: Uncategorized

		measure '# actions de prévention réalisées supplémentaires par adhérent' = EXTERNALMEASURE("# actions de prévention réalisées supplémentaires par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\5 - Evolution du remplissage
			lineageTag: f1134eee-84d6-4ad9-b124-3e95abeb3abd
			sourceLineageTag: b99b6247-25ff-4f73-8a74-8124ab4769b9
			dataCategory: Uncategorized

		measure '# actions de prévention reprises depuis la FE' = EXTERNALMEASURE("# actions de prévention reprises depuis la FE", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Synergies FE/DU
			lineageTag: 57a29d23-7b87-4a40-8a15-386258f9437d
			sourceLineageTag: be8f05c9-75ce-425d-a270-d853e34173e3
			dataCategory: Uncategorized

		measure '# adhérents abonnés noa' = EXTERNALMEASURE("# adhérents abonnés noa", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Adhérents concernés
			lineageTag: d970891f-7a6f-4dc8-a0f1-89de09e65f7a
			sourceLineageTag: 8187d8b5-48b9-40c1-b9f5-3928c850fc2b
			dataCategory: Uncategorized

		measure '# adhérents abonnés noa avec DU généré l''année dernière' = EXTERNALMEASURE("# adhérents abonnés noa avec DU généré l'année dernière", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Adhérents concernés
			lineageTag: 8454df5f-0996-42cb-b827-f16c9d1a349e
			sourceLineageTag: 666f2d2d-97cd-4c14-a540-e8b69c46ec89
			dataCategory: Uncategorized

		measure '# adhérents abonnés noa avec partage FE activé actuellement' = EXTERNALMEASURE("# adhérents abonnés noa avec partage FE activé actuellement", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1 - Adhérents concernés
			lineageTag: 7305044b-03f7-4534-81c1-eec95c37f65b
			sourceLineageTag: b0f937de-a008-45ba-84a0-8d7580910ac3
			dataCategory: Uncategorized

		measure '# adhérents avec alerte aucun risque identifié' = EXTERNALMEASURE("# adhérents avec alerte aucun risque identifié", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Alertes de remplissage
			lineageTag: f090e552-1e89-41af-9cec-c6102730f081
			sourceLineageTag: 7204513e-d1a1-4380-82cc-d3d5c918e557
			dataCategory: Uncategorized

		measure '# adhérents avec alerte principale' = EXTERNALMEASURE("# adhérents avec alerte principale", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Alertes de remplissage
			lineageTag: 91894baa-4b04-4c99-b072-1965c2448fdd
			sourceLineageTag: bb2f5431-ff84-4bf0-a7e1-57ec1ef69178
			dataCategory: Uncategorized

		measure '# adhérents avec alerte risque sans unité' = EXTERNALMEASURE("# adhérents avec alerte risque sans unité", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Alertes de remplissage
			lineageTag: 2f02395d-94ca-4806-be22-6cfffa55cb5f
			sourceLineageTag: 7352ee2a-f26f-47bf-9af9-468b3ecdc11d
			dataCategory: Uncategorized

		measure '# adhérents avec alerte unité sans risque' = EXTERNALMEASURE("# adhérents avec alerte unité sans risque", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3 - Alertes de remplissage
			lineageTag: fa6b33c8-0689-4d38-80eb-785fdad1189d
			sourceLineageTag: feab9ade-081b-4ea4-abd9-095ce80bd081
			dataCategory: Uncategorized

		measure '# risques' = EXTERNALMEASURE("# risques", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Remplissage actuel
			lineageTag: a602d005-0b4c-4638-99cf-18a85035c64c
			sourceLineageTag: 3a984762-a399-4e8c-94cb-63436eedad1d
			dataCategory: Uncategorized

		measure '# risques par adhérent' = EXTERNALMEASURE("# risques par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\2 - Remplissage actuel
			lineageTag: 3b5e46aa-fe4c-4ca0-afb4-428e8d105012
			sourceLineageTag: 67037b2b-34d1-42a3-bcb0-578ec757ca1b
			dataCategory: Uncategorized

		measure '# risques repris depuis la FE' = EXTERNALMEASURE("# risques repris depuis la FE", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Synergies FE/DU
			lineageTag: dc84392f-b6b7-4964-9045-8d1ba4f412b6
			sourceLineageTag: 60821bfc-1682-4aae-97cc-3066092deceb
			dataCategory: Uncategorized

		measure '# risques supplémentaires par adhérent' = EXTERNALMEASURE("# risques supplémentaires par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\5 - Evolution du remplissage
			lineageTag: 99743146-e0b9-4eb0-9ab6-0d215452ed40
			sourceLineageTag: 3fe0ad6d-f7b6-42ff-b5ef-9a933fef0338
			dataCategory: Uncategorized

		measure '# unités de travail' = EXTERNALMEASURE("# unités de travail", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2 - Remplissage actuel
			lineageTag: e9fb704e-f870-4f76-b398-47a2f8bfa6bf
			sourceLineageTag: d04df1c3-eed4-4a3e-a8e9-516647a6bc4e
			dataCategory: Uncategorized

		measure '# unités de travail par adhérent' = EXTERNALMEASURE("# unités de travail par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\2 - Remplissage actuel
			lineageTag: 8c4c623a-7a3c-4e0e-a1a8-a63cff4977fd
			sourceLineageTag: bfae4038-b2ca-4b2d-b3b3-0258d2137006
			dataCategory: Uncategorized

		measure '# unités de travail reprises depuis la FE' = EXTERNALMEASURE("# unités de travail reprises depuis la FE", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4 - Synergies FE/DU
			lineageTag: 023419fa-1d83-48b4-8a59-a7230f2cec56
			sourceLineageTag: 20b5baae-fc32-410c-8aed-05d34a450106
			dataCategory: Uncategorized

		measure '# unités de travail supplémentaires par adhérent' = EXTERNALMEASURE("# unités de travail supplémentaires par adhérent", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0
			displayFolder: Indicateurs\5 - Evolution du remplissage
			lineageTag: 11ba41f1-68a9-4910-a49c-6ebf14644efe
			sourceLineageTag: 5be92736-25f5-4736-94c7-a185c6fc5c72
			dataCategory: Uncategorized

		measure '% actions de prévention reprises depuis la FE' = EXTERNALMEASURE("% actions de prévention reprises depuis la FE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			lineageTag: efeb70a6-44e5-43de-a1e5-a054987189ba
			sourceLineageTag: b8807219-0b51-474a-b2b4-2ea8be34462b
			dataCategory: Uncategorized

		measure '% adhérents abonnés noa avec DU généré l''année dernière' = EXTERNALMEASURE("% adhérents abonnés noa avec DU généré l'année dernière", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			lineageTag: b1d1916c-d0a3-4600-9fd5-52dd8589bd2b
			sourceLineageTag: c13efeb3-e396-4eb7-94bf-d93ee65ebff1
			dataCategory: Uncategorized

		measure '% adhérents abonnés noa avec partage FE activé actuellement' = EXTERNALMEASURE("% adhérents abonnés noa avec partage FE activé actuellement", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			lineageTag: 3a827c46-e800-4937-b7a9-ff4ad128ecba
			sourceLineageTag: 5f0dffbd-f13d-43c8-a8f5-c654147f1318
			dataCategory: Uncategorized

		measure '% adhérents avec alerte principale' = EXTERNALMEASURE("% adhérents avec alerte principale", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			lineageTag: 2109ba45-3267-4b2d-80b3-e9e58a5a9bf3
			sourceLineageTag: 32f058b0-717c-464c-bd1d-e0e140965190
			dataCategory: Uncategorized

		measure '% risques repris depuis la FE' = EXTERNALMEASURE("% risques repris depuis la FE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			lineageTag: c8be5729-368a-4ce6-82fb-2671c0243d07
			sourceLineageTag: af65a23c-38c9-4fb3-a0c1-c12d40a09f69
			dataCategory: Uncategorized

		measure '% unités de travail reprises depuis la FE' = EXTERNALMEASURE("% unités de travail reprises depuis la FE", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			lineageTag: 42789ddc-45fd-4c96-9ef8-e646cd555482
			sourceLineageTag: 9bd2b546-3328-4940-b05e-ea65fb7a642c
			dataCategory: Uncategorized

	ref table 'Saisie - dossier salarié'

		measure '# Accidents de travail par dossier' = EXTERNALMEASURE("# Accidents de travail par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 0237ad0f-4679-4be6-ad72-aca4ecfba681
			sourceLineageTag: 295da0e3-a095-471e-9c51-c942ed869b5b
			dataCategory: Uncategorized

		measure '# Adaptations de poste par dossier' = EXTERNALMEASURE("# Adaptations de poste par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\4 - Informations concernant les propositions et l'avis du médecin du travail
			lineageTag: b74b4411-3932-4a8d-b0ee-94c2684aa7be
			sourceLineageTag: 2f3a3f75-b1b4-4d7e-8bd4-eb13df9dca3d
			dataCategory: Uncategorized

		measure '# Affections longue durée par dossier' = EXTERNALMEASURE("# Affections longue durée par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 5e2740a0-e419-409e-8bfe-3b737881c072
			sourceLineageTag: 5ca7606b-2428-493e-a409-47d6057c9927
			dataCategory: Uncategorized

		measure '# Allocations Adulte Handicapé par dossier' = EXTERNALMEASURE("# Allocations Adulte Handicapé par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: b03db320-0e21-4040-87c6-2b02f25d74e7
			sourceLineageTag: 3c487a9e-a81d-4ab5-b330-a51fcdac4ef4
			dataCategory: Uncategorized

		measure '# Antécédents avec thésaurus par dossier' = EXTERNALMEASURE("# Antécédents avec thésaurus par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 08902988-b558-4814-83a0-4478eab0489f
			sourceLineageTag: 4351d8fc-2393-4a53-b476-45b083924c09
			dataCategory: Uncategorized

		measure '# Antécédents familiaux avec RAS par dossier' = EXTERNALMEASURE("# Antécédents familiaux avec RAS par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: e2a85339-b740-480f-9307-7c0289884177
			sourceLineageTag: 6d735165-62f5-4feb-8731-16d9f5e8a97e
			dataCategory: Uncategorized

		measure '# Antécédents familiaux par dossier' = EXTERNALMEASURE("# Antécédents familiaux par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: c3a538c8-4150-4fe4-89b0-20350e147b4b
			sourceLineageTag: f443f843-540a-48be-8566-af06ebff53b7
			dataCategory: Uncategorized

		measure '# Antécédents personnels avec RAS par dossier' = EXTERNALMEASURE("# Antécédents personnels avec RAS par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: bc95cac9-fb4f-4858-a893-69ac4fc2c1e1
			sourceLineageTag: 615e6e35-a077-44f1-8e91-81a206ce921d
			dataCategory: Uncategorized

		measure '# Antécédents personnels par dossier' = EXTERNALMEASURE("# Antécédents personnels par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 9cb035d4-8e72-46be-84ba-60ba21dbe6f7
			sourceLineageTag: 5d8c7403-706f-458c-ab93-f20c925d86e4
			dataCategory: Uncategorized

		measure '# Arrêts de travail par dossier' = EXTERNALMEASURE("# Arrêts de travail par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 34a27171-7bcb-40aa-a55e-2e7205724d99
			sourceLineageTag: fac6ddfb-03f7-43af-a645-53b23011419e
			dataCategory: Uncategorized

		measure '# Arrêts/Accidents/Maladies pro avec RAS par dossier' = EXTERNALMEASURE("# Arrêts/Accidents/Maladies pro avec RAS par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: ff100a8e-1f63-4bee-a16d-10fbf9455d19
			sourceLineageTag: 4467ae2f-9918-4ad4-81bb-074ff5136422
			dataCategory: Uncategorized

		measure '# Causes d''inaptitude par visite d''inaptitude (dossier)' = EXTERNALMEASURE("# Causes d'inaptitude par visite d'inaptitude (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\4 - Informations concernant les propositions et l'avis du médecin du travail
			lineageTag: e2d47173-c1a5-4ef0-9321-ba77718dbf65
			sourceLineageTag: 528abf81-72a1-4fad-86b9-063cbfa52361
			dataCategory: Uncategorized

		measure '# Courriers autres par dossier' = EXTERNALMEASURE("# Courriers autres par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\4 - Informations concernant les propositions et l'avis du médecin du travail
			lineageTag: 2b0fa051-d7a0-4a12-8d25-ba29150de6c5
			sourceLineageTag: 29357cdb-e342-450d-9c1a-0004aa3d7954
			dataCategory: Uncategorized

		measure '# Courriers d''orientation par dossier' = EXTERNALMEASURE("# Courriers d'orientation par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\4 - Informations concernant les propositions et l'avis du médecin du travail
			lineageTag: bdd6a696-c263-4176-86a1-49e6f5b9dce9
			sourceLineageTag: 5101ae14-b99c-4987-90b7-74d40869be59
			dataCategory: Uncategorized

		measure '# Courriers de prescription par dossier' = EXTERNALMEASURE("# Courriers de prescription par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\4 - Informations concernant les propositions et l'avis du médecin du travail
			lineageTag: ac910a44-bda5-431e-aaa7-4c0476e42b3d
			sourceLineageTag: 3568ddcd-adbd-416d-b21b-5800e13471f8
			dataCategory: Uncategorized

		measure '# Diplômes et formations par dossier' = EXTERNALMEASURE("# Diplômes et formations par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.1 - Général
			lineageTag: fd03942e-cfd4-429d-a73a-77cbaab71229
			sourceLineageTag: 241976e0-7741-4429-8201-1ccf9200df49
			dataCategory: Uncategorized

		measure '# Diplômes par dossier' = EXTERNALMEASURE("# Diplômes par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 84887802-01f7-4737-ab2f-7934e88baf92
			sourceLineageTag: 3522eeaf-4dcb-4635-8d88-089e1b965f69
			dataCategory: Uncategorized

		measure '# Dossiers' = EXTERNALMEASURE("# Dossiers", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\5 - Synthèse
			lineageTag: 2e95d0dc-9101-4f89-bc9c-769dc769f31a
			sourceLineageTag: 934df8ee-3d5e-4b50-865c-2c7b52e15289
			dataCategory: Uncategorized

		measure '# Echelles anormales par dossier' = EXTERNALMEASURE("# Echelles anormales par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: b26e67df-967c-41cb-bf97-917b073c355d
			sourceLineageTag: afb5add3-67bf-4c2d-830e-8017230e1d10
			dataCategory: Uncategorized

		measure '# Echelles par dossier' = EXTERNALMEASURE("# Echelles par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: d026bdb8-9527-4fcf-bdcc-67154d516992
			sourceLineageTag: a072f9ef-6ff0-4251-b381-2dffb0ca1d04
			dataCategory: Uncategorized

		measure '# Emploi actuel par dossier' = EXTERNALMEASURE("# Emploi actuel par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.3 - Informations concernant l'emploi actuel
			lineageTag: 54243653-1b58-43a3-97d4-6c7564e39a21
			sourceLineageTag: ea1d6b9a-e412-4316-bc62-767fc79e2973
			dataCategory: Uncategorized

		measure '# Emplois antérieurs par dossier' = EXTERNALMEASURE("# Emplois antérieurs par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.2 - Informations concernant les emplois antérieurs
			lineageTag: c6fc5027-5c94-4e6f-9367-b810adb94223
			sourceLineageTag: f21db572-e844-429b-99d3-e0b3e1bff115
			dataCategory: Uncategorized

		measure '# Examens cliniques avec RAS par dossier' = EXTERNALMEASURE("# Examens cliniques avec RAS par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.4 - Données de l'examen clinique
			lineageTag: 7d080217-e64e-4345-a9a8-467828ec8622
			sourceLineageTag: 88042695-d20b-4adb-99da-83691cd654ef
			dataCategory: Uncategorized

		measure '# Examens cliniques avec thésaurus par dossier' = EXTERNALMEASURE("# Examens cliniques avec thésaurus par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.4 - Données de l'examen clinique
			lineageTag: 1976925c-cb09-4604-98bf-735e1e6810a7
			sourceLineageTag: 991696ff-4bdf-49ba-b422-f819dd24576d
			dataCategory: Uncategorized

		measure '# Examens cliniques par dossier' = EXTERNALMEASURE("# Examens cliniques par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.4 - Données de l'examen clinique
			lineageTag: 62f1d99f-87cc-4493-a68a-a93c5149651b
			sourceLineageTag: 04798c01-96aa-4b5a-a796-0814cacc999f
			dataCategory: Uncategorized

		measure '# Examens paracliniques en visite par dossier' = EXTERNALMEASURE("# Examens paracliniques en visite par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.5 - Données des examens paracliniques
			lineageTag: ed4de9dc-08ba-4659-8166-19e35854fa9c
			sourceLineageTag: 70b40431-2b1c-48e9-adda-29323d7d1191
			dataCategory: Uncategorized

		measure '# Examens paracliniques pré visite par dossier' = EXTERNALMEASURE("# Examens paracliniques pré visite par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.5 - Données des examens paracliniques
			lineageTag: 76a614ad-ac24-4951-802f-c4830a29fb89
			sourceLineageTag: 9e738b55-20f9-4b09-9ece-10f004f8a8dd
			dataCategory: Uncategorized

		measure '# Examens paracliniques prescrits par dossier' = EXTERNALMEASURE("# Examens paracliniques prescrits par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.5 - Données des examens paracliniques
			lineageTag: c779a67d-59e1-4d08-8ff6-ec6e6c747b6e
			sourceLineageTag: 6d7b27d5-1aa9-47d1-be70-e1a81884f075
			dataCategory: Uncategorized

		measure '# Expositions emploi actuel déclarées par l''employeur par dossier' = EXTERNALMEASURE("# Expositions emploi actuel déclarées par l'employeur par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.3 - Informations concernant l'emploi actuel
			lineageTag: cfc4a787-e756-4002-90f3-c71d71f175b1
			sourceLineageTag: a6bf8e09-a2f4-4040-80aa-1fabc21f1e64
			dataCategory: Uncategorized

		measure '# Expositions emploi actuel déclarées par le salarié par dossier' = EXTERNALMEASURE("# Expositions emploi actuel déclarées par le salarié par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.3 - Informations concernant l'emploi actuel
			lineageTag: cfcd2733-b26f-43fe-bae0-594c2dd034fe
			sourceLineageTag: 0c6132d3-6fb4-4cbd-9955-5a7a62ee8ae6
			dataCategory: Uncategorized

		measure '# Expositions emploi actuel provenant de l''ancien logiciel par dossier' = EXTERNALMEASURE("# Expositions emploi actuel provenant de l'ancien logiciel par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.3 - Informations concernant l'emploi actuel
			lineageTag: 38c294cf-fa7d-448b-b920-ab46bf43bff9
			sourceLineageTag: b9b4162c-2b22-4649-859e-60d81fee8981
			dataCategory: Uncategorized

		measure '# Expositions emploi actuel saisies par le professionnel de santé par dossier' = EXTERNALMEASURE("# Expositions emploi actuel saisies par le professionnel de santé par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.3 - Informations concernant l'emploi actuel
			lineageTag: cec47adc-1d10-4e4a-b2f8-c3dc176e0833
			sourceLineageTag: fa68412a-b3cb-499c-b5a5-c4e30b09b00f
			dataCategory: Uncategorized

		measure '# Expositions emplois antérieurs déclarées par l''employeur par dossier' = EXTERNALMEASURE("# Expositions emplois antérieurs déclarées par l'employeur par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.2 - Informations concernant les emplois antérieurs
			lineageTag: 5060e37c-222f-43fe-8a0a-f87a165373db
			sourceLineageTag: a47bf3b1-7266-45e6-ae65-b1be50fc3299
			dataCategory: Uncategorized

		measure '# Expositions emplois antérieurs déclarées par le salarié par dossier' = EXTERNALMEASURE("# Expositions emplois antérieurs déclarées par le salarié par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.2 - Informations concernant les emplois antérieurs
			lineageTag: c62a8cd3-7801-4a57-ad25-237aa818a3bb
			sourceLineageTag: 6361d624-f226-4fff-a8ca-29346312372d
			dataCategory: Uncategorized

		measure '# Expositions emplois antérieurs provenant de l''ancien logiciel par dossier' = EXTERNALMEASURE("# Expositions emplois antérieurs provenant de l'ancien logiciel par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.2 - Informations concernant les emplois antérieurs
			lineageTag: d12b8453-a53d-496c-8586-bc12fb94fb7b
			sourceLineageTag: c851f560-ef4f-4f64-95fa-08290635d7d2
			dataCategory: Uncategorized

		measure '# Expositions emplois antérieurs saisies par le professionnel de santé par dossier' = EXTERNALMEASURE("# Expositions emplois antérieurs saisies par le professionnel de santé par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.2 - Informations concernant les emplois antérieurs
			lineageTag: b40e433d-9221-45ab-9cf0-f62f0a601159
			sourceLineageTag: 646a4bf6-b51f-41ec-abb9-9fe48039cb42
			dataCategory: Uncategorized

		measure '# Gollac complété par dossier' = EXTERNALMEASURE("# Gollac complété par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: c5bbef1c-25fb-4f55-aea4-f0c3f318192f
			sourceLineageTag: 2bc38729-139d-4dde-8b7a-82d51f9f14a1
			dataCategory: Uncategorized

		measure '# Habitus par dossier' = EXTERNALMEASURE("# Habitus par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: a8a727d6-2f2e-4f02-9f78-d00547b24ea1
			sourceLineageTag: ea4c1ca7-97a4-4970-9a7c-fc798cc93e07
			dataCategory: Uncategorized

		measure '# Incapacités permanentes par dossier' = EXTERNALMEASURE("# Incapacités permanentes par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 4c9ff5d0-25da-411e-ac03-eb1dcdb06281
			sourceLineageTag: f57c4490-fa3a-4247-a88e-3be6cd90ade0
			dataCategory: Uncategorized

		measure '# Injections vaccinales par dossier' = EXTERNALMEASURE("# Injections vaccinales par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 553b2fa8-f36d-4481-bb76-f2505d58e046
			sourceLineageTag: 9234e47a-71d6-40f8-8b76-1b8648531546
			dataCategory: Uncategorized

		measure '# Invalidités de guerre par dossier' = EXTERNALMEASURE("# Invalidités de guerre par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: fa1bb1b3-6917-4933-bef0-62dcea8cf861
			sourceLineageTag: be297f9d-4b03-4dd7-a1c4-fff84d8007ea
			dataCategory: Uncategorized

		measure '# Invalidités par dossier' = EXTERNALMEASURE("# Invalidités par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: b9f7e9c9-5c50-42b4-8b27-1ea7cbc022cc
			sourceLineageTag: 92dd830a-3ff0-405f-9aa5-71e57cc98051
			dataCategory: Uncategorized

		measure '# Logements par dossier' = EXTERNALMEASURE("# Logements par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 57de3e44-fe3e-42a2-adf9-b4b8c4c52405
			sourceLineageTag: bc64a273-9f6a-4ac7-bcef-eea471e2e760
			dataCategory: Uncategorized

		measure '# Maladies professionnelles par dossier' = EXTERNALMEASURE("# Maladies professionnelles par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 94b0f1c2-5046-4f95-b05f-d4417755d520
			sourceLineageTag: 858fff3f-f11d-482c-945f-fa6398619470
			dataCategory: Uncategorized

		measure '# Memos par dossier' = EXTERNALMEASURE("# Memos par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\5 - Synthèse
			lineageTag: df8ee09e-737e-4ea4-b647-08c1a2ff72c0
			sourceLineageTag: 56213587-4d8c-4b3a-98f0-21364613a50b
			dataCategory: Uncategorized

		measure '# Mesures par dossier' = EXTERNALMEASURE("# Mesures par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.5 - Données des examens paracliniques
			lineageTag: ce5390d8-5f92-4424-9e44-efd5cba72e5a
			sourceLineageTag: 09cc258d-082e-4f3a-a81c-383a80fffb70
			dataCategory: Uncategorized

		measure '# Notes d''ancien emploi par dossier' = EXTERNALMEASURE("# Notes d'ancien emploi par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.2 - Informations concernant les emplois antérieurs
			lineageTag: 36683a89-fb18-4d79-9386-fd704b4d78d4
			sourceLineageTag: fbe1d1ac-2c07-4f4e-ab2d-800ceced77ff
			dataCategory: Uncategorized

		measure '# Notes expositions anciens emplois par dossier' = EXTERNALMEASURE("# Notes expositions anciens emplois par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.2 - Informations concernant les emplois antérieurs
			lineageTag: 1e845ce6-610a-400c-ace0-04eea16bdbaa
			sourceLineageTag: b4d8ab6d-77cd-47b8-9851-d57669a9248a
			dataCategory: Uncategorized

		measure '# Notes liées aux expositions par dossier' = EXTERNALMEASURE("# Notes liées aux expositions par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.3 - Informations concernant l'emploi actuel
			lineageTag: 2ba61db9-482b-4eb4-95c3-f71d995566bc
			sourceLineageTag: 3b1833ab-e856-4981-91b9-eaffd8e92346
			dataCategory: Uncategorized

		measure '# Notes par dossier' = EXTERNALMEASURE("# Notes par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\5 - Synthèse
			lineageTag: b5381fba-2dc6-4535-9661-a9e79aeace38
			sourceLineageTag: 574f8fa8-5008-4ec3-a8f7-95c87de68ec1
			dataCategory: Uncategorized

		measure '# Notes socio-professionnelles par dossier' = EXTERNALMEASURE("# Notes socio-professionnelles par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 81916094-484d-4858-aa8c-a9238d5d5279
			sourceLineageTag: d7a9043c-ab85-42d1-befc-a634607990e3
			dataCategory: Uncategorized

		measure '# Pathologies avec RAS par dossier' = EXTERNALMEASURE("# Pathologies avec RAS par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: e3608ecc-ad09-4141-a938-ef823fbd0f6e
			sourceLineageTag: 817684f6-15cc-46af-971a-6c6bf88b327a
			dataCategory: Uncategorized

		measure '# Pathologies avec thésaurus par dossier' = EXTERNALMEASURE("# Pathologies avec thésaurus par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 82f55c1d-17c5-44cf-bcbf-c2da39ed441a
			sourceLineageTag: 7ef361a7-f14b-4837-a29f-975992d647ee
			dataCategory: Uncategorized

		measure '# Pathologies par dossier' = EXTERNALMEASURE("# Pathologies par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 198e2662-d210-494f-a334-56017d243809
			sourceLineageTag: a0e06306-a56f-47ca-94db-12ad03619386
			dataCategory: Uncategorized

		measure '# Plaquettes de prévention par dossier' = EXTERNALMEASURE("# Plaquettes de prévention par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\4 - Informations concernant les propositions et l'avis du médecin du travail
			lineageTag: d2e5373e-a758-4196-8423-b1608840385c
			sourceLineageTag: e22c5ce7-dfaf-4811-9b87-e04ddee9e5e9
			dataCategory: Uncategorized

		measure '# Recommandations orales par dossier' = EXTERNALMEASURE("# Recommandations orales par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\4 - Informations concernant les propositions et l'avis du médecin du travail
			lineageTag: 252ca46d-f465-41ee-b822-59bb4b408fd9
			sourceLineageTag: ae2fe68f-f951-4ecb-9ece-a95f198f3774
			dataCategory: Uncategorized

		measure '# RQTH par dossier' = EXTERNALMEASURE("# RQTH par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: f248eec0-b628-49cb-9a73-cc2a655568b6
			sourceLineageTag: d980cf3d-19f8-4921-aad9-fbf1c74bb721
			dataCategory: Uncategorized

		measure '# Situations administratives par dossier' = EXTERNALMEASURE("# Situations administratives par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: e20ade06-38d1-41f8-9b70-65889e22405f
			sourceLineageTag: b2f50d54-8af2-4b24-ac00-465fd7599808
			dataCategory: Uncategorized

		measure '# Situations financières avec RAS par dossier' = EXTERNALMEASURE("# Situations financières avec RAS par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 63b23b47-b585-4b33-bb3c-608337bec289
			sourceLineageTag: 918d70d0-9039-43ce-a45f-5b2248002742
			dataCategory: Uncategorized

		measure '# Situations financières par dossier' = EXTERNALMEASURE("# Situations financières par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 0739f1f6-f406-463a-b3ae-a077cf449518
			sourceLineageTag: 033cd213-3812-48f7-abf1-d4685276b661
			dataCategory: Uncategorized

		measure '# Situations personnelles et familiales par dossier' = EXTERNALMEASURE("# Situations personnelles et familiales par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 992c418e-6118-4348-91d7-c22ff2e7405d
			sourceLineageTag: f9d08158-aa47-4831-b3f1-977fad4178f6
			dataCategory: Uncategorized

		measure '# Statuts vaccinaux par dossier' = EXTERNALMEASURE("# Statuts vaccinaux par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 66d1a3df-1f38-4cc7-b3e0-cf3db95efa55
			sourceLineageTag: 7ff518b0-a67d-45e7-9972-e4a1649a0666
			dataCategory: Uncategorized

		measure '# Thésaurus accidents de travail par dossier' = EXTERNALMEASURE("# Thésaurus accidents de travail par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: b3f53577-3fa3-46d2-a6dc-f18924d3619c
			sourceLineageTag: 1b964876-4d57-434c-a2a9-a595e48619f3
			dataCategory: Uncategorized

		measure '# Thésaurus antécédents familiaux par dossier' = EXTERNALMEASURE("# Thésaurus antécédents familiaux par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 0090a6e2-f971-4613-8c02-43c1058c4d63
			sourceLineageTag: d7a641cb-6158-4ef3-a5b0-2016bbce93bd
			dataCategory: Uncategorized

		measure '# Thésaurus antécédents personnels par dossier' = EXTERNALMEASURE("# Thésaurus antécédents personnels par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: e083f9d7-01d3-47d2-97e0-4e53b530b4d7
			sourceLineageTag: e75227dc-fa2d-4b0a-9405-13521e846b3d
			dataCategory: Uncategorized

		measure '# Thésaurus arrêts de travail par dossier' = EXTERNALMEASURE("# Thésaurus arrêts de travail par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 43cb410e-39ce-4238-917a-c6741f6205ac
			sourceLineageTag: 63ccb3ab-e6fc-44f6-8c7e-71d2bef93a51
			dataCategory: Uncategorized

		measure '# Thésaurus cim10 par dossier' = EXTERNALMEASURE("# Thésaurus cim10 par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 58ffad90-5271-417d-9626-95e4deccc751
			sourceLineageTag: 9d672d38-9eb3-4b04-9cfd-e344df8e0a2d
			dataCategory: Uncategorized

		measure '# Thésaurus diplômes par dossier' = EXTERNALMEASURE("# Thésaurus diplômes par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 10737abc-3c3d-435a-8d8d-f04ef874f7d7
			sourceLineageTag: d2736e69-e87e-4d6d-9792-23f59f588db8
			dataCategory: Uncategorized

		measure '# Thésaurus examens cliniques par dossier' = EXTERNALMEASURE("# Thésaurus examens cliniques par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.4 - Données de l'examen clinique
			lineageTag: f17a3d10-81a0-47a0-9d6a-3b79a435756f
			sourceLineageTag: 23d35e38-f820-4366-b7e7-cc18e5cdcc47
			dataCategory: Uncategorized

		measure '# Thésaurus hors examens cliniques par dossier' = EXTERNALMEASURE("# Thésaurus hors examens cliniques par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 07e7197d-0819-4773-a69b-6c1d7c023dd2
			sourceLineageTag: 3e978152-1f48-4873-b5ef-143db4170df3
			dataCategory: Uncategorized

		measure '# Thésaurus maladies professionnelles par dossier' = EXTERNALMEASURE("# Thésaurus maladies professionnelles par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 4fc9b03a-61f4-466b-a850-950a7ceac4b8
			sourceLineageTag: 69df5e7b-572b-463e-b099-66c1ea6bf5da
			dataCategory: Uncategorized

		measure '# Thésaurus par dossier' = EXTERNALMEASURE("# Thésaurus par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\5 - Synthèse
			lineageTag: 1983d504-50f5-4610-96e5-b06e30ca0ffd
			sourceLineageTag: 8d3c5ce1-6382-4345-a67a-65c1b4cea5bb
			dataCategory: Uncategorized

		measure '# Thésaurus pathologies par dossier' = EXTERNALMEASURE("# Thésaurus pathologies par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 91a0421a-f4d8-4697-9924-0cf7a6c8f44c
			sourceLineageTag: ea9193a6-a9cd-4ce7-bcef-e8aba7f39de9
			dataCategory: Uncategorized

		measure '# Thésaurus situations personnelles et familiales par dossier' = EXTERNALMEASURE("# Thésaurus situations personnelles et familiales par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 466aac97-67b4-43c6-a2ba-046f6b4d8fb5
			sourceLineageTag: 814a9f36-402f-4159-b30d-ae5c97816206
			dataCategory: Uncategorized

		measure '# Thésaurus traitements par dossier' = EXTERNALMEASURE("# Thésaurus traitements par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: b77d0790-2273-417c-89a7-e1983e6633db
			sourceLineageTag: 78aa2626-cb60-498f-821b-a31ec88f069e
			dataCategory: Uncategorized

		measure '# Traitements avec RAS par dossier' = EXTERNALMEASURE("# Traitements avec RAS par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 0b7a9a4e-5d62-4f37-b069-d8013b7577c6
			sourceLineageTag: 7a84b8fc-26a6-407e-ae0f-794e80b9de35
			dataCategory: Uncategorized

		measure '# Traitements par dossier' = EXTERNALMEASURE("# Traitements par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 6d02593e-39d8-4eec-8eed-3adce6b20fb5
			sourceLineageTag: 364b32c5-9ff5-429c-85fb-58ed5001bf79
			dataCategory: Uncategorized

		measure '# Vécus au travail par dossier' = EXTERNALMEASURE("# Vécus au travail par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 16a2cb1e-13b5-41b7-ab14-15c50432aa9e
			sourceLineageTag: 9c03e968-0944-4782-bfd7-32aaa386a039
			dataCategory: Uncategorized

		measure '# Victimes civiles de guerre par dossier' = EXTERNALMEASURE("# Victimes civiles de guerre par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 35546557-67d5-4b7e-83ba-3bded02188d5
			sourceLineageTag: 230ff426-18ee-4f11-90bb-5e56c74f8dcf
			dataCategory: Uncategorized

		measure '# Victimes de terrorisme par dossier' = EXTERNALMEASURE("# Victimes de terrorisme par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 744c6b93-1d3f-4900-a4d8-a0b0a2c72a1b
			sourceLineageTag: 8804fb94-75c4-49a4-90f1-85b0cad2ebcd
			dataCategory: Uncategorized

		measure '# Visites par dossier' = EXTERNALMEASURE("# Visites par dossier", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\5 - Synthèse
			lineageTag: bd4de73e-e28f-4ef7-994e-bf685c6c3815
			sourceLineageTag: 447b1c96-7be8-4959-b086-f308041fe2e6
			dataCategory: Uncategorized

		measure '% Adaptations de poste avec type renseigné (dossier)' = EXTERNALMEASURE("% Adaptations de poste avec type renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 17379892-9935-403e-9a67-2042a29cff88
			sourceLineageTag: cb640893-77ed-4b18-a865-962f3280ebcc
			dataCategory: Uncategorized

		measure '% Arrêts de travail avec date de début renseignée (dossier)' = EXTERNALMEASURE("% Arrêts de travail avec date de début renseignée (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 10019dec-50e1-479b-94ee-34c99d5750d3
			sourceLineageTag: 23c4e644-297b-4ec8-aff9-6427bb152dde
			dataCategory: Uncategorized

		measure '% Arrêts de travail avec date de fin renseignée (dossier)' = EXTERNALMEASURE("% Arrêts de travail avec date de fin renseignée (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: d8870681-b3ec-45e7-b243-643b33b932b0
			sourceLineageTag: f254932e-27c7-4d4f-9f4c-7e46f3e97f56
			dataCategory: Uncategorized

		measure '% Emploi actuel avec description renseignée (dossier)' = EXTERNALMEASURE("% Emploi actuel avec description renseignée (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 33e3877f-e000-4203-8948-9fb0363c4b60
			sourceLineageTag: ad2739c0-9a13-432c-9059-cddea8aad09a
			dataCategory: Uncategorized

		measure '% Emploi actuel avec équipement renseigné (dossier)' = EXTERNALMEASURE("% Emploi actuel avec équipement renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 814895ca-73b6-471a-8a47-092eb8831def
			sourceLineageTag: 7975483c-4fea-4225-9fa3-cccdb249ef86
			dataCategory: Uncategorized

		measure '% Emploi actuel avec horaires renseignés (dossier)' = EXTERNALMEASURE("% Emploi actuel avec horaires renseignés (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 8dcbd533-ec57-4885-a411-1d465794aae2
			sourceLineageTag: e323b2d8-d699-48e4-beea-bbd2a8e99958
			dataCategory: Uncategorized

		measure '% Emploi actuel avec lieu renseigné (dossier)' = EXTERNALMEASURE("% Emploi actuel avec lieu renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 885401fb-af6f-4846-8f9a-7fc05611fdb9
			sourceLineageTag: cf9b84df-9206-4485-8358-d0224b1b8e32
			dataCategory: Uncategorized

		measure '% Emploi actuel avec PCS renseigné (dossier)' = EXTERNALMEASURE("% Emploi actuel avec PCS renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: b896ea54-577d-401f-b6c6-0fc4ce03594e
			sourceLineageTag: 1f0f04fb-8a63-483f-b5f4-c34c2d60ef9b
			dataCategory: Uncategorized

		measure '% Emploi actuel avec poste renseigné (dossier)' = EXTERNALMEASURE("% Emploi actuel avec poste renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 6d123d2b-f33a-4600-b0f9-5af43dcb075d
			sourceLineageTag: b9836bab-7567-4662-b372-9a916b95f428
			dataCategory: Uncategorized

		measure '% Emploi actuel avec tâches renseignées (dossier)' = EXTERNALMEASURE("% Emploi actuel avec tâches renseignées (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 03b49213-5586-4760-bf73-dc042d3193e4
			sourceLineageTag: 03f54e55-27e7-43b9-9e6e-1b46ddb1ef20
			dataCategory: Uncategorized

		measure '% Emploi actuel avec trajet renseigné (dossier)' = EXTERNALMEASURE("% Emploi actuel avec trajet renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: e8da6d84-7dfc-4b47-8f43-5012c82bee15
			sourceLineageTag: be3e0047-5c6e-4415-a082-38479cf4e538
			dataCategory: Uncategorized

		measure '% Emploi actuel avec type de contrat renseigné (dossier)' = EXTERNALMEASURE("% Emploi actuel avec type de contrat renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 76b5bdea-6f61-4685-a4a8-55a47da1321f
			sourceLineageTag: 2b897b98-f55b-46c7-98de-f9378869d71b
			dataCategory: Uncategorized

		measure '% Emplois antérieurs avec description renseignée (dossier)' = EXTERNALMEASURE("% Emplois antérieurs avec description renseignée (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: a67587dd-503f-48de-b6d3-cccadb73f279
			sourceLineageTag: 797273b2-a363-4bed-ba69-6127deb8ea42
			dataCategory: Uncategorized

		measure '% Emplois antérieurs avec équipement renseigné (dossier)' = EXTERNALMEASURE("% Emplois antérieurs avec équipement renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 5fcd0ad0-1a2a-440a-b6c6-abda326a621c
			sourceLineageTag: 08105c8f-afd8-4df5-a8b5-2c87332047b8
			dataCategory: Uncategorized

		measure '% Emplois antérieurs avec horaires renseignés (dossier)' = EXTERNALMEASURE("% Emplois antérieurs avec horaires renseignés (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: eff49ff0-9c99-4a01-b634-15ebf1fcb4a0
			sourceLineageTag: c9b42376-58d9-4459-82ae-f1319ecc2146
			dataCategory: Uncategorized

		measure '% Emplois antérieurs avec lieu renseigné (dossier)' = EXTERNALMEASURE("% Emplois antérieurs avec lieu renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 4e58b899-b051-4f0f-88d5-0b4a2c708eae
			sourceLineageTag: 55e52fd1-1a39-4e04-9010-d9a2b08057fa
			dataCategory: Uncategorized

		measure '% Emplois antérieurs avec PCS renseigné (dossier)' = EXTERNALMEASURE("% Emplois antérieurs avec PCS renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: eb229413-5596-4fe5-8c94-9cd79dcbf5c1
			sourceLineageTag: 87ad70b1-8e44-4b1f-bdd9-ab598c8cf244
			dataCategory: Uncategorized

		measure '% Emplois antérieurs avec poste renseigné (dossier)' = EXTERNALMEASURE("% Emplois antérieurs avec poste renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: b81813cd-52f3-4b18-9d2e-68c9d9643bbc
			sourceLineageTag: b54c70a1-770f-4f29-bcb7-048523c343a6
			dataCategory: Uncategorized

		measure '% Emplois antérieurs avec tâches renseignées (dossier)' = EXTERNALMEASURE("% Emplois antérieurs avec tâches renseignées (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 64956f85-47b6-412a-a988-0826bd52beca
			sourceLineageTag: ea938b14-d032-408c-9530-b5ba6d6b607b
			dataCategory: Uncategorized

		measure '% Emplois antérieurs avec trajet renseigné (dossier)' = EXTERNALMEASURE("% Emplois antérieurs avec trajet renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 057d4c3d-ace7-4aee-a071-416e39270f76
			sourceLineageTag: edfdf92d-0274-4066-8567-448da7443cde
			dataCategory: Uncategorized

		measure '% Emplois antérieurs avec type de contrat renseigné (dossier)' = EXTERNALMEASURE("% Emplois antérieurs avec type de contrat renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: d0318e5e-bfbb-4eeb-b24a-49f7335c6c89
			sourceLineageTag: 521e7e35-5bde-4d4c-a11c-048ed8bce66e
			dataCategory: Uncategorized

		measure '% Etat global de vaccination renseigné (dossier)' = EXTERNALMEASURE("% Etat global de vaccination renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 3495302e-2116-4630-bc66-43711b36f97b
			sourceLineageTag: 2b332a5c-6a37-411c-a798-88f8014c0f13
			dataCategory: Uncategorized

		measure '% Examens cliniques avec RAS (dossier)' = EXTERNALMEASURE("% Examens cliniques avec RAS (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: f77f330a-3745-4b97-83d1-8d1cf68ababd
			sourceLineageTag: fecb92f3-085e-489f-b37f-c86df2cfb4b6
			dataCategory: Uncategorized

		measure '% Examens cliniques avec thésaurus (dossier)' = EXTERNALMEASURE("% Examens cliniques avec thésaurus (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 2f3e9fa1-3438-4069-a3a0-cf1e227265ee
			sourceLineageTag: 478a63b2-ffa8-4971-a6e3-27bff0bca930
			dataCategory: Uncategorized

		measure '% Injections vaccinales avec numéro de lot renseigné (dossier)' = EXTERNALMEASURE("% Injections vaccinales avec numéro de lot renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: b367e966-acc3-418a-a98c-10a194d24e24
			sourceLineageTag: cde36c0d-dc6e-4f87-91bb-8aad978be59e
			dataCategory: Uncategorized

		measure '% Nom et prénom renseigné (dossier)' = EXTERNALMEASURE("% Nom et prénom renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 2ce3c565-e454-428d-98d5-40815d00ea0c
			sourceLineageTag: ad963982-92ac-4f23-8daf-9acbbe6a0ad6
			dataCategory: Uncategorized

		measure '% Notes avec thésaurus (dossier)' = EXTERNALMEASURE("% Notes avec thésaurus (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 320a5cdb-2a53-434b-a306-2985b5fb70fc
			sourceLineageTag: f15b1331-ef55-4dbd-b2d5-61b1fedb9eec
			dataCategory: Uncategorized

		measure '% Notes avec thésaurus ou RAS (dossier)' = EXTERNALMEASURE("% Notes avec thésaurus ou RAS (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 40a2165c-ea56-4948-bc0a-4c964cf41f3a
			sourceLineageTag: 4e0fad8a-f374-4632-a37f-d8c2fbd02836
			dataCategory: Uncategorized

		measure '% Notes hors examen clinique avec thésaurus ou RAS (dossier)' = EXTERNALMEASURE("% Notes hors examen clinique avec thésaurus ou RAS (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 2e368369-cbba-489b-b2a6-e9218ec537b1
			sourceLineageTag: 8c9b8669-f3e8-4495-a018-7eb83cfd796d
			dataCategory: Uncategorized

		measure '% Notes sociales avec thésaurus ou RAS (dossier)' = EXTERNALMEASURE("% Notes sociales avec thésaurus ou RAS (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 3422d666-1176-4267-bb0e-afa6a24b772b
			sourceLineageTag: a45c8015-51b8-4304-8073-a5b769963c7b
			dataCategory: Uncategorized

		measure '% Numéro de téléphone renseigné (dossier)' = EXTERNALMEASURE("% Numéro de téléphone renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 5f8cc1fc-39f6-4c99-ae60-6df453bc970b
			sourceLineageTag: a0bdf65b-dff3-4bc0-ab7d-83727880a193
			dataCategory: Uncategorized

		measure '% Pathologies avec date de début renseignée (dossier)' = EXTERNALMEASURE("% Pathologies avec date de début renseignée (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: aca375fd-12ee-48f5-ba7f-a35502184bef
			sourceLineageTag: a48569cf-f960-4edb-83f9-ce8a2dbe5db0
			dataCategory: Uncategorized

		measure '% Pathologies avec date de fin renseignée (dossier)' = EXTERNALMEASURE("% Pathologies avec date de fin renseignée (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: c7bea887-557e-4808-8899-ded511d95586
			sourceLineageTag: 31d03831-80d5-48e6-9ac8-d728fbfc53d8
			dataCategory: Uncategorized

		measure '% Refus au consentement partage des données (dossier)' = EXTERNALMEASURE("% Refus au consentement partage des données (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 6ac3a470-e41c-4650-bb35-aa8ffb44f892
			sourceLineageTag: dd1d7c87-cfa7-4b7e-820a-0409f4b228ec
			dataCategory: Uncategorized

		measure '% Réponse au consentement partage des données (dossier)' = EXTERNALMEASURE("% Réponse au consentement partage des données (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 49bf5f9d-b9da-4ba2-aabd-ab6153cb2513
			sourceLineageTag: 96b6632b-ca46-4eab-9853-fcb2cc66139c
			dataCategory: Uncategorized

		measure '% Réponse suivi médecin traitant (dossier)' = EXTERNALMEASURE("% Réponse suivi médecin traitant (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: ffd0d63e-63b1-4a31-b2e4-ce9181a69c4b
			sourceLineageTag: 3c73480a-f245-495e-aff4-b4eed5b27bf4
			dataCategory: Uncategorized

		measure '% Statuts vaccinaux avec état renseigné (dossier)' = EXTERNALMEASURE("% Statuts vaccinaux avec état renseigné (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: e051d328-233d-473a-bd2b-c1de962d9421
			sourceLineageTag: f2c6b726-027e-4b19-9101-1615aadf1912
			dataCategory: Uncategorized

		measure '% Visites avec adaptation de poste (dossier)' = EXTERNALMEASURE("% Visites avec adaptation de poste (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: db65e8ec-a17f-46b1-891d-19ec4a474767
			sourceLineageTag: 8ee09081-b09d-49a8-967a-ab0ee1055c4d
			dataCategory: Uncategorized

		measure '% Visites avec conclusion (dossier)' = EXTERNALMEASURE("% Visites avec conclusion (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 39ba5d24-53d7-4c44-90ee-05c67dd07bd2
			sourceLineageTag: f2ab3e29-f225-4c00-9558-7f15793af61a
			dataCategory: Uncategorized

		measure '% Visites avec échelle remplie (dossier)' = EXTERNALMEASURE("% Visites avec échelle remplie (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: e7426188-3b73-4f95-b91b-7516eb33f408
			sourceLineageTag: dd43e756-f518-4a88-afa9-631020c02ad8
			dataCategory: Uncategorized

		measure '% Visites avec examen clinique (dossier)' = EXTERNALMEASURE("% Visites avec examen clinique (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: d4c659da-d919-48ca-9321-4b7d789e7d0a
			sourceLineageTag: de50a2b5-07d2-4c6d-87fc-b3e43c7dfd42
			dataCategory: Uncategorized

		measure '% Visites avec IRDP rempli (dossier)' = EXTERNALMEASURE("% Visites avec IRDP rempli (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: a16a8198-16db-413a-b6d5-cbe5baaa730e
			sourceLineageTag: 00972072-98ea-4ff9-abe8-687ef9301057
			dataCategory: Uncategorized

		measure '% Visites avec IRI rempli (dossier)' = EXTERNALMEASURE("% Visites avec IRI rempli (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 5285af14-4f86-49c7-b430-fbf4aeaa6aba
			sourceLineageTag: 68637f04-cc6a-4395-96fa-f7c9d77a3008
			dataCategory: Uncategorized

		measure '% Visites avec situation administrative (dossier)' = EXTERNALMEASURE("% Visites avec situation administrative (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 7222041b-5b7d-4075-8068-68b8c49b364c
			sourceLineageTag: aec440b1-1b86-4c1f-bf45-68522b5559e5
			dataCategory: Uncategorized

		measure '% Visites d''inaptitude avec cause (dossier)' = EXTERNALMEASURE("% Visites d'inaptitude avec cause (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: ca63c349-112d-47a7-bb9c-4ac8138e99d8
			sourceLineageTag: ce28c504-6200-4cd0-a6b6-95ed189f721b
			dataCategory: Uncategorized

		measure '% Visites de suivi individuel (dossier)' = EXTERNALMEASURE("% Visites de suivi individuel (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 2a29330d-c91f-4743-b3b1-9d21dbe67953
			sourceLineageTag: b2b471c3-f013-4596-99cb-e87bfe489c3a
			dataCategory: Uncategorized

		measure '% Visites IRDP à risque avec facteurs renseignés (dossier)' = EXTERNALMEASURE("% Visites IRDP à risque avec facteurs renseignés (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 5ec76caf-040c-4c00-a342-f02e7ac6df88
			sourceLineageTag: f839e608-7284-47e7-b2f2-21cb4eacfde4
			dataCategory: Uncategorized

		measure '% Visites IRI à risque avec facteurs renseignés (dossier)' = EXTERNALMEASURE("% Visites IRI à risque avec facteurs renseignés (dossier)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: ed10babf-23b5-4dfc-b959-6c1e2d119486
			sourceLineageTag: 0d231390-2bc8-4ab8-993a-a6b20c6480a9
			dataCategory: Uncategorized

	ref table 'Saisie - visite'

		measure '# Accidents de travail par visite' = EXTERNALMEASURE("# Accidents de travail par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 222bce36-f95b-43b1-953a-ad732d1f7bb7
			sourceLineageTag: c200915d-9f9a-473e-bdc5-21a2ed536641
			dataCategory: Uncategorized

		measure '# Affections longue durée par visite' = EXTERNALMEASURE("# Affections longue durée par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 95216e24-4984-4f0f-bb54-6ff80e7c28f8
			sourceLineageTag: d31f2015-5f27-4285-805d-a65df0ec5907
			dataCategory: Uncategorized

		measure '# Allocations Adulte Handicapé par visite' = EXTERNALMEASURE("# Allocations Adulte Handicapé par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 95d48e6c-ab02-4d2b-b781-47556258de6b
			sourceLineageTag: d1f0389e-d3b5-4deb-9cfa-f7dba34f9334
			dataCategory: Uncategorized

		measure '# Antécédents familiaux avec RAS par visite' = EXTERNALMEASURE("# Antécédents familiaux avec RAS par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 765f3d06-d2e1-4115-ba23-1d3f66288a80
			sourceLineageTag: 930929aa-40ba-4b2e-84fa-9ac7c2df0916
			dataCategory: Uncategorized

		measure '# Antécédents familiaux par visite' = EXTERNALMEASURE("# Antécédents familiaux par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: a2e4d832-d887-450d-ae72-f208af53c3c2
			sourceLineageTag: 23b5954a-5c23-461b-9742-0641f77ef541
			dataCategory: Uncategorized

		measure '# Antécédents personnels avec RAS par visite' = EXTERNALMEASURE("# Antécédents personnels avec RAS par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 0c8f451f-e30a-42b8-84ce-154e0f667712
			sourceLineageTag: 9c4440af-6a20-4878-9bbb-90da2bb986bb
			dataCategory: Uncategorized

		measure '# Antécédents personnels par visite' = EXTERNALMEASURE("# Antécédents personnels par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 5d15c952-2816-49c9-a06d-865da2679202
			sourceLineageTag: 84d5e982-f928-456a-ac3c-810adbea60bd
			dataCategory: Uncategorized

		measure '# Arrêts de travail par visite' = EXTERNALMEASURE("# Arrêts de travail par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: cd5af1ab-8517-4819-a85e-44c47a85c4bd
			sourceLineageTag: dece33f4-2b28-4943-adc0-3cff40b396ac
			dataCategory: Uncategorized

		measure '# Arrêts/Accidents/Maladies pro avec RAS par visite' = EXTERNALMEASURE("# Arrêts/Accidents/Maladies pro avec RAS par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 62e748b4-e823-48b7-b72d-472a69b419e2
			sourceLineageTag: d2c0373c-f4f0-4727-a392-fa49ecf07e9c
			dataCategory: Uncategorized

		measure '# Causes d''inaptitude par visite d''inaptitude (visite)' = EXTERNALMEASURE("# Causes d'inaptitude par visite d'inaptitude (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\4 - Informations concernant les propositions et l'avis du médecin du travail
			lineageTag: 2e0e16d1-b98c-4eb5-9d92-b46042656af2
			sourceLineageTag: ac133393-d226-4b00-a528-f1cf60b42d31
			dataCategory: Uncategorized

		measure '# Courriers autres par visite' = EXTERNALMEASURE("# Courriers autres par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\4 - Informations concernant les propositions et l'avis du médecin du travail
			lineageTag: 2b7ec31b-0da5-43dc-9076-8fb9ab015fc5
			sourceLineageTag: ae19b212-3591-487c-8bb9-ce1d0360747d
			dataCategory: Uncategorized

		measure '# Courriers d''orientation par visite' = EXTERNALMEASURE("# Courriers d'orientation par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\4 - Informations concernant les propositions et l'avis du médecin du travail
			lineageTag: 43aa0cbe-67c2-47e7-917e-6d8a0472534b
			sourceLineageTag: 653b36fd-f366-4b7b-a000-7c74d6eea4b6
			dataCategory: Uncategorized

		measure '# Courriers de prescription par visite' = EXTERNALMEASURE("# Courriers de prescription par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\4 - Informations concernant les propositions et l'avis du médecin du travail
			lineageTag: d7862c00-f7ef-4b48-a8e9-2e6e5a7ce252
			sourceLineageTag: baf9251a-f63e-400c-aa18-dfd345c9d66f
			dataCategory: Uncategorized

		measure '# Diplômes par visite' = EXTERNALMEASURE("# Diplômes par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 2ea1801d-f738-423e-9ecb-e75745252662
			sourceLineageTag: d5721867-4855-4347-b277-c2cca63e7cac
			dataCategory: Uncategorized

		measure '# Echelles anormales par visite' = EXTERNALMEASURE("# Echelles anormales par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: d0426daa-8a1a-44c5-92fe-3d56959fecdf
			sourceLineageTag: 84d3b54d-5b8e-4042-a26d-0553aff5460a
			dataCategory: Uncategorized

		measure '# Echelles par visite' = EXTERNALMEASURE("# Echelles par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: b84e1717-c251-4b16-93a6-acfb0cbc7a28
			sourceLineageTag: 1c1c274f-d38e-49e3-b765-d3b9b564c93b
			dataCategory: Uncategorized

		measure '# Emploi actuel par visite' = EXTERNALMEASURE("# Emploi actuel par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.3 - Informations concernant l'emploi actuel
			lineageTag: 4c2c8533-47b1-43a8-890c-5600fa6c1542
			sourceLineageTag: 3b6ac174-7534-4eba-84d5-83e363ab4402
			dataCategory: Uncategorized

		measure '# Examens cliniques avec RAS par visite' = EXTERNALMEASURE("# Examens cliniques avec RAS par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.4 - Données de l'examen clinique
			lineageTag: aac8c8d4-2e23-429d-aade-5b7708580ddf
			sourceLineageTag: 8c2e7c2d-e678-49d9-a3f7-8cf310b6fff0
			dataCategory: Uncategorized

		measure '# Examens cliniques avec thésaurus par visite' = EXTERNALMEASURE("# Examens cliniques avec thésaurus par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.4 - Données de l'examen clinique
			lineageTag: c2876bc9-4546-4583-bad2-1734caf7675e
			sourceLineageTag: 25701c3d-e2d7-49f0-8f8b-53db62a6f905
			dataCategory: Uncategorized

		measure '# Examens cliniques par visite' = EXTERNALMEASURE("# Examens cliniques par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.4 - Données de l'examen clinique
			lineageTag: 4ea448af-59d1-4e43-9e16-620f025138b7
			sourceLineageTag: bbb71f2f-19a7-4427-bb05-40f5b75a4ef1
			dataCategory: Uncategorized

		measure '# Examens paracliniques en visite par visite' = EXTERNALMEASURE("# Examens paracliniques en visite par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.5 - Données des examens paracliniques
			lineageTag: 0278b8d4-a49b-4e2b-9d7a-2e9b3fe59111
			sourceLineageTag: 79f1e22a-9c9e-4a1c-b06f-8800cd68da81
			dataCategory: Uncategorized

		measure '# Examens paracliniques pré visite par visite' = EXTERNALMEASURE("# Examens paracliniques pré visite par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.5 - Données des examens paracliniques
			lineageTag: 334010b0-5800-4bc1-91b9-270a2bc8cb58
			sourceLineageTag: 99fc23ed-ed8b-4c81-ac10-10089a2c123c
			dataCategory: Uncategorized

		measure '# Examens paracliniques prescrits par visite' = EXTERNALMEASURE("# Examens paracliniques prescrits par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.5 - Données des examens paracliniques
			lineageTag: de1f6cc4-acbd-42aa-8f09-dee41cc4f53d
			sourceLineageTag: fc4fad4d-b4d7-4956-9b51-77d0104a0971
			dataCategory: Uncategorized

		measure '# Expositions emploi actuel déclarées par l''employeur par visite' = EXTERNALMEASURE("# Expositions emploi actuel déclarées par l'employeur par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.3 - Informations concernant l'emploi actuel
			lineageTag: d8ec2b60-7fff-4e27-8e72-8d75b1ea1209
			sourceLineageTag: 6dd8a39c-ed0d-47b0-8290-248a06424989
			dataCategory: Uncategorized

		measure '# Expositions emploi actuel déclarées par le salarié par visite' = EXTERNALMEASURE("# Expositions emploi actuel déclarées par le salarié par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.3 - Informations concernant l'emploi actuel
			lineageTag: cff3f616-4c09-4b84-9a3f-c753979b9b6a
			sourceLineageTag: f255924a-5d75-4364-baad-e1ac42775259
			dataCategory: Uncategorized

		measure '# Expositions emploi actuel provenant de l''ancien logiciel par visite' = EXTERNALMEASURE("# Expositions emploi actuel provenant de l'ancien logiciel par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.3 - Informations concernant l'emploi actuel
			lineageTag: 1272dea3-8773-49c5-89c3-9454870fada3
			sourceLineageTag: 79fbf126-e93f-407d-8a17-358243a120f4
			dataCategory: Uncategorized

		measure '# Expositions emploi actuel saisies par le professionnel de santé par visite' = EXTERNALMEASURE("# Expositions emploi actuel saisies par le professionnel de santé par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.3 - Informations concernant l'emploi actuel
			lineageTag: 0b6190c8-eff7-4ae9-87aa-53e043af08d5
			sourceLineageTag: c6f00629-a276-4e75-8446-8a465ad6f4f4
			dataCategory: Uncategorized

		measure '# Gollac complété par visite' = EXTERNALMEASURE("# Gollac complété par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 206829fe-d8b7-497c-8335-da62a4e3e4a2
			sourceLineageTag: d81250ff-7415-45ad-85b0-3b0d7cf58e6a
			dataCategory: Uncategorized

		measure '# Habitus par visite' = EXTERNALMEASURE("# Habitus par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: defdc1b7-e696-40df-b774-41b25f4bfd37
			sourceLineageTag: b8c77f1e-30dc-462c-a55c-b82e400a4d59
			dataCategory: Uncategorized

		measure '# Incapacités permanentes par visite' = EXTERNALMEASURE("# Incapacités permanentes par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 9142a978-6be7-4231-9966-e533b6e05c89
			sourceLineageTag: 4c6878d7-adbb-43f7-8838-5db91a9a8ace
			dataCategory: Uncategorized

		measure '# Injections vaccinales par visite' = EXTERNALMEASURE("# Injections vaccinales par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 78595c20-46cc-4f8f-b4a1-fbcf6f51c0c6
			sourceLineageTag: e9af4f70-1b27-457c-a784-1bf1b48bcc95
			dataCategory: Uncategorized

		measure '# Invalidités de guerre par visite' = EXTERNALMEASURE("# Invalidités de guerre par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 69774ab0-d5d3-42cd-93dc-a00372407f7b
			sourceLineageTag: f094c7da-5cac-4864-9322-5014b1dc25ff
			dataCategory: Uncategorized

		measure '# Invalidités par visite' = EXTERNALMEASURE("# Invalidités par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 372f4361-31dd-468e-b1e5-c37ba0656d57
			sourceLineageTag: 612fe0eb-cad1-4cdc-9cef-fe6116537066
			dataCategory: Uncategorized

		measure '# Logements par visite' = EXTERNALMEASURE("# Logements par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: d89015f9-cd3b-475b-828c-29fee01fb29f
			sourceLineageTag: 2f8186cb-1006-43b0-a790-997cf789a478
			dataCategory: Uncategorized

		measure '# Maladies professionnelles par visite' = EXTERNALMEASURE("# Maladies professionnelles par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: f8543407-919e-43bd-a219-f0648d86e3ed
			sourceLineageTag: 7495e9bc-ddd5-4fe9-927d-a1a01a530cb3
			dataCategory: Uncategorized

		measure '# Mesures par visite' = EXTERNALMEASURE("# Mesures par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.5 - Données des examens paracliniques
			lineageTag: 387d4a3e-0016-41ed-9650-e0789d56cfca
			sourceLineageTag: 1ed5a0b1-cfdb-4071-ab25-5468ee536ca2
			dataCategory: Uncategorized

		measure '# Notes liées aux expositions par visite' = EXTERNALMEASURE("# Notes liées aux expositions par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\2 - Informations concernant l'emploi et les activités professionnelles\2.3 - Informations concernant l'emploi actuel
			lineageTag: 7ffde9e1-49d5-42d3-8514-c639fa70a7cf
			sourceLineageTag: 47a1f311-ab19-4d9d-88aa-18b855b3b581
			dataCategory: Uncategorized

		measure '# Notes par visite' = EXTERNALMEASURE("# Notes par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\5 - Synthèse
			lineageTag: 1bf01f14-d959-4601-a96f-63a04227172b
			sourceLineageTag: 0b653c7a-3dc2-4e4c-8f1f-318a00e59c53
			dataCategory: Uncategorized

		measure '# Notes socio-professionnelles par visite' = EXTERNALMEASURE("# Notes socio-professionnelles par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: a6e45213-4fb8-4b1d-8bd3-000580c99489
			sourceLineageTag: ff8fa03e-7f71-473c-9e88-0f171a6451e9
			dataCategory: Uncategorized

		measure '# Pathologies avec RAS par visite' = EXTERNALMEASURE("# Pathologies avec RAS par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 1f7a6ffc-59f5-421f-acbc-d23185488e8c
			sourceLineageTag: 0dd69e50-1cd7-489a-8434-118c77fe5439
			dataCategory: Uncategorized

		measure '# Pathologies par visite' = EXTERNALMEASURE("# Pathologies par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 41712f18-52ae-4e70-bd58-2fc02e92ffc1
			sourceLineageTag: 4944ea91-94b5-42b6-b106-f811274c3ea3
			dataCategory: Uncategorized

		measure '# Plaquettes de prévention par visite' = EXTERNALMEASURE("# Plaquettes de prévention par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\4 - Informations concernant les propositions et l'avis du médecin du travail
			lineageTag: 4cbf4647-2973-42d2-86f0-f40b14e6d397
			sourceLineageTag: 3479b247-55cf-465d-b5d8-f6d8717e8466
			dataCategory: Uncategorized

		measure '# Recommandations orales par visite' = EXTERNALMEASURE("# Recommandations orales par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\4 - Informations concernant les propositions et l'avis du médecin du travail
			lineageTag: afc6f8a7-5023-41ab-a37a-b14d1f4ff86d
			sourceLineageTag: 91390e21-30af-44be-b176-89f33a73f950
			dataCategory: Uncategorized

		measure '# RQTH par visite' = EXTERNALMEASURE("# RQTH par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 9e43e706-c0c2-47d3-9b3c-88492cbdbef8
			sourceLineageTag: 43c9a74e-a598-4550-b2f3-681ce681af76
			dataCategory: Uncategorized

		measure '# Situations administratives par visite' = EXTERNALMEASURE("# Situations administratives par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 1f7417e1-73c5-4112-859c-0c2d22efb221
			sourceLineageTag: 02087d32-c178-4d24-8a0f-3ec1f8a3fa35
			dataCategory: Uncategorized

		measure '# Situations financières avec RAS par visite' = EXTERNALMEASURE("# Situations financières avec RAS par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: ef95b0fc-49e0-4061-82fe-a9d7c7285fcc
			sourceLineageTag: 9f3521a9-b636-45e1-8ac0-21a011fb0e56
			dataCategory: Uncategorized

		measure '# Situations financières par visite' = EXTERNALMEASURE("# Situations financières par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 9bf8bb1a-ffe1-40d2-bc00-e993277c3bf0
			sourceLineageTag: 77a6808a-5e77-4ccb-8470-c7fb17d86e29
			dataCategory: Uncategorized

		measure '# Situations personnelles et familiales par visite' = EXTERNALMEASURE("# Situations personnelles et familiales par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: df489c77-d04d-4f82-acf6-152344537d3d
			sourceLineageTag: 72baacb7-f21a-4d6f-a932-ca81c1c99005
			dataCategory: Uncategorized

		measure '# Thésaurus accidents de travail par visite' = EXTERNALMEASURE("# Thésaurus accidents de travail par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: cbea934a-b934-45ab-9a09-ded8ec0fd8e4
			sourceLineageTag: cec03792-c13c-4651-8511-59b0e83faec7
			dataCategory: Uncategorized

		measure '# Thésaurus antécédents familiaux par visite' = EXTERNALMEASURE("# Thésaurus antécédents familiaux par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 65c9503e-7955-46cc-b7c7-251cf331df67
			sourceLineageTag: f9761eb9-790d-4284-aa23-643c30221fb0
			dataCategory: Uncategorized

		measure '# Thésaurus antécédents personnels par visite' = EXTERNALMEASURE("# Thésaurus antécédents personnels par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 117f8775-69f9-4c45-95ee-5900482cd864
			sourceLineageTag: 1851062a-f2a5-4444-b0a4-39180c416c72
			dataCategory: Uncategorized

		measure '# Thésaurus arrêts de travail par visite' = EXTERNALMEASURE("# Thésaurus arrêts de travail par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: b40a0783-14df-4a5a-bcc8-c6479381cd65
			sourceLineageTag: f46a9e76-0fb5-4076-b921-e6429c0e07cb
			dataCategory: Uncategorized

		measure '# Thésaurus cim10  par visite' = EXTERNALMEASURE("# Thésaurus cim10  par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: f38cc116-f581-4833-92fb-6085980232bd
			sourceLineageTag: 0e17cf64-afbe-4a06-881d-481f6ef78b5d
			dataCategory: Uncategorized

		measure '# Thésaurus diplômes par visite' = EXTERNALMEASURE("# Thésaurus diplômes par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 84c23888-fe21-4722-a0e0-fd85d3e269d0
			sourceLineageTag: 0628862c-7845-45eb-9065-c86ad854041d
			dataCategory: Uncategorized

		measure '# Thésaurus examens cliniques par visite' = EXTERNALMEASURE("# Thésaurus examens cliniques par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.4 - Données de l'examen clinique
			lineageTag: 3c2cd6f5-8e6e-407e-b7fa-56e44e99f672
			sourceLineageTag: 6e99fe11-17ee-4817-a490-11c954275301
			dataCategory: Uncategorized

		measure '# Thésaurus hors examens cliniques par visite' = EXTERNALMEASURE("# Thésaurus hors examens cliniques par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 0cb1628b-0cbb-45a7-8972-438e74977e80
			sourceLineageTag: c5cb13b2-785f-467e-8bf1-dc9bac60c2e4
			dataCategory: Uncategorized

		measure '# Thésaurus maladies professionnelles par visite' = EXTERNALMEASURE("# Thésaurus maladies professionnelles par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 5ff025d4-596d-4011-a193-a300cb77f4b6
			sourceLineageTag: 987d6799-6a37-4336-8b1f-a6ab3e7c6d3a
			dataCategory: Uncategorized

		measure '# Thésaurus par visite' = EXTERNALMEASURE("# Thésaurus par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\5 - Synthèse
			lineageTag: 432b7780-ce75-49ce-a3d4-4d0a07fabe7e
			sourceLineageTag: 06ad9002-cfcf-4210-ad75-02007f8607be
			dataCategory: Uncategorized

		measure '# Thésaurus pathologies par visite' = EXTERNALMEASURE("# Thésaurus pathologies par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: c19d8639-a06c-417f-a27c-dfd01f0c2a26
			sourceLineageTag: 92572f4f-d172-47ab-8ded-b307069639bd
			dataCategory: Uncategorized

		measure '# Thésaurus situations personnelles et familiales par visite' = EXTERNALMEASURE("# Thésaurus situations personnelles et familiales par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 51281faf-dff2-4bbe-9210-cc3b99705463
			sourceLineageTag: c80e105e-aa6d-43cc-95ea-8d757c1cfb7c
			dataCategory: Uncategorized

		measure '# Thésaurus traitements par visite' = EXTERNALMEASURE("# Thésaurus traitements par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 1c10accd-c5e0-4005-9832-141292f8ea9f
			sourceLineageTag: 68fae1c6-d467-4c13-9965-88a71bfc5558
			dataCategory: Uncategorized

		measure '# Traitements avec RAS par visite' = EXTERNALMEASURE("# Traitements avec RAS par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 6b365c1f-5f76-460f-8f4f-907a149fc8d4
			sourceLineageTag: a0c5b380-0021-41d8-ab96-f64ff94efd3a
			dataCategory: Uncategorized

		measure '# Traitements par visite' = EXTERNALMEASURE("# Traitements par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: d38ac4cb-3627-42f1-a3a9-62f0ebb8d544
			sourceLineageTag: 4df1f40f-97d6-4100-a79f-c43e7a134608
			dataCategory: Uncategorized

		measure '# Vécus au travail par visite' = EXTERNALMEASURE("# Vécus au travail par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: e1e4d51a-3e51-4bc8-8b74-17f51972226c
			sourceLineageTag: 50b55ddd-bbae-416e-a407-dd51a54314c0
			dataCategory: Uncategorized

		measure '# Victimes civiles de guerre par visite' = EXTERNALMEASURE("# Victimes civiles de guerre par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: 951c35be-4573-48ad-8708-737c62e56f4e
			sourceLineageTag: f3535636-bca3-4fa9-817d-6a16a7364f4e
			dataCategory: Uncategorized

		measure '# Victimes de terrorisme par visite' = EXTERNALMEASURE("# Victimes de terrorisme par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00
			displayFolder: Indicateurs\3 - Informations recueillies durant les examens médicaux\3.2 - Données de l'interrogatoire
			lineageTag: d5569c78-0931-4241-b858-bc1b3172a977
			sourceLineageTag: 74f0d23e-318a-49b6-a6b6-0151c4bde6ce
			dataCategory: Uncategorized

		measure '# Visites' = EXTERNALMEASURE("# Visites", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\5 - Synthèse
			lineageTag: 67d1dcd0-3603-4964-9c2c-73fe77b35e4f
			sourceLineageTag: d4933fef-5960-4453-8823-503cdd730d87
			dataCategory: Uncategorized

		measure '% Arrêts de travail avec date de début renseignée (visite)' = EXTERNALMEASURE("% Arrêts de travail avec date de début renseignée (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: b325a1db-016f-4e9e-8493-1f65289ab331
			sourceLineageTag: 1dc68341-aca5-4a42-9a8a-3a9a87aa76a7
			dataCategory: Uncategorized

		measure '% Arrêts de travail avec date de fin renseignée (visite)' = EXTERNALMEASURE("% Arrêts de travail avec date de fin renseignée (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: abd05c96-93c9-4403-a6da-4c94c3a59563
			sourceLineageTag: f90d563d-4f7b-4562-b94f-13df56001dc8
			dataCategory: Uncategorized

		measure '% Echelles anormales avec Gollac (visite)' = EXTERNALMEASURE("% Echelles anormales avec Gollac (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: afeeb043-f102-4cb7-a829-9019b14f457c
			sourceLineageTag: 59a9e1f7-2b94-419b-8349-bcc51b882cb7
			dataCategory: Uncategorized

		measure '% Emploi actuel avec description renseignée (visite)' = EXTERNALMEASURE("% Emploi actuel avec description renseignée (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: c6291bec-39b9-4ce6-9cf4-9033269c9bfa
			sourceLineageTag: ee290602-b868-45d4-ac00-ca7c63476817
			dataCategory: Uncategorized

		measure '% Emploi actuel avec équipement renseigné (visite)' = EXTERNALMEASURE("% Emploi actuel avec équipement renseigné (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 997532a3-fa93-4e51-938d-0d79fd501013
			sourceLineageTag: 9ba982a3-df44-471c-bc7a-f3c45feba36d
			dataCategory: Uncategorized

		measure '% Emploi actuel avec horaires renseignés (visite)' = EXTERNALMEASURE("% Emploi actuel avec horaires renseignés (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: bc193250-ca89-4022-87a5-a94bbe755275
			sourceLineageTag: 5e1b1b75-7974-4628-9317-a60c258d114b
			dataCategory: Uncategorized

		measure '% Emploi actuel avec lieu renseigné (visite)' = EXTERNALMEASURE("% Emploi actuel avec lieu renseigné (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 06914162-f6ac-481b-9676-546b753a6b66
			sourceLineageTag: 0561128f-7f27-41fb-b18e-ecdbe3361c41
			dataCategory: Uncategorized

		measure '% Emploi actuel avec PCS renseigné (visite)' = EXTERNALMEASURE("% Emploi actuel avec PCS renseigné (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: d4a23f43-a0f1-4201-b51b-0c18af8371b5
			sourceLineageTag: 60587e8a-1019-4c03-b18e-3beda3706bbf
			dataCategory: Uncategorized

		measure '% Emploi actuel avec poste renseigné (visite)' = EXTERNALMEASURE("% Emploi actuel avec poste renseigné (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 1d830d9e-98d0-40b9-8406-3b57bc762b98
			sourceLineageTag: ee382297-d125-4e00-8e23-f58a0d68b82e
			dataCategory: Uncategorized

		measure '% Emploi actuel avec tâches renseignées (visite)' = EXTERNALMEASURE("% Emploi actuel avec tâches renseignées (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: ce122c5b-eb40-46f9-8dc1-a631383cf092
			sourceLineageTag: 70ebdb99-e49b-495d-bfac-1eba5a2a7b89
			dataCategory: Uncategorized

		measure '% Emploi actuel avec trajet renseigné (visite)' = EXTERNALMEASURE("% Emploi actuel avec trajet renseigné (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 791b44ee-f0bb-43ee-98d4-ad7eddb2ce09
			sourceLineageTag: d53e6437-34a1-4bf2-9239-b19d81207e6e
			dataCategory: Uncategorized

		measure '% Emploi actuel avec type de contrat renseigné (visite)' = EXTERNALMEASURE("% Emploi actuel avec type de contrat renseigné (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 63df380a-8193-4919-9234-48298461fb70
			sourceLineageTag: dd78d636-6df3-45a8-bf39-6c8dfeb237e8
			dataCategory: Uncategorized

		measure '% Etat global de vaccination renseigné (visite)' = EXTERNALMEASURE("% Etat global de vaccination renseigné (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 2a032895-776d-4c7f-b715-9cd53d8b0fcf
			sourceLineageTag: 87334cbd-3ef5-4619-92c2-d83acef07b17
			dataCategory: Uncategorized

		measure '% Examens cliniques avec RAS (visite)' = EXTERNALMEASURE("% Examens cliniques avec RAS (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: c321131c-ee45-41f8-b98b-1ad57e34eef8
			sourceLineageTag: aca0ec7e-e491-4dd9-b1ee-3df482741696
			dataCategory: Uncategorized

		measure '% Examens cliniques avec thésaurus (visite)' = EXTERNALMEASURE("% Examens cliniques avec thésaurus (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 8f167232-7d13-4c8a-ba36-39a389a98710
			sourceLineageTag: c8ccd153-0a41-43cd-bd7a-04608b5ea774
			dataCategory: Uncategorized

		measure '% Injections vaccinales avec numéro de lot renseigné (visite)' = EXTERNALMEASURE("% Injections vaccinales avec numéro de lot renseigné (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: d2316daa-2802-44c4-9767-5be9a130904c
			sourceLineageTag: 86cf4cac-72dd-4aeb-a918-dd490e7d9635
			dataCategory: Uncategorized

		measure '% Notes avec thésaurus (visite)' = EXTERNALMEASURE("% Notes avec thésaurus (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 4130a1d7-8e05-4eee-b951-0fe8991a662d
			sourceLineageTag: e1b14e44-2da8-41b1-accd-043f50150ce8
			dataCategory: Uncategorized

		measure '% Notes avec thésaurus ou RAS (visite)' = EXTERNALMEASURE("% Notes avec thésaurus ou RAS (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 61323332-9580-484f-b7e9-b5d4aef8800d
			sourceLineageTag: 07ecd8bf-30de-4a32-bd33-f96fe49ef849
			dataCategory: Uncategorized

		measure '% Notes hors examen clinique avec thésaurus ou RAS (visite)' = EXTERNALMEASURE("% Notes hors examen clinique avec thésaurus ou RAS (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 34f075bb-3cea-4aa0-9648-0f4c147aed4d
			sourceLineageTag: 10e9248c-3f39-4df8-b137-359d221412c9
			dataCategory: Uncategorized

		measure '% Notes sociales avec thésaurus ou RAS (visite)' = EXTERNALMEASURE("% Notes sociales avec thésaurus ou RAS (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 71b5b2d5-0b20-4d70-8c64-7f8bac4b9cbf
			sourceLineageTag: 64c1bd71-eecd-4feb-ac50-87d5b66b69aa
			dataCategory: Uncategorized

		measure '% Pathologies avec date de début renseignée (visite)' = EXTERNALMEASURE("% Pathologies avec date de début renseignée (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 22b54f86-4665-4dcf-b227-f98fcfeb610a
			sourceLineageTag: ad385f46-5bab-49e8-ac18-29de7e80f31b
			dataCategory: Uncategorized

		measure '% Pathologies avec date de fin renseignée (visite)' = EXTERNALMEASURE("% Pathologies avec date de fin renseignée (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: c77e64c3-84c7-4d47-8d8c-c64fbe065baa
			sourceLineageTag: fcfb1507-0782-4baf-9660-17c98fcf7f55
			dataCategory: Uncategorized

		measure '% Visites avec adaptation de poste (visite)' = EXTERNALMEASURE("% Visites avec adaptation de poste (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 99cd1e59-84f5-4702-b61d-fe4d76a940a3
			sourceLineageTag: 2fe477e6-68fa-4661-af86-a7c2656a5b06
			dataCategory: Uncategorized

		measure '% Visites avec conclusion (visite)' = EXTERNALMEASURE("% Visites avec conclusion (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: df43f946-bb13-41fe-816a-29061066be44
			sourceLineageTag: 21549e8d-0bb6-48f0-b0a3-4a73a86d24f0
			dataCategory: Uncategorized

		measure '% Visites avec échelle remplie (visite)' = EXTERNALMEASURE("% Visites avec échelle remplie (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: ab50939c-6584-4172-a4da-a9a07c347f0a
			sourceLineageTag: f900a489-fe31-4087-ac26-2a3f5e31425c
			dataCategory: Uncategorized

		measure '% Visites avec examen clinique (visite)' = EXTERNALMEASURE("% Visites avec examen clinique (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 297c2439-612f-415e-949c-8289e6dee5cb
			sourceLineageTag: 8c4bbc0f-2ef8-499a-9b01-dc769164df32
			dataCategory: Uncategorized

		measure '% Visites avec IRDP rempli (visite)' = EXTERNALMEASURE("% Visites avec IRDP rempli (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 3f329823-ef6d-4a5f-bc6b-13760829b699
			sourceLineageTag: fba68562-7e76-4857-bb4c-a65f853d5cdd
			dataCategory: Uncategorized

		measure '% Visites avec IRI rempli (visite)' = EXTERNALMEASURE("% Visites avec IRI rempli (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 6e2e4736-2bbc-4911-b5c5-dc1a836633be
			sourceLineageTag: 1ff3db2d-997d-4883-bca3-7fdee75493a3
			dataCategory: Uncategorized

		measure '% Visites avec situation administrative (visite)' = EXTERNALMEASURE("% Visites avec situation administrative (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 031b4495-3cb0-4db4-880e-9905dca8b011
			sourceLineageTag: fd190911-bd48-402d-a60a-648544db8be6
			dataCategory: Uncategorized

		measure '% Visites d''inaptitude avec cause (visite)' = EXTERNALMEASURE("% Visites d'inaptitude avec cause (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 2e022353-c684-49ef-9f6b-13d070e7da41
			sourceLineageTag: efaa5249-667a-4850-be31-a9f9c0414753
			dataCategory: Uncategorized

		measure '% Visites de suivi individuel (visite)' = EXTERNALMEASURE("% Visites de suivi individuel (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: afeb5264-9612-4fd8-8831-39be8cb6a2a4
			sourceLineageTag: f3984072-450b-4200-99ec-2e7bd3111c25
			dataCategory: Uncategorized

		measure '% Visites IRDP à risque avec facteurs renseignés (visite)' = EXTERNALMEASURE("% Visites IRDP à risque avec facteurs renseignés (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: 14f34f1f-c8ad-4681-a9a5-1546bb3798c7
			sourceLineageTag: 325b02a7-571d-408d-af18-863ec68999b9
			dataCategory: Uncategorized

		measure '% Visites IRI à risque avec facteurs renseignés (visite)' = EXTERNALMEASURE("% Visites IRI à risque avec facteurs renseignés (visite)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0.00\ %
			lineageTag: aa5d9e86-c05a-475e-99ad-e66d29e0f246
			sourceLineageTag: 20023e14-9b58-4e9b-9ecf-3fc0e2d4e36d
			dataCategory: Uncategorized

	ref table Saisonniers

		measure '# saisonniers suivis au moins 1 jour sur la période' = EXTERNALMEASURE("# saisonniers suivis au moins 1 jour sur la période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 7124d775-e371-47b8-9bfe-083adace0fb8
			sourceLineageTag: bc200fa5-3807-4359-aedd-006f7afdf663
			dataCategory: Uncategorized

		measure '# saisonniers suivis en début de période' = EXTERNALMEASURE("# saisonniers suivis en début de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 56cd5848-95ed-42a9-9949-3d69e6f548ab
			sourceLineageTag: 66f67c3f-8d97-4b37-b6a5-97a13673ee6d
			dataCategory: Uncategorized

		measure '# saisonniers suivis en fin de période' = EXTERNALMEASURE("# saisonniers suivis en fin de période", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 60438fce-151d-417e-91b6-6e7396f58cf8
			sourceLineageTag: 2a3bc864-81dc-454a-9dad-4b57278e75c5
			dataCategory: Uncategorized

	ref table Salariés

		measure 'Effectif fonction publique' = EXTERNALMEASURE("Effectif fonction publique", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages
			lineageTag: 4ac6b691-e444-444e-b248-629273ed9680
			sourceLineageTag: 3b59cd92-2125-4ad3-8a66-6e84ad64ce25
			dataCategory: Uncategorized

		measure 'Effectif suivi' = EXTERNALMEASURE("Effectif suivi", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages
			lineageTag: 5cc5c4a3-498e-46f8-bafa-461594dd327c
			sourceLineageTag: 93fab5e0-00cf-46a8-92e5-634bf0dddf4d
			dataCategory: Uncategorized

		measure 'Effectif suivi (intérim & non intérim)' = EXTERNALMEASURE("Effectif suivi (intérim & non intérim)", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages\Modèle de charge
			lineageTag: 90739fe2-b5eb-4d26-b9ab-30b0c5e892b6
			sourceLineageTag: d3bbc365-722f-4895-8812-1156997cec3b
			dataCategory: Uncategorized

		measure 'Effectif suivi intérimaire' = EXTERNALMEASURE("Effectif suivi intérimaire", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages
			lineageTag: d86c7268-fca0-408e-902c-b42da30f98b0
			sourceLineageTag: 98dfbe66-b4ce-45dc-8565-46dc1a5b563a
			dataCategory: Uncategorized

		measure 'Effectif suivi intérimaire SI' = EXTERNALMEASURE("Effectif suivi intérimaire SI", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages\Modèle de charge
			lineageTag: 8691c5c2-b4e2-48ac-9913-6933d250e3c4
			sourceLineageTag: 6b56b47c-1e1f-4944-b898-33293ae3916a
			dataCategory: Uncategorized

		measure 'Effectif suivi intérimaire SIA' = EXTERNALMEASURE("Effectif suivi intérimaire SIA", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages\Modèle de charge
			lineageTag: d9d9329f-1360-49eb-a8d7-fbd1ec3c8a49
			sourceLineageTag: 9e9e40cd-cf54-47d2-af50-e9590dcc2d0a
			dataCategory: Uncategorized

		measure 'Effectif suivi intérimaire SIR' = EXTERNALMEASURE("Effectif suivi intérimaire SIR", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages\Modèle de charge
			lineageTag: 4279f169-8804-403e-a4fc-031c8761c7b5
			sourceLineageTag: 6bd52766-e378-4fb8-9933-24764135700c
			dataCategory: Uncategorized

		measure 'Effectif suivi intérimaire total' = EXTERNALMEASURE("Effectif suivi intérimaire total", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages\Modèle de charge
			lineageTag: 8c514fb4-58c2-449a-8df1-ce6c94f83a84
			sourceLineageTag: 7988f033-6f7d-49e9-88e0-76224d567875
			dataCategory: Uncategorized

		measure 'Effectif suivi non-intérimaire' = EXTERNALMEASURE("Effectif suivi non-intérimaire", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages
			lineageTag: 75ca8002-6252-4c23-92e2-8d2c53fa5d71
			sourceLineageTag: 93833bad-538a-440d-8687-67f7111de747
			dataCategory: Uncategorized

		measure 'Effectif suivi non-intérimaire SI' = EXTERNALMEASURE("Effectif suivi non-intérimaire SI", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages\Modèle de charge
			lineageTag: 9ad602ac-ade5-4ef6-a431-bbb040a05d02
			sourceLineageTag: 878eb9be-c7d2-4ea5-80de-097a2ef16ec1
			dataCategory: Uncategorized

		measure 'Effectif suivi non-intérimaire SIA' = EXTERNALMEASURE("Effectif suivi non-intérimaire SIA", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages\Modèle de charge
			lineageTag: f880189e-d2c6-4ec3-8f15-e7020486ad5f
			sourceLineageTag: 9cc033fe-80d3-44f1-8d91-6c56ee4157ea
			dataCategory: Uncategorized

		measure 'Effectif suivi non-intérimaire SIR' = EXTERNALMEASURE("Effectif suivi non-intérimaire SIR", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages\Modèle de charge
			lineageTag: ceb1ed78-63af-434d-a779-083794131c9f
			sourceLineageTag: 7dd304fd-cfe0-4ee4-9438-109fcb0c0a93
			dataCategory: Uncategorized

		measure 'Effectif suivi non-intérimaire total' = EXTERNALMEASURE("Effectif suivi non-intérimaire total", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages\Modèle de charge
			lineageTag: d7967ce0-b04e-4e04-83a0-9264c40d3611
			sourceLineageTag: 8307b5ed-1831-4726-803c-e65743d340b5
			dataCategory: Uncategorized

		measure 'Nombre d''adhérents' = EXTERNALMEASURE("Nombre d'adhérents", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages
			lineageTag: 1996967b-b33c-461a-b86a-7061fbd7d073
			sourceLineageTag: 1d4e530c-f192-4e27-abdb-9715a516c6e9
			dataCategory: Uncategorized

		measure 'Nombre de collections' = EXTERNALMEASURE("Nombre de collections", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages
			lineageTag: bf6cb5d9-5be7-4d81-a543-4e44d8c42c4e
			sourceLineageTag: 5f563277-748b-4f40-a7f4-071e851d7ab5
			dataCategory: Uncategorized

		measure 'Nombre de personnes suivies' = EXTERNALMEASURE("Nombre de personnes suivies", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Comptages
			lineageTag: 049770ca-f8a1-4406-893a-2de8f0fd34d5
			sourceLineageTag: dd63e9bd-3868-4532-8c00-038d0d23c88b
			dataCategory: Uncategorized

		measure 'Taux d''agents fonction publique' = EXTERNALMEASURE("Taux d'agents fonction publique", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux
			lineageTag: 1f65932b-1c69-4d53-85ac-e67997723c3f
			sourceLineageTag: 9b492885-93ab-4631-97d3-b29ad34518ba
			dataCategory: Uncategorized

		measure 'Taux d''intérimaires' = EXTERNALMEASURE("Taux d'intérimaires", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux
			lineageTag: 34aea7b5-ce56-43d6-b088-da3d326ceefb
			sourceLineageTag: 80bc4227-654d-42cd-bc4e-aa86afb44e8a
			dataCategory: Uncategorized

		measure 'Taux de retard (salariés)' = EXTERNALMEASURE("Taux de retard (salariés)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux
			lineageTag: a195c2e5-4d0f-41ad-a0a9-8c4f9bfcd537
			sourceLineageTag: 77a7d3ec-21d4-408f-a028-c5ac173826c2
			dataCategory: Uncategorized

		measure 'Taux de retard SIR (salariés)' = EXTERNALMEASURE("Taux de retard SIR (salariés)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux
			lineageTag: 77560a61-1b26-4876-8c2f-92df5fa8debe
			sourceLineageTag: 51bbd2ab-0d1d-4577-b552-f76d78c62d92
			dataCategory: Uncategorized

		measure 'Taux de salariés SIA' = EXTERNALMEASURE("Taux de salariés SIA", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux
			lineageTag: 3b4ee51d-683f-4740-99b8-a2dd7655a035
			sourceLineageTag: 850671c3-2947-461e-9f4c-dd5555f1f3ee
			dataCategory: Uncategorized

		measure 'Taux de salariés SIR' = EXTERNALMEASURE("Taux de salariés SIR", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux
			lineageTag: 59c72659-10db-4ed1-b199-cc50422d0d6c
			sourceLineageTag: df721c3c-1ce6-4eea-9438-1b37eee3a999
			dataCategory: Uncategorized

	ref table 'Temps travail'

		measure 'Nombre d''annulations excusées' = EXTERNALMEASURE("Nombre d'annulations excusées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Nombre de RDV/visites
			lineageTag: 847e63cc-f493-4b76-82db-6c4f266d66ea
			sourceLineageTag: 7971aec3-f8ab-4572-bc90-d5816eb00347
			dataCategory: Uncategorized

		measure 'Nombre d''annulations non excusées' = EXTERNALMEASURE("Nombre d'annulations non excusées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Nombre de RDV/visites
			lineageTag: 2fa1a476-bb9d-431e-b15c-10916c96c98c
			sourceLineageTag: 38fa2953-d8c2-444a-a4ca-9b71f984d4ce
			dataCategory: Uncategorized

		measure 'Nombre de créneaux' = EXTERNALMEASURE("Nombre de créneaux", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Nombre de RDV/visites
			lineageTag: 880000e5-0bb2-4529-b2cc-ed603cbcd213
			sourceLineageTag: 30b7d4f7-3fc7-4f79-9d2f-37d7355dd3bf
			dataCategory: Uncategorized

		measure 'Nombre de visites réalisées' = EXTERNALMEASURE("Nombre de visites réalisées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Nombre de RDV/visites
			lineageTag: f1fbd578-86cc-4a54-a9fd-4e52fa36dc19
			sourceLineageTag: 2f8194b1-d7e1-4cc1-b212-0d26cb910a65
			dataCategory: Uncategorized

		measure 'Nombre moyen de visites réalisées par heure de vacation' = EXTERNALMEASURE("Nombre moyen de visites réalisées par heure de vacation", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.00
			displayFolder: Indicateurs\Taux liés aux vacations
			lineageTag: 36b45b95-7eb2-4032-9a03-fbb5cce5e509
			sourceLineageTag: 16a9dfbb-9f35-4255-821f-41417836fc5b
			dataCategory: Uncategorized

		measure 'Taux activité en zone non clinique' = EXTERNALMEASURE("Taux activité en zone non clinique", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux liés aux zones non clinique
			lineageTag: ad41380c-f6e1-486d-abd4-08095a8c21c4
			sourceLineageTag: 47f8b869-1dba-40e3-b0e9-964de966d1aa
			dataCategory: Uncategorized

		measure 'Taux activité hors zone non clinique' = EXTERNALMEASURE("Taux activité hors zone non clinique", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux liés aux zones non clinique
			lineageTag: 6affdc6d-0941-41ec-b961-0d70e4029aab
			sourceLineageTag: 9a201bae-1fd3-4e56-bae1-0926f8b27c40
			dataCategory: Uncategorized

		measure 'Taux AMT (zone non clinique)' = EXTERNALMEASURE("Taux AMT (zone non clinique)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux liés aux zones non clinique
			lineageTag: 9fdd7bd2-60f6-4eae-ba42-61f8c42354ef
			sourceLineageTag: 502e6d5f-647b-44bf-8f73-b9020650d6f2
			dataCategory: Uncategorized

		measure 'Taux annulation excusée (vacation)' = EXTERNALMEASURE("Taux annulation excusée (vacation)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux liés aux vacations
			lineageTag: c2c7efdb-7c75-4076-9b1e-22b615cbefcf
			sourceLineageTag: bb2ee6ba-a456-4169-b2da-c7fbde68e3fc
			dataCategory: Uncategorized

		measure 'Taux annulation non excusée (vacation)' = EXTERNALMEASURE("Taux annulation non excusée (vacation)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux liés aux vacations
			lineageTag: 1d74563f-624f-4920-bb7e-2fa5e88183f3
			sourceLineageTag: ef671719-3951-4ec4-98e1-7b85ae053ee1
			dataCategory: Uncategorized

		measure 'Taux d''effectivité (zone non clinique)' = EXTERNALMEASURE("Taux d'effectivité (zone non clinique)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux liés aux zones non clinique
			lineageTag: c5f896f1-e925-4401-aedc-fa484aa7669b
			sourceLineageTag: 00dab695-3835-4b61-a91d-b1608a56fb84
			dataCategory: Uncategorized

		measure 'Taux d''indisponibilité' = EXTERNALMEASURE("Taux d'indisponibilité", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux de répartition
			lineageTag: 904577a6-2438-439f-aa33-0c0ee4d72e82
			sourceLineageTag: b9af069f-b049-4516-87f6-3b32978e3e1a
			dataCategory: Uncategorized

		measure 'Taux de vacations' = EXTERNALMEASURE("Taux de vacations", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux de répartition
			lineageTag: 9bee5f57-c869-4801-8fcc-c04ee16bdfe8
			sourceLineageTag: c81062e2-a08f-4a4e-9734-2b9bd8da7ebf
			dataCategory: Uncategorized

		measure 'Taux de zones non-cliniques' = EXTERNALMEASURE("Taux de zones non-cliniques", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux de répartition
			lineageTag: 2fe60b34-c1ad-4fb8-861a-00be5fdf35b0
			sourceLineageTag: cb7dbfac-1b08-48b5-a854-8f760867016d
			dataCategory: Uncategorized

		measure 'Taux hors zone' = EXTERNALMEASURE("Taux hors zone", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux de répartition
			lineageTag: 5dd0ea4d-9ad8-44b1-93fa-7c28a0857846
			sourceLineageTag: a57d58e9-a5ec-4816-99d7-77fcb384effe
			dataCategory: Uncategorized

		measure 'Taux non exploité (vacation)' = EXTERNALMEASURE("Taux non exploité (vacation)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux liés aux vacations
			lineageTag: c18d7e3c-5eda-47ae-8324-00250815405e
			sourceLineageTag: 1200a4a9-d590-4b43-b8b3-d921fd9b4389
			dataCategory: Uncategorized

		measure 'Taux non exploité (zone non clinique)' = EXTERNALMEASURE("Taux non exploité (zone non clinique)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux liés aux zones non clinique
			lineageTag: b6cff8b9-adac-4010-97a5-e10eef7a5345
			sourceLineageTag: 75ed38c4-4786-477f-bfbb-89f33664bf97
			dataCategory: Uncategorized

		measure 'Taux RDV déplacé (vacation)' = EXTERNALMEASURE("Taux RDV déplacé (vacation)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux liés aux vacations
			lineageTag: f4855452-b75c-4930-969c-8402defc6d11
			sourceLineageTag: 562dd2b0-bec2-43ff-99e7-2685e4c9077f
			dataCategory: Uncategorized

		measure 'Taux RDV en vacation' = EXTERNALMEASURE("Taux RDV en vacation", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux liés aux vacations
			lineageTag: 11ed64b2-df2c-4843-98b8-81d9dee7a1e8
			sourceLineageTag: 681df3ef-3594-4899-96b8-557a02227ea9
			dataCategory: Uncategorized

		measure 'Taux RDV hors vacation' = EXTERNALMEASURE("Taux RDV hors vacation", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux liés aux vacations
			lineageTag: 06c1ef0b-16e8-4b21-b54f-01def3febc19
			sourceLineageTag: fae139e0-bc0e-4a54-b340-47e5febedbca
			dataCategory: Uncategorized

		measure 'Taux temps connexe (zone non clinique)' = EXTERNALMEASURE("Taux temps connexe (zone non clinique)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux liés aux zones non clinique
			lineageTag: 8eeb5425-3d0e-4467-9c70-5c609bc0f929
			sourceLineageTag: 6ad636f8-4892-419f-9f15-dcc13122cc54
			dataCategory: Uncategorized

		measure 'Taux visite réalisée (vacation)' = EXTERNALMEASURE("Taux visite réalisée (vacation)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\Taux liés aux vacations
			lineageTag: 7ac1ee04-f2f4-4d8f-914d-ce92749802c8
			sourceLineageTag: 59a0efe3-e583-4503-a820-14aff8cef3a4
			dataCategory: Uncategorized

		measure 'Temps total AMT (en heures)' = EXTERNALMEASURE("Temps total AMT (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Temps totaux en heures
			lineageTag: a984836a-f15f-400a-83ce-dd8694d9b6c6
			sourceLineageTag: 495be07b-bc6a-41ef-af57-f20827b91452
			dataCategory: Uncategorized

		measure 'Temps total annulations excusées (en heures)' = EXTERNALMEASURE("Temps total annulations excusées (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Temps totaux en heures
			lineageTag: c18ebab1-06e2-416f-9833-0dcc8054bdfe
			sourceLineageTag: 549d0657-4689-41f5-b650-80954d2960c7
			dataCategory: Uncategorized

		measure 'Temps total annulations non excusées (en heures)' = EXTERNALMEASURE("Temps total annulations non excusées (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Temps totaux en heures
			lineageTag: 19884414-9548-48a1-aeb5-1bf4869cd7cd
			sourceLineageTag: f93df58e-cd2c-4de9-b9a9-4edbff9727ec
			dataCategory: Uncategorized

		measure 'Temps total créneaux (en heures)' = EXTERNALMEASURE("Temps total créneaux (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Temps totaux en heures
			lineageTag: c63dd0ca-70ae-48d6-9d38-a02500e573b9
			sourceLineageTag: 9c12bc69-5cf1-48f3-8dfb-f10fb57e5776
			dataCategory: Uncategorized

		measure 'Temps total en zone (en heures)' = EXTERNALMEASURE("Temps total en zone (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Temps totaux en heures
			lineageTag: c07794c7-2d22-4d91-830b-2718d67d2443
			sourceLineageTag: 6bc9647a-90e8-459a-a0c1-02d875f2975d
			dataCategory: Uncategorized

		measure 'Temps total non exploité (en heures)' = EXTERNALMEASURE("Temps total non exploité (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Temps totaux en heures
			lineageTag: bda9e894-aba3-4669-bec9-7a763b31c5b2
			sourceLineageTag: 3ad49e99-501b-4f98-a0b1-a8dfbd408c06
			dataCategory: Uncategorized

		measure 'Temps total RDV déplacé (en heures)' = EXTERNALMEASURE("Temps total RDV déplacé (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Temps totaux en heures
			lineageTag: a0c5f104-aa33-450a-a44e-7b9f75d719b1
			sourceLineageTag: dc099a0e-342c-4326-8a40-e66c0d178bda
			dataCategory: Uncategorized

		measure 'Temps total temps connexes (en heures)' = EXTERNALMEASURE("Temps total temps connexes (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Temps totaux en heures
			lineageTag: 3d6132e1-997d-4715-bec5-e0caa92a7506
			sourceLineageTag: 3b5f3d98-205d-45f0-aef4-d57c1f7d8140
			dataCategory: Uncategorized

		measure 'Temps total vacation (en heures)' = EXTERNALMEASURE("Temps total vacation (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Temps totaux en heures
			lineageTag: 61cdd884-01b8-4f40-b5d4-1dadafba0306
			sourceLineageTag: 7e4b3eb4-9926-4c65-983b-419e8ca48aa6
			dataCategory: Uncategorized

		measure 'Temps total visites réalisées (en heures)' = EXTERNALMEASURE("Temps total visites réalisées (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Temps totaux en heures
			lineageTag: ce5c4388-97cc-45f2-802e-523ccc541def
			sourceLineageTag: 8419f6c8-c69e-4dd5-a464-fa4050e5a632
			dataCategory: Uncategorized

		measure 'Temps total zone d''activité non clinique (en heures)' = EXTERNALMEASURE("Temps total zone d'activité non clinique (en heures)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\Temps totaux en heures
			lineageTag: 240834fd-7925-45a1-87da-228b1250251f
			sourceLineageTag: 71983a54-53a4-4f7b-ae0e-8a1a0eac781b
			dataCategory: Uncategorized

	ref table 'Utilisateurs et équipes médicales'

		measure 'ETP pondéré par équipe médicale' = EXTERNALMEASURE("ETP pondéré par équipe médicale", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00
			displayFolder: Indicateurs
			lineageTag: 8cd43011-acd6-447e-84ba-d13e95c3fee2
			sourceLineageTag: 81882f51-e019-4886-89c2-db41fe779902
			dataCategory: Uncategorized

		measure 'ETP total par utilisateur' = EXTERNALMEASURE("ETP total par utilisateur", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.00
			displayFolder: Indicateurs
			lineageTag: 2a034d2f-dd9b-402f-922b-5f284a327710
			sourceLineageTag: 516f746b-6e0e-480d-9121-aaa09f4d3418
			dataCategory: Uncategorized

		measure 'Nombre d''équipes médicales concernées' = EXTERNALMEASURE("Nombre d'équipes médicales concernées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: 42cb7e71-0b15-49aa-9ac7-56ca6928fcad
			sourceLineageTag: b0451683-b315-4437-a195-84b6f4db214f
			dataCategory: Uncategorized

		measure 'Nombre d''utilisateurs concernés' = EXTERNALMEASURE("Nombre d'utilisateurs concernés", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs
			lineageTag: e2ab59ec-eca2-42ea-bb63-82122a8e1143
			sourceLineageTag: a4794262-9b59-4da1-99d8-5e4e758cfd21
			dataCategory: Uncategorized

	ref table Visite

		measure '# Réponses moyen par questionnaire' = EXTERNALMEASURE("# Réponses moyen par questionnaire", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			displayFolder: Indicateurs\2. Questionnaires\Comptages
			lineageTag: 81ec5079-33d1-411a-b0ce-875b2d331838
			sourceLineageTag: 3e477ff2-806f-4dd4-a899-7554141cb97b
			dataCategory: Uncategorized

		measure '1er quartile durée après transfert (en minutes)' = EXTERNALMEASURE("1er quartile durée après transfert (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\03. Durée après transfert
			lineageTag: 507977ed-c257-41fb-895a-a2e00939c7b6
			sourceLineageTag: e066072e-fc2d-407a-beab-7ae35b415e21
			dataCategory: Uncategorized

		measure '1er quartile durée attente avant tablette (en minutes)' = EXTERNALMEASURE("1er quartile durée attente avant tablette (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\01. Durée attente avant tablette
			lineageTag: 55fbb1af-7d76-4fa1-b4af-394e6ae20fdf
			sourceLineageTag: f1f49ca3-2a29-4f36-9591-4a1265fd9557
			dataCategory: Uncategorized

		measure '1er quartile durée attente visio' = EXTERNALMEASURE("1er quartile durée attente visio", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\5. Visio\Salle d'attente visio
			lineageTag: 55ffb953-5b31-4109-b2ca-ad8c5ea9dd04
			sourceLineageTag: a33e3b65-7f14-4580-b6c2-b17df026678b
			dataCategory: Uncategorized

		measure '1er quartile durée entretien visio' = EXTERNALMEASURE("1er quartile durée entretien visio", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\5. Visio\Entretien visio
			lineageTag: 6b0ee055-b35c-48f3-87fe-8c842dea69dc
			sourceLineageTag: 264f6cce-e724-4d87-8419-f49085d865ee
			dataCategory: Uncategorized

		measure '1er quartile durée pré visite théorique (en minutes)' = EXTERNALMEASURE("1er quartile durée pré visite théorique (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\05. Durée pré visite théorique
			lineageTag: 1b115743-35d2-4cab-9831-ce3d5a6e0f88
			sourceLineageTag: a552d48d-b208-486a-9a63-a227c975c689
			dataCategory: Uncategorized

		measure '1er quartile durée présence salarié (en minutes)' = EXTERNALMEASURE("1er quartile durée présence salarié (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\04. Durée présence salarié
			lineageTag: f0e1b885-1d35-4d84-b9d3-442374c79e60
			sourceLineageTag: 7bf4652b-03cf-4e7d-8c0e-aa1d48db19c7
			dataCategory: Uncategorized

		measure '1er quartile durée questionnaire' = EXTERNALMEASURE("1er quartile durée questionnaire", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\07. Durée questionnaire
			lineageTag: 69f35af2-990e-4f2e-8abf-085fad164cc3
			sourceLineageTag: 5a94fcb4-75f9-49b3-8012-2d28c63afcd1
			dataCategory: Uncategorized

		measure '1er quartile durée sur tablette (en minutes)' = EXTERNALMEASURE("1er quartile durée sur tablette (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\02. Durée sur tablette
			lineageTag: 938cc5e4-a372-49a1-ba30-737a03ef1514
			sourceLineageTag: d60c69ba-edad-4fd9-ae82-4bf717493fda
			dataCategory: Uncategorized

		measure '1er quartile durée test audio' = EXTERNALMEASURE("1er quartile durée test audio", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\09. Durée test audio
			lineageTag: c2a89bf9-2d26-4195-8dd0-c89d9285a152
			sourceLineageTag: 76844fe2-a5ce-45a7-8738-bbc801817c64
			dataCategory: Uncategorized

		measure '1er quartile durée test couleur ishihara' = EXTERNALMEASURE("1er quartile durée test couleur ishihara", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\11. Durée test couleur ishihara
			lineageTag: 1ce2c8d8-332d-409c-b483-fc206eda7c90
			sourceLineageTag: f2fe06a7-3ed9-408b-b280-43ecced6c6f1
			dataCategory: Uncategorized

		measure '1er quartile durée test imc' = EXTERNALMEASURE("1er quartile durée test imc", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\08. Durée test imc
			lineageTag: fb175b35-41b7-42a6-8d96-52dff9d487b6
			sourceLineageTag: c084d51d-f5b5-4a26-a51d-63f13545d57f
			dataCategory: Uncategorized

		measure '1er quartile durée test pression sanguine' = EXTERNALMEASURE("1er quartile durée test pression sanguine", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\10. Durée test pression sanguine
			lineageTag: 1cb15d37-180a-40bd-a9ea-a94b35845f8d
			sourceLineageTag: 4eeab68f-4f01-422c-afad-ca99c9e3cb30
			dataCategory: Uncategorized

		measure '1er quartile durée test vision astigmate' = EXTERNALMEASURE("1er quartile durée test vision astigmate", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\12. Durée test vision astigmate
			lineageTag: f4a8a7e7-6d26-49eb-8e30-98b03a48f66e
			sourceLineageTag: dd48bdb5-e3be-4cc5-aad1-ade76dce1f55
			dataCategory: Uncategorized

		measure '1er quartile durée test vision de loin' = EXTERNALMEASURE("1er quartile durée test vision de loin", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\14. Durée test vision de loin
			lineageTag: 01dd9b4e-0d35-422b-84cd-e8f191332c20
			sourceLineageTag: 2a0ddb74-5d60-443e-a520-1e949450b570
			dataCategory: Uncategorized

		measure '1er quartile durée test vision de près' = EXTERNALMEASURE("1er quartile durée test vision de près", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\13. Durée test vision de près
			lineageTag: 014cfd6a-6484-4d24-96ec-4ff44c4fe631
			sourceLineageTag: c789ca20-79aa-4afd-b183-93bbeabeef84
			dataCategory: Uncategorized

		measure '1er quartile durée visite théorique (en minutes)' = EXTERNALMEASURE("1er quartile durée visite théorique (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\06. Durée visite théorique
			lineageTag: b28aa5a5-fdf2-41d1-aff6-170c7a9976ae
			sourceLineageTag: ff31503d-c0b0-4b70-b284-d5fbaed9adaf
			dataCategory: Uncategorized

		measure '3ème quartile durée après transfert(en minutes)' = EXTERNALMEASURE("3ème quartile durée après transfert(en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\03. Durée après transfert
			lineageTag: 4486ddee-bb1d-4b6f-b3e2-e9d59a5ee9ca
			sourceLineageTag: a2e83483-b38d-4b64-a550-93ade8b7881e
			dataCategory: Uncategorized

		measure '3ème quartile durée attente avant tablette (en minutes)' = EXTERNALMEASURE("3ème quartile durée attente avant tablette (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\01. Durée attente avant tablette
			lineageTag: f549df05-8e17-4632-a2c6-b4b76d47d9b9
			sourceLineageTag: 1099a935-450c-43ab-810e-32079a3641e1
			dataCategory: Uncategorized

		measure '3ème quartile durée attente visio' = EXTERNALMEASURE("3ème quartile durée attente visio", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\5. Visio\Salle d'attente visio
			lineageTag: 4562e3dd-749f-4ff4-a168-6f2e6d8a6d2c
			sourceLineageTag: c21b4d19-959f-4e93-9765-95b10c32eb52
			dataCategory: Uncategorized

		measure '3ème quartile durée entretien visio' = EXTERNALMEASURE("3ème quartile durée entretien visio", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\5. Visio\Entretien visio
			lineageTag: 79d0d9f3-2625-440b-8080-62cf38c03bb9
			sourceLineageTag: 8568c7dd-034d-44d5-9add-da87cdc15161
			dataCategory: Uncategorized

		measure '3ème quartile durée pré visite théorique (en minutes)' = EXTERNALMEASURE("3ème quartile durée pré visite théorique (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\05. Durée pré visite théorique
			lineageTag: 8bce31f4-e729-4414-bc2a-3197fbfba6f8
			sourceLineageTag: 0b1baca6-3ad5-428a-a6c5-add5901d619a
			dataCategory: Uncategorized

		measure '3ème quartile durée présence salarié (en minutes)' = EXTERNALMEASURE("3ème quartile durée présence salarié (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\04. Durée présence salarié
			lineageTag: 07a58ae9-7492-4502-8367-1441d1d98b0e
			sourceLineageTag: ae21646f-34f9-4da5-81ab-85ead878d0a1
			dataCategory: Uncategorized

		measure '3ème quartile durée questionnaire' = EXTERNALMEASURE("3ème quartile durée questionnaire", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\07. Durée questionnaire
			lineageTag: 5401e59d-77c0-4fdd-9ec9-f7c809f45311
			sourceLineageTag: 8951c1f9-f0bc-454e-adbd-f8c93254cc1e
			dataCategory: Uncategorized

		measure '3ème quartile durée sur tablette (en minutes)' = EXTERNALMEASURE("3ème quartile durée sur tablette (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\02. Durée sur tablette
			lineageTag: e10a308f-97f8-4a73-b1f2-8e1b89c03bc5
			sourceLineageTag: 88311fcf-280c-43bc-9c8b-4d0fcff86199
			dataCategory: Uncategorized

		measure '3ème quartile durée test audio' = EXTERNALMEASURE("3ème quartile durée test audio", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\09. Durée test audio
			lineageTag: 1c2e5411-66bb-400d-be73-84bee6b3724f
			sourceLineageTag: 1bec6f9f-1a6f-4bba-9eb2-cbbd83f8377a
			dataCategory: Uncategorized

		measure '3ème quartile durée test couleur ishihara' = EXTERNALMEASURE("3ème quartile durée test couleur ishihara", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\11. Durée test couleur ishihara
			lineageTag: 782cd9f4-6b73-4c3a-960e-ee1186e88d70
			sourceLineageTag: 3c91d027-32d7-4065-8400-28e05d0b2111
			dataCategory: Uncategorized

		measure '3ème quartile durée test imc' = EXTERNALMEASURE("3ème quartile durée test imc", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\08. Durée test imc
			lineageTag: 2cadaf0f-28d5-480a-b1a1-095239d4c69d
			sourceLineageTag: 85d87ee7-03fe-4cd4-af16-cbf6a751b7fa
			dataCategory: Uncategorized

		measure '3ème quartile durée test pression sanguine' = EXTERNALMEASURE("3ème quartile durée test pression sanguine", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\10. Durée test pression sanguine
			lineageTag: 3a5c5632-29d9-40fc-afc3-d701121dc897
			sourceLineageTag: eb61c52d-e88a-430c-ab5a-9591c7c0ec25
			dataCategory: Uncategorized

		measure '3ème quartile durée test vision astigmate' = EXTERNALMEASURE("3ème quartile durée test vision astigmate", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\12. Durée test vision astigmate
			lineageTag: eea6b215-c259-440f-b426-181bff0df0ea
			sourceLineageTag: c0b4788e-7799-4c3d-8872-6b2be42d4353
			dataCategory: Uncategorized

		measure '3ème quartile durée test vision de loin' = EXTERNALMEASURE("3ème quartile durée test vision de loin", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\14. Durée test vision de loin
			lineageTag: 5597bcc8-c23a-4d1f-bd56-f7a7c33eeb3d
			sourceLineageTag: 2c59744f-3081-415c-95ca-ba85164c6e0a
			dataCategory: Uncategorized

		measure '3ème quartile durée test vision de près' = EXTERNALMEASURE("3ème quartile durée test vision de près", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\13. Durée test vision de près
			lineageTag: d8bc7627-c1dd-48e9-b65c-477c43180850
			sourceLineageTag: e10d7e3b-3f09-4d6b-9c88-08bbc1d29623
			dataCategory: Uncategorized

		measure '3ème quartile durée visite théorique (en minutes)' = EXTERNALMEASURE("3ème quartile durée visite théorique (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\06. Durée visite théorique
			lineageTag: bdd9ca10-0bbf-4807-9e48-04585a5af76a
			sourceLineageTag: 385e4969-af8f-4f4b-8a22-46e4f66258ef
			dataCategory: Uncategorized

		measure 'Délai moyen de planification des visites d''embauche (en jours)' = EXTERNALMEASURE("Délai moyen de planification des visites d'embauche (en jours)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0
			displayFolder: Indicateurs\3. Parcours salarié
			lineageTag: 14976c73-3d79-4d3c-a547-20a904641884
			sourceLineageTag: ae35b42c-314f-4128-b2a6-c5f185b65862
			dataCategory: Uncategorized

		measure 'Durée moyenne après transfert (en minutes)' = EXTERNALMEASURE("Durée moyenne après transfert (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\03. Durée après transfert
			lineageTag: 47a96d24-76a0-4d8a-ad8e-c73b0684a790
			sourceLineageTag: 967fce3a-a416-4bc3-b8cb-a1f75b22f873
			dataCategory: Uncategorized

		measure 'Durée moyenne archivage (en jours)' = EXTERNALMEASURE("Durée moyenne archivage (en jours)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié
			lineageTag: 30af866c-0c3c-4378-a7a5-94c2b1c347be
			sourceLineageTag: 1a1ff416-ae82-4710-b77e-8443e9cf04be
			dataCategory: Uncategorized

		measure 'Durée moyenne attente avant tablette (en minutes)' = EXTERNALMEASURE("Durée moyenne attente avant tablette (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\01. Durée attente avant tablette
			lineageTag: e57334ef-b895-4986-a40a-84e6d6f101dd
			sourceLineageTag: d3e69010-5c86-4d68-bb3e-06e63a016cbe
			dataCategory: Uncategorized

		measure 'Durée moyenne attente visio' = EXTERNALMEASURE("Durée moyenne attente visio", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\5. Visio\Salle d'attente visio
			lineageTag: 1610fbed-d7e4-4454-ba34-e7e6a283ec04
			sourceLineageTag: 10bc8299-c1e9-45fd-be1f-1ccf94a2149c
			dataCategory: Uncategorized

		measure 'Durée moyenne avant transfert vers salle d''attente (en minutes)' = EXTERNALMEASURE("Durée moyenne avant transfert vers salle d'attente (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié
			lineageTag: 47e328a3-f70f-45b5-815e-7de92e096119
			sourceLineageTag: a81bc008-b6d9-4477-9c07-9fd82f4e2246
			dataCategory: Uncategorized

		measure 'Durée moyenne entretien visio' = EXTERNALMEASURE("Durée moyenne entretien visio", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\5. Visio\Entretien visio
			lineageTag: 6483ef74-a07d-43c6-8115-a45422f7b945
			sourceLineageTag: 685b6358-bbf4-43c0-b7e5-1153a6af75df
			dataCategory: Uncategorized

		measure 'Durée moyenne pré visite théorique (en minutes)' = EXTERNALMEASURE("Durée moyenne pré visite théorique (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\05. Durée pré visite théorique
			lineageTag: f13ef62c-5a41-42a5-a15d-4f41677f22e9
			sourceLineageTag: 5f863655-8a63-4f1f-8e88-4677671ff0c9
			dataCategory: Uncategorized

		measure 'Durée moyenne présence salarié (en minutes)' = EXTERNALMEASURE("Durée moyenne présence salarié (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\04. Durée présence salarié
			lineageTag: 81e1d689-6e76-413c-aec7-af69aa8d416b
			sourceLineageTag: 36bfebab-d2c0-4809-adce-d09e07fbe48c
			dataCategory: Uncategorized

		measure 'Durée moyenne questionnaire' = EXTERNALMEASURE("Durée moyenne questionnaire", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\07. Durée questionnaire
			lineageTag: f4bf1ade-6b6b-4da1-87cb-1f178be3d560
			sourceLineageTag: d3faf561-cf9a-4481-b51e-8afdfe25248e
			dataCategory: Uncategorized

		measure 'Durée moyenne session Tytocare' = EXTERNALMEASURE("Durée moyenne session Tytocare", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\6. Tytocare
			lineageTag: ead28154-4987-4822-a491-fa2130293f48
			sourceLineageTag: 1f027f37-adfc-4fd9-a2d6-308fe7d004df
			dataCategory: Uncategorized

		measure 'Durée moyenne sur tablette (en minutes)' = EXTERNALMEASURE("Durée moyenne sur tablette (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\02. Durée sur tablette
			lineageTag: 952ab116-d364-4b7a-9ddd-399eeea00d37
			sourceLineageTag: 06612c10-2669-4cf5-b5eb-63e10c02899f
			dataCategory: Uncategorized

		measure 'Durée moyenne test audio' = EXTERNALMEASURE("Durée moyenne test audio", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\09. Durée test audio
			lineageTag: d1552a7c-8c20-4e07-a224-2cac93961062
			sourceLineageTag: 398f2c24-50cf-42a9-ac1e-840db2b366b5
			dataCategory: Uncategorized

		measure 'Durée moyenne test couleur ishihara' = EXTERNALMEASURE("Durée moyenne test couleur ishihara", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\11. Durée test couleur ishihara
			lineageTag: 00f984c6-fe15-4837-be12-d605725ddd92
			sourceLineageTag: 5d6b6e7d-fca3-4a82-9172-fdcf94f09659
			dataCategory: Uncategorized

		measure 'Durée moyenne test imc' = EXTERNALMEASURE("Durée moyenne test imc", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\08. Durée test imc
			lineageTag: 9cbe06fa-a8cb-4ce5-8487-e8b742f66a0b
			sourceLineageTag: 4c3c0ee5-fab1-4403-b478-47ef83ffd512
			dataCategory: Uncategorized

		measure 'Durée moyenne test pression sanguine' = EXTERNALMEASURE("Durée moyenne test pression sanguine", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\10. Durée test pression sanguine
			lineageTag: d613f542-c427-421a-a266-7ba1ad831179
			sourceLineageTag: 2faf9fb8-1d3a-4aa2-878c-1f1acd3614eb
			dataCategory: Uncategorized

		measure 'Durée moyenne test vision astigmate' = EXTERNALMEASURE("Durée moyenne test vision astigmate", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\12. Durée test vision astigmate
			lineageTag: 9fb41973-fcee-44da-86f4-facbe060ad4d
			sourceLineageTag: 21e45d96-e623-4f55-876b-0d7b9b4c6cb6
			dataCategory: Uncategorized

		measure 'Durée moyenne test vision de loin' = EXTERNALMEASURE("Durée moyenne test vision de loin", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\14. Durée test vision de loin
			lineageTag: 84ae6c53-f082-4f50-a7de-c8170dbfb7bd
			sourceLineageTag: ba251886-f353-4708-a1eb-9ffa411085fd
			dataCategory: Uncategorized

		measure 'Durée moyenne test vision de près' = EXTERNALMEASURE("Durée moyenne test vision de près", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\13. Durée test vision de près
			lineageTag: 94798fe7-515e-4a07-8ce3-a5ac3e5aafc2
			sourceLineageTag: 1313b35d-693b-4af5-9787-e3be2397d336
			dataCategory: Uncategorized

		measure 'Durée moyenne visite théorique (en minutes)' = EXTERNALMEASURE("Durée moyenne visite théorique (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\06. Durée visite théorique
			lineageTag: 52d79082-d30e-4472-81ff-9c185203c602
			sourceLineageTag: 711bedb8-fea2-4254-891d-6d07720cecc6
			dataCategory: Uncategorized

		measure 'Médiane durée après transfert (en minutes)' = EXTERNALMEASURE("Médiane durée après transfert (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\03. Durée après transfert
			lineageTag: 7ae0b79a-9dd1-4b8a-8f3c-7099e1a74d4d
			sourceLineageTag: 0d73e046-2a31-45f7-8625-a6dfc4da6efa
			dataCategory: Uncategorized

		measure 'Médiane durée attente avant tablette (en minutes)' = EXTERNALMEASURE("Médiane durée attente avant tablette (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\01. Durée attente avant tablette
			lineageTag: 6776645a-8631-40b5-bf88-b8149581fcfc
			sourceLineageTag: 4774653f-dc27-4f55-8918-a8327d26654e
			dataCategory: Uncategorized

		measure 'Médiane durée attente visio' = EXTERNALMEASURE("Médiane durée attente visio", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\5. Visio\Salle d'attente visio
			lineageTag: 04806ee9-1b8b-435a-b712-52e461d8f5ec
			sourceLineageTag: 45304a57-5de6-48ac-8862-0a6dfd87beac
			dataCategory: Uncategorized

		measure 'Médiane durée entretien visio' = EXTERNALMEASURE("Médiane durée entretien visio", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\5. Visio\Entretien visio
			lineageTag: c28b2f74-21d7-45f8-bb43-122003cc0080
			sourceLineageTag: a91a7d02-3d14-4100-924b-a8432593b809
			dataCategory: Uncategorized

		measure 'Médiane durée pré visite théorique (en minutes)' = EXTERNALMEASURE("Médiane durée pré visite théorique (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\05. Durée pré visite théorique
			lineageTag: aec9065c-a54e-42e0-a395-7ef21ffe674e
			sourceLineageTag: df0d1947-3bcc-4b61-9a93-da58aa4df703
			dataCategory: Uncategorized

		measure 'Médiane durée présence salarié (en minutes)' = EXTERNALMEASURE("Médiane durée présence salarié (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\04. Durée présence salarié
			lineageTag: 818017b9-d263-4977-b977-736f77b9af58
			sourceLineageTag: 4664e018-6f5e-4fb1-9fdb-f4279a9590df
			dataCategory: Uncategorized

		measure 'Médiane durée questionnaire' = EXTERNALMEASURE("Médiane durée questionnaire", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\07. Durée questionnaire
			lineageTag: a8114442-73b0-4795-903b-6d87907e7109
			sourceLineageTag: 314d9049-ce8b-4f8b-b074-366ad2209528
			dataCategory: Uncategorized

		measure 'Médiane durée sur tablette (en minutes)' = EXTERNALMEASURE("Médiane durée sur tablette (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\02. Durée sur tablette
			lineageTag: c5dcd108-deeb-4803-9610-474296d1de89
			sourceLineageTag: 7acab4aa-9a6a-4b09-b196-e8d8db053192
			dataCategory: Uncategorized

		measure 'Médiane durée test audio' = EXTERNALMEASURE("Médiane durée test audio", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\09. Durée test audio
			lineageTag: e9554cad-987e-4469-b501-6dd7d1ee4826
			sourceLineageTag: 1d435c3c-9021-405a-8084-0f21142232e3
			dataCategory: Uncategorized

		measure 'Médiane durée test couleur ishihara' = EXTERNALMEASURE("Médiane durée test couleur ishihara", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\11. Durée test couleur ishihara
			lineageTag: 25c94538-31a5-4b51-bb1f-312ad5650575
			sourceLineageTag: 3ab2c1c4-a6aa-49ce-98d4-d2d3fb72cc13
			dataCategory: Uncategorized

		measure 'Médiane durée test imc' = EXTERNALMEASURE("Médiane durée test imc", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\08. Durée test imc
			lineageTag: 214d6074-d00f-448d-87d6-2d2bb7b949ea
			sourceLineageTag: 4f82b7df-0e00-4a2c-b4bf-268eca439f1b
			dataCategory: Uncategorized

		measure 'Médiane durée test pression sanguine' = EXTERNALMEASURE("Médiane durée test pression sanguine", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\10. Durée test pression sanguine
			lineageTag: 5f9959f7-b753-401a-a928-8d9bf3df4f63
			sourceLineageTag: 22f08f6a-2324-4bae-90bf-af93ae4c0329
			dataCategory: Uncategorized

		measure 'Médiane durée test vision astigmate' = EXTERNALMEASURE("Médiane durée test vision astigmate", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\12. Durée test vision astigmate
			lineageTag: 771d0c04-0aff-4a12-a74b-475c6ac66132
			sourceLineageTag: 1f4cea8a-461b-484b-b9cc-f3f4deaf55fc
			dataCategory: Uncategorized

		measure 'Médiane durée test vision de loin' = EXTERNALMEASURE("Médiane durée test vision de loin", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\14. Durée test vision de loin
			lineageTag: d3488458-e0be-4d10-b626-fab86c620ed2
			sourceLineageTag: ea4cd0a2-4357-4f6d-9326-e85220bceb3d
			dataCategory: Uncategorized

		measure 'Médiane durée test vision de près' = EXTERNALMEASURE("Médiane durée test vision de près", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\13. Durée test vision de près
			lineageTag: 16f4fc84-a2e2-4173-bb11-a74bd882b3b5
			sourceLineageTag: 7629085a-a79a-42f8-a328-df6c82aa2f58
			dataCategory: Uncategorized

		measure 'Médiane durée visite théorique (en minutes)' = EXTERNALMEASURE("Médiane durée visite théorique (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié\06. Durée visite théorique
			lineageTag: 4cbc7584-80c1-46b2-84a2-ce67a73c94fb
			sourceLineageTag: 7c09baa0-c0f8-4c2d-8f9c-0197116d41f4
			dataCategory: Uncategorized

		measure 'Nombre de connexions à l''espace salarié après visite' = EXTERNALMEASURE("Nombre de connexions à l'espace salarié après visite", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1. Général\Comptages
			lineageTag: d2eef763-b7c7-4137-abbb-d69a17b947e1
			sourceLineageTag: ea07694a-51ca-43aa-92bb-31ac441242e0
			dataCategory: Uncategorized

		measure 'Nombre de connexions à la tablette' = EXTERNALMEASURE("Nombre de connexions à la tablette", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1. Général\Comptages
			lineageTag: d0cdb20f-7e75-460c-8e28-5f18919836bd
			sourceLineageTag: 2218fbd5-5594-47a8-b6e7-aeb930a9d1ef
			dataCategory: Uncategorized

		measure 'Nombre de questionnaires remplis' = EXTERNALMEASURE("Nombre de questionnaires remplis", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2. Questionnaires\Comptages
			lineageTag: f94aea40-1e29-43b2-8c14-22ef24b73098
			sourceLineageTag: 5f06c71c-a15d-440a-b8b8-8a7b9360d5d3
			dataCategory: Uncategorized

		measure 'Nombre de questionnaires remplis sur l''espace salarié' = EXTERNALMEASURE("Nombre de questionnaires remplis sur l'espace salarié", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2. Questionnaires\Comptages
			lineageTag: 2bbfc288-28ae-4651-a164-00a12e2bca74
			sourceLineageTag: 400d2ea3-9a89-4a9b-978d-ea1a83266eb3
			dataCategory: Uncategorized

		measure 'Nombre de questionnaires remplis sur tablette' = EXTERNALMEASURE("Nombre de questionnaires remplis sur tablette", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\2. Questionnaires\Comptages
			lineageTag: 62a1fbb5-ce1d-4fa3-8d31-3f89d552d18c
			sourceLineageTag: 19021a86-967a-4cd7-a1af-fd77102d82fc
			dataCategory: Uncategorized

		measure 'Nombre de sessions Tytocare' = EXTERNALMEASURE("Nombre de sessions Tytocare", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\6. Tytocare
			lineageTag: 397d9556-4497-473c-85ef-48d1ea9bb7b1
			sourceLineageTag: 0e6bd451-1e14-4d62-aeb6-73be8ca7fb48
			dataCategory: Uncategorized

		measure 'Nombre de visites' = EXTERNALMEASURE("Nombre de visites", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1. Général\Comptages
			lineageTag: bdf3b2d7-7b56-42c8-899e-92c1e34bf06b
			sourceLineageTag: fd499a0d-bcf5-41d4-986b-a8a5d5465a28
			dataCategory: Uncategorized

		measure 'Nombre de visites avec certification de la liste réduite des expositions' = EXTERNALMEASURE("Nombre de visites avec certification de la liste réduite des expositions", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1. Général\Comptages
			lineageTag: 9d460c25-7a4e-49bb-b08f-513333583ff0
			sourceLineageTag: c00de534-f195-4d99-a79f-0f5f84f0c501
			dataCategory: Uncategorized

		measure 'Nombre de visites avec revue' = EXTERNALMEASURE("Nombre de visites avec revue", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1. Général\Comptages
			lineageTag: cc844fbe-95d1-4a79-80c7-248528b29c95
			sourceLineageTag: 755ca011-57d6-41f7-a59b-acfd80ed97f6
			dataCategory: Uncategorized

		measure 'Nombre de visites comptant comme mi-carrière' = EXTERNALMEASURE("Nombre de visites comptant comme mi-carrière", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1. Général\Comptages
			lineageTag: 19dc8824-d6e3-495b-979b-4f5b55858684
			sourceLineageTag: 17b54448-9556-44b6-b84a-6474eda169a1
			dataCategory: Uncategorized

		measure 'Nombre de visites comptant comme périodique' = EXTERNALMEASURE("Nombre de visites comptant comme périodique", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1. Général\Comptages
			lineageTag: d0df8274-f8f1-40e5-8a23-c2ccc96ae82b
			sourceLineageTag: 7239d289-e1c0-4a7e-8b94-92919022dd7e
			dataCategory: Uncategorized

		measure 'Nombre de visites en visio' = EXTERNALMEASURE("Nombre de visites en visio", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\1. Général\Comptages
			lineageTag: 9a927caa-1364-40f4-8eaf-ff53fd3d77fd
			sourceLineageTag: 651a5ad1-6f22-4d42-afd4-e82075048aea
			dataCategory: Uncategorized

		measure 'Nombre moyen de plaquettes distribuées par visite' = EXTERNALMEASURE("Nombre moyen de plaquettes distribuées par visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: 0.0
			displayFolder: Indicateurs\4. Plaquettes
			lineageTag: 3f9d3b95-0b15-4f1e-a625-c5386d98e366
			sourceLineageTag: 31ac3350-6bc6-4dd9-b782-6cfab30b31ad
			dataCategory: Uncategorized

		measure 'Nombre total de plaquettes distribuées' = EXTERNALMEASURE("Nombre total de plaquettes distribuées", INTEGER, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\4. Plaquettes
			lineageTag: 98051043-0d28-46e6-9d92-8d3e36cd5a59
			sourceLineageTag: 4e4fb0c0-e75c-4d2d-a05f-0dc09e678003
			dataCategory: Uncategorized

		measure 'Retard moyen avant entretien' = EXTERNALMEASURE("Retard moyen avant entretien", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié
			lineageTag: 77940edd-9a95-4a83-a3f2-70845218275d
			sourceLineageTag: 6f1eb024-085b-4eef-9cdf-6f5a825479da
			dataCategory: Uncategorized

		measure 'Retard moyen salarié (en minutes)' = EXTERNALMEASURE("Retard moyen salarié (en minutes)", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #,##0
			displayFolder: Indicateurs\3. Parcours salarié
			lineageTag: 281e7d00-e389-412b-b2e3-42b5a4f9a970
			sourceLineageTag: 27807992-e928-40a1-b7c1-309d1cdd63e6
			dataCategory: Uncategorized

		measure 'Taux de connexion à l''espace salarié après visite' = EXTERNALMEASURE("Taux de connexion à l'espace salarié après visite", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\1. Général\Taux
			lineageTag: 1097bfac-f8c1-497a-9f30-a2593cb59437
			sourceLineageTag: 03d088b9-758b-4c9f-acd6-17e9f5e2c02a
			dataCategory: Uncategorized

		measure 'Taux de questionnaires remplis sur l''espace salarié' = EXTERNALMEASURE("Taux de questionnaires remplis sur l'espace salarié", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\2. Questionnaires\Taux
			lineageTag: 475b8a87-5391-4fbe-ba74-a884905e6050
			sourceLineageTag: e017ecb9-9da7-4701-beaf-c194e33dafa9
			dataCategory: Uncategorized

		measure 'Taux de questionnaires remplis sur tablette' = EXTERNALMEASURE("Taux de questionnaires remplis sur tablette", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\2. Questionnaires\Taux
			lineageTag: b6e46161-a3f2-4d42-a8d9-07d507dffad6
			sourceLineageTag: 3b7340e2-8635-425c-b789-3d0d666aa905
			dataCategory: Uncategorized

		measure 'Taux de visites avec connexion à la tablette' = EXTERNALMEASURE("Taux de visites avec connexion à la tablette", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\1. Général\Taux
			lineageTag: 20ec0711-0fed-4c3d-9727-fa7f44eac766
			sourceLineageTag: 812c176b-1705-40a7-87ae-21363e5299ee
			dataCategory: Uncategorized

		measure 'Taux de visites avec questionnaire rempli' = EXTERNALMEASURE("Taux de visites avec questionnaire rempli", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\2. Questionnaires\Taux
			lineageTag: 82722441-9e55-40a5-99e4-2b5ea15a4c25
			sourceLineageTag: ab488a39-492b-4ffc-97b7-5082f4ac8fc0
			dataCategory: Uncategorized

		measure 'Taux de visites avec revue' = EXTERNALMEASURE("Taux de visites avec revue", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\1. Général\Taux
			lineageTag: 307125ee-758d-4eff-bc70-34ff76609327
			sourceLineageTag: f7710214-5797-415c-8340-f86746a0e464
			dataCategory: Uncategorized

		measure 'Taux de visites en visio' = EXTERNALMEASURE("Taux de visites en visio", DOUBLE, "DirectQuery à AS – Rapport mensuel EPD")
			formatString: #0.0%
			displayFolder: Indicateurs\1. Général\Taux
			lineageTag: e7dcdde8-9992-4ec6-a789-a678f01e2fa5
			sourceLineageTag: 2f04812d-5086-4e33-bc6c-c492c93b1fb4
			dataCategory: Uncategorized

