createOrReplace

	table 'AMT v2'
		lineageTag: 900c7530-2c1b-442c-8a49-6f887d9f992a

		measure '# AMT annulées' = EXTERNALMEASURE("# AMT annulées", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 25a8efcc-2878-403d-a3d6-8201bbf1fa1e
			sourceLineageTag: DirectQuery à AS – pst38.# AMT annulées
			dataCategory: Uncategorized

		measure '# AMT en cours réalisables avec le module' = EXTERNALMEASURE("# AMT en cours réalisables avec le module", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 4 - Module FE
			lineageTag: b46b6571-89e4-4e5f-83b5-836263392d8f
			sourceLineageTag: DirectQuery à AS – pst38.# AMT en cours réalisables avec le module
			dataCategory: Uncategorized

		measure '# AMT en cours réalisées avec le module' = EXTERNALMEASURE("# AMT en cours réalisées avec le module", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 4 - Module FE
			lineageTag: 7c991008-8ee5-44fb-ae1d-bbea0b2bf6a1
			sourceLineageTag: DirectQuery à AS – pst38.# AMT en cours réalisées avec le module
			dataCategory: Uncategorized

		measure '# AMT en cours' = EXTERNALMEASURE("# AMT en cours", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 2482d727-df83-409f-9d24-9223e1ed3be7
			sourceLineageTag: DirectQuery à AS – pst38.# AMT en cours
			dataCategory: Uncategorized

		measure '# AMT par entreprise' = EXTERNALMEASURE("# AMT par entreprise", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: a3e28798-28bd-47fb-bec1-da1f1ba66bb7
			sourceLineageTag: DirectQuery à AS – pst38.# AMT par entreprise
			dataCategory: Uncategorized

		measure '# AMT suspendues' = EXTERNALMEASURE("# AMT suspendues", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: b9e8885b-6fe6-4221-a500-749360579d22
			sourceLineageTag: DirectQuery à AS – pst38.# AMT suspendues
			dataCategory: Uncategorized

		measure '# AMT terminées avec le module' = EXTERNALMEASURE("# AMT terminées avec le module", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 4 - Module FE
			lineageTag: 6c54e659-30fd-4cbb-9254-cdc1516e3494
			sourceLineageTag: DirectQuery à AS – pst38.# AMT terminées avec le module
			dataCategory: Uncategorized

		measure '# AMT terminées réalisables avec le module' = EXTERNALMEASURE("# AMT terminées réalisables avec le module", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 4 - Module FE
			lineageTag: e7f1d827-87c0-43d1-ad93-1954606233f0
			sourceLineageTag: DirectQuery à AS – pst38.# AMT terminées réalisables avec le module
			dataCategory: Uncategorized

		measure '# AMT terminées' = EXTERNALMEASURE("# AMT terminées", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 710de168-58bf-4c65-9e63-0cc7d575eeac
			sourceLineageTag: DirectQuery à AS – pst38.# AMT terminées
			dataCategory: Uncategorized

		measure '# AMT' = EXTERNALMEASURE("# AMT", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: cd96a770-628d-4446-a2d6-e2289b8c733b
			sourceLineageTag: DirectQuery à AS – pst38.# AMT
			dataCategory: Uncategorized

		measure '# autre type évènement' = EXTERNALMEASURE("# autre type évènement", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: 159a0ff4-388c-4bbe-b83a-b555c8ef16b8
			sourceLineageTag: DirectQuery à AS – pst38.# autre type évènement
			dataCategory: Uncategorized

		measure '# collections concernées (AMT)' = EXTERNALMEASURE("# collections concernées (AMT)", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: bad03d05-0d58-4634-9f64-beb94acdfa0e
			sourceLineageTag: DirectQuery à AS – pst38.# collections concernées (AMT)
			dataCategory: Uncategorized

		measure '# entreprises concernées (AMT)' = EXTERNALMEASURE("# entreprises concernées (AMT)", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: a5970e7d-789a-4df5-81ad-66ef9e36ac19
			sourceLineageTag: DirectQuery à AS – pst38.# entreprises concernées (AMT)
			dataCategory: Uncategorized

		measure '# évènement collectif (AMT)' = EXTERNALMEASURE("# évènement collectif (AMT)", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 0592e9f0-58d4-4a10-8fff-906c36c6e647
			sourceLineageTag: DirectQuery à AS – pst38.# évènement collectif (AMT)
			dataCategory: Uncategorized

		measure '# évènement collectif' = EXTERNALMEASURE("# évènement collectif", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: c77d88af-acb7-4bf0-8077-e2748e016133
			sourceLineageTag: DirectQuery à AS – pst38.# évènement collectif
			dataCategory: Uncategorized

		measure '# évènements total' = EXTERNALMEASURE("# évènements total", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: d827b8f7-c9be-46a5-83e7-9709f7bd7e85
			sourceLineageTag: DirectQuery à AS – pst38.# évènements total
			dataCategory: Uncategorized

		measure '# intervenants' = EXTERNALMEASURE("# intervenants", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 5c124487-962c-4b1e-816c-b57309829a8f
			sourceLineageTag: DirectQuery à AS – pst38.# intervenants
			dataCategory: Uncategorized

		measure '# intervention (AMT)' = EXTERNALMEASURE("# intervention (AMT)", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 9c6b7994-b670-42e1-8ac7-357b4033b7c5
			sourceLineageTag: DirectQuery à AS – pst38.# intervention (AMT)
			dataCategory: Uncategorized

		measure '# intervention' = EXTERNALMEASURE("# intervention", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: 0fcc0203-a3c0-476d-a58b-05d55412a2a8
			sourceLineageTag: DirectQuery à AS – pst38.# intervention
			dataCategory: Uncategorized

		measure '# rédaction' = EXTERNALMEASURE("# rédaction", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: 188ec613-1d11-4476-a204-c3c9676709d7
			sourceLineageTag: DirectQuery à AS – pst38.# rédaction
			dataCategory: Uncategorized

		measure '# salariés concernés (AMT périmètre salarié)' = EXTERNALMEASURE("# salariés concernés (AMT périmètre salarié)", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 70be3d70-b925-4b61-bc1e-f9cfd918e554
			sourceLineageTag: DirectQuery à AS – pst38.# salariés concernés (AMT périmètre salarié)
			dataCategory: Uncategorized

		measure '# salariés couverts' = EXTERNALMEASURE("# salariés couverts", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: fdd72c79-5ef7-4063-9cf5-2ae18ffd5a48
			sourceLineageTag: DirectQuery à AS – pst38.# salariés couverts
			dataCategory: Uncategorized

		measure '# tâches planifiées' = EXTERNALMEASURE("# tâches planifiées", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 34059198-ae66-41a8-8882-7efebe52d353
			sourceLineageTag: DirectQuery à AS – pst38.# tâches planifiées
			dataCategory: Uncategorized

		measure '# tâches réalisées' = EXTERNALMEASURE("# tâches réalisées", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: baa2edc9-8a03-4e46-93bc-28e36bd5d008
			sourceLineageTag: DirectQuery à AS – pst38.# tâches réalisées
			dataCategory: Uncategorized

		measure '% AMT en cours réalisées avec le module' = EXTERNALMEASURE("% AMT en cours réalisées avec le module", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0\ %
			displayFolder: 4 - Module FE
			lineageTag: 912b820d-166d-4ee8-a5cd-79401973dd30
			sourceLineageTag: DirectQuery à AS – pst38.% AMT en cours réalisées avec le module
			dataCategory: Uncategorized

		measure '% AMT terminées avec le module' = EXTERNALMEASURE("% AMT terminées avec le module", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0\ %
			displayFolder: 4 - Module FE
			lineageTag: 8b4bda01-551c-42da-becb-510f641886f7
			sourceLineageTag: DirectQuery à AS – pst38.% AMT terminées avec le module
			dataCategory: Uncategorized

		measure 'Durée autre type évènement (h)' = EXTERNALMEASURE("Durée autre type évènement (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: e616a208-c025-440f-bc11-f367f5ac4f8b
			sourceLineageTag: DirectQuery à AS – pst38.Durée autre type évènement (h)
			dataCategory: Uncategorized

		measure 'Durée estimée action (h)' = EXTERNALMEASURE("Durée estimée action (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			isHidden
			displayFolder: 3 - Durées réelles (fois intervenant)
			lineageTag: 8b6fa715-89ea-4214-92ac-b10480b1dd61
			sourceLineageTag: DirectQuery à AS – pst38.Durée estimée action (h)
			dataCategory: Uncategorized

		measure 'Durée estimée chez l''adhérent (h)' = EXTERNALMEASURE("Durée estimée chez l'adhérent (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			isHidden
			displayFolder: 3 - Durées réelles (fois intervenant)
			lineageTag: b0159899-0f12-458a-8638-1625661dd534
			sourceLineageTag: DirectQuery à AS – pst38.Durée estimée chez l'adhérent (h)
			dataCategory: Uncategorized

		measure 'Durée évènement collectif (AMT)' = EXTERNALMEASURE("Durée évènement collectif (AMT)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 1 - AMT
			lineageTag: fb25cf9a-b3b8-46f3-91a3-4a146934217a
			sourceLineageTag: DirectQuery à AS – pst38.Durée évènement collectif (AMT)
			dataCategory: Uncategorized

		measure 'Durée évènement collectif (h)' = EXTERNALMEASURE("Durée évènement collectif (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: 8493e6e4-00fd-48eb-a21a-2fbfc83ed644
			sourceLineageTag: DirectQuery à AS – pst38.Durée évènement collectif (h)
			dataCategory: Uncategorized

		measure 'Durée intervention (AMT)' = EXTERNALMEASURE("Durée intervention (AMT)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 1 - AMT
			lineageTag: 61b401dd-2122-4448-b5e1-e9885315c595
			sourceLineageTag: DirectQuery à AS – pst38.Durée intervention (AMT)
			dataCategory: Uncategorized

		measure 'Durée intervention (h)' = EXTERNALMEASURE("Durée intervention (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: 05072151-8c36-4167-8a59-f6fd64dc05fb
			sourceLineageTag: DirectQuery à AS – pst38.Durée intervention (h)
			dataCategory: Uncategorized

		measure 'Durée rédaction (h)' = EXTERNALMEASURE("Durée rédaction (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: e0ed290d-2bf9-4e57-b65a-4c1cccf543e6
			sourceLineageTag: DirectQuery à AS – pst38.Durée rédaction (h)
			dataCategory: Uncategorized

		measure 'Durée réelle intervention (h)' = EXTERNALMEASURE("Durée réelle intervention (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 3 - Durées réelles (fois intervenant)
			lineageTag: 43b8ec4e-e057-49ec-aeb7-a3c98f95e08b
			sourceLineageTag: DirectQuery à AS – pst38.Durée réelle intervention (h)
			dataCategory: Uncategorized

		measure 'Durée réelle rédaction (h)' = EXTERNALMEASURE("Durée réelle rédaction (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 3 - Durées réelles (fois intervenant)
			lineageTag: 51a74f33-3326-4888-974b-6b1fb7c1d0af
			sourceLineageTag: DirectQuery à AS – pst38.Durée réelle rédaction (h)
			dataCategory: Uncategorized

		measure 'Durée réelle totale (h)' = EXTERNALMEASURE("Durée réelle totale (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 3 - Durées réelles (fois intervenant)
			lineageTag: c9b75e85-f39a-438d-b0b6-0e1820d4c173
			sourceLineageTag: DirectQuery à AS – pst38.Durée réelle totale (h)
			dataCategory: Uncategorized

		measure 'Durée réelle trajet (h)' = EXTERNALMEASURE("Durée réelle trajet (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 3 - Durées réelles (fois intervenant)
			lineageTag: b06a079d-68e3-4420-80b0-8a72687210a4
			sourceLineageTag: DirectQuery à AS – pst38.Durée réelle trajet (h)
			dataCategory: Uncategorized

		measure 'Durée totale des évènements (h)' = EXTERNALMEASURE("Durée totale des évènements (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 2 - Evènements (fois intervenant)
			lineageTag: 27beab2d-f1e9-4d66-a858-a2991b05c1d7
			sourceLineageTag: DirectQuery à AS – pst38.Durée totale des évènements (h)
			dataCategory: Uncategorized

		measure '# autre type évènement (AMT)' = EXTERNALMEASURE("# autre type évènement (AMT)", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 6944f123-f9ec-46c9-ae75-54ea29811ee5
			sourceLineageTag: DirectQuery à AS – pst38.# autre type évènement (AMT)
			dataCategory: Uncategorized

		measure '# évènements (AMT)' = EXTERNALMEASURE("# évènements (AMT)", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 8c9dc4ad-0592-49c0-a65e-bfcc151175aa
			sourceLineageTag: DirectQuery à AS – pst38.# évènements (AMT)
			dataCategory: Uncategorized

		measure '# rédaction (AMT)' = EXTERNALMEASURE("# rédaction (AMT)", INTEGER, "DirectQuery à AS – pst38")
			formatString: #,##0
			displayFolder: 1 - AMT
			lineageTag: 4c98f5c7-0bf2-480b-a77c-f0c9485e5635
			sourceLineageTag: DirectQuery à AS – pst38.# rédaction (AMT)
			dataCategory: Uncategorized

		measure 'Durée autre type évènement (AMT)' = EXTERNALMEASURE("Durée autre type évènement (AMT)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 1 - AMT
			lineageTag: 32be7bc0-f7c4-4907-a013-a02e4fe40d98
			sourceLineageTag: DirectQuery à AS – pst38.Durée autre type évènement (AMT)
			dataCategory: Uncategorized

		measure 'Durée évènement (AMT)' = EXTERNALMEASURE("Durée évènement (AMT)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 1 - AMT
			lineageTag: 43903958-4e0f-443b-8b31-9ae37a211d76
			sourceLineageTag: DirectQuery à AS – pst38.Durée évènement (AMT)
			dataCategory: Uncategorized

		measure 'Durée rédaction (AMT)' = EXTERNALMEASURE("Durée rédaction (AMT)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 1 - AMT
			lineageTag: 1980888e-9a6f-44d0-b7c2-7524db421dbb
			sourceLineageTag: DirectQuery à AS – pst38.Durée rédaction (AMT)
			dataCategory: Uncategorized

		measure 'Durée autre type évènement pondérée (AMT)' = EXTERNALMEASURE("Durée autre type évènement pondérée (AMT)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: f783ba2e-c9b1-486b-9d7b-b9736859498c
			sourceLineageTag: DirectQuery à AS – pst38.Durée autre type évènement pondérée (AMT)
			dataCategory: Uncategorized

		measure 'Durée autre type évènement pondérée (h)' = EXTERNALMEASURE("Durée autre type évènement pondérée (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: bd502594-8e97-4a12-9ed3-c6e2f85161ad
			sourceLineageTag: DirectQuery à AS – pst38.Durée autre type évènement pondérée (h)
			dataCategory: Uncategorized

		measure 'Durée estimée action pondérée (h)' = EXTERNALMEASURE("Durée estimée action pondérée (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: bd944045-462e-4151-96bb-1a88f6b8bb01
			sourceLineageTag: DirectQuery à AS – pst38.Durée estimée action pondérée (h)
			dataCategory: Uncategorized

		measure 'Durée estimée chez l''adhérent pondérée (h)' = EXTERNALMEASURE("Durée estimée chez l'adhérent pondérée (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: 43df0dee-e1a6-4272-af87-c2fb847edfb1
			sourceLineageTag: DirectQuery à AS – pst38.Durée estimée chez l'adhérent pondérée (h)
			dataCategory: Uncategorized

		measure 'Durée évènement collectif pondérée (AMT)' = EXTERNALMEASURE("Durée évènement collectif pondérée (AMT)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: 070790ff-4dbd-47bb-af00-0b3993f015d1
			sourceLineageTag: DirectQuery à AS – pst38.Durée évènement collectif pondérée (AMT)
			dataCategory: Uncategorized

		measure 'Durée évènement collectif pondérée (h)' = EXTERNALMEASURE("Durée évènement collectif pondérée (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: 937df587-eda9-48e4-b2ef-6eca367ea45a
			sourceLineageTag: DirectQuery à AS – pst38.Durée évènement collectif pondérée (h)
			dataCategory: Uncategorized

		measure 'Durée évènement pondérée (AMT)' = EXTERNALMEASURE("Durée évènement pondérée (AMT)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: aac5ac96-da88-42de-9f78-029c8cb392e7
			sourceLineageTag: DirectQuery à AS – pst38.Durée évènement pondérée (AMT)
			dataCategory: Uncategorized

		measure 'Durée intervention pondérée (AMT)' = EXTERNALMEASURE("Durée intervention pondérée (AMT)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: 988a88f4-3f09-44f3-af57-3a3f014aac5a
			sourceLineageTag: DirectQuery à AS – pst38.Durée intervention pondérée (AMT)
			dataCategory: Uncategorized

		measure 'Durée intervention pondérée (h)' = EXTERNALMEASURE("Durée intervention pondérée (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: 66ef3ba4-e203-41e9-8cd1-c66df8a41c52
			sourceLineageTag: DirectQuery à AS – pst38.Durée intervention pondérée (h)
			dataCategory: Uncategorized

		measure 'Durée rédaction pondérée (AMT)' = EXTERNALMEASURE("Durée rédaction pondérée (AMT)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: e12faa10-872b-454a-a947-600e2a9f4678
			sourceLineageTag: DirectQuery à AS – pst38.Durée rédaction pondérée (AMT)
			dataCategory: Uncategorized

		measure 'Durée rédaction pondérée (h)' = EXTERNALMEASURE("Durée rédaction pondérée (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: b46a306d-4f0f-42a1-a591-c0fdbad0be6a
			sourceLineageTag: DirectQuery à AS – pst38.Durée rédaction pondérée (h)
			dataCategory: Uncategorized

		measure 'Durée réelle intervention pondérée (h)' = EXTERNALMEASURE("Durée réelle intervention pondérée (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: 1aea2ffd-7ce7-48b6-9566-be51fb3020a9
			sourceLineageTag: DirectQuery à AS – pst38.Durée réelle intervention pondérée (h)
			dataCategory: Uncategorized

		measure 'Durée réelle rédaction pondérée (h)' = EXTERNALMEASURE("Durée réelle rédaction pondérée (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: 80811c1d-bfef-4d0d-b07d-9fd69a99f324
			sourceLineageTag: DirectQuery à AS – pst38.Durée réelle rédaction pondérée (h)
			dataCategory: Uncategorized

		measure 'Durée réelle totale pondérée (h)' = EXTERNALMEASURE("Durée réelle totale pondérée (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: d7fe3b5a-80ce-4543-a196-3fcf56d94cab
			sourceLineageTag: DirectQuery à AS – pst38.Durée réelle totale pondérée (h)
			dataCategory: Uncategorized

		measure 'Durée réelle trajet pondérée (h)' = EXTERNALMEASURE("Durée réelle trajet pondérée (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: 9405a172-76e2-412b-b94f-7256fd92b128
			sourceLineageTag: DirectQuery à AS – pst38.Durée réelle trajet pondérée (h)
			dataCategory: Uncategorized

		measure 'Durée totale des évènements pondérée (h)' = EXTERNALMEASURE("Durée totale des évènements pondérée (h)", DOUBLE, "DirectQuery à AS – pst38")
			formatString: #,##0.0
			displayFolder: 5 - Durée dépréciée
			lineageTag: 283c766d-8018-413c-a128-3fcf1efd6ca0
			sourceLineageTag: DirectQuery à AS – pst38.Durée totale des évènements pondérée (h)
			dataCategory: Uncategorized

		column duree_estimee_action_adherent_intervenant
			dataType: double
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: 81c403a8-203d-4642-89d4-141bf9958d38
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_estimee_action_adherent_intervenant

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column duree_estimee_action_intervenant
			dataType: double
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: 0cc66715-9ef6-4738-846f-9704ddde1d41
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_estimee_action_intervenant

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_amt_source
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: b6708cf0-54f9-4f31-9bbd-4abc67abade4
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: id_amt_source

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_centre_convocation
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: fc0d4dc4-d44b-4acf-9bb7-e3d53b52ec84
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_centre_convocation

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_createur_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 229260e4-9b45-4bf3-a25f-40d25f0a8193
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_createur_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_date_cloture_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: f5c62252-7413-40be-bbcc-d05927db8713
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_date_cloture_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_date_creation_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: da6d40a9-39c5-48c6-9f10-b03b26e2e0ea
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_date_creation_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_date_demande_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: c55fa583-39e9-413b-9c57-0fb87e0af605
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_date_demande_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_date_derniere_intervention_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: c344e6d7-4951-424b-8f22-b471b88bb271
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_date_derniere_intervention_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_date_echeance_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 818475f1-fae3-4cd4-8146-78563439f601
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_date_echeance_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_date_statut_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: d003b320-069c-475f-a954-34e8c9321e3c
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: id_date_statut_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_demandeur_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 2737a542-0b4d-4845-bc6c-bb3b5f098695
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_demandeur_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_entreprise
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: dc27834b-d0ce-4517-9e00-0b279c77d0db
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_entreprise

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_entreprise_collection_regroupante
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 97934f59-1403-41a3-b36b-a564141ecd47
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: id_entreprise_collection_regroupante

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_etiquette_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 987e1b2f-a573-4d3c-b9d3-9c70b9e66bb5
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_etiquette_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_groupe_description_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 6c45a77e-dc15-4854-b7dd-d581a25af776
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_groupe_description_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_groupe_tache_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 76510a89-be76-4e5c-8a86-bee1d15e6789
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_groupe_tache_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_intervenant_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 07036e46-0215-48c1-9e36-a9529816cd28
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_intervenant_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_modele_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 170c781c-75a5-4267-84d7-534bd779145a
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_modele_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_secteur
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: adc0ad7e-b7a2-409a-a01f-eb3c903b30d7
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_secteur

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_statut_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: c1e0654c-da53-4ac4-82ac-755ae2c8bf5a
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_statut_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_titre_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 97eb4bb7-d3d4-4e28-8e6f-1777f0bde0cd
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_titre_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column nb_amt_realisable_module_fe
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: bd4d2f47-07cd-4dd8-94ee-5eaa98ee8cce
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_amt_realisable_module_fe

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column nb_autre_type_evenement_intervenant
			dataType: int64
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: 8dc2bc44-cb29-4cb6-9ef6-6f23fdb86919
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_autre_type_evenement_intervenant

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column nb_donnee_saisie_module_fe
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 592064c8-37ed-4fff-941a-e4c39fb716ab
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_donnee_saisie_module_fe

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column nb_evenement_collectif
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 0b5ddb84-42d3-450c-b9c9-29bc6bfce407
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_evenement_collectif

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column nb_evenement_collectif_intervenant
			dataType: int64
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: dbbb8079-a667-48ea-b63b-b602502a470c
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_evenement_collectif_intervenant

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column nb_fe_generee_module_fe
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 15e14807-c002-42da-affd-90c94040e686
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_fe_generee_module_fe

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column nb_intervention
			dataType: int64
			formatString: #,##0
			displayFolder: Colonnes inutilisées
			lineageTag: 7fd85c75-8d22-4997-81c9-e3e816b5483c
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_intervention

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column nb_intervention_intervenant
			dataType: int64
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: 88edc9f4-1319-4b99-ab9a-01432a758c5c
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_intervention_intervenant

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column nb_redaction_intervenant
			dataType: int64
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: 9dc28612-0977-4a8b-b504-903b78794b7e
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_redaction_intervenant

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column nb_salarie_concerne
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: d0315b07-6217-497e-bb9a-072ab70105b5
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_salarie_concerne

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column nb_salarie_suivi
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 0be89be7-833b-478b-b484-5588228312b9
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_salarie_suivi

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column nb_tache_planifiee
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 32805749-dc6f-4da9-9259-e679abe3dfc4
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_tache_planifiee

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column nb_tache_realisee
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: cbd6483d-ad90-4c33-96c0-ae5ce74b94a4
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_tache_realisee

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column nb_total_evenement_intervenant
			dataType: int64
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: 761cc23b-d5ff-480e-bf11-55c83b966697
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_total_evenement_intervenant

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_date_dernier_evenement_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: be7c7c9c-b659-4857-a0ae-60b1a62f210f
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: id_date_dernier_evenement_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_date_premiere_intervention_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 6f248d68-802f-4730-ba67-2b7efb0b3fcb
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: id_date_premiere_intervention_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_date_derniere_redaction_amt
			dataType: int64
			displayFolder: Colonnes inutilisées
			lineageTag: 9f27be3e-a757-4edc-b3a9-1e1a763ddeb2
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: id_date_derniere_redaction_amt

			changedProperty = IsHidden

			annotation SummarizationSetBy = Automatic

		column id_amt
			dataType: int64
			isHidden
			displayFolder: Colonnes inutilisées
			lineageTag: d0332a60-8741-48ea-aa1e-e3490bef0913
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: id_amt

			annotation SummarizationSetBy = Automatic

		column id_amt_perimetre_entreprise
			dataType: int64
			isHidden
			displayFolder: Colonnes inutilisées
			lineageTag: b21ec2da-cfca-4f5a-b42e-0ca46d8260ca
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: id_amt_perimetre_entreprise

			annotation SummarizationSetBy = Automatic

		column id_amt_perimetre_unique
			dataType: int64
			isHidden
			displayFolder: Colonnes inutilisées
			lineageTag: 515346c5-e588-4bcc-a058-74f39c0ef82e
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: id_amt_perimetre_unique

			annotation SummarizationSetBy = Automatic

		column id_info_amt_v2
			dataType: int64
			isHidden
			displayFolder: Colonnes inutilisées
			lineageTag: 4eeab433-33ea-4ad4-9ecb-5a978c782d02
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: id_info_amt_v2

			annotation SummarizationSetBy = Automatic

		column nb_intervenant
			dataType: int64
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: 67b16334-bdbe-4396-8a27-df541aa06f3c
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_intervenant

			annotation SummarizationSetBy = Automatic

		column 'Date dernier statut à affecter'
			dataType: dateTime
			formatString: dd/mm/yyyy
			displayFolder: Date dernier statut AMT
			lineageTag: bb62fa87-1742-40d3-8292-d2f86eb607bc
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: Date dernier statut à affecter

			annotation SummarizationSetBy = Automatic

		column 'Date dernier statut à faire'
			dataType: dateTime
			formatString: dd/mm/yyyy
			displayFolder: Date dernier statut AMT
			lineageTag: 97231a66-b35f-4f80-b670-2c81880142e5
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: Date dernier statut à faire

			annotation SummarizationSetBy = Automatic

		column 'Date dernier statut à valider'
			dataType: dateTime
			formatString: dd/mm/yyyy
			displayFolder: Date dernier statut AMT
			lineageTag: 0e8fa307-9723-4d01-8f11-30ee23ed8272
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: Date dernier statut à valider

			annotation SummarizationSetBy = Automatic

		column 'Date dernier statut abandonné'
			dataType: dateTime
			formatString: dd/mm/yyyy
			displayFolder: Date dernier statut AMT
			lineageTag: d404d209-6890-4644-bfa5-c21f62a82540
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: Date dernier statut abandonné

			annotation SummarizationSetBy = Automatic

		column 'Date dernier statut en cours'
			dataType: dateTime
			formatString: dd/mm/yyyy
			displayFolder: Date dernier statut AMT
			lineageTag: 8622c2f8-a0bc-47c3-aed7-ea02d5c0445d
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: Date dernier statut en cours

			annotation SummarizationSetBy = Automatic

		column 'Date dernier statut suspendu'
			dataType: dateTime
			formatString: dd/mm/yyyy
			displayFolder: Date dernier statut AMT
			lineageTag: 1b705ff2-0a96-4b84-9b29-beaeadc5ba92
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: Date dernier statut suspendu

			annotation SummarizationSetBy = Automatic

		column 'Date dernier statut terminé'
			dataType: dateTime
			formatString: dd/mm/yyyy
			displayFolder: Date dernier statut AMT
			lineageTag: e04f0839-ba3d-43f2-9525-625cb79773fd
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: Date dernier statut terminé

			annotation SummarizationSetBy = Automatic

		column 'Date dernier statut validé'
			dataType: dateTime
			formatString: dd/mm/yyyy
			displayFolder: Date dernier statut AMT
			lineageTag: 183a427f-e9ac-4af8-a425-1fd7a2da3226
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: Date dernier statut validé

			annotation SummarizationSetBy = Automatic

		column duree_autre_type_evenement_planning
			dataType: double
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: 7fdbcf64-9e57-4f65-80a7-9afcb53f30cc
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_autre_type_evenement_planning

			annotation SummarizationSetBy = Automatic

		column duree_autre_type_evenement_planning_intervenant
			dataType: double
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: 2b1a03ee-88e6-4f02-a259-2cbe9c229540
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_autre_type_evenement_planning_intervenant

			annotation SummarizationSetBy = Automatic

		column duree_evenement_collectif_planning
			dataType: double
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: 82c74da0-748a-497d-be59-74956913537e
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_evenement_collectif_planning

			annotation SummarizationSetBy = Automatic

		column duree_evenement_collectif_planning_intervenant
			dataType: double
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: 2eefd4ae-c866-4043-a0c7-48c96a0c135a
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_evenement_collectif_planning_intervenant

			annotation SummarizationSetBy = Automatic

		column duree_evenements_planning
			dataType: double
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: db5ce742-d183-469c-9335-2ffbd9e260f9
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_evenements_planning

			annotation SummarizationSetBy = Automatic

		column duree_intervention_planning
			dataType: double
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: f554883e-83a3-47db-9441-7abd1e1b7c32
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_intervention_planning

			annotation SummarizationSetBy = Automatic

		column duree_intervention_planning_intervenant
			dataType: double
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: 85114a83-f5e0-43fd-8aac-b15c54dd2b53
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_intervention_planning_intervenant

			annotation SummarizationSetBy = Automatic

		column duree_intervention_saisie_manuellement_intervenant
			dataType: double
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: 198dc457-0159-47a2-a142-6ad290c4fc57
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_intervention_saisie_manuellement_intervenant

			annotation SummarizationSetBy = Automatic

		column duree_redaction_planning
			dataType: double
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: 5b68ed94-f8a0-467a-a516-2a586cd6d0ff
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_redaction_planning

			annotation SummarizationSetBy = Automatic

		column duree_redaction_planning_intervenant
			dataType: double
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: eb62dda4-8c75-4861-b3f5-a935c55948f6
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_redaction_planning_intervenant

			annotation SummarizationSetBy = Automatic

		column duree_redaction_saisie_manuellement_intervenant
			dataType: double
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: c39abd97-0217-40d1-861c-3415bd38acc8
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_redaction_saisie_manuellement_intervenant

			annotation SummarizationSetBy = Automatic

		column duree_totale_evenement_planning_intervenant
			dataType: double
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: 7e019ce4-7976-4970-a504-a721f758b18e
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_totale_evenement_planning_intervenant

			annotation SummarizationSetBy = Automatic

		column duree_totale_saisie_manuellement_intervenant
			dataType: double
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: b30e3366-7659-4ac0-85eb-2b47808bff9d
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_totale_saisie_manuellement_intervenant

			annotation SummarizationSetBy = Automatic

		column duree_trajet_planning_intervenant
			dataType: double
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: e63c9033-e96c-43b0-a9ea-d1b3812f6af2
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_trajet_planning_intervenant

			annotation SummarizationSetBy = Automatic

		column duree_trajet_saisie_manuellement_intervenant
			dataType: double
			isHidden
			formatString: #,##0.0
			displayFolder: Colonnes inutilisées
			lineageTag: be337168-fa36-4bc3-b38e-4ed4857a4d81
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: duree_trajet_saisie_manuellement_intervenant

			annotation SummarizationSetBy = Automatic

		column nb_autre_type_evenement
			dataType: int64
			isHidden
			formatString: #,##0
			displayFolder: Colonnes inutilisées
			lineageTag: 1edde729-f705-41b0-832b-5836dca32036
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_autre_type_evenement

			annotation SummarizationSetBy = Automatic

		column nb_evenements
			dataType: int64
			isHidden
			formatString: #,##0
			displayFolder: Colonnes inutilisées
			lineageTag: d9a90b15-16da-4135-ab41-afd4d3fcae49
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_evenements

			annotation SummarizationSetBy = Automatic

		column nb_redaction
			dataType: int64
			isHidden
			formatString: #,##0
			displayFolder: Colonnes inutilisées
			lineageTag: 77e6248c-9ccc-476c-b767-a07a17167681
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_redaction

			annotation SummarizationSetBy = Automatic

		column code_rls_utilisateur_secteur
			dataType: string
			isHidden
			displayFolder: Colonnes inutilisées
			lineageTag: bc92bf56-a30b-45af-9699-92edba991aa3
			dataCategory: Uncategorized
			summarizeBy: none
			sourceColumn: code_rls_utilisateur_secteur

			annotation SummarizationSetBy = Automatic

		column nb_entreprise
			dataType: int64
			isHidden
			formatString: 0
			displayFolder: Colonnes inutilisées
			lineageTag: 3d4bfbed-e623-4e9e-b8ce-d778c8d2cb63
			dataCategory: Uncategorized
			summarizeBy: sum
			sourceColumn: nb_entreprise

			annotation SummarizationSetBy = Automatic

		column 'Délai AMT statut à Faire -> Terminée' =
				
				DATEDIFF([Date dernier statut à faire], [Date dernier statut terminé], DAY)
			formatString: 0
			displayFolder: Date dernier statut AMT
			lineageTag: 4c711ea3-7a58-49fb-8734-107c0ef5267b
			summarizeBy: sum

			changedProperty = DisplayFolder

			changedProperty = Name

			annotation SummarizationSetBy = Automatic

		column 'Délai AMT statut en cours -> à valider' =
				
				DATEDIFF([Date dernier statut en cours], [Date dernier statut à valider], DAY)
			formatString: 0
			displayFolder: Date dernier statut AMT
			lineageTag: af3cf623-27da-42dc-bd49-1d4c799d5008
			summarizeBy: sum

			changedProperty = DisplayFolder

			changedProperty = Name

			annotation SummarizationSetBy = Automatic

		column 'Délai AMT statut à valider -> validée' =
				
				DATEDIFF([Date dernier statut à valider], [Date dernier statut validé], DAY)
			formatString: 0
			displayFolder: Date dernier statut AMT
			lineageTag: 4ff51823-7e29-4b82-a629-75c869e27346
			summarizeBy: sum

			changedProperty = DisplayFolder

			changedProperty = Name

			annotation SummarizationSetBy = Automatic	

		partition 'AMT v2' = entity
			mode: directQuery
			source
				entityName: AMT v2
				expressionSource: 'DirectQuery à AS – pst38'

